### ISSUE TITLE
群聊无法获取到内容

### ISSUE THREAD

**Issue by xieyqxie** [fuergaosi233/wechat-chatgpt#10]
单独私聊正常，群聊@之后，Hit GPT Enabled User:，不会有这个请求，请教一下是什么原因呢？

**Comment by fuergaosi233** [comment]
Can you provide more information? 
Such as log...

**Comment by fuergaosi233** [comment]
Can you provide more information? 
Such as log...

**Comment by moseeking** [comment]
> Can you provide more information? 
> 
> Such as log...

**Comment by cloudGrin** [comment]
#54 同样的问题，debug发现是大小写问题，导致return了
