### ISSUE TITLE
即使是英文输出也会不完整

### ISSUE THREAD

**Issue by OliverGrace** [fuergaosi233/wechat-chatgpt#107]
网站上使用它会持续输出文字一段时间，但是是完整的。在微信当中就发不全了。
<img width="382" alt="ss" src="https://user-images.githubusercontent.com/5617905/206657289-016f2349-7db6-491b-872c-cb701f815c4d.png">

**Comment by fuergaosi233** [comment]
It's supposed to send multiple texts, right?

**Comment by OliverGrace** [comment]
> It's supposed to send multiple texts, right?

@fuergaosi233 Yep, but it sent only several parts, not all of them.

**Comment by fuergaosi233** [comment]
> > It's supposed to send multiple texts, right?
> 
> @fuergaosi233 Yep, but it sent only several parts, not all of them.

Is there any way to reproduce it?

**Comment by RealTong** [comment]
Solved.
