### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by cjd9023** [fuergaosi233/wechat-chatgpt#114]
假如把bot放在一个大几百人的群, 微信几十上百人一起@容易覆盖信息及被人投诉, 是否可考虑通过黑白名单来支持可选. ( 我个别账号已经被封了30天, 申诉太麻烦了)
空白或没配置就是默认没限制.

希望有个白名单及黑名单能配置wechat id, 能动态监控 config.yaml 文件修改实时生效
whitelist_wechat_id_list = xxx1,xxxx2,xxxx3 # 只有这几个管理员能@特
blacklist_wechat_id_list = yyyy1,yyyy2,yyyy3 # 频繁@的用户能手动限制(先支持手动添加/删除)

不现实就当我没提过, 哈哈 😄

**Comment by peterhiking** [comment]
同求
