### ISSUE TITLE
登上了，但是其他人发消息会出现Cannot read properties of undefined

### ISSUE THREAD

**Issue by laotutou007** [fuergaosi233/wechat-chatgpt#115]
<img width="1139" alt="Screen Shot 2022-12-09 at 5 48 12 PM" src="https://user-images.githubusercontent.com/69883652/206673880-a89e672b-d4b9-4324-a622-ed0fc29816f9.png">

**Comment by chaoming56** [comment]
用session 登陆就可以解决

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/102

**Comment by 1183747933** [comment]
> 
什么意思

**Comment by 1183747933** [comment]
> 用session 登陆就可以解决

什么意思

**Comment by laotutou007** [comment]
可能是环境问题导致的
