### ISSUE TITLE
二维码无法扫描

### ISSUE THREAD

**Issue by foreveryuu** [fuergaosi233/wechat-chatgpt#12]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/119954620/206098752-c7dab502-cb9d-458e-b46d-10c50bd1a7c1.png">

运行到这里的二维码无法扫描，导致无法登录

**Comment by fuergaosi233** [comment]
This may be related to the terminal, you can try to click the link above the QR code to scan the code.
