### ISSUE TITLE
和ChatGpt网页版回答不一致

### ISSUE THREAD

**Issue by LemonYu997** [fuergaosi233/wechat-chatgpt#122]
网页版可以回答很多复杂的问题，这个只会回答很抱歉，提供不了这种服务之类的回答。
是网页版和开放API不一样吗？

**Comment by fuguiKz** [comment]
After using the web version of OpenAI, I can confidently say that it is indeed capable of answering complex questions. The difference between the web version and the open API may be in the specific implementation and capabilities of each, but the web version certainly meets the expectations outlined on the official website.

Additionally, it has come to my attention that some individuals may be using an access token for OpenAI to call the "text-davinci-003" model and impersonate chatgpt, which does not provide answers of the same quality as chatgpt. I suggest checking if any other projects have been used, and if not, using circumspect language or fictional scenarios to avoid detection by chatgpt.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/74097723/206701298-430c7edb-4c3b-472a-9df7-a41626d12cba.png">

**Comment by RealTong** [comment]
Currently OpenAI does not have an API.
So it uses https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py .
Theoretically, it is the same as the web version. But it is not excluded that OpenAI can somehow recognize the inverse features and return a different response.

**Comment by RealTong** [comment]
Currently OpenAI does not have an API. 
So it uses https://github.com/transitive-bullshit/chatgpt-api . Theoretically, it is the same as the web version. But it is not excluded that OpenAI can somehow recognize the inverse features and return a different response.

**Comment by fuergaosi233** [comment]
Yes, this project is using the web version as the API so it's not OpenAPI.
