### ISSUE TITLE
What caused this error and how can I fix it

### ISSUE THREAD

**Issue by i01ortal** [fuergaosi233/wechat-chatgpt#123]
![image](https://user-images.githubusercontent.com/57478262/206699955-b4738a7d-957c-4e1e-a0c3-276186583f0d.png)
I get the error whenever I try to execute using a different version of the docker container

**Comment by i01ortal** [comment]
> 您可以尝试升级 revChatGPT #106
I tried a few things but it didn't work, can you help me

**Comment by fuergaosi233** [comment]
I think you should make sure you can log in to OpenAI 🤔?
