### ISSUE TITLE
使用的Docker版本，部署在digitalocean上1C1G的机器上，响应速度极慢

### ISSUE THREAD

**Issue by abel533** [fuergaosi233/wechat-chatgpt#124]
>使用podman运行的Docker容器。

第一个问题，过了很久很久才回复，后面的问题都没有回复。

有人遇到类似问题吗？

**Comment by Code-Dramatist** [comment]
那不是响应极慢, 而是chatgpt的回复方式, 就是一个字一个字蹦出来, 要等结果全部出来后, 这个模块才能去获取答案转发到微信. 那个chatgpt的页面就是要等回复后才能继续多个问题, 所以可能你一下子说太多就给pass掉了
