### ISSUE TITLE
设置了代理，但未使用，反馈很慢

### ISSUE THREAD

**Issue by LiangYang666** [fuergaosi233/wechat-chatgpt#128]
通过
`docker run --env http_proxy="http://192.168.1.38:7890" --net host -d  --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest`
启动容器后，通过 dockers exec -it wechat-chatgpt bash，然后curl www.google.com能获取网页，也能从代理软件看到走了代理，但是微信登录后发消息反馈很慢，而且自始至终也没走代理，请问是设置错了吗，应该怎么做

**Comment by m4p1e** [comment]
这个项目用的其他的chatGPT package, 这个package本身并不支持proxy

**Comment by lian-store** [comment]
> > 通过`docker run --env http_proxy="http://192.168.1.38:7890" --net host -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest`启动启动，通过dockers exec -It Wechat -Chatgpt bash，curl [www.google.com能没有走代理，请问是设置错了吗，应该怎么做](http://www.google.com%E8%83%BD%E8%8E%B7%E5%8F%96%E7%BD%91%E9%A1%B5%EF%BC%8C%E4%B9%9F%E8%83%BD%E4%BB%8E%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E7%9C%8B%E5%88%B0%E8%B5%B0%E4%BA%86%E4%BB%A3%E7%90%86%EF%BC%8C%E4%BD%86%E6%98%AF%E5%BE%AE%E4%BF%A1%E7%99%BB%E5%BD%95%E5%90%8E%E5%8F%91%E6%B6%88%E6%81%AF%E5%8F%8D%E9%A6%88%E5%BE%88%E6%85%A2%EF%BC%8C%E8%80%8C%E4%B8%94%E8%87%AA%E5%A7%8B%E8%87%B3%E7%BB%88%E4%B9%9F%E6%B2%A1%E8%B5%B0%E4%BB%A3%E7%90%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E8%AE%BE%E7%BD%AE%E9%94%99%E4%BA%86%E5%90%97%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%81%9A)
> 
> 我认为微信不支持代理。 但 OpenAI 登录会支持代理。 <img alt="图片" width="828" src="https://user-images.githubusercontent.com/22197568/206730941-f338ead7-4510-4f75-be67-fdc8f2ebdb68.png">

这里有没有考虑将他改成config.yml来配置呢？因为docker上来读取代理是不现实的，但是我试了在里面直接写死地址是可以完成代理登录的

**Comment by LiangYang666** [comment]
docker容器内是读取到了代理配置的，我执行容器内bash并进入后，执行curl命令，是会走代理的，但是问题是除此之外，整个容器运行时就没有用过代理

**Comment by fuergaosi233** [comment]
> > > 通过`docker run --env http_proxy="http://192.168.1.38:7890" --net host -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest`启动启动，通过dockers exec -It Wechat -Chatgpt bash，curl [www.google.com能没有走代理，请问是设置错了吗，应该怎么做](http://www.google.com%E8%83%BD%E8%8E%B7%E5%8F%96%E7%BD%91%E9%A1%B5%EF%BC%8C%E4%B9%9F%E8%83%BD%E4%BB%8E%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E7%9C%8B%E5%88%B0%E8%B5%B0%E4%BA%86%E4%BB%A3%E7%90%86%EF%BC%8C%E4%BD%86%E6%98%AF%E5%BE%AE%E4%BF%A1%E7%99%BB%E5%BD%95%E5%90%8E%E5%8F%91%E6%B6%88%E6%81%AF%E5%8F%8D%E9%A6%88%E5%BE%88%E6%85%A2%EF%BC%8C%E8%80%8C%E4%B8%94%E8%87%AA%E5%A7%8B%E8%87%B3%E7%BB%88%E4%B9%9F%E6%B2%A1%E8%B5%B0%E4%BB%A3%E7%90%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E8%AE%BE%E7%BD%AE%E9%94%99%E4%BA%86%E5%90%97%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%81%9A)
> > 
> > 
> > 我认为微信不支持代理。 但 OpenAI 登录会支持代理。 <img alt="图片" width="828" src="https://user-images.githubusercontent.com/22197568/206730941-f338ead7-4510-4f75-be67-fdc8f2ebdb68.png">
> 
> 这里有没有考虑将他改成config.yml来配置呢？因为docker上来读取代理是不现实的，但是我试了在里面直接写死地址是可以完成代理登录的

Good advice

**Comment by fuergaosi233** [comment]
> > > 通过`docker run --env http_proxy="http://192.168.1.38:7890" --net host -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest`启动启动，通过dockers exec -It Wechat -Chatgpt bash，curl [www.google.com能没有走代理，请问是设置错了吗，应该怎么做](http://www.google.com%E8%83%BD%E8%8E%B7%E5%8F%96%E7%BD%91%E9%A1%B5%EF%BC%8C%E4%B9%9F%E8%83%BD%E4%BB%8E%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E7%9C%8B%E5%88%B0%E8%B5%B0%E4%BA%86%E4%BB%A3%E7%90%86%EF%BC%8C%E4%BD%86%E6%98%AF%E5%BE%AE%E4%BF%A1%E7%99%BB%E5%BD%95%E5%90%8E%E5%8F%91%E6%B6%88%E6%81%AF%E5%8F%8D%E9%A6%88%E5%BE%88%E6%85%A2%EF%BC%8C%E8%80%8C%E4%B8%94%E8%87%AA%E5%A7%8B%E8%87%B3%E7%BB%88%E4%B9%9F%E6%B2%A1%E8%B5%B0%E4%BB%A3%E7%90%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E8%AE%BE%E7%BD%AE%E9%94%99%E4%BA%86%E5%90%97%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%81%9A)
> > 
> > 
> > 我认为微信不支持代理。 但 OpenAI 登录会支持代理。 <img alt="图片" width="828" src="https://user-images.githubusercontent.com/22197568/206730941-f338ead7-4510-4f75-be67-fdc8f2ebdb68.png">
> 
> 这里有没有考虑将他改成config.yml来配置呢？因为docker上来读取代理是不现实的，但是我试了在里面直接写死地址是可以完成代理登录的

https://github.com/fuergaosi233/wechat-chatgpt/pull/216
