### ISSUE TITLE
用账号密码启动提示这个

### ISSUE THREAD

**Issue by yn-ayw** [fuergaosi233/wechat-chatgpt#129]
![image](https://user-images.githubusercontent.com/78069636/206715851-7c052a92-b9e6-476f-b5ed-691b921d3718.png)
Logging in...
Traceback (most recent call last):
  File "src/generate_session.py", line 29, in <module>
    print(login(email, password))
  File "src/generate_session.py", line 15, in login
    chatbot.login(
  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-QX5Bu5eO-py3.8/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 171, in login
    self.config['session_token'] = auth.session_token
AttributeError: 'OpenAIAuth' object has no attribute 'session_token'

**Comment by RealTong** [comment]
Seems to be the same problem as https://github.com/fuergaosi233/wechat-chatgpt/issues/123

**Comment by Code-Dramatist** [comment]
这个问题好像是一个库的版本问题, 等待pr中, 现在可以用密钥的形式先用, 账号密码还有问题

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/134 
Try it again,pls.

**Comment by Code-Dramatist** [comment]
用账号密码登录, 需要注意代理地区吗, 用密钥好像是无所谓的, 不知道用账号密码是不是需要注意代理

**Comment by JerryKingQAQ** [comment]
更新了库还是遇到同样的问题

**Comment by Code-Dramatist** [comment]
我更新库了,正常登入
![image](https://user-images.githubusercontent.com/29671214/206746752-1f576ead-7963-4adb-b41c-2c75da6904a5.png)
