### ISSUE TITLE
在阿里云服务器上无法docker build

### ISSUE THREAD

**Issue by ZhuGeRoastedFish** [fuergaosi233/wechat-chatgpt#130]
9/11环节安装requests时报错
• Installing requests (2.28.1)

  TimeoutError

  The read operation timed out

  at /usr/local/lib/python3.11/ssl.py:1134 in read
      1130│         if self._sslobj is None:
      1131│             raise ValueError("Read on closed or unwrapped SSL socket.")
      1132│         try:
      1133│             if buffer is not None:
    → 1134│                 return self._sslobj.read(len, buffer)
      1135│             else:
      1136│                 return self._sslobj.read(len)
      1137│         except SSLError as x:
      1138│             if x.args[0] == SSL_ERROR_EOF and self.suppress_ragged_eofs:

The following error occurred when trying to handle this error:

  ReadTimeoutError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.11/site-packages/urllib3/response.py:449 in _error_catcher
      445│ 
      446│             except SocketTimeout:
      447│                 # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
      448│                 # there is yet no clean way to get at it from this context.
    → 449│                 raise ReadTimeoutError(self._pool, None, "Read timed out.")
      450│ 
      451│             except BaseSSLError as e:
      452│                 # FIXME: Is there a better way to differentiate between SSLErrors?
      453│                 if "read operation timed out" not in str(e):

The following error occurred when trying to handle this error:

  ConnectionError

  HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

  at /usr/local/lib/python3.11/site-packages/requests/models.py:822 in generate
       818│                     raise ChunkedEncodingError(e)
       819│                 except DecodeError as e:
       820│                     raise ContentDecodingError(e)
       821│                 except ReadTimeoutError as e:
    →  822│                     raise ConnectionError(e)
       823│                 except SSLError as e:
       824│                     raise RequestsSSLError(e)
       825│             else:
       826│                 # Standard file-like object.

**Comment by fuergaosi233** [comment]
Use `docker pull` instead pls.

**Comment by ZhuGeRoastedFish** [comment]
> Use `docker pull` instead pls.

感谢感谢！！！！我这云服务器缺这缺那得，总弄不好。多亏了博主的镜像！一下搞好了
