### ISSUE TITLE
请问扫描二维码登录后报这个错应该怎么办

### ISSUE THREAD

**Issue by 1040269943** [fuergaosi233/wechat-chatgpt#135]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by fuergaosi233** [comment]
You need to authenticate your WeChat account with your real name first and make sure you can log in via WeChat web, https://web.wechat.com/ 🙏.
