### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by OliverGrace** [fuergaosi233/wechat-chatgpt#136]
`Because chatbot-twitter depends on both revChatGPT (^0.0.27) and revchatgpt (^0.0.33.5), version solving failed.
The command '/bin/sh -c poetry install && npm install && rm -rf ~/.npm/' returned a non-zero code: 1
`

**Comment by OliverGrace** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/139#issue-1486966323

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/141
