### ISSUE TITLE
docker应用启动报错

### ISSUE THREAD

**Issue by zhouwenxiaobupt** [fuergaosi233/wechat-chatgpt#152]
![image](https://user-images.githubusercontent.com/46025787/206767713-d6089bbb-fd59-41fc-a0ae-9d128f5cdf6e.png)

把最新代码下载后，修改完配置文件后，首先安装 npm install 和 poetry  install 后， 在windows启动docker 后，在powershell,拉取镜像并登陆报错， node版本为19.2.0。
希望可以得到解答，谢谢

**Comment by xiaocin** [comment]
解决了吗

**Comment by zhouwenxiaobupt** [comment]
没呢，目前不知道啥原因

**Comment by tangyoungyang** [comment]
-v 挂载的路径有问题

**Comment by zhouwenxiaobupt** [comment]
请问该怎么修改才能运行嘛
