### ISSUE TITLE
发送消息过于频繁，可稍后再试

### ISSUE THREAD

**Issue by geekyouth** [fuergaosi233/wechat-chatgpt#155]
![image](https://user-images.githubusercontent.com/12899262/206821650-60c1590b-ebde-4c9e-8d83-bb46ba6bdd06.png)

他会一直尝试回复一个会话，但没有地方设置重试次数。这样太蠢了

**Comment by fuergaosi233** [comment]
Has anyone been Posting this?

**Comment by peterhiking** [comment]
确实 我也碰到这个问题了 只好了重启容器
