### ISSUE TITLE
大家的响应时间大概多久？

### ISSUE THREAD

**Issue by LiangYang666** [fuergaosi233/wechat-chatgpt#156]
我感觉回复的很慢，从微信发出到接收到回复，大概都在45秒以上，大家反馈响应的时间大概怎么样

**Comment by liaozhangsheng** [comment]
我是在自己电脑上用node部署的，响应也很慢

**Comment by DBeidachazi** [comment]
普通对话两分钟，生成代码要超级慢

**Comment by LiangYang666** [comment]
> 普通对话两分钟，生成代码要超级慢

那你这个太慢了，我基本都是四五十秒

**Comment by skyone123** [comment]
很慢，一分多钟

**Comment by fuergaosi233** [comment]
Thinking of using a proxy?

**Comment by skyone123** [comment]
> Thinking of using a proxy?

用的香港服务器，应该不至于代理问题

**Comment by DBeidachazi** [comment]
> > Thinking of using a proxy?
> 
> 用的香港服务器，应该不至于代理问题

你的香港服务器是可以不用使用代理的吗

**Comment by xsstomy** [comment]
对比过网页的，网页大概 5、6秒开始回答问题，问题全部回答结束之后差不多确实需要40、50秒的样子。个人也觉得慢了，然后换成openai的API，回复很快， 10 秒内回答全部问题，但是引发了新的问题，微信封号。我几个朋友号提醒异常，封了 7 天，自己的号也异常了一次。

**Comment by LiangYang666** [comment]
> 

我也拿api key使用了下，反馈的很快，我没弹出异常提醒，但是每次都会消耗账号里的金额

**Comment by ytb1079014809** [comment]
api key这个有了后，在哪里设置呀

**Comment by LiangYang666** [comment]
> > 对比过网页的，网页大概 5、6秒开始回答问题，问题全部回答结束之后差不多确实需要40、50秒的样子。个人也觉得慢了，然后换成openai的API，回复很快， 10 秒内回答全部问题，但是引发了新的问题，微信封号。我几个朋友号提醒异常，封了 7 天，自己的号也异常了一次。
> 
> 不建议对接API，回复太过频繁了，而且单独私聊的时候，很多人会瞎聊，会触发关键词，本人号第二次封了，禁止扫码登录其他的设备了。
那还是不用api了吧，/(ㄒoㄒ)/~~
