### ISSUE TITLE
Mac环境可以用吗

### ISSUE THREAD

**Issue by AlphaSue** [fuergaosi233/wechat-chatgpt#157]

**Comment by RealTong** [comment]
可以.  
只要有Node Python环境就可以了.  或者可以使用Docker

**Comment by crazygo** [comment]
我在 mac 上使用 docker 环境允许，遇到这样的错误，请问应该如何解决呢？谢谢。
poetry install
Installing dependencies from lock file

No dependencies to install or update

--
poetry show 能看到 
revchatgpt         0.0.34

但是使用 npm run dev 后，报错
raise RuntimeError("Could import revChatGPT. Please install it first. You can run `poetry install` to install it.")\n'

**Comment by fuergaosi233** [comment]
> 我在 mac 上使用 docker 环境运行，遇到这样的错误，请问应该如何解决呢？谢谢。 poetry install Installing dependencies from lock file
> 
> No dependencies to install or update
> 
> -- poetry show 能看到 revchatgpt 0.0.34
> 
> 但是使用 npm run dev 后，报错 raise RuntimeError("Could import revChatGPT. Please install it first. You can run `poetry install` to install it.")\n'

Use docker image in the README to start pls.
