### ISSUE TITLE
回复的信息不完整，话说怎么解决呢？

### ISSUE THREAD

**Issue by Josecep** [fuergaosi233/wechat-chatgpt#158]
![image](https://user-images.githubusercontent.com/115909081/206825586-ade4345b-fc16-4511-942a-e37aa2b073b4.png)

**Comment by partnerSun** [comment]
回复：继续

**Comment by Josecep** [comment]
谢谢

**Comment by Josecep** [comment]
> 

貌似，不行
![M6$)NZ44RQW%MD B$45)OU4](https://user-images.githubusercontent.com/115909081/206827492-e3339d1d-f899-421c-a762-7ec188b29429.jpg)

**Comment by RealTong** [comment]
可以在问题前加上 「请一次说完」 之类的

**Comment by Josecep** [comment]
> 可以在问题前加上 「请一次说完」 之类的

您好，群里@继续，貌似可以，还有一个问题，是不是问题和继续有时间间隔，超过多少秒，就答非所问了，
