### ISSUE TITLE
railway如何部署？

### ISSUE THREAD

**Issue by lawlite19** [fuergaosi233/wechat-chatgpt#159]

**Comment by RealTong** [comment]
1. 点击项目主页(README)上的Deploy on Railway按钮
2. 登录你的Github,
3. 添加Environment variables
4. 填写完成后点击`Deploy`
5. 然后等待Build完成之后, 去到`Deploy Logs` 查看QRCode. 如果直接扫不上的话, 点击QRCode上面的URL, 就可以食用了

**Comment by liuyuansharp** [comment]
> 
请问这种方式部署，不需要填自己的账号密码 cookie吗？ 
Environment variables 这里需要填什么呢？

**Comment by liuyuansharp** [comment]
@RealTong 
请问这种方式部署，不需要填自己的账号密码 cookie吗？
Environment variables 这里需要填什么呢？

**Comment by lawlite19** [comment]
@RealTong 
depoly log为什么是空的
![image](https://user-images.githubusercontent.com/14356062/206834998-e985cced-0aee-4a74-b010-8ce3434fa331.png)

**Comment by lawlite19** [comment]
> @RealTong depoly log为什么是空的 ![image](https://user-images.githubusercontent.com/14356062/206834998-e985cced-0aee-4a74-b010-8ce3434fa331.png)

忽略，有日志，是我网络问题没有加载..
