### ISSUE TITLE
bot安装报错

### ISSUE THREAD

**Issue by jasondeepny** [fuergaosi233/wechat-chatgpt#16]
![截屏2022-12-07 16 05 56](https://user-images.githubusercontent.com/37728137/206122980-4dc7caa2-14ed-411c-9612-429092302337.png)

**Comment by jasondeepny** [comment]
Installing dependencies from lock file

Package operations: 11 installs, 0 updates, 0 removals

  • Installing soupsieve (2.3.2.post1)
  • Installing beautifulsoup4 (4.11.1)
  • Installing certifi (2022.9.24)
  • Installing charset-normalizer (2.1.1)
  • Installing idna (3.4)
  • Installing urllib3 (1.26.13)
  • Installing bs4 (0.0.1)
  • Installing lxml (4.9.1): Failed

  CalledProcessError

  Command '['/Users/macbook/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-oB4fExls-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/macbook/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-oB4fExls-py3.10', '--no-deps', '/Users/macbook/Library/Caches/pypoetry/artifacts/a9/a6/05/7107ffa1d3867278db7f555d3b55e64d2cf97aa806317c942419c2d58d/lxml-4.9.1.tar.gz']' returned non-zero exit status 1.

  at /usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│
       530│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/macbook/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-oB4fExls-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/macbook/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-oB4fExls-py3.10', '--no-deps', '/Users/macbook/Library/Caches/pypoetry/artifacts/a9/a6/05/7107ffa1d3867278db7f555d3b55e64d2cf97aa806317c942419c2d58d/lxml-4.9.1.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/macbook/Library/Caches/pypoetry/artifacts/a9/a6/05/7107ffa1d3867278db7f555d3b55e64d2cf97aa806317c942419c2d58d/lxml-4.9.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: lxml
    Building wheel for lxml (pyproject.toml): started
    Building wheel for lxml (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Building wheel for lxml (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [91 lines of output]
        Building lxml version 4.9.1.
        Building without Cython.
        Building against libxml2 2.9.4 and libxslt 1.1.29
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.macosx-12-x86_64-cpython-310
        creating build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/_elementpath.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/sax.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/pyclasslookup.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/builder.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/doctestcompare.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/usedoctest.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/cssselect.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/ElementInclude.py -> build/lib.macosx-12-x86_64-cpython-310/lxml
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/soupparser.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/defs.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/_setmixin.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/clean.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/_diffcommand.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/html5parser.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/formfill.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/builder.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/ElementSoup.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/_html5builder.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/usedoctest.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        copying src/lxml/html/diff.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/html
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron
        copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron
        copying src/lxml/etree.h -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/etree_api.h -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/lxml.etree.h -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/lxml.etree_api.h -> build/lib.macosx-12-x86_64-cpython-310/lxml
        copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/c14n.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/__init__.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/schematron.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/tree.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/uri.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/xpath.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/xslt.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/config.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/lxml-version.h -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        copying src/lxml/includes/etree_defs.h -> build/lib.macosx-12-x86_64-cpython-310/lxml/includes
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/rng
        copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/rng
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl
        copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl
        copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl
        creating build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-12-x86_64-cpython-310/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
        running build_ext
        building 'lxml.etree' extension
        creating build/temp.macosx-12-x86_64-cpython-310
        creating build/temp.macosx-12-x86_64-cpython-310/src
        creating build/temp.macosx-12-x86_64-cpython-310/src/lxml
        clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/Users/macbook/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-oB4fExls-py3.10/include -I/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/lxml/etree.c -o build/temp.macosx-12-x86_64-cpython-310/src/lxml/etree.o -w -flat_namespace
        clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12'
        Compile failed: command '/usr/bin/clang' failed with exit code 1
        creating var
        creating var/folders
        creating var/folders/yc
        creating var/folders/yc/z8t35v1j6_7b5wvtx5n1xt8h0000gn
        creating var/folders/yc/z8t35v1j6_7b5wvtx5n1xt8h0000gn/T
        cc -I/usr/include/libxml2 -c /var/folders/yc/z8t35v1j6_7b5wvtx5n1xt8h0000gn/T/xmlXPathInitkp4wlcqw.c -o var/folders/yc/z8t35v1j6_7b5wvtx5n1xt8h0000gn/T/xmlXPathInitkp4wlcqw.o
        clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=12'
        *********************************************************************************
        Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
        Perhaps try: xcode-select --install
        *********************************************************************************
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for lxml
  Failed to build lxml
  ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects


  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/macbook/Library/Caches/pypoetry/artifacts/a9/a6/05/7107ffa1d3867278db7f555d3b55e64d2cf97aa806317c942419c2d58d/lxml-4.9.1.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│

  • Installing requests (2.28.1)
  • Installing tls-client (0.1.5)

**Comment by fuergaosi233** [comment]
I just added Docker to the list of ways you can build with Docker
