### ISSUE TITLE
"I am a beginner. Can you provide a tutorial that starts from scratch and is usable? I don't know what docter is. Thank you."

### ISSUE THREAD

**Issue by itwxb** [fuergaosi233/wechat-chatgpt#162]
"I am a beginner. Can you provide a tutorial that starts from scratch and is usable? I don't know what docter is. Thank you."

**Comment by Yecgaa1** [comment]
docker not docter！If you know Chinese, this [video ](https://www.bilibili.com/video/BV11D4y1h7iC)cna help you
If not, may be you can google "How to use docker in windows". But this project is for wechat. Are you sure you want to use wechat rather than anything else.
