### ISSUE TITLE
我的私聊可以回复，但是群聊@它没有回

### ISSUE THREAD

**Issue by Wzhishun** [fuergaosi233/wechat-chatgpt#163]
![image](https://user-images.githubusercontent.com/49648647/206827835-3310e3c0-010d-4e08-a312-5f18df1b82ba.png)

**Comment by RealTong** [comment]
Bot的微信昵称和群聊里的昵称一样吗?

**Comment by molydaner** [comment]
我现在出现了一个群可以@，另一个群@之后没反应的情况

**Comment by ZhangYiXi-dev** [comment]
群里的名称要和本身微信的名称一致才会回复

**Comment by molydaner** [comment]
> 

解决了感谢

**Comment by yunzck8s** [comment]
我也是这个问题，但是名称一致还没有触发
