### ISSUE TITLE
请问可以像网页那样继续保持同一线程对话，接下来的对话与之前的对话相关么

### ISSUE THREAD

**Issue by Yecgaa1** [fuergaosi233/wechat-chatgpt#164]

**Comment by Code-Dramatist** [comment]
有的

**Comment by Yecgaa1** [comment]
> 有的

请问该如何触发

**Comment by inannan423** [comment]
应该是默认触发的，但是在群聊中得保证相邻问题的相关性

**Comment by Yecgaa1** [comment]
噢好的，可能是早上测试时间隔太久了。顺带问一下，有计划添加回复bot来触发而不是@的功能吗

> 应该是默认触发的，但是在群聊中得保证相邻问题的相关性

**Comment by inannan423** [comment]
IDK，我不是主要贡献者，可以 @ OWNER 问一下。

**Comment by Yecgaa1** [comment]
> IDK，我不是主要贡献者，可以 @ OWNER 问一下。

好的，谢谢
