### ISSUE TITLE
0.0.3版本 Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by LemonYu997** [fuergaosi233/wechat-chatgpt#165]
config.yaml已经配置过了email、password、session_token，但是还是报错

```
🎯 Triggered ChatGPT: 你好
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:35)
    at ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:35)
    at ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:27)
    at WechatyImpl.<anonymous> (file:///app/src/main.ts:32:26)
    at WechatyImpl.emit (node:events:513:28)
    at WechatyImpl.emit (node:domain:489:12)
    at WechatyImpl.emit (file:///app/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetWechat4u.<anonymous> (file:///app/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)

```

**Comment by RealTong** [comment]
在启动之后,  `Start GPT Bot Config is:` 这一行完整的日志可以发出来吗(注意脱敏)

**Comment by luoqingchen1116** [comment]
Start GPT Bot Config is:{"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}

**Comment by qinpengzy** [comment]
我遇到了同样的问题，解决方案是重新页面把cookie的放进去就行了，我对比发现那一串auth的更新了。暂时还没研究出策略和原因，如果能帮助排查就更好了！

**Comment by luoqingchen1116** [comment]
> 在启动之后, `Start GPT Bot Config is:` 这一行完整的日志可以发出来吗(注意脱敏)



> 我遇到了同样的问题，解决方案是重新页面把cookie的放进去就行了，我对比发现那一串auth的更新了。暂时还没研究出策略和原因，如果能帮助排查就更好了！

我重新放了下  ,还是一样  我的  ,我的chatPrivateTiggerKeyword后面啥都没有,

**Comment by molydaner** [comment]
问题在config.yaml中

**Comment by RealTong** [comment]
正常的情况是: `Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"MYEMAIL","password":"MYPASSWORD"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"/chat "}
`
我感觉是你的配置文件写错了. 你可以贴出config.yaml

**Comment by molydaner** [comment]
chatGPTAccountPool:
  - session_token: <your session_token>
 上面的代码在输入到config.yaml时不要使用CTRL+V，要是用鼠标右键——粘贴才可以，用CTRL＋v时，这行代码会被加入奇怪的元素

**Comment by luoqingchen1116** [comment]
@molydaner 可以了 谢谢

**Comment by jhrcc** [comment]
> @molydaner 可以了 谢谢

请问你是通过什么部署的呢？

**Comment by luoqingchen1116** [comment]
docker+token


缘定奈何桥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fuergaosi233/wechat-chatgpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fuergaosi233/wechat-chatgpt] 0.0.3版本 Error: ⚠️ No chatgpt item in pool (Issue #165)





  
@molydaner 可以了 谢谢
  
请问你是通过什么部署的呢？

**Comment by liudao** [comment]
是空格搞的鬼，一定要加上空格
![image](https://user-images.githubusercontent.com/407607/206846575-e55092ef-7ffa-4873-b5ac-591efe5244b0.png)

**Comment by QingYang1807** [comment]
我通过修改config.yaml文件内容为如下格式，解决了这个问题

chatGPTAccountPool:
  - email: email
  - password: password
  - session_token: session_token
chatPrivateTiggerKeyword: ""

**Comment by QingYang1807** [comment]
chatGPTAccountPool:
  \- email: email
  \- password: password
  \- session_token: session_token
chatPrivateTiggerKeyword: ""

**Comment by QingYang1807** [comment]
我通过修改config.yaml格式如下，解决了这个问题
chatGPTAccountPool:
  \- email: email
  \- password: password
  \- session_token: session_token
chatPrivateTiggerKeyword: ""

**Comment by QingYang1807** [comment]
![image](https://user-images.githubusercontent.com/41716258/206855667-64b3803a-c21c-4ddd-9c58-2b7e877f87d6.png)
