### ISSUE TITLE
二维码已失效，请重新扫码登录

### ISSUE THREAD

**Issue by timedomain1** [fuergaosi233/wechat-chatgpt#168]
出现二维码以后，手机上显示已失效，请问怎么刷新一张二维码出来

**Comment by RealTong** [comment]
最简单的办法是重新运行一次

**Comment by timedomain1** [comment]
> 

能不能指导下，怎么重新运行

**Comment by RealTong** [comment]
如果你使用`npm run  dev`启动的:  你可以直接Ctrl+C退出之后重新`npm run dev`
如果你使用`Docker`启动的: `docker restart ContainerName`
如果你使用`Railway`启动的: 单击你的WechatBot 的service, 点击背景颜色为绿色的`View Logs` 旁边的三个点, 然后`restart` 按钮

**Comment by RealTong** [comment]
很高兴可以帮您解决问题! 那这个Issues我就先关闭了.
