### ISSUE TITLE
扫码登陆后没有提示命名机器人

### ISSUE THREAD

**Issue by ysrock** [fuergaosi233/wechat-chatgpt#17]
User Contact<rock> logged in
Chatgpt pool size: 1
Message: Message#Unknown[🗣Contact<rock>]

如何开始使用？@什么名字可以开始呢？

**Comment by ysrock** [comment]
我自己还没用上，机器人和公众号聊上了。。

**Comment by fuergaosi233** [comment]
> User Contact logged in Chatgpt pool size: 1 Message: Message#Unknown[🗣Contact]
> 
> 如何开始使用？@什么名字可以开始呢？

You can chat directly @ it in a group or in private chat.

**Comment by ysrock** [comment]
> > User Contact logged in Chatgpt pool size: 1 Message: Message#Unknown[🗣Contact]
> > 如何开始使用？@什么名字可以开始呢？
> 
> You can chat directly @ it in a group or in private chat.

好的，以前没用过wechaty机器人，刚才实验成功了。

**Comment by zhanglp92** [comment]
> 

你怎么做的? 登录成功了，但不知道咋使用

**Comment by kevinsir** [comment]
怎么试验的哇。。。我也是，提示机器人成功了，但是不会回消息

**Comment by ysrock** [comment]
用另外的微信给登录了机器人的微信发信息即可，也可以在群里@

kevinsir ***@***.***> 于2022年12月13日周二 12:36写道：
