### ISSUE TITLE
多个聊天的上下文隔离

### ISSUE THREAD

**Issue by tete1030** [fuergaosi233/wechat-chatgpt#171]
目前的实现里，多个聊天之间共用同一个chat上下文，会导致多个群聊之间的对话泄漏。能不能使用不同的上下文

**Comment by fuergaosi233** [comment]
No, Each user will have their own context.

**Comment by tete1030** [comment]
先别着急关哈，我做了实验的，你可以在两个聊天里做实验。我的实验是：
1. A: 群聊，问一个问题，等待回答
2. B: 私聊bot，问另一个问题，等待回答
3. 在A里问：“我的上一个问题是什么”，Bot准确给出了在B里的回答。

这说明两个会话是共用的

**Comment by tete1030** [comment]
不知道是不是因为我使用了session_token作为登陆凭证导致的

**Comment by tete1030** [comment]
> No, Each user will have their own context.

我又理解了一次，你的意思是说，每个聊天用户是自己的context，但是不分群聊和私聊，对吗？这个可以改进吗

**Comment by sunshanpeng** [comment]
这确实有点点问题，因为conversation需要一个问题结束后才能继续下一个，如果同一个用户在不同群里使用机器人的话很容易限流，我看看提个PR
