### ISSUE TITLE
群聊被@以后出现`uncaughtException GError: socket hang up`错误

### ISSUE THREAD

**Issue by protectione055** [fuergaosi233/wechat-chatgpt#172]
扫码登陆后，从终端可以看到群聊信息，但是被@后直接报错退出。这是我看到的报错信息：
```
uncaughtException GError: socket hang up
    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketOnEnd (node:_http_client:518:9)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (node:domain:489:12) {
  code: 2,
  details: 'Error: socket hang up\n' +
    '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at TLSSocket.socketOnEnd (node:_http_client:518:9)\n' +
    '    at TLSSocket.emit (node:events:525:35)\n' +
    '    at TLSSocket.emit (node:domain:489:12)'
}
06:15:59 WARN PuppetWechat4u contactRawPayload(Error: socket hang up) wechat4u.batchGetContact() exception: undefined
06:16:01 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}
```

重新登陆后对私聊功能进行了测试，返回`错误代码429`后程序退出：
```
🎯 Triggered ChatGPT: 你是谁
err is ChatGPTAPI error 429
```

请问有人知道是什么问题吗？

**Comment by RealTong** [comment]
> 扫码登陆后，从终端可以看到群聊信息，但是被@后直接报错退出。这是我看到的报错信息：
> 
> ```
> uncaughtException GError: socket hang up
>     at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)
>     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)
>     at RedirectableRequest.emit (node:events:525:35)
>     at RedirectableRequest.emit (node:domain:489:12)
>     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
>     at ClientRequest.emit (node:events:513:28)
>     at ClientRequest.emit (node:domain:489:12)
>     at TLSSocket.socketOnEnd (node:_http_client:518:9)
>     at TLSSocket.emit (node:events:525:35)
>     at TLSSocket.emit (node:domain:489:12) {
>   code: 2,
>   details: 'Error: socket hang up\n' +
>     '    at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
>     '    at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:518:25)\n' +
>     '    at RedirectableRequest.emit (node:events:525:35)\n' +
>     '    at RedirectableRequest.emit (node:domain:489:12)\n' +
>     '    at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)\n' +
>     '    at ClientRequest.emit (node:events:513:28)\n' +
>     '    at ClientRequest.emit (node:domain:489:12)\n' +
>     '    at TLSSocket.socketOnEnd (node:_http_client:518:9)\n' +
>     '    at TLSSocket.emit (node:events:525:35)\n' +
>     '    at TLSSocket.emit (node:domain:489:12)'
> }
> 06:15:59 WARN PuppetWechat4u contactRawPayload(Error: socket hang up) wechat4u.batchGetContact() exception: undefined
> 06:16:01 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
> uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
>     at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
>     at Watchdog.emit (node:events:513:28)
>     at Watchdog.emit (node:domain:489:12)
>     at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
>     at listOnTimeout (node:internal/timers:559:17)
>     at processTimers (node:internal/timers:502:7) {
>   code: 2,
>   details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
>     '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
>     '    at Watchdog.emit (node:events:513:28)\n' +
>     '    at Watchdog.emit (node:domain:489:12)\n' +
>     '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
>     '    at listOnTimeout (node:internal/timers:559:17)\n' +
>     '    at processTimers (node:internal/timers:502:7)'
> }
> ```
> 
> 重新登陆后对私聊功能进行了测试，返回`错误代码429`后程序退出：
> 
> ```
> 🎯 Triggered ChatGPT: 你是谁
> err is ChatGPTAPI error 429
> ```
> 
> 请问有人知道是什么问题吗？

https://github.com/fuergaosi233/wechat-chatgpt/issues/26

**Comment by protectione055** [comment]
错误代码429的问题过一段时间就解决了，但是微信登陆后`uncaughtException GError: socket hang up`的问题还在，而且没找到相关的issue

**Comment by h596865948** [comment]
配置多个账号时除首个账号 其他都会出现err is ChatGPTAPI error 429  是请求限制的问题么？  那这一个群里只能一个个排队问问题了吗
