### ISSUE TITLE
AttributeError: 'OpenAIAuth' object has no attribute 'session_token'

### ISSUE THREAD

**Issue by JerryKingQAQ** [fuergaosi233/wechat-chatgpt#173]
![image](https://user-images.githubusercontent.com/95563982/206836074-72e7c35b-b2f8-4c6a-a4d2-2cf13b81444b.png)
版本已经更新到0.033.5了，依然会出现题目错误

**Comment by superlwb** [comment]
> ![image](https://user-images.githubusercontent.com/95563982/206836074-72e7c35b-b2f8-4c6a-a4d2-2cf13b81444b.png) 版本已经更新到0.033.5了，依然会出现题目错误

是不是你配置文件错了？
如果是用session_token的话，配置文件把前面两个属性删除了。
例如：
![image](https://user-images.githubusercontent.com/76443237/206837655-9e09ea69-3906-495a-9ace-ca3296b6d028.png)

**Comment by JerryKingQAQ** [comment]
> > ![image](https://user-images.githubusercontent.com/95563982/206836074-72e7c35b-b2f8-4c6a-a4d2-2cf13b81444b.png) 版本已经更新到0.033.5了，依然会出现题目错误
> 
> 是不是你配置文件错了？ 如果是用session_token的话，配置文件把前面两个属性删除了。 例如： ![image](https://user-images.githubusercontent.com/76443237/206837655-9e09ea69-3906-495a-9ace-ca3296b6d028.png)

你好，使用的是账户密码的方式
![image](https://user-images.githubusercontent.com/95563982/206838031-654f4e74-eeb1-44c0-87c9-d546c7c1c83b.png)

**Comment by JerryKingQAQ** [comment]
> > ![image](https://user-images.githubusercontent.com/95563982/206836074-72e7c35b-b2f8-4c6a-a4d2-2cf13b81444b.png) 版本已经更新到0.033.5了，依然会出现题目错误
> 
> 是不是你配置文件错了？ 如果是用session_token的话，配置文件把前面两个属性删除了。 例如： ![image](https://user-images.githubusercontent.com/76443237/206837655-9e09ea69-3906-495a-9ace-ca3296b6d028.png)

![image](https://user-images.githubusercontent.com/95563982/206838122-cd252550-f96c-4af5-b49d-4282b92f12b0.png)
具体的报错如上

**Comment by superlwb** [comment]
使用账号登录的话，因为地域限制，中国在内，所以不能正常登录，需要配置代理才可以登录。我推荐您使用我的方法试试。

**Comment by JerryKingQAQ** [comment]
> 使用账号登录的话，因为地域限制，中国在内，所以不能正常登录，需要配置代理才可以登录。我推荐您使用我的方法试试。

服务器是在首尔的，应该可以吧？

**Comment by JerryKingQAQ** [comment]
已解决，将镜像全部删除重装。
