### ISSUE TITLE
会不会有微信号被盗的风险？

### ISSUE THREAD

**Issue by EpicWang** [fuergaosi233/wechat-chatgpt#174]
不太懂这个原理是什么，但是微信授权登陆，会不会有账号被盗的风险？

**Comment by Yecgaa1** [comment]
登录是在部署服务器上模拟电脑端登录而已，如果你的服务器是你自己掌控的那至少这个项目没有让你增加被盗号的风险，但是你自己的数据安全仍要你自己负责

**Comment by nt1r** [comment]
我也有这个疑问，今天遇到这个Error吓死我了。

const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(你需要开通微信支付，才可继续操作。)
    at Function.from (D:\TypeScript_Projects\wechat_bot\node_modules\gerror\src\gerror\gerror.ts:69:17)
    at Bridge.onDialog (D:\TypeScript_Projects\wechat_bot\node_modules\wechaty-puppet-wechat\src\bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(你需要开通微信支付，才可继续操作。)\n' +
    '    at Function.from (D:\\TypeScript_Projects\\wechat_bot\\node_modules\\gerror\\src\\gerror\\gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (D:\\TypeScript_Projects\\wechat_bot\\node_modules\\wechaty-puppet-wechat\\src\\bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

这都明摆在这里了，让你开通微信支付才能继续操作。之后他跑不跑路我都不敢想，兄弟。
