### ISSUE TITLE
 'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' +

### ISSUE THREAD

**Issue by kukico** [fuergaosi233/wechat-chatgpt#177]
Anyone has solutions to error  'Error: getaddrinfo EAI_AGAIN login.wx.qq.com\n' ?

**Comment by IIsoo** [comment]
me too, how to solve this problem?

**Comment by luoqingchen1116** [comment]
check your dns

**Comment by RealTong** [comment]
It seems to be the same problem as https://github.com/fuergaosi233/wechat-chatgpt/issues/180
