### ISSUE TITLE
uncaughtException GError: getaddrinfo EAI_AGAIN login.wx.qq.com

### ISSUE THREAD

**Issue by luoqingchen1116** [fuergaosi233/wechat-chatgpt#180]
![图片](https://user-images.githubusercontent.com/86885717/206840831-f419fd06-31fd-4cae-98d5-7507194b6f8e.png)

**Comment by fuergaosi233** [comment]
Check your DNS configuration, it should be irrelevant to the project 🤔.

**Comment by IIsoo** [comment]
> 

怎么检查DNS设置啊，我正好就是用这个服务器搭了个网站，好像改了DNS

**Comment by realstatus** [comment]
如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt

**Comment by luoqingchen1116** [comment]
> 如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt

感谢大哥   可以了

**Comment by ymaGo** [comment]
大佬，win11使用docker出现同样的错误，如何解决？

**Comment by ymaGo** [comment]
> 

大佬，win11使用docker出现同样错误，如何解决？

**Comment by ymaGo** [comment]
> 如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt

大佬，win11使用docker出现同样错误，如何解决？

**Comment by ehye** [comment]
> > 如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt
> 
> 大佬，win11使用docker出现同样错误，如何解决？


Try add DNS in Docker Desktop - Setting - Docker Engine

```json
"dns": [
    "8.8.8.8"
  ]
```

**Comment by ymaGo** [comment]
> > > 如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt
> > 
> > 
> > 大佬，win11使用docker出现同样错误，如何解决？
> 
> Try add DNS in Docker Desktop - Setting - Docker Engine
> 
> ```json
> "dns": [
>     "8.8.8.8"
>   ]
> ```

成功了，感谢

**Comment by Waterkin** [comment]
> > > > 如果是用docker搭建的话，可能是docker无法上网，可以使用systemctl restart docker来重新启动docker，然后重启wechat-chatgpt
> > > 
> > > 
> > > 大佬，win11使用docker出现同样错误，如何解决？
> > 
> > 
> > Try add DNS in Docker Desktop - Setting - Docker Engine
> > ```json
> > "dns": [
> >     "8.8.8.8"
> >   ]
> > ```
> 
> 成功了，感谢

成功了，感谢！
