### ISSUE TITLE
拉到微信群里以后，短时间艾特了多次，问了太多问题，现在遇到 “OpenAI 服务器限流，请稍后再试”，  请问这个多久会恢复呢？ 还是说需要手动进行别的操作？

### ISSUE THREAD

**Issue by Sherlockliu7777** [fuergaosi233/wechat-chatgpt#182]
拉到微信群里以后，短时间艾特了多次，问了太多问题，现在遇到 “OpenAI 服务器限流，请稍后再试”，  请问这个多久会恢复呢？ 还是说需要手动进行别的操作？

**Comment by RealTong** [comment]
不确定多长时间会恢复.
只能减少请求次数, 这是OpenAI限制的

**Comment by gaoobin** [comment]
> 拉到微信群里以后，短时间艾特了多次，问了太多问题，现在遇到 “OpenAI 服务器限流，请稍后再试”， 请问这个多久会恢复呢？ 还是说需要手动进行别的操作？

我也出现了这个问题，你的多久恢复的？
