### ISSUE TITLE
error.response.headers['set-cookie'] [

### ISSUE THREAD

**Issue by varnew** [fuergaosi233/wechat-chatgpt#184]
微信扫码确认登陆后，控制台输出下列信息，且机器人没有反应
error.response.headers['set-cookie'] [

**Comment by RealTong** [comment]
I had the same error.
I restarted the app and the error disappeared, then everything was fine

**Comment by xrwang8** [comment]
I had the same error.I am deployed on Japanese ecs

**Comment by bdss58** [comment]
me too~

**Comment by Hsheep9** [comment]
我的bot 报错“something went wrong”
![image](https://user-images.githubusercontent.com/100297006/225028405-b0dc3ae7-1f77-4d83-b227-c4245ccda1c7.png)
