### ISSUE TITLE
用的railway部署，这是OpenAI账号原因吗?

### ISSUE THREAD

**Issue by jmpcyc** [fuergaosi233/wechat-chatgpt#188]
at async ChatGPTPoole.startPools (file:///app/src/chatgpt.ts:136:26)
at async ChatGPTBot.startGPTBot (file:///app/src/chatgpt.ts:233:5)
at async WechatyImpl.<anonymous> (file:///app/src/main.ts:23:7) {
shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py smtp****@outlook.com ******',
command: 'sh -c poetry run python3 src/generate_session.py smtp**@outlook.com *****',
escapedCommand: 'sh -c "poetry run python3 src/generate_session.py smtp**@outlook.com *****"',
exitCode: 1,
signal: undefined,
signalDescription: undefined,
stdout: "Namespace(email='smtp****@outlook.com', password='*****')",
stderr: 'Traceback (most recent call last):\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 309, in part_seven\n' +
'    self.part_eight(old_state=state, new_state=new_state)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 363, in part_eight\n' +
'    raise Exception("Auth0 did not issue an access token")\n' +
'Exception: Auth0 did not issue an access token\n' +
'\n' +
'During handling of the above exception, another exception occurred:\n' +
'\n' +
'Traceback (most recent call last):\n' +
'  File "/app/src/generate_session.py", line 50, in <module>\n' +
'    print(login(args.email, args.password))\n' +
'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
'  File "/app/src/generate_session.py", line 19, in login\n' +
'    chatbot = Chatbot(\n' +
'              ^^^^^^^^\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__\n' +
'    self.refresh_session()\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session\n' +
'    raise exc\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session\n' +
'    self.login(self.config["email"], self.config["password"])\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login\n' +
'    raise exc\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login\n' +
'    auth.begin()\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin\n' +
'    self.part_two()\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two\n' +
'    self.part_three(token=csrf_token)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 147, in part_three\n' +
'    self.part_four(url=url)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 181, in part_four\n' +
'    self.part_five(state=state)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 220, in part_five\n' +
'    self.part_six(state=state, captcha=None)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 263, in part_six\n' +
'    self.part_seven(state=state)\n' +
'  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 314, in part_seven\n' +
'    raise Exception("State not found")\n' +
'Exception: State not found',
failed: true,
timedOut: false,
isCanceled: false,
killed: false
}

**Comment by RealTong** [comment]
This may be an account or OpenAI issue, not related to the project.

**Comment by fuergaosi233** [comment]
> This may be an account or OpenAI issue, not related to the project.

Your are right
@jmpcyc  Pls check you can login via this account pls.
