### ISSUE TITLE
请问大家有用nas安装成功的么？代理如何设置？

### ISSUE THREAD

**Issue by stjacob** [fuergaosi233/wechat-chatgpt#190]

**Comment by zyxhe** [comment]
威联通成功了，没用代理，就是获得token的时候用了下梯子

**Comment by stjacob** [comment]
> 威联通成功了，没用代理，就是获得token的时候用了下梯子
不用设置代理么？直接连没问题？

**Comment by zyxhe** [comment]
> Reference

NAS没有代理，配置好config.yaml里的token扫码登陆就可用了

**Comment by zyxhe** [comment]
> > 威联通成功了，没用代理，就是获得令牌的时候用了下梯子 不用设置代理么？直接连没问题？



> 不用设置代理么？直接连没问题？

NAS没有代理，配置好config.yaml里的token扫码登陆就可用了

**Comment by stjacob** [comment]
用token搞好了。谢谢
