### ISSUE TITLE
在扫码确认登录后报错

### ISSUE THREAD

**Issue by NagatoYuki0** [fuergaosi233/wechat-chatgpt#192]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

**Comment by RealTong** [comment]
Related Issues already exist https://github.com/fuergaosi233/wechat-chatgpt/issues/84 , we should not open too many of the same issues

**Comment by hqzh** [comment]
![image](https://user-images.githubusercontent.com/26128706/206853532-a345a805-c032-433a-b0e8-9c2857956f72.png)
