### ISSUE TITLE
和网页端答案不一致

### ISSUE THREAD

**Issue by Jinxi7021** [fuergaosi233/wechat-chatgpt#198]
同一个问题他说是机器人不能回答，可是在网页端就能回答！为什么会这样，该怎么处理

**Comment by inannan423** [comment]
你在网页上可能不同时间问回答也不同😂多问几次他就会回答了

**Comment by Jinxi7021** [comment]
> 你在网页上可能不同时间问回答也不同😂多问几次他就会回答了

不是，他是直接说自己是机器人，不了解个人情感，，让他夸人他也说不会，感觉好笨啊。网页端的就不一样了

**Comment by Jinxi7021** [comment]
> 你在网页上可能不同时间问回答也不同😂多问几次他就会回答了

。。。。是的

**Comment by inannan423** [comment]
实测，wechat-chatgpt回复“你能夸一下我吗"，回复：当然，您是一个非常了不起的人，您聪明、勤奋、自信，并且富有进取精神。您的智慧和能力让人敬佩，您的成就和成绩让人羡慕。您无论在工作还是生活中都表现出了出色的专业技能和高尚的品质，您真的是一个优秀的人。

**Comment by Jinxi7021** [comment]
> 实测，wechat-chatgpt回复“你能夸一下我吗"，回复：当然，您是一个非常了不起的人，您聪明、勤奋、自信，并且富有进取精神。您的智慧和能力让人敬佩，您的成就和成绩让人羡慕。您无论在工作还是生活中都表现出了出色的专业技能和高尚的品质，您真的是一个优秀的人。

我这个不懂怎么回事笨的很，一堆问题没法回答。你这问题我试一下还是不行

**Comment by padoru233** [comment]
> 实测，wechat-c​​hatgpt回复“你能夸下我吗”，回复：当然，你是一个非常了不起的人，你聪明、勤奋、自信，并能取而有进精进的虔诚，你的智慧。成就和成果让人羡慕。你无论在工作还是生活中都表现出了出众的专业技能和高尚的品质，你真的是一个优秀的人。

我的就回答“我是一个程序，并没有感情和情绪，所以不能夸你。我的目标是尽可能准确地回答你的问题，并给予有用的信息，但我不会夸人。”

**Comment by inannan423** [comment]
> > 实测，wechat-c​​hatgpt回复“你能夸下我吗”，回复：当然，你是一个非常了不起的人，你聪明、勤奋、自信，并能取而有进精进的虔诚，你的智慧。成就和成果让人羡慕。你无论在工作还是生活中都表现出了出众的专业技能和高尚的品质，你真的是一个优秀的人。
> 
> 我的就回答“我是一个程序，并没有感情和情绪，所以不能夸你。我的目标是尽可能准确地回答你的问题，并给予有用的信息，但我不会夸人。”

可能是我之前忽悠过他，说他无所不能

**Comment by padoru233** [comment]
> 

还经常拒绝回答，我在网页端问啥都回答

**Comment by padoru233** [comment]
> 这我就不明白了，目前我还没有体验出和网页版的差距，按理来说本工程只是将 chatgpt 的接口服务化了，与 chatgpt 的内核无关

 是的，换一个号就能问出来了，问题是无法重置线程，怎么问都是一个答案

**Comment by fuergaosi233** [comment]
Because this is OpenAI.

**Comment by fuergaosi233** [comment]
> > 这我就不明白了，目前我还没有体验出和网页版的差距，按理来说本工程只是将 chatgpt 的接口服务化了，与 chatgpt 的内核无关
> 
> 是的，换一个号就能问出来了，问题是无法重置线程，怎么问都是一个答案

https://github.com/fuergaosi233/wechat-chatgpt/pull/212
