### ISSUE TITLE
AttributeError: 'OpenAIAuth' object has no attribute 'session_token'

### ISSUE THREAD

**Issue by AeroXi** [fuergaosi233/wechat-chatgpt#2]
after scanning the QR code:
```
shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py example@qq.com password',
  command: 'sh -c poetry run python3 src/generate_session.py example@qq.com password',
  escapedCommand: 'sh -c "poetry run python3 src/generate_session.py example@qq.com password"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "['src/generate_session.py', 'example@qq.com', 'password']\n" +
    'Logging in...',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/Users/aeroxi/projects/wechat-chatgpt/src/generate_session.py", line 29, in <module>\n' +
    '    print(login(email, password))\n' +
    '  File "/Users/aeroxi/projects/wechat-chatgpt/src/generate_session.py", line 15, in login\n' +
    '    chatbot.login(\n' +
    '  File "/Users/aeroxi/Library/Caches/pypoetry/virtualenvs/chatbot-twitter-j1zZPlSb-py3.10/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 171, in login\n' +
    "    self.config['session_token'] = auth.session_token\n" +
    "AttributeError: 'OpenAIAuth' object has no attribute 'session_token'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by fuergaosi233** [comment]
From my experience, you may need to set a proxy. You can use
``` sh
export http_proxy=<YOUR PROXY>
```
to enable proxy.

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102 
I add seesion_token support, you can try use session token use ChatGPT

**Comment by foreveryuu** [comment]
我设置了代理，同样没有解决问题，使用PyChatGPT项目的时候，设置代理是有效的

**Comment by foreveryuu** [comment]
> [#6（评论）](https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102) 我添加了 seesion_token 支持，你可以尝试使用会话令牌使用 ChatGPT

我设置了代理，同样没有解决问题，使用PyChatGPT项目的时候，设置代理是有效的

**Comment by foreveryuu** [comment]
> [#6（评论）](https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102) 我添加了seesion_token支持，你可以尝试使用会话指令牌使用ChatGPT

另外也试过设置seesion_token，同样无效，同时观察到seesion_token似乎一直在变化

**Comment by fuergaosi233** [comment]
> > [#6（评论）](https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102) 我添加了seesion_token支持，你可以尝试使用会话指令牌使用ChatGPT
> 
> 另外也试过设置seesion_token，同样无效，同时观察到seesion_token似乎一直在变化

Could you use `poetry run python3 src/generate_session.py <Your Email> <Your Password>` to test?

**Comment by fuergaosi233** [comment]
According to the experience, you should first determine whether your IP can log in to Open AI. For example, HK IP cannot use openAPI.

**Comment by foreveryuu** [comment]
> 

我可以登录OpenAI，用的是韩国IP

**Comment by foreveryuu** [comment]
> > > [#6（评论）](https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102)我添加了seesion_token支持，你可以尝试使用会话指示牌使用ChatGPT
> > 
> > 
> > 其他人也尝试过设置seesion_token，同样无效，同时观察到seesion_token似乎一直在变化
> 
> 你可以`poetry run python3 src/generate_session.py <Your Email> <Your Password>`用来测试吗？

想问一下这是完整命令吗？<Your Email> <Your Password>需要在输入吗？似乎不需要

**Comment by foreveryuu** [comment]
> 根据经验，首先要判断自己的IP是否可以登录Open AI。例如，HK IP 不能使用 openAPI。

<img width="566" alt="image" src="https://user-images.githubusercontent.com/119954620/206151882-1c3be535-c20c-47b4-8fef-1c219a017275.png">
看起来是因为这个py文件引起的

**Comment by OliverGrace** [comment]
@AeroXi plz clear your password

**Comment by OliverGrace** [comment]
I setup on a server located in US. Same issue. Only if I fill in account, passwd, and token it won't output error log. But got ChatGPT error 503 after interacting with the bot

**Comment by OliverGrace** [comment]
And the docker container building will faile at step 5/11 `COPY package*.json .`. And the container tags will be <none>. Even if i manually tag it, it won't work. the container will be stopped itself.

**Comment by fuergaosi233** [comment]
> > > > [#6（评论）](https://github.com/fuergaosi233/wechat-chatgpt/pull/6#issue-1480678102) 我添加了seesion_token支持，你可以尝试使用会话指令牌使用ChatGPT
> > > 
> > > 
> > > 另外也试过设置seesion_token，同样无效，同时观察到seesion_token似乎一直在变化
> > 
> > 
> > Could you use `poetry run python3 src/generate_session.py <Your Email> <Your Password>` to test?
> 
> Logging in... Traceback (most recent call last): File "/app/src/generate_session.py", line 29, in print(login(email, password)) ^^^^^^^^^^^^^^^^^^^^^^ File "/app/src/generate_session.py", line 15, in login chatbot.login( File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 171, in login self.config['session_token'] = auth.session_token ^^^^^^^^^^^^^^^^^^ AttributeError: 'OpenAIAuth' object has no attribute 'session_token'

Can you be sure you can log in successfully on OpenAI website?

**Comment by wuxiaodong1208** [comment]
最新的版本还是有这个问题呢。同样的账号密码和session_token 在 0.0.2-alpha 版本是可以的。 不是代理问题
