### ISSUE TITLE
docker部署之后,给登录的微信账号发消息没有回复,日志上面也显示微信消息了,就是没有回复

### ISSUE THREAD

**Issue by creazytom** [fuergaosi233/wechat-chatgpt#200]

**Comment by Asap-roland** [comment]
一样

**Comment by bluesyk** [comment]
程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。
这种模式一开始也把我绕晕了。

要支持自己答复自己，修改一下代码。
https://github.com/fuergaosi233/wechat-chatgpt/blob/main/src/chatgpt.ts  注释掉294，重启容器就可以了。
![image](https://user-images.githubusercontent.com/17310897/206855947-de397422-a11a-4e42-aff9-5c1ef38633c7.png)


1.登录容器docker exec -it wechat-chatgpt  bash
2.apt-get install vim 安装编辑器
3. 然后到src目录编辑vim  chatgpt.ts，修改后保存退出。
4. 退出容器，重启容器即可。docker restart  wechat-chatgpt

备注：也可以拷贝出来编辑后在拷贝回去。 docker cp命令。

不过自己的第一次提问有的时候问题是英文，后面就正常了。原因未知。

**Comment by bluesyk** [comment]
不过如果提问的速度太快，就会碰到OpenAI服务器限流的情况，不过稍等会儿答复也会回自动回来。

**Comment by bbhxwl** [comment]
> 程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 这种模式一开始也把我绕晕了，一开始折腾的其他几个wechat-chatgpt,默认都是可以自己和自己聊天的。
> 
> 要支持自己答复自己，修改一下代码。 https://github.com/fuergaosi233/wechat-chatgpt/blob/main/src/chatgpt.ts 注释掉294，重启容器就可以了。 ![image](https://user-images.githubusercontent.com/17310897/206855947-de397422-a11a-4e42-aff9-5c1ef38633c7.png)
> 
> 1.登录容器docker exec -it wechat-chatgpt bash 2.apt-get install vim 安装编辑器 3. 然后到src目录编辑vim chatgpt.ts，修改后保存退出。 4. 退出容器，重启容器即可。docker restart wechat-chatgpt
> 
> 备注：也可以拷贝出来编辑后在拷贝回去。 docker cp命令。
> 
> 不过自己的第一次提问有的时候回答是英文，后面就正常了。原因未知。

此时此刻，各种出错不知道为什么，刚才还能说话了。

**Comment by bluesyk** [comment]
不行就先回退吧，我这边是用docker安装的，修改后可以自己和自己通话。
另外还加了一些打印日志，把chatGPT的应答也打出来了，不过一开始回答复英文的有点奇怪。

![image](https://user-images.githubusercontent.com/17310897/206858364-b014028a-4a51-4ff0-889e-b38278344b56.png)

**Comment by acheong08** [comment]
@bluesyk When I try to send a message to myself, this error occurs: https://github.com/fuergaosi233/wechat-chatgpt/issues/116 

How did you get it to send?

**Comment by yangyunhui1999** [comment]
> 程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 这种模式一开始也把我绕晕了，一开始折腾的其他几个wechat-chatgpt,默认都是可以自己和自己聊天的。
> 
> 要支持自己答复自己，修改一下代码。 https://github.com/fuergaosi233/wechat-chatgpt/blob/main/src/chatgpt.ts 注释掉294，重启容器就可以了。 ![image](https://user-images.githubusercontent.com/17310897/206855947-de397422-a11a-4e42-aff9-5c1ef38633c7.png)
> 
> 1.登录容器docker exec -it wechat-chatgpt bash 2.apt-get install vim 安装编辑器 3. 然后到src目录编辑vim chatgpt.ts，修改后保存退出。 4. 退出容器，重启容器即可。docker restart wechat-chatgpt
> 
> 备注：也可以拷贝出来编辑后在拷贝回去。 docker cp命令。
> 
> 不过自己的第一次提问有的时候回答是英文，后面就正常了。原因未知。



> 程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 这种模式一开始也把我绕晕了，一开始折腾的其他几个wechat-chatgpt,默认都是可以自己和自己聊天的。
> 
> 要支持自己答复自己，修改一下代码。 https://github.com/fuergaosi233/wechat-chatgpt/blob/main/src/chatgpt.ts 注释掉294，重启容器就可以了。 ![image](https://user-images.githubusercontent.com/17310897/206855947-de397422-a11a-4e42-aff9-5c1ef38633c7.png)
> 
> 1.登录容器docker exec -it wechat-chatgpt bash 2.apt-get install vim 安装编辑器 3. 然后到src目录编辑vim chatgpt.ts，修改后保存退出。 4. 退出容器，重启容器即可。docker restart wechat-chatgpt
> 
> 备注：也可以拷贝出来编辑后在拷贝回去。 docker cp命令。
> 
> 不过自己的第一次提问有的时候回答是英文，后面就正常了。原因未知。

我这边注释后，自己跟自己聊天能够触发chatgpt，但是到talker.say后报发送文本消息失败的错误
![1670738072266](https://user-images.githubusercontent.com/49811653/206888726-64ada46a-c9f7-4163-892e-6757ffa7018f.png)
