### ISSUE TITLE
arm mac m1

### ISSUE THREAD

**Issue by paything** [fuergaosi233/wechat-chatgpt#204]
OSError: /root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

**Comment by fuergaosi233** [comment]
Use docker deploy pls.

**Comment by paything** [comment]
i user docker on arm64 machine
