### ISSUE TITLE
wechat offline

### ISSUE THREAD

**Issue by paything** [fuergaosi233/wechat-chatgpt#207]
ARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}
uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)\n' +
    '    at RedirectableRequest.emit (node:events:513:28)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at Timeout.<anonymous> (/app/node_modules/follow-redirects/index.js:169:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'

**Comment by fuergaosi233** [comment]
This is a problem with Wechaty where you need to restart the service to relogin.

**Comment by theLastWinner** [comment]
> This is a problem with Wechaty where you need to restart the service to relogin.

请问，有什么方式可以解决吗？我看Wechaty 最近都没有更新了。 @fuergaosi233

**Comment by yucheng-Li** [comment]
puppet: 'wechaty-puppet-wechat' is work fine

**Comment by wdodo** [comment]
> ARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000} uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}" at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33) at Watchdog.emit (node:events:513:28) at Watchdog.emit (node:domain:489:12) at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) { code: 2, details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' + ' at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' + ' at Watchdog.emit (node:events:513:28)\n' + ' at Watchdog.emit (node:domain:489:12)\n' + ' at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' + ' at listOnTimeout (node:internal/timers:559:17)\n' + ' at processTimers (node:internal/timers:502:7)' } uncaughtException GError [AxiosError]: timeout of 60000ms exceeded at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16) at RedirectableRequest.emit (node:events:513:28) at RedirectableRequest.emit (node:domain:489:12) at Timeout. (/app/node_modules/follow-redirects/index.js:169:12) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) { code: 2, details: 'AxiosError: timeout of 60000ms exceeded\n' + ' at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)\n' + ' at RedirectableRequest.emit (node:events:513:28)\n' + ' at RedirectableRequest.emit (node:domain:489:12)\n' + ' at Timeout. (/app/node_modules/follow-redirects/index.js:169:12)\n' + ' at listOnTimeout (node:internal/timers:559:17)\n' + ' at processTimers (node:internal/timers:502:7)'

问题解决了吗？

**Comment by yucheng-Li** [comment]
已收到

**Comment by yiv** [comment]
uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
at RedirectableRequest.handleRequestTimeout (/app/node_modules/axios/lib/adapters/http.js:555:16)
at RedirectableRequest.emit (node:events:513:28)
at RedirectableRequest.emit (node:domain:489:12)
at Timeout. (/app/node_modules/follow-redirects/index.js:169:12)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7) {
code: 2,

同样的错误，跑一段时间后，就会报错导致机器人掉线

**Comment by yucheng-Li** [comment]
已收到
