### ISSUE TITLE
docker logs -f 这一步出错了

### ISSUE THREAD

**Issue by BAILE2852** [fuergaosi233/wechat-chatgpt#209]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:438:20)
    at Object.readFileSync (node:fs:484:19)
    at file:///app/src/config.ts:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Cupcc** [comment]
请用文本编辑器，将所有缩进用空格打出来，注意冒号后存在空格。 不要用ide会自动将空格转换成tab。

**Comment by BAILE2852** [comment]
是在session_token的格式吗？我按照视频上边来的还是没解决

**Comment by fuergaosi233** [comment]
Make sure you put the configuration in container

**Comment by Carlingwang** [comment]
遇到了同样的问题，你解决了吗

**Comment by BAILE2852** [comment]
> 遇到了同样的问题，你解决了吗

我也是个新手 搞不太明白

**Comment by Carlingwang** [comment]
![image](https://user-images.githubusercontent.com/105225658/206939049-2922760d-bda7-44b6-9bfe-3179707971d8.png)

**Comment by Carlingwang** [comment]
你的是这样吗

**Comment by BAILE2852** [comment]
我在我的虚拟机上跑的 一样的报错

**Comment by Carlingwang** [comment]
这个解决了，config里面写错了，账号和token都不需要<>

**Comment by BAILE2852** [comment]
我的原本config里面就没加<>
