### ISSUE TITLE
please add access token support for openai

### ISSUE THREAD

**Issue by fanson** [fuergaosi233/wechat-chatgpt#21]
please add access token support for openai
the cookie will be expired, maybe the access token would be better

**Comment by fuergaosi233** [comment]
As far as I know, ChatGPT does not currently support API calls to 🤔

**Comment by BoundlessLearning** [comment]
> 

我看文档是有的啊，而且不通过库也能直接通过HTTP调用。它的例子里就有用curl调用的。拼上header和参数就直接Post
原文地址在这儿：https://beta.openai.com/docs/api-reference/making-requests

**Comment by UNICKCHENG** [comment]
> > As far as I know, ChatGPT does not currently support API calls to 🤔
> > 我看它官网文档里是有的，可以直接通过HTTP调用，例子里就是用curl，header里写API_TOKEN，拼上参数直接POST就行了。
> > https://beta.openai.com/docs/api-reference/making-requests

虽然可以使用下面的方式来配置 [^1] , 但似乎在目前可用的模型中找不到 `ChatGPT` 对应的 model  [^2]
```javascript
import { Configuration, OpenAIApi } from "openai";
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

const completion = await openai.createCompletion({
  model: "text-davinci-002",
  prompt: "Hello world",
});
console.log(completion.data.choices[0].text);
```

通过 F12 来查看后端接口 `https://chat.openai.com/backend-api/models` 返回值，有一个 `text-davinci-002-render` ，我尝试在可用模型列表中搜索相关信息，结果得不到任何返回
![image](https://user-images.githubusercontent.com/32270702/206485228-7f402a10-2c74-48e3-a8e3-1dec6ceb4186.png)


[^1]: https://www.npmjs.com/package/chatgpt
[^2]: https://beta.openai.com/docs/api-reference/models/list

**Comment by BoundlessLearning** [comment]
> > > As far as I know, ChatGPT does not currently support API calls to 🤔
> > > 我看它官网文档里是有的，可以直接通过HTTP调用，例子里就是用curl，header里写API_TOKEN，拼上参数直接POST就行了。
> > > https://beta.openai.com/docs/api-reference/making-requests
> 
> 虽然可以使用下面的方式来配置 [1](#user-content-fn-1-bb8f2700491290909bdc07b5c52f581b) , 但似乎在目前可用的模型中找不到 `ChatGPT` 对应的 model [2](#user-content-fn-2-bb8f2700491290909bdc07b5c52f581b)
> 
> ```js
> import { Configuration, OpenAIApi } from "openai";
> const configuration = new Configuration({
>   apiKey: process.env.OPENAI_API_KEY,
> });
> const openai = new OpenAIApi(configuration);
> 
> const completion = await openai.createCompletion({
>   model: "text-davinci-002",
>   prompt: "Hello world",
> });
> console.log(completion.data.choices[0].text);
> ```
> 
> 通过 F12 来查看后端接口 `https://chat.openai.com/backend-api/models` 返回值，有一个 `text-davinci-002-render` ，我尝试在可用模型列表中搜索相关信息，结果得不到任何返回 ![image](https://user-images.githubusercontent.com/32270702/206485228-7f402a10-2c74-48e3-a8e3-1dec6ceb4186.png)
> 
> ## Footnotes
> 1. https://www.npmjs.com/package/chatgpt [↩](#user-content-fnref-1-bb8f2700491290909bdc07b5c52f581b)
> 2. https://beta.openai.com/docs/api-reference/models/list [↩](#user-content-fnref-2-bb8f2700491290909bdc07b5c52f581b)

我测试了一下nodejs的接口，是可以正常调用的。你检查一下是否是API_KEY没有写对之类的问题。
![](https://user-images.githubusercontent.com/113996191/206579664-c120edec-2717-4bdc-9439-40793a818386.png)

**Comment by transitive-bullshit** [comment]
@UNICKCHENG ChatGPT is very new, and OpenAI has purposefully not added an official API for it yet.

This project is using https://github.com/transitive-bullshit/chatgpt-api to access the unofficial API, which will be converted to use the official OpenAI API once it's released.

**Comment by UNICKCHENG** [comment]
@BoundlessLearning  很遗憾 `text-davinci-002` 并不是 ChatGPT 的模型，如果使用 `text-davinci-002` 模型操作的话，得到的结果并不太乐观 [^1] 。

正如 [transitive-bullshit ](https://github.com/fuergaosi233/wechat-chatgpt/issues/21#issuecomment-1343479334) 谈到的 ，目前官方暂未开源 ChatGPT API。

[^1]: https://github.com/UNICKCHENG/ChatGPT-For-Wechat/blob/main/src/openai.js
