### ISSUE TITLE
小白咨询个使用问题

### ISSUE THREAD

**Issue by huangzuomin** [fuergaosi233/wechat-chatgpt#215]
运行后，微信扫描二维码，提示登陆web微信
然后，怎么怎么调用chatgpt？

**Comment by huangzuomin** [comment]
换了个微信可以了

**Comment by kofwj** [comment]
我也是一样的，提示web微信后，然后看不到啥啊？

**Comment by huangzuomin** [comment]
扫码的微信就变成机器人，要其他微信发给扫码微信激活机器人对话

**Comment by whitefg** [comment]
> 扫码的微信就变成机器人，要其他微信发给扫码微信激活机器人对话

还需要设置什么吗，比如登陆chatgpt，我扫码后发消息无反应，就按README文件daocker部署的做完了

**Comment by RealTong** [comment]
需要使用其他的微信号和你登录的账号进行对话
