### ISSUE TITLE
pull access denied for wechat-chatgpt

### ISSUE THREAD

**Issue by jpfree** [fuergaosi233/wechat-chatgpt#22]
root@debian:~/wechat-chatgpt# docker run -v $(pwd)/config.yaml:/app/config.yaml wechat-chatgpt
Unable to find image 'wechat-chatgpt:latest' locally
docker: Error response from daemon: pull access denied for wechat-chatgpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by fuergaosi233** [comment]
Have you built locally?

**Comment by RealTong** [comment]
> root@debian:~/wechat-chatgpt# docker run -v $(pwd)/config.yaml:/app/config.yaml wechat-chatgpt Unable to find image 'wechat-chatgpt:latest' locally docker: Error response from daemon: pull access denied for wechat-chatgpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.

在使用`docker run `之前可以先使用 `docker build -t wechat-chatgpt .` 构建一个镜像

**Comment by OliverGrace** [comment]
> > root@debian:~/wechat-chatgpt# docker run -v $(pwd)/config.yaml:/app/config.yaml wechat-chatgpt Unable to find image 'wechat-chatgpt:latest' locally docker: Error response from daemon: pull access denied for wechat-chatgpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.
> 
> 在使用`docker run `之前可以先使用 `docker build -t wechat-chatgpt .` 构建一个镜像

构建会在step 5/11完成后直接返回终端，然后image的tag是<none>，即使手动打tag运行镜像也不行，会报错

**Comment by jpfree** [comment]
> 

是的，我构建镜像也是这个报错
