### ISSUE TITLE
设置多个token好像也不能同时问2个问题？

### ISSUE THREAD

**Issue by bbhxwl** [fuergaosi233/wechat-chatgpt#221]
我设置了5个号，启动提示检测到5个了，怎么同时问还提示限流。

**Comment by peterhiking** [comment]
我添加了16个账号,还是会限流,应该不是代码的问题,是OpenAI那边的问题

**Comment by bbhxwl** [comment]
> 我添加了16个账号,还是会限流,应该不是代码的问题,是OpenAI那边的问题

不应该吧，换号也限难道限的ip？

**Comment by peterhiking** [comment]
> > 我添加了16个账号,还是会限流,应该不是代码的问题,是OpenAI那边的问题
> 
> 不应该吧，换号也限难道限的ip？

有可能是这样的捏
