### ISSUE TITLE
当前账号无法使用该服务

### ISSUE THREAD

**Issue by liuyixin-louis** [fuergaosi233/wechat-chatgpt#223]
无法登陆，当前账号无法使用该服务

**Comment by byegates** [comment]
一样的问题，是要注册新的微信吗？

**Comment by huangzuomin** [comment]
微信需要国内手机实名认证

**Comment by RealTong** [comment]
Please check if you can log in on the https://wx.qq.com/

**Comment by byegates** [comment]
> 微信需要国内手机实名认证

是的，我换了个国内手机号注册的微信就搞定了

**Comment by liuyixin-louis** [comment]
same here, solved when using WeChat registered with mainland phone
