### ISSUE TITLE
微信回复不完全

### ISSUE THREAD

**Issue by cyear** [fuergaosi233/wechat-chatgpt#224]
网页完整正常，微信消息缺失

**Comment by learner-NKH** [comment]
我遇到同样的问题，微信消息缺失，尤其是长文本

**Comment by jejune5** [comment]
回复继续即可，是chatgpt本身的原因

**Comment by cyear** [comment]
> 回复继续即可，是chatgpt本身的原因

并不是，继续他那个中间断开了，比如
1.xxxx
2.xx,
然后没了，继续他可能就说
4.xxxxx
