### ISSUE TITLE
不可以连续对话，网页可以

### ISSUE THREAD

**Issue by cyear** [fuergaosi233/wechat-chatgpt#225]
![Screenshot_20221211-044717.png](https://user-images.githubusercontent.com/77969791/206874667-16c777ff-35ad-454c-bb81-e37647df70f2.png)

**Comment by HisMax** [comment]
**网页端也无法做到叭，你需要去催眠它。**

不然当问一些比较绝对的问题，或者是涉及到功能设定外的内容，它就会说OpenAI content policy了

You can't do it on the web page, you need to hypnotize it properly. 

Otherwise, when asking some relatively absolute questions, or involving content other than function settings

> it will " OpenAI content policy "
