### ISSUE TITLE
二维码无法扫描，以及uncaughtException AssertionError [ERR_ASSERTION]: 400 != 400错误

### ISSUE THREAD

**Issue by westonZhang** [fuergaosi233/wechat-chatgpt#227]
执行`docker logs -f wechat-chatgpt`命令后，出现的二维码有异常（感觉位置有些错乱），无法扫描，`Ctrl C`后再次运行，出现报错：uncaughtException AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)
    at /app/node_modules/wechat4u/src/core.js:108:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
    '    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:108:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by inannan423** [comment]
二维码之前没有生成链接吗？

**Comment by lemmonyx** [comment]
我的也是执行这个后在一长串说啥config.yaml无法读取什么的或者路径出错。看openai分析的

**Comment by A11en0** [comment]
The same issue to #95.

**Comment by Crabor** [comment]
你需要先将docker容器运行起来再执行docker logs -f wechat-chatgpt

**Comment by A11en0** [comment]
> 你需要先将docker容器运行起来再执行docker logs -f wechat-chatgpt

显然已经做了啊，不然怎么触发这个错误
