### ISSUE TITLE
企业微信用户发到微信上的消息chatGPT监控不到

### ISSUE THREAD

**Issue by OMGkillerMao** [fuergaosi233/wechat-chatgpt#229]

**Comment by liudao** [comment]
现在根本不支持企业微信扫码吧

**Comment by OMGkillerMao** [comment]
> 现在根本不支持企业微信扫码吧

不是企业微信扫码，是微信上可以添加企业微信好友，然后在企业微信上发信息到微信上，chatGPT在微信上检测不到企微发来的信息

**Comment by fuergaosi233** [comment]
> 现在根本不支持企业微信扫码吧

Enterprise wechat login is not supported
