### ISSUE TITLE
用railway部署后 回答速度非常慢，大约30s以上

### ISSUE THREAD

**Issue by gumplus** [fuergaosi233/wechat-chatgpt#230]
这个速度问题怎么解决？
为何和web端 速度差距那么大
另外railway部署 不需要提供 API key的话 是不是慢的原因？

如何提升速度呢

**Comment by inannan423** [comment]
railway服务器在境外，转发消息增加延迟是肯定的，可以考虑自己部署环境。

**Comment by gumplus** [comment]
thx
