### ISSUE TITLE
是否可以实现在群聊里 被关键词触发 聊天？

### ISSUE THREAD

**Issue by gumplus** [fuergaosi233/wechat-chatgpt#236]

**Comment by QYQSDTC** [comment]
同问

**Comment by sunshanpeng** [comment]
技术上可以。
目前群聊里是@机器人触发聊天，是希望@机器人+关键字触发聊天还是希望2种触发方式都可以，我看针对触发方式有很多需求
#248 #246 #243

**Comment by QYQSDTC** [comment]
@sunshanpeng 因为微信限制登录，很难搞一个小号当机器人挂在那，所以我觉得要是在群里能像现在私聊一样搞一个关键词触发会很好，当然@机器人+关键词也不错，这样也不影响正常的沟通和交流。

**Comment by RealTong** [comment]
添加了屏蔽词功能, 试试这个分支
https://github.com/fuergaosi233/wechat-chatgpt/tree/feat/add-block-word

**Comment by RealTong** [comment]
Completed!
