### ISSUE TITLE
有没有大神帮忙看下我这个登录了 发送消息为什么没有回复呢

### ISSUE THREAD

**Issue by CloudyTurnXXX** [fuergaosi233/wechat-chatgpt#241]
有没有大神帮忙看下我这个登录了 发送消息为什么没有回复呢
![image](https://user-images.githubusercontent.com/99886885/206888268-c10d257a-a983-49a6-b3ad-94cbb8c2c80c.png)

**Comment by ytb1079014809** [comment]
你后面的反馈可以看一下不

**Comment by CloudyTurnXXX** [comment]
什么反馈

**Comment by ytb1079014809** [comment]
建议你把token重新获取一下

**Comment by CloudyTurnXXX** [comment]
![image](https://user-images.githubusercontent.com/99886885/206888569-da4478ab-26bb-40f2-91bf-4ddefc821b08.png)
重新获取的token 后重启了docker 容器 还是没有回复

**Comment by SHENINOTES** [comment]
程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 需要修改代码！详见问题“docker部署之后,给登录的微信账号发消息没有回复,日志上面也显示微信消息了,就是没有回复”下面的回复

**Comment by CloudyTurnXXX** [comment]
谢谢大佬

**Comment by yangyunhui1999** [comment]
> 程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 需要修改代码！详见问题“docker部署之后,给登录的微信账号发消息没有回复,日志上面也显示微信消息了,就是没有回复”下面的回复

我这边注释后，但是出现了发送文本消息失败的错误
![1670738072266](https://user-images.githubusercontent.com/49811653/206889188-52cfa0ea-7516-4356-be26-4fa38799a99b.png)

**Comment by gaojunbin** [comment]
> > 程序默认不是自己聊天，默认是把你设置为人工智能来回答别人。别人@你的时候，机器人自动帮你应答。 需要修改代码！详见问题“docker部署之后,给登录的微信账号发消息没有回复,日志上面也显示微信消息了,就是没有回复”下面的回复
> 
> 我这边注释后，但是出现了发送文本消息失败的错误 ![1670738072266](https://user-images.githubusercontent.com/49811653/206889188-52cfa0ea-7516-4356-be26-4fa38799a99b.png)

想问下解决了嘛～遇到同样的问题（回复他人以及群聊都正常，自己发给自己不正常，注释掉以后报同样的错误）

**Comment by RealTong** [comment]
@gaojunbin @yangyunhui1999 
不支持私聊中自己向自己发送消息
