### ISSUE TITLE
用账号密码登录不了

### ISSUE THREAD

**Issue by vite666** [fuergaosi233/wechat-chatgpt#242]
前面截掉了一些个人信息，后面是报错消息
![image](https://user-images.githubusercontent.com/71123610/206888330-e3457d0a-9d12-42b6-b0d9-f88ea06c4615.png)

**Comment by vite666** [comment]
![image](https://user-images.githubusercontent.com/71123610/206896004-6b80d613-7781-40bc-9f12-b549f2b46aad.png)

**Comment by JacksonTom** [comment]
我也是，这是遇到验证码了吗？

**Comment by xiasummer1019** [comment]
应该是验证码，过不去
