### ISSUE TITLE
我这边将talker.self注释后，自己跟自己聊天能够触发chatgpt，但是到talker.say后报发送文本消息失败的错误,还有群聊是不是只有@才会触发

### ISSUE THREAD

**Issue by yangyunhui1999** [fuergaosi233/wechat-chatgpt#243]
我这边将talker.self注释后，自己跟自己聊天能够触发chatgpt，但是到talker.say后报发送文本消息失败的错误,还有群聊是不是只有@才会触发
![1670738072266](https://user-images.githubusercontent.com/49811653/206888791-d36dc045-9c0f-4e3d-a8f0-83fb1cf632a8.png)

**Comment by RealTong** [comment]
Solved,
