### ISSUE TITLE
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time

### ISSUE THREAD

**Issue by Xuyangzheng1** [fuergaosi233/wechat-chatgpt#245]
`(myenv) PS F:\wechat-chatgpt> docker logs -f wechat-chatgpt                                 

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`  
[nodemon] watching path(s): config.yaml/**/*  
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)        
    at tryReadSync (node:fs:438:20)
    at Object.readFileSync (node:fs:484:19)   
    at file:///app/src/config.ts:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -21,
  syscall: 'read',
npm ERR! path /app
npm ERR! command failed
npm ERR! signal SIGTERMnpm ERR! command sh -c -- nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-11T05_34_11_678Z-debug-0.log`

**Comment by unixcs** [comment]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/app/README.md'
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by unixcs** [comment]
我也是这个报错  不知道什么原因

**Comment by unixcs** [comment]
@Xuyangzheng1 我尝试使用cookie等路后 没有报错 你也试试看，不使用账户密码
