### ISSUE TITLE
怎么接入到微信公众号，token在哪里啊

### ISSUE THREAD

**Issue by jiudaibuyu** [fuergaosi233/wechat-chatgpt#247]
怎么接入到微信公众号，token在哪里啊

**Comment by inannan423** [comment]
在 [这里](https://github.com/fuergaosi233/wechat-chatgpt/blob/main/README_ZH.md#b-%E4%BD%BF%E7%94%A8-session-token) 查看获取 token 的方式，接入微信公众号现在好像还不行。

**Comment by huangzuomin** [comment]
我也想知道答案，这个不知道能否接公众号

**Comment by gtoxlili** [comment]
接入公众号的话可以用我这个( [gtoxlili/wechat-chatGPT](https://github.com/gtoxlili/wechat-chatGPT)
