### ISSUE TITLE
只要别人跟我说话或@我就会触发chatGPT？

### ISSUE THREAD

**Issue by DoubleBlock** [fuergaosi233/wechat-chatgpt#248]
我测试了好像是的。大家是这种情况吗？那样会影响自己的微信使用啊

**Comment by inannan423** [comment]
建议用小号，或者设置触发词，文档中有触发词配置说明。

**Comment by DoubleBlock** [comment]
> 建议用小号，或者设置触发词，文档中有触发词配置说明。
明白了

**Comment by RealTong** [comment]
在config中添加 `chatPrivateTiggerKeyword` 字段即可解决
