### ISSUE TITLE
开发者工具中不显示tokens

### ISSUE THREAD

**Issue by xyliu-uir** [fuergaosi233/wechat-chatgpt#249]
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/50279789/206891919-39e5f1a6-2455-4ef2-85d0-529b06bd1208.png">
您好，请问开发者工具中不显示tokens应该怎么办呢？

**Comment by sunshanpeng** [comment]
你这个不是官网，官网是[ChatGPT](https://chat.openai.com/chat)
