### ISSUE TITLE
运行成功，但是报ERR_ASSERTION

### ISSUE THREAD

**Issue by c121914yu** [fuergaosi233/wechat-chatgpt#25]
uncaughtException AssertionError [ERR_ASSERTION]: 1205 == 0

有时候报这个错仍可以发消息，但是时间久了就会断开。没找到这个错误是什么

**Comment by fuergaosi233** [comment]
Could you provide more information?

**Comment by Qasak** [comment]
u may have been temporarily blocked by WeChat

https://github.com/nodeWechat/wechat4u/issues/192

**Comment by c121914yu** [comment]
> 

Yes, that's the problem..  today is ok.
