### ISSUE TITLE
部署在群晖docker上，目前非常稳定流畅

### ISSUE THREAD

**Issue by huangzuomin** [fuergaosi233/wechat-chatgpt#250]
我感觉也应该可以部署在软路由的docker上，大家有兴趣可以试试

**Comment by unixcs** [comment]
需要挂梯子么

**Comment by huangzuomin** [comment]
梯子挂软路由上

**Comment by YondSun** [comment]
软路由也是跑在群晖docker里的吗？

**Comment by protectione055** [comment]
请问群晖上跑的config.yaml怎么配置？

**Comment by huangzuomin** [comment]
> 

软路由独立硬件

**Comment by huangzuomin** [comment]
> 
进高级设置，添加存储空间，添加文件，装载路径写 /app/config.yaml

**Comment by honghuanice** [comment]
> > 
> 
> 进入高级设置，添加存储空间，添加文件，加载路径写入/app/config.yaml

能讲一下之后操作咩？

**Comment by songdone** [comment]
能出个群晖docker部署的教程吗？全网找不到关于群晖里部署的

**Comment by yang-lz439** [comment]
有教程吗？

**Comment by xiewenxuan** [comment]
> 

没有二维码出来怎么办啊，显示 docker安装了运行了。

**Comment by baiasse** [comment]
有没有教程，群晖上怎么布署
