### ISSUE TITLE
扫码登录后，发送消息 No chatgpt item in pool 刚换过token 报这个错，

### ISSUE THREAD

**Issue by juziqishui11** [fuergaosi233/wechat-chatgpt#251]
扫码登录后的报错 ：uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3

收到信息时的报错：
Message#Text[🗣Contact<枫城>]   你好
🎯 Triggered ChatGPT: 你好
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)

**Comment by huangzuomin** [comment]
换个浏览器登陆openai，再复制token试试

**Comment by juziqishui11** [comment]
> 换个浏览器登陆openai，再复制token试试

还是不行，他还有这些UC哦呜
shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py 15757101418@163.com Mxxx',
  command: 'sh -c poetry run python3 src/generate_session.py 15757101418@163.com Mxxx',

**Comment by RealTong** [comment]
> > 换个浏览器登陆openai，再复制token试试
> 
> 还是不行，他还有这些UC哦呜 shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py [15757101418@163.com](mailto:15757101418@163.com) Mxxx', command: 'sh -c poetry run python3 src/generate_session.py [15757101418@163.com](mailto:15757101418@163.com) Mxxx',

有详细的报错吗? 主要看stdout, stderr 这两行

**Comment by juziqishui11** [comment]
> > > 换个浏览器登陆openai，再复制token试试
> > 
> > 
> > 还是不行，他还有这些UC哦呜 shortMessage: 'Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py [15757101418@163.com](mailto:15757101418@163.com) Mxxx', command: 'sh -c poetry run python3 src/generate_session.py [15757101418@163.com](mailto:15757101418@163.com) Mxxx',
> 
> 有详细的报错吗? 主要看stdout, stderr 这两行
> 
> 另外可以尝试这个issues的解决方案 #210
日志显示这个，我怀疑自己都没登录成功
stdout: "Namespace(email='15757101418@163.com', password='Mxxxx')",
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 50, in <module>\n' +

**Comment by niudage** [comment]
ok night

**Comment by juziqishui11** [comment]
> 
后面还有这个内容
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false

**Comment by lanyucomputer** [comment]
> > 
> 
> 后面还有这个内容 failed: true, timedOut: false, isCanceled: false, killed: false

我的和你的一样

**Comment by lanyucomputer** [comment]
登陆成功的提示有ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
接受消息后的反应是这样的：

**Comment by lanyucomputer** [comment]
,"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"123"}
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
Message: Message#Unknown[🗣Contact<Michael>]
Message: Message#Unknown[🗣Contact<Michael>]
Message: Message#Text[🗣Contact<Michael>]        再发123
Message: Message#Text[🗣Contact<小敏>]   123
🎯 Triggered ChatGPT: 123
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)
Message: Message#Text[🗣Contact<Michael>]        发你好
Message: Message#Text[🗣Contact<小敏>]   你好
Message: Message#Text[🗣Contact<Michael>]        发怎么减肥最快？
Message: Message#Text[🗣Contact<小敏>]   怎么减肥最快？
Message: Message#Text[🗣Contact<Michael>]        有没有回复？
Message: Message#Text[🗣Contact<小敏>]   没有




多次重拉镜像也是这样

**Comment by lee-chard** [comment]
> > ,"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"123"} ChatGPTPools: 1 🤖️ Start GPT Bot Success, ready to handle message! Message: Message#Unknown[🗣Contact] Message: Message#Unknown[🗣Contact] Message: Message#Text[🗣Contact] 再发123 Message: Message#Text[🗣Contact<小敏>] 123 🎯 Triggered ChatGPT: 123 Error: ⚠️ No chatgpt item in pool at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35) at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12) at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:308:24) at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:334:16) at async WechatyImpl. (file:///app/src/main.ts:32:9) Message: Message#Text[🗣Contact] 发你好 Message: Message#Text[🗣Contact<小敏>] 你好 Message: Message#Text[🗣Contact] 发怎么减肥最快？ Message: Message#Text[🗣Contact<小敏>] 怎么减肥最快？ Message: Message#Text[🗣Contact] 有没有回复？ Message: Message#Text[🗣Contact<小敏>] 没有
> > 多次重拉镜像也是这样
> 
> +1

+1

**Comment by RealTong** [comment]
Currently there are multiple identical Issues https://github.com/fuergaosi233/wechat-chatgpt/issues/210, I need to close the extra issues to ensure efficient information flow.

Thank you for your support, when we find a solution available, I will reopen it
