### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by RealTong** [fuergaosi233/wechat-chatgpt#255]
# FAQ: 

> ⚠️ Update 2022.12.14 多个用户开始反馈微信暂时封禁, 理由是「使用第三方软件, 外挂, 插件等非官方工具或其他违规行为」

## 扫码之后出现[uncaughtException AssertionError [ERR_ASSERTION]]怎么办
可能的原因
* 首先, 确保你使用的是`微信`扫描, 而不是`WeChat`. [微信与wechat有什么区别](https://kf.qq.com/touch/wxappfaq/210825fYjmqM210825qUrIJ7.html?platform=15)
* 确认微信是否已经实名认证
* 微信的注册时间比较新(目前不清楚什么时间点之前注册的微信可以使用. 但知道能登录[网页版](https://wx.qq.com/)微信就一定可以)

可能的解决方法: 
* 点微信我的->钱包->身份信息会提示完善个人信息。可能是个人地址没填，补全这个个人信息。
* 确认是否可以在 https://wx.qq.com/ 登录
* 更换微信

## Error: ⚠️ No chatgpt item in pool
>~~WARNING: 2022/12/12. OpenAI改进了认证. 会导致无法登录而出现`⚠️ No chatgpt item in pool`, 我们正在积极寻找可用的解决方案.~~
> 此问题已解决

可能的原因: 
* Token已经过期, 需要使用新的Token
* IP不在OpenAI服务范围内(如使用了CN IP)
* 没有安装Python poetry等环境. 

可能的解决办法: 
* 确保你的部署环境可以正常登录 https://chat.openai.com/chat . 不要使用CN, HK等IP
* 在 https://chat.openai.com/chat 重新复制`__Secure-next-auth.session-token`到配置文件
* 如果你使用Docker等部署方式. 请检查容器是否可以连接网络
* 安装[python](https://www.python.org/downloads/), [poetry](https://python-poetry.org/docs/). 

## 我怎么设置触发规则
分两种情况: 
在群聊: 
* 群聊中, 你需要@机器人, 才可触发 

在私聊: 
* 私聊中, 默认是100%触发, 你可以通过配置config.yaml中的`chatPrivateTiggerKeyword` 字段来解决

## 为什么扫码之后, 并且没有报错, 但是没反应呢.

这是因为, 扫码的账号成为了bot. 你可以使用其他账号添加这个bot来体验wechat-chatgpt

**Comment by gaojunbin** [comment]
@RealTong Hi，想请问下https://github.com/fuergaosi233/wechat-chatgpt/issues/241#issuecomment-1345468355 这个问题中注释掉skip自己的消息那行代码后，会出现这样的错误是因为什么呀。（他人，群聊都正常）

**Comment by moss1991** [comment]
hi，扫码成功，控制台可以看到，发送账号打印出来的信息，但是发送账号没有收到chatgpt的返回结果

**Comment by casens** [comment]
请问python，poetry 有版本要求么？应该是装在主机里，不是docker容器里安装吧？
---- 安装[python], [poetry]

**Comment by lijinmao** [comment]
私聊的时候是可以的，但在群聊里，无法触发chatgpt回答呢，我看日志已经识别出来关键字了，但是没有去Trigger chatgpt。是需要配置什么吗？

**Comment by RealTong** [comment]
> 私聊的时候是可以的，但在群聊里，无法触发chatgpt回答呢，我看日志已经识别出来关键字了，但是没有去Trigger chatgpt。是需要配置什么吗？

在群聊中需要@bot

**Comment by why-you-trust-me** [comment]
> hi，扫码成功，控制台可以看到，发送账号打印出来的信息，但是发送账号没有收到chatgpt的返回结果

我这边也是在railway后台能看到微信信息，然后设置了触发关键字，也是没有收到chatgpt回复

**Comment by WindC00** [comment]
群聊@后加关键词还是无法触发

**Comment by xyxzfj** [comment]
同样的问题. 哪里有 bot 可@?

**Comment by Pancat007** [comment]
扫码登录之后log都没显示，微信加了好友发消息 “/cmd help” 也没反应，可以出一个具体的教程吗？
