### ISSUE TITLE
微信登陆不了

### ISSUE THREAD

**Issue by xhl101711** [fuergaosi233/wechat-chatgpt#257]
微信登陆的时候遇到下面的问题，怎么解决
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by RealTong** [comment]
* 进行实名认证
* 点微信我的->钱包->身份信息会提示完善个人信息。可能是个人地址没填，补全这个个人信息。
* 确认是否可以在 https://wx.qq.com/ 登录
* 更换账户
