### ISSUE TITLE
uncaughtException AssertionError [ERR_ASSERTION]: 1==0报错

### ISSUE THREAD

**Issue by whitefg** [fuergaosi233/wechat-chatgpt#259]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by super-MARIwang** [comment]
应该是微信号被限制，不能登录网页版的原因，我也遇到了，搜了一下无解，tx的问题

**Comment by slovx2** [comment]
我也是碰到这个错误。实名认证，绑定银行卡，过一会就可以了
