### ISSUE TITLE
Error: ChatGPTAPI error 429

### ISSUE THREAD

**Issue by Dinxin** [fuergaosi233/wechat-chatgpt#26]
模型一直都回复这个，这是为什么呢？

**Comment by OliverGrace** [comment]
EEROR 503

**Comment by RealTong** [comment]
有更详细的日志吗?
从你给的信息来看是 「请求次数过多,,,可以尝试更换IP」

**Comment by wulabing** [comment]
429 状态码是请求过多了 被限制了 
HTTP/1.1 429 Too Many Requests

**Comment by OliverGrace** [comment]
会跟微信团队干起来导致429

**Comment by fuergaosi233** [comment]
In the latest version, filtering of wechat team messages has been added, and 429 and 503 can be handled together in another issue

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/27
