### ISSUE TITLE
ChatGPT已经支持了/help和/define命令，这和我们的命令是冲突的吧？

### ISSUE THREAD

**Issue by slovx2** [fuergaosi233/wechat-chatgpt#260]
看到最新代码里支持了/reset 等命令

建议换个前缀，比如 -

**Comment by RealTong** [comment]
Under what circumstances does it conflict?

**Comment by slovx2** [comment]
> Under what circumstances does it conflict?

我们把聊天内容含/help的消息拦截了，这个消息就没法发给ChatGPT了

**Comment by RealTong** [comment]
This is a normal situation
