### ISSUE TITLE
Error: ChatGPTAPI error 503

### ISSUE THREAD

**Issue by font-ds** [fuergaosi233/wechat-chatgpt#27]
<img width="852" alt="WeChat4aeb7956f02e8d749db10d7b52fa2ce2" src="https://user-images.githubusercontent.com/73658138/206172303-10f6bea4-4722-433e-afca-4cd85e4ecc13.png">

**Comment by RealTong** [comment]
可以附上更详细的日志吗, 截图里看不出来

**Comment by font-ds** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/73658138/206185106-2ebdf691-0dd1-4d68-8f00-064c35a7668e.png">
时不时会出现这样的问题，而且第二次查询同样问题就又会变正常

**Comment by luoyeETH** [comment]
我有同样的问题，多个人同时提问时容易发生

**Comment by AeroXi** [comment]
我也遇到同样问题，每次都是这个报错

**Comment by fuergaosi233** [comment]
The problem may be that It tries to create conversations for everyone, and I control this ability as a switch configuration.

**Comment by OliverGrace** [comment]
Frequently get 503, only one person is chatting

**Comment by transitive-bullshit** [comment]
This will happen if you're you're calling into the ChatGPT API too often.

@fuergaosi233 I recommend adding https://github.com/sindresorhus/p-throttle around your calls to `ChatGPTAPI.sendMessage` to help prevent 429 and 503 errors.

Or you can do this by awaiting on a [delay](https://github.com/sindresorhus/delay) like I'm doing here: https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/9dde16f1df611d9b7968832910a2174c92e7524e/src/respond-to-new-mentions.ts#L155-L159

This will greatly increase the robustness of your apps to ensure that the ChatGPT API doesn't mark your project / account / IP address as too aggressive.
