### ISSUE TITLE
一个账号很容易发生429错误，请问怎么配置账号池

### ISSUE THREAD

**Issue by thefreelight** [fuergaosi233/wechat-chatgpt#270]

**Comment by peterhiking** [comment]
chatGPTAccountPool:
  - id: 1
    email: email
    password: password
  - id: 2
    email: email
    password: password
  - id: 3
    email: email
    password: password

**Comment by peterhiking** [comment]
短横线被转换成了点

**Comment by huangzuomin** [comment]
谁知道注册是用了谷歌邮箱自动登陆，怎么在openai后台增加密码？

**Comment by YanQiu0207** [comment]
> 谁知道注册是用了谷歌邮箱自动登陆，怎么在 openai 后台增加密码？

好像不支持第三方账号。我后来重新注册了 OpenAI 的账号才登录成功。
