### ISSUE TITLE
ValueError: Captcha detected' 账号密码登录失败

### ISSUE THREAD

**Issue by Gohoy** [fuergaosi233/wechat-chatgpt#281]
如何解决
 exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "Namespace(email='')",
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 50, in <module>\n' +
    '    print(login(args.email, args.password))\n' +
    '          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/app/src/generate_session.py", line 19, in login\n' +
    '    chatbot = Chatbot(\n' +
    '              ^^^^^^^^\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 62, in __init__\n' +
    '    self.refresh_session()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 296, in refresh_session\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 293, in refresh_session\n' +
    '    self.login(self.config["email"], self.config["password"])\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 326, in login\n' +
    '    raise exc\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 319, in login\n' +
    '    auth.begin()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin\n' +
    '    self.part_two()\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two\n' +
    '    self.part_three(token=csrf_token)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 147, in part_three\n' +
    '    self.part_four(url=url)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 181, in part_four\n' +
    '    self.part_five(state=state)\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/OpenAIAuth/OpenAIAuth.py", line 219, in part_five\n' +
    '    raise ValueError("Captcha detected")\n' +
    'ValueError: Captcha detected',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false

**Comment by AL8023** [comment]
我也是这样，token加了也是这样，请问有什么解决办法吗

**Comment by moonD4rk** [comment]
> 我也是这样，token加了也是这样，请问有什么解决办法吗

remove username and password line, just like this `cat config.yaml`

``` yaml
chatGPTAccountPool:
  - session_token: <your token>
chatPrivateTiggerKeyword: <your keyword>
```

**Comment by acheong08** [comment]
Captcha support has actually been added to `revChatGPT` although documentation is missing.

@fuergaosi233 You can reference https://github.com/acheong08/ChatGPT/blob/6fabbc88deea2a8ad08b4b90fbf8315935d67787/src/revChatGPT/__main__.py#L10-L34, https://github.com/acheong08/ChatGPT/blob/6fabbc88deea2a8ad08b4b90fbf8315935d67787/src/revChatGPT/__main__.py#L95-L96, and https://github.com/acheong08/OpenAIAuth/blob/24886c94597d6535402c7eba9d3bef95de95ba76/src/OpenAIAuth/OpenAIAuth.py#L230-L240
