### ISSUE TITLE
DALL·E 2能支持吗

### ISSUE THREAD

**Issue by soapmancn** [fuergaosi233/wechat-chatgpt#282]
openai 还有一个画画的ai , DALL·E 2, 能不能支持下大佬🤓

**Comment by RealTong** [comment]
暂时不能支持DALL · E.

眼下最紧急的事情时解决ChatGPT Token失效的问题.

当然, 等到未来某天, 我们会考虑支持DALL · E, 到时候我们再重新打开这个Issues
