### ISSUE TITLE
Railway 无法deploy

### ISSUE THREAD

**Issue by Mj1ao** [fuergaosi233/wechat-chatgpt#284]
![image](https://user-images.githubusercontent.com/92769835/206909397-6c146512-088e-474c-bf63-6191b13e201e.png)
railway部署不了

**Comment by Mj1ao** [comment]
是为啥

**Comment by butchoosed** [comment]
你的railway是怎么配置的？截图看下settings

**Comment by Mj1ao** [comment]
> 你的railway是怎么配置的？截图看下settings

![image](https://user-images.githubusercontent.com/92769835/206911303-2e01a6c9-1e49-491a-9924-763a5ce0f105.png)
他在这个页面的时候都打不开setting

**Comment by Mj1ao** [comment]
> 

可以教教我不
加个v带带

**Comment by Mj1ao** [comment]
> 你的railway是怎么配置的？截图看下settings

![1670771219223](https://user-images.githubusercontent.com/92769835/206911488-43c51f9f-c3c8-40e0-82da-7d6be6c06bf1.png)

**Comment by jammesliu** [comment]
你解决了吗？我遇到了你一样的问题

**Comment by yanglanshi** [comment]
解决了吗？我也遇到这个问题

**Comment by jammesliu** [comment]
> 解决了吗？我也遇到这个问题
还没有

**Comment by orkunzozturk** [comment]
same problem. should i add npm run dev in the build command settings?
