### ISSUE TITLE
我的session_token方式也开始报错了，昨晚还是正常的。

### ISSUE THREAD

**Issue by smallersoup** [fuergaosi233/wechat-chatgpt#294]
报错信息如下：
Error: ⚠️ No chatgpt item in pool
    at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:176:13)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:188:35)
    at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:197:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:253:12)
    at async ChatGPTBot.onGroupMessage (file:///app/src/chatgpt.ts:318:24)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:336:16)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by JacketChenlll** [comment]
so do I.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/62599133/206941133-e3b46524-d124-423c-a91f-aea28dc41e6e.png">

**Comment by lyf9375** [comment]
应该是不行了，我看了下我的Session_token每次刷新都在变，这个方法应该用不了

**Comment by xubingod** [comment]
同上   在更新token时发现新增了一个验证你是否为人机的状态
![image](https://user-images.githubusercontent.com/91514008/206941543-68aeef3f-b737-45c8-814b-ba25f30e78f9.png)

**Comment by padoru233** [comment]
同，重新获取了Session_token也不行

**Comment by xubingod** [comment]
你认真看一下，每刷新一次页面，对应的token都在更换 ，这在之前是没发生过的

**Comment by mpwang** [comment]
please refer to https://github.com/acheong08/ChatGPT/issues/261

**Comment by inccleo** [comment]
So is mine

**Comment by JacketChenlll** [comment]
> 你认真看一下，每次刷新一页，对应的token都在更换，这之前是没有发生过的

这个其实昨天就是这个样子了，昨天我更新的时候就发现了，但昨天还是可用的

**Comment by xigan-bit** [comment]
所以有人解决了吗...

**Comment by mikehu2016** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup
这个解决了，等@fuergaosi233更新吧

**Comment by goodluckily** [comment]
同样出现了，这种情况

**Comment by mikehu2016** [comment]
OpenAI has added cloudflare to protect their services. Please use [session tokens](https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication) along with cf_clearance (more details in wiki)

https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by IssacSydney** [comment]
在原来的config.yaml中，无法识别cf-clearance，是不是只能等原作者更新了

**Comment by smallersoup** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/21979752/206945898-960feb53-5880-4275-9581-bd679a08a29f.png">
看来等作者更新后，config.yaml 要放两个token了？

**Comment by IssacSydney** [comment]
应该是这样的

**Comment by IssacSydney** [comment]
暂时是不是没有解决办法（仅修改config.yaml）

**Comment by xyzzen** [comment]
昨天玩了一天,今天不行了 那个token的确一会就会自己更新.  然后使用账号密码不知道为什么老是报错啊 'Exception: API error',

**Comment by QingShewky** [comment]
我的也是，一开始用账号密码登录，不行，显示缺项目，然后用的token，昨天还行，今天就歇b了

**Comment by Harry-Jing** [comment]
请求api时需要添加cf_clearance的cookies

**Comment by smallersoup** [comment]
进群交流
![IMG_0109](https://user-images.githubusercontent.com/21979752/207011977-f1d164ec-e89a-4e35-b21c-7ff36ffe1afc.JPG)

**Comment by QingShan-123** [comment]
可以再发一下群吗？

**Comment by fzyt** [comment]
> 进群交流
> ![IMG_0109](https://user-images.githubusercontent.com/21979752/207011977-f1d164ec-e89a-4e35-b21c-7ff36ffe1afc.JPG)
> 

可以再发一次二维码吗
