### ISSUE TITLE
这个的接口貌似不是chatGPT的

### ISSUE THREAD

**Issue by cgddgc** [fuergaosi233/wechat-chatgpt#296]
![image](https://user-images.githubusercontent.com/20945826/206942500-0fe9adef-3150-46ec-9a1b-836f084f3395.png)
![image](https://user-images.githubusercontent.com/20945826/206942530-e98f4f38-285b-4463-a928-1ad958d5691f.png)

**Comment by xubingod** [comment]
一致
![image](https://user-images.githubusercontent.com/91514008/206942882-69f856da-284b-403b-8304-63b932a4691e.png)
