### ISSUE TITLE
uncaughtException AssertionError

### ISSUE THREAD

**Issue by reverie-dev** [fuergaosi233/wechat-chatgpt#3]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /wechat-chatgpt/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /wechat-chatgpt/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by fuergaosi233** [comment]
Can you provide more information?

**Comment by reverie-dev** [comment]
node version: v19.2.0

**Comment by HandsomeWu6** [comment]
same question

**Comment by fool-cats** [comment]
same here

**Comment by Mv-Victor** [comment]
可能是账号未实名得问题  可以换个wechat账号试试

**Comment by reverie-dev** [comment]
> > node version: v19.2.0
> 
> Can you confirm that your account can use wechat on the Web? 
 I just tried it on the web version of WeChat, but I can't log in. 
 **I think it should be my wechat account problem.** Thanks for your awesome work.
