### ISSUE TITLE
Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by YangWudi233** [fuergaosi233/wechat-chatgpt#301]
![image](https://user-images.githubusercontent.com/119562309/206948045-55e755b4-b245-45c6-a49a-9f2931c9b457.png)

**Comment by zhai0122** [comment]
一样，好像是chatgpt使用cf了

**Comment by YangWudi233** [comment]
那需要怎么解决呢QAQ
