### ISSUE TITLE
用HK的服务器，网络是没有问题的，配置了用户名密码，报错

### ISSUE THREAD

**Issue by bryan31** [fuergaosi233/wechat-chatgpt#307]
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/924838/206956172-5f0f92cf-8ec6-4dcc-8b2e-fc4327565482.png">

**Comment by fuergaosi233** [comment]
OpenAI requires a Cloudflare token to use now.

**Comment by bryan31** [comment]
> OpenAI requires a Cloudflare token to use now.

then how to solve it

**Comment by bryan31** [comment]
> OpenAI requires a Cloudflare token to use now.

how to config the Cloudflare token

**Comment by fuergaosi233** [comment]
> > OpenAI requires a Cloudflare token to use now.
> 
> then how to solve it

I'm working on it

**Comment by emmmnaadada** [comment]
> OpenAI requires a Cloudflare token to use now.

I'm sure you can fix this

**Comment by bryan31** [comment]
> > > OpenAI requires a Cloudflare token to use now.
> > 
> > 
> > then how to solve it
> 
> I'm working on it

Im looking forward to it

**Comment by yuxuemao** [comment]
香港的节点登录不了openai

**Comment by jli113** [comment]
OpenAI is not available in Hongkong

**Comment by xubingod** [comment]
> > > > OpenAI现在需要一个Cloudflare令牌才能使用。
> > > 
> > > 
> > > 那么如何解决呢
> > 
> > 
> > 我正在努力
> 
> 我很期待

我也相信你可以的
