### ISSUE TITLE
运行sudo docker logs -f gpt之后报错

### ISSUE THREAD

**Issue by 6Superman6** [fuergaosi233/wechat-chatgpt#312]
uncaughtException AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)
    at /app/node_modules/wechat4u/src/core.js:108:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
    '    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:108:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

**Comment by sivanWu0222** [comment]
Me too, ask for help
