### ISSUE TITLE
貌似加上了cf验证？怎么用的？直接配置吗？还要保留以前的账号密码吗

### ISSUE THREAD

**Issue by lonely1215225** [fuergaosi233/wechat-chatgpt#317]

**Comment by lonely1215225** [comment]
clearanceToken和拿sessionToken方法一样
userAgent是填什么呢

**Comment by lonely1215225** [comment]
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
貌似直接粘浏览器的就好了

**Comment by OnePieceJoker** [comment]
目前我使用最新的配置，还是得到了403的错误，你这边成功了吗

**Comment by Zhangxxl** [comment]
> 

docker镜像还没更新, 等更新吧

**Comment by yaje0008** [comment]
作者的动作很快，赞

**Comment by lonely1215225** [comment]
我自己构建的docker  还是不行的 配置都填了 验证不成功

**Comment by emmmnaadada** [comment]
> 我自己构建的docker 还是不行的 配置都填了 验证不成功

我也是

**Comment by lee-chard** [comment]
> 作者的动作很快，赞

作者这是更新了什么，taken和cl一起加上去吗？

**Comment by lee-chard** [comment]
哦，我看到了 #313

**Comment by lee-chard** [comment]
> userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 貌似直接粘浏览器的就好了

openAIProxy:填什么呢？

**Comment by xyzzen** [comment]
配置了最新的 会提示Refresh token failed,  不知道怎么回事.
