### ISSUE TITLE
如何与自己对话

### ISSUE THREAD

**Issue by az031120103** [fuergaosi233/wechat-chatgpt#322]
微信号变成机器人后，如何自问自答？

**Comment by cjd9023** [comment]
哥, 你的机器人现在能用吗? 所有人都用不了了

**Comment by emmmnaadada** [comment]
> 哥, 你的机器人现在能用吗? 所有人都用不了了

用不了

**Comment by alwaysc** [comment]
chatgpt.ts L327行注释掉就行

**Comment by alwaysc** [comment]
> 微信号变成机器人后，如何自问自答？

chatgpt.ts L327行注释掉就行

**Comment by az031120103** [comment]
> 哥, 你的机器人现在能用吗? 所有人都用不了了

用不了
