### ISSUE TITLE
作者更新后有人成功了吗？我还是No chatgpt item in pool

### ISSUE THREAD

**Issue by zjh2765400096** [fuergaosi233/wechat-chatgpt#323]

**Comment by Lukangkang123** [comment]
> 我成功了

你可能只能撑俩小时

**Comment by ys-zzu** [comment]
> > 我成功了
> 
> 你可能只能撑俩小时

是吗。。我才刚运行一会儿。反应比较慢

**Comment by lee-chard** [comment]
> 我成功了

这是我的QQ：2970496661
我加上了cl和useragent都没用

**Comment by xyzzen** [comment]
我的也加上了 请求的时候会报错:  Refresh token failed,  有成功的经验没

**Comment by bthuntergg** [comment]
有成功的吗 我无论是  railway  还是本地都是一样

**Comment by zjh2765400096** [comment]
> 我成功了

除了加上cf_clearance和agent还有其他步骤吗？

**Comment by ys-zzu** [comment]
> > 我成功了
> 
> 这是我的QQ：2970496661 我加上了cl和useragent都没用

加了

**Comment by vegaviazhang** [comment]
![image](https://user-images.githubusercontent.com/60467454/207007560-acbef566-bd45-46f6-9b03-4ca3a32a6c78.png)

有老哥成功的吗，加微信群分享下经验呗

**Comment by jasonhu** [comment]
更新新版本后我也没有成功。

- 我的变量设置
<img width="520" alt="image" src="https://user-images.githubusercontent.com/819963/207029908-a086eb52-6dbb-4eb6-a425-719b7c6687b3.png">

- 我的错误日志
<img width="779" alt="image" src="https://user-images.githubusercontent.com/819963/207030088-b9afc34a-78ee-410e-9644-498b0706820f.png">

我观察了下，好像chatgpt的token刷新机制变了。。。

**Comment by jasonhu** [comment]
改了下代码，打印出来的日志是这样子的。感觉是底层chatgptapi需要修改token刷新逻辑才行了。

<img width="774" alt="image" src="https://user-images.githubusercontent.com/819963/207032725-4c53ab2c-2eb2-4ca0-8ebc-dfbeb71b6f38.png">

**Comment by jasonhu** [comment]
- 我知道原因了，参加这个链接。https://github.com/transitive-bullshit/chatgpt-api
- 主要是的原因是cf的那个token，绑定了请求端的ip地址。。。

<img width="937" alt="image" src="https://user-images.githubusercontent.com/819963/207035124-3cb08aaa-fe70-4df5-97bc-7a981a4c1ab2.png">

**Comment by dockercore** [comment]
> 2970496661



> * 我知道原因了，参加这个链接。https://github.com/transitive-bullshit/chatgpt-api
> * 主要是的原因是cf的那个token，绑定了请求端的ip地址。。。
> 
> <img alt="image" width="937" src="https://user-images.githubusercontent.com/819963/207035124-3cb08aaa-fe70-4df5-97bc-7a981a4c1ab2.png">

官方修复了，不过有个别人使用这种 https://github.com/transitive-bullshit/chatgpt-api/issues/104
