### ISSUE TITLE
一点建议供参考

### ISSUE THREAD

**Issue by stjacob** [fuergaosi233/wechat-chatgpt#325]
cloudflare算是比较完备的防自动化的手段，之前我做另一个项目的时候也尝试了很久，现存的一些网络库有这样那样的问题。最后是用selenium+chrome driver实际登录的方式来做自动化的，供 @fuergaosi233  参考，希望顺利。

**Comment by RealTong** [comment]
> cloudflare算是比较完备的防自动化的手段，之前我做另一个项目的时候也尝试了很久，现存的一些网络库有这样那样的问题。最后是用selenium+chrome driver实际登录的方式来做自动化的，供 @fuergaosi233 参考，希望顺利。

感谢您的建议 ! 

我们有尝试相似的解决方案, 但模拟浏览器的方案比较重, 而且不便于部署.
2022.12.13, 几乎100%触发验证码, 此方案更不太行得通了

我们会积极寻找可用的解决方案. 感谢!
