### ISSUE TITLE
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by hcr707305003** [fuergaosi233/wechat-chatgpt#326]
![image](https://user-images.githubusercontent.com/22547038/207013022-cf18e6b9-ccc1-485c-a827-f368fbd5d61e.png)
前天没有这个问题，重新npm run dev就出现了，新机部署也一样

**Comment by LeiLei123-cmd** [comment]
微信未实名认证

**Comment by hcr707305003** [comment]
> 

ok了

**Comment by Killua-Zhuang** [comment]
怎么解决的 就是实名认证吗
