### ISSUE TITLE
docker 镜像的配置更新一下吧

### ISSUE THREAD

**Issue by IssacSydney** [fuergaosi233/wechat-chatgpt#328]
按照新的要求改了config.yaml，运行成功但是还是显示no ..in pool,帮助一下云服务器玩家解决一下困扰吧

**Comment by lee-chard** [comment]
境外服务器要服务器ip地址与输入的token一致，把服务器做出v2ray代理

**Comment by IssacSydney** [comment]
v2rayN里面没有首尔的节点，怎么处理？
