### ISSUE TITLE
bypass captcha and refresh token and cookie with password

### ISSUE THREAD

**Issue by moonD4rk** [fuergaosi233/wechat-chatgpt#332]
Hi, revChatGPT.py already support [captcha recognition API](https://github.com/acheong08/ChatGPT/blob/e9963f1228aaea0c4e2fd3c69e9af2d165bc5c99/src/revChatGPT/__main__.py#L10
)

Is it possible refresh cookie and token with [puppeteer](https://github.com/puppeteer/puppeteer), and support API to bypass [captcha](https://github.com/fuergaosi233/wechat-chatgpt/issues/281) with [tesseract ocr](https://github.com/tesseract-ocr/) or other business captcha recognition service?

https://github.com/fuergaosi233/wechat-chatgpt/issues/281

**Comment by dockercore** [comment]
> 嗨，revChatGPT.py 已支持[捕获获取别API](https://github.com/acheong08/ChatGPT/blob/e9963f1228aaea0c4e2fd3c69e9af2d165bc5c99/src/revChatGPT/__main__.py#L10)
> 
> 是否可以使用[puppeteer](https://github.com/puppeteer/puppeteer)刷新cookie和token，并支持API绕过tesseract [ocr或其他业务验证密码别服务的](https://github.com/tesseract-ocr/)[捕获](https://github.com/fuergaosi233/wechat-chatgpt/issues/281)？[](https://github.com/tesseract-ocr/)
> 
> #281

确实
