### ISSUE TITLE
使用时，返回较长的信息（观察是这样）就会报错：未知错误，请看日志 | Error unknown, please see the log

### ISSUE THREAD

**Issue by PrinsYin** [fuergaosi233/wechat-chatgpt#340]

**Comment by Cheukfung** [comment]
今天开始，即使是官方网页，chatgpt回复长文本时，准确来说是回复时间超过一分钟，长连接就会断开，显示network error并无法保留回答的前半段内容，不清楚是bug还是访问人数太多官方做的限制

**Comment by qq2607439876** [comment]
> 今天开始，即使是官方网页，chatgpt回复长文本时，准确来说是回复时间超过一分钟，长连接就会断开，显示network error并无法保留回答的前半段内容，不清楚是bug还是访问人数太多官方做的限制

我还以为只有我这样呢

**Comment by PrinsYin** [comment]
> 今天开始，即使是官方网页，chatgpt回复长文本时，准确来说是回复时间超过一分钟，长连接就会断开，显示network error并无法保留回答的前半段内容，不清楚是bug还是访问人数太多官方做的限制



谢谢！

**Comment by Cheukfung** [comment]
今天官网已经可以正常使用了
