### ISSUE TITLE
revChatGPT 使用报错

### ISSUE THREAD

**Issue by Blitzer207** [fuergaosi233/wechat-chatgpt#341]
RuntimeError: Could import revChatGPT. Please install it first. You can run `poetry install` to install it.',
2022-12-12 14:19:38   failed: true,
2022-12-12 14:19:38   timedOut: false,
2022-12-12 14:19:38   isCanceled: false,
2022-12-12 14:19:38   killed: false

但是我确实已经安装了 revChatGP，而且使用poetry show 查看package 显示如下：
$ poetry show
anyio              3.6.2     High level compatibility layer for multiple asynchronous e...
certifi            2022.12.7 Python package for providing Mozilla's CA Bundle.
charset-normalizer 2.1.1     The Real First Universal Charset Detector. Open, modern an...
h11                0.14.0    A pure-Python, bring-your-own-I/O implementation of HTTP/1.1
h2                 4.1.0     HTTP/2 State-Machine based protocol implementation
hpack              4.0.0     Pure-Python HPACK header compression
httpcore           0.16.2    A minimal low-level HTTP client.
httpx              0.23.1    The next generation HTTP client.
hyperframe         6.0.1     HTTP/2 framing layer for Python
idna               3.4       Internationalized Domain Names in Applications (IDNA)
openaiauth         0.0.6     OpenAI Authentication Reverse Engineered
**requests**           2.28.1    Python HTTP for Humans.
revchatgpt         0.0.34    ChatGPT is a reverse engineering of OpenAI's ChatGPT API
rfc3986            1.5.0     Validating URI References per RFC 3986
sniffio            1.3.0     Sniff out which async library your code is running under
tls-client         0.1.5     Advanced Python HTTP Client.
urllib3            1.26.13   HTTP library with thread-safe connection pooling, file pos...

**Comment by FrozenPeak0701** [comment]
+1

**Comment by acheong08** [comment]
可以关了。revChatGPT死了。现在用这https://github.com/transitive-bullshit/chatgpt-api
