### ISSUE TITLE
我的显示账号添加成功，但是收不到返回消息

### ISSUE THREAD

**Issue by wanna1114** [fuergaosi233/wechat-chatgpt#342]
我的显示账号添加成功，但是收不到返回消息
<img width="1309" alt="WechatIMG98" src="https://user-images.githubusercontent.com/82891095/207061423-6ffe084a-fe62-40c6-b1b0-c8441e3e76de.png">

**Comment by poshoi** [comment]
和我一样 不知道什么问题
