### ISSUE TITLE
大佬们这个怎么解决

### ISSUE THREAD

**Issue by EdisonChen1** [fuergaosi233/wechat-chatgpt#344]
![ea6c520ba87a248375c99a06ad1a515](https://user-images.githubusercontent.com/80750797/207070496-90acbe21-1dd5-41b6-ac79-8ce41abc369a.jpg)

**Comment by Soupcpu** [comment]
chatgpt加了Cloudflare，请求被挡住了，这个项目恐怕是寄了，除非能搞到别的api

**Comment by 6Superman6** [comment]
vim config.ymal?
