### ISSUE TITLE
第一次运行是成功的，但是后续想要换个微信登录，再次运行程序后一直报错？如图

### ISSUE THREAD

**Issue by huakaiwuyeshu** [fuergaosi233/wechat-chatgpt#345]
<img width="1019" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/31621727/207073082-e321ba00-5af1-4a76-a925-74f59c2cc56b.png">
如图所示，docker 的运行日志

**Comment by xlxiaodai** [comment]
是否是未实名认证？
