### ISSUE TITLE
希望作者出一个只需要api key的 去调用api，收费也行，我不差钱

### ISSUE THREAD

**Issue by lonely1215225** [fuergaosi233/wechat-chatgpt#347]

**Comment by magicknight** [comment]
你有多不差钱？OpenAI的报价是 0.02 美元一个 token，这段话差不多35个token。

就是说每一句话要收你5块钱，你放到聊天群里试试看。

**Comment by Aoiujz** [comment]
https://github.com/869413421/wechatbot
拿走不谢

**Comment by Aoiujz** [comment]
> 你有多不差钱？OpenAI的报价是 0.02 美元一个 token，这段话差不多35个token。
> 
> 就是说每一句话要收你5块钱，你放到聊天群里试试看。

造谣不要成本么？

**Comment by goxofy** [comment]
> 你有多不差钱？OpenAI的报价是 0.02 美元一个 token，这段话差不多35个token。
> 
> 就是说每一句话要收你5块钱，你放到聊天群里试试看。

。。。你在哪看的

**Comment by risin42** [comment]
https://openai.com/api/pricing/#faq-token

> 1 token is approximately 4 characters

汉字的话，可能是两个字 =1 token

Davinci 模型的价格是 $0.0200  / 1K tokens，也就是＄1=50K tokens，大概25,000个汉字。

这是 text-davinci-003 的价格，且效果是不如 ChatGPT 的，目前 ChatGPT 并没有官方 API。

**Comment by A11en0** [comment]
> https://openai.com/api/pricing/#faq-token
> 
> > 1 token is approximately 4 characters
> 
> 汉字的话，可能是两个字 =1 token
> 
> Davinci 模型的价格是 $0.0200 / 1K tokens，也就是＄1=50K tokens，大概25,000个汉字。
> 
> 这是 text-davinci-003 的价格，且效果是不如 ChatGPT 的，目前 ChatGPT 并没有官方 API。

你再重新算算...

**Comment by lonely1215225** [comment]
笑死，我是看了价格之后才说的🤣，我没有卡，光用初始18刀就好了，没了再去注册账号就好了

**Comment by regomne** [comment]
重点还是chat gpt目前没有api，想花钱也没处用……

**Comment by bbhxwl** [comment]
这样的话我都自己做了一个公众号的

**Comment by ys-zzu** [comment]
关键是现在收费的那个api没有这个测试的智能

**Comment by bbhxwl** [comment]
> 关键是现在收费的那个api没有这个测试的智能

那就只能模拟了，真赚钱用的话，用模拟浏览器自己做了。浏览器层面的协议稍微不用天天更新。

**Comment by xhcdream** [comment]
> 你有多不差钱？OpenAI的报价是 0.02 美元一个 token，这段话差不多35个token。
> 
> 就是说每一句话要收你5块钱，你放到聊天群里试试看。

自己大概openai的官网，然后点击下方的pricing，用你睿智的眼睛看看，Davinci是1K个tokens收费0.02美刀

**Comment by vector4wang** [comment]
这里的token只针对输出吗？还是要把输入和输出都算上？在线等(2023年2月11日17:11:41)

**Comment by Prelude-life** [comment]
> 这里的token只针对输出吗？还是要把输入和输出都算上？在线等(2023年2月11日17:11:41)

官网说了输出输出都算

**Comment by ZPLOVEXYH** [comment]
> 

关键哪里有这么多手机号码来接收验证码呢？

**Comment by hellohufan** [comment]
> 
一个汉字是两个token，25个汉字就是1美金，折合差不多人民币7元了

**Comment by ZPLOVEXYH** [comment]
可以关注我开发的微信公众号【房飞布机器人】，免费体验人机对话。
