### ISSUE TITLE
一直提示No chatgpt item in pool

### ISSUE THREAD

**Issue by gamefi001** [fuergaosi233/wechat-chatgpt#352]
![image](https://user-images.githubusercontent.com/116825370/207228921-3e23e9c7-10ed-4454-8ee4-64c8d76f256f.png)

**Comment by RoadMillion** [comment]
今天用网页版玩发现每次都有机器人检测，估计要想办法绕过，一时半会不能用了

**Comment by nx4dm1n** [comment]
多看看历史issues吧，这个问题很多人都解答过了

**Comment by zhou22827665** [comment]
一直报这个问题，之前都是好好的，即使从新来一遍，也是不行

**Comment by Lukangkang123** [comment]
> 多看看历史issues吧，这个问题很多人都解答过了

这个问题是openAI的反机器人机制引起的，截止目前并没有解决。

**Comment by ys-zzu** [comment]
短短一天改了两次反机器人方式，看来官方是铁了心封堵所有入口。寄了

**Comment by Lukangkang123** [comment]
官方的chatGPT看来是不能用了，用这个官方提供的接口吧：https://github.com/869413421/wechatbot。 虽然效果没有官网好，但是能用而且稳定

**Comment by Lukangkang123** [comment]
> > 官方的chatGPT看来是不能用了，用这个官方提供的接口吧：[https://github.com/869413421/wechatbot。](https://github.com/869413421/wechatbot%E3%80%82) 虽然效果没有官网好，但是能用而且稳定
> 
> 官方的接口在哪？这个链接好像是个错的

你把最后的句号去掉就行了

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/210

**Comment by joker1499** [comment]
> > > 官方的chatGPT看来是不能用了，用这个官方提供的接口吧：[https://github.com/869413421/wechatbot。](https://github.com/869413421/wechatbot%E3%80%82) 虽然效果没有官网好，但是能用而且稳定
> > 
> > 
> > 官方的接口在哪？这个链接好像是个错的
> 
> 你把最后的句号去掉就行了
链接失效了

**Comment by joker1499** [comment]
> > > 官方的chatGPT看来是不能用了，用这个官方提供的接口吧：[https://github.com/869413421/wechatbot。](https://github.com/869413421/wechatbot%E3%80%82) 虽然效果没有官网好，但是能用而且稳定
> > 
> > 
> > 官方的接口在哪？这个链接好像是个错的
> 
> 你把最后的句号去掉就行了

有没有新的官方方法

**Comment by Lukangkang123** [comment]
> > > > 官方的chatGPT看来是不能用了，用这个官方提供的接口吧：[https://github.com/869413421/wechatbot。](https://github.com/869413421/wechatbot%E3%80%82) 虽然效果没有官网好，但是能用而且稳定
> > > 
> > > 
> > > 官方的接口在哪？这个链接好像是个错的
> > 
> > 
> > 你把最后的句号去掉就行了
> 
> 有没有新的官方方法

有QQ版本的，亲测这个流程简单最好用：[chat_gpt_oicq](https://github.com/easydu2002/chat_gpt_oicq)
