### ISSUE TITLE
隔壁貌似有新解决办法了

### ISSUE THREAD

**Issue by lonely1215225** [fuergaosi233/wechat-chatgpt#356]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/44398275/207240121-94f32373-df41-413f-83cf-6bbf869d57de.png">

**Comment by yangchuansheng** [comment]
没用，现在又多了一层反机器人验证

**Comment by vvanglro** [comment]
可以用我的项目来去获取cookie.  [cf-clearance](https://github.com/vvanglro/cf-clearance)

**Comment by RealTong** [comment]
OpenAI的验证一直在升级...

**Comment by JanYork** [comment]
> 可以用我的项目来去获取cookie. [cf-clearance](https://github.com/vvanglro/cf-clearance)

这个能绕过它最新的验证吗，貌似携带了cookie和UA等信息还是会被拦截返回403

**Comment by vvanglro** [comment]
还是可以正常通过cloudflare的检测.
```sh
curl http://localhost:8000/challenge -H "Content-Type:application/json" -X POST -d '{"proxy": {"server": "socks5://localhost:7890"}, "timeout":20, "url": "https://nowsecure.nl"}'
```
```json
{"success":true,"msg":"cf challenge success","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","cookies":{"cf_clearance":"iXZGO8EoNQQ3BhhepFtvLIAei_ptfkc6BQjZE3piVpM-1670982357-0-1-4c2e3e39.4447693d.65706037-160","__Host-next-auth.csrf-token":"8177b8a36bcaeb6d2f180feaca55d8b390c0bdb4019ba92e85ce6a5ac4ca9399%7C1d17e8bb0be2b9ed4f7c3acd06de56c41db47ed2a5062881008c2db27a52b698","__Secure-next-auth.callback-url":"https%3A%2F%2Fchat.openai.com","__cf_bm":"NYShfKXBEAxMJdGAEBSYH08cWIJYyExVHhWfgjRMNU0-1670982357-0-AYzKRRZ8xiRiLW1FOO6tuIiZ1oVbARS1UQ42Zl25XCepZWrxtNyap16UOpYUIiDsdheA6axO8g4B6Iu29h1oyjc="}}
```
但是后续使用cookie的时候必须和挑战cloudflare时是相同IP和UA.  至于cookie能用多久和请求的频率还得在测试.

**Comment by JanYork** [comment]
> 还是可以正常通过cloudflare的检测.
> 
> ```shell
> curl http://localhost:8000/challenge -H "Content-Type:application/json" -X POST -d '{"proxy": {"server": "socks5://localhost:7890"}, "timeout":20, "url": "https://nowsecure.nl"}'
> ```
> 
> ```json
> {"success":true,"msg":"cf challenge success","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","cookies":{"cf_clearance":"iXZGO8EoNQQ3BhhepFtvLIAei_ptfkc6BQjZE3piVpM-1670982357-0-1-4c2e3e39.4447693d.65706037-160","__Host-next-auth.csrf-token":"8177b8a36bcaeb6d2f180feaca55d8b390c0bdb4019ba92e85ce6a5ac4ca9399%7C1d17e8bb0be2b9ed4f7c3acd06de56c41db47ed2a5062881008c2db27a52b698","__Secure-next-auth.callback-url":"https%3A%2F%2Fchat.openai.com","__cf_bm":"NYShfKXBEAxMJdGAEBSYH08cWIJYyExVHhWfgjRMNU0-1670982357-0-AYzKRRZ8xiRiLW1FOO6tuIiZ1oVbARS1UQ42Zl25XCepZWrxtNyap16UOpYUIiDsdheA6axO8g4B6Iu29h1oyjc="}}
> ```
> 
> 但是后续使用cookie的时候必须和挑战cloudflare时是相同IP和UA. 至于cookie能用多久和请求的频率还得在测试.

可自动更新获取cf的令牌吗，手动会很麻烦

**Comment by Tarhyru** [comment]
> 还是可以正常通过cloudflare的检测.
> 
> ```shell
> curl http://localhost:8000/challenge -H "Content-Type:application/json" -X POST -d '{"proxy": {"server": "socks5://localhost:7890"}, "timeout":20, "url": "https://nowsecure.nl"}'
> ```
> 
> ```json
> {"success":true,"msg":"cf challenge success","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","cookies":{"cf_clearance":"iXZGO8EoNQQ3BhhepFtvLIAei_ptfkc6BQjZE3piVpM-1670982357-0-1-4c2e3e39.4447693d.65706037-160","__Host-next-auth.csrf-token":"8177b8a36bcaeb6d2f180feaca55d8b390c0bdb4019ba92e85ce6a5ac4ca9399%7C1d17e8bb0be2b9ed4f7c3acd06de56c41db47ed2a5062881008c2db27a52b698","__Secure-next-auth.callback-url":"https%3A%2F%2Fchat.openai.com","__cf_bm":"NYShfKXBEAxMJdGAEBSYH08cWIJYyExVHhWfgjRMNU0-1670982357-0-AYzKRRZ8xiRiLW1FOO6tuIiZ1oVbARS1UQ42Zl25XCepZWrxtNyap16UOpYUIiDsdheA6axO8g4B6Iu29h1oyjc="}}
> ```
> 
> 但是后续使用cookie的时候必须和挑战cloudflare时是相同IP和UA. 至于cookie能用多久和请求的频率还得在测试.

用这个拿到 cf_clearance 之后是不是需要自己实现模拟登陆？

**Comment by goxofy** [comment]
> 还是可以正常通过cloudflare的检测.
> ```sh
> curl http://localhost:8000/challenge -H "Content-Type:application/json" -X POST -d '{"proxy": {"server": "socks5://localhost:7890"}, "timeout":20, "url": "https://nowsecure.nl"}'
> ```
> ```json
> {"success":true,"msg":"cf challenge success","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","cookies":{"cf_clearance":"iXZGO8EoNQQ3BhhepFtvLIAei_ptfkc6BQjZE3piVpM-1670982357-0-1-4c2e3e39.4447693d.65706037-160","__Host-next-auth.csrf-token":"8177b8a36bcaeb6d2f180feaca55d8b390c0bdb4019ba92e85ce6a5ac4ca9399%7C1d17e8bb0be2b9ed4f7c3acd06de56c41db47ed2a5062881008c2db27a52b698","__Secure-next-auth.callback-url":"https%3A%2F%2Fchat.openai.com","__cf_bm":"NYShfKXBEAxMJdGAEBSYH08cWIJYyExVHhWfgjRMNU0-1670982357-0-AYzKRRZ8xiRiLW1FOO6tuIiZ1oVbARS1UQ42Zl25XCepZWrxtNyap16UOpYUIiDsdheA6axO8g4B6Iu29h1oyjc="}}
> ```
> 但是后续使用cookie的时候必须和挑战cloudflare时是相同IP和UA.  至于cookie能用多久和请求的频率还得在测试.

这样的话几乎不可能在服务器上跑了
