### ISSUE TITLE
微信号有可能会被封

### ISSUE THREAD

**Issue by protectione055** [fuergaosi233/wechat-chatgpt#359]
微信以”使用第三方软件、外挂、插件等非官方工具或其他违规行为“为理由把我的号封了。幸好是第一次，短信验证完打了几个勾保证以后不用就解封了。各位用的时候最好别用大号登陆。

**Comment by acai66** [comment]
刚解封，

**Comment by Lupeiwen0** [comment]
+1

**Comment by ColdZheng** [comment]
我也是

**Comment by xiaoyanyuha** [comment]
高位操作

**Comment by chenzzqa** [comment]
俺也一样

**Comment by yousalian** [comment]
> 确实是这样的，不知道为什么

转发到TG就好了 官方还提供api

**Comment by chenzzqa** [comment]
微信是怎么个检测机制

**Comment by protectione055** [comment]
> 微信是怎么个检测机制

最好笑的是张小龙给的理由是”经用户举报并查实“。只有少数几个朋友知道我在用这个bot，而且都不是那种会整别人的人。

**Comment by cxin-william** [comment]
大家都别搞了，看来都被提示了，理由更是奇葩，我还以为我被谁举报了

**Comment by OMGkillerMao** [comment]
每次扫码还得翻墙去扫？好麻烦

**Comment by xuweijie123** [comment]
+1

**Comment by chenzzqa** [comment]
> 我觉得你们更大的可能是, 用国外的服务器, 异地登录吧. 要是用软路由带上分流, 机器在国内没啥问题

也有可能

**Comment by Halimao** [comment]
> 我觉得你们更大的可能是, 用国外的服务器, 异地登录吧. 要是用软路由带上分流, 机器在国内没啥问题

跟服务器没关系，昨天就本地机器登录了下测试验证下，啥事都没做就关掉，然后下午突然就被封了

**Comment by joose1983** [comment]
刚解封，千万别用大号登录！

**Comment by chenzzqa** [comment]
下午还登了好多次，后面就给关小黑屋了，解封后不搞应该就没事了吧，害怕

**Comment by miozus** [comment]
我 docker 部署，扫描二维码登陆过，所以被重点关注了，大家一起封

不要用大号试

![image](https://user-images.githubusercontent.com/35659194/207290242-fbdbc31d-aad4-4b57-9e3f-6180e220693e.png)

**Comment by Ulysses0817** [comment]
应该不是流量和ip的问题，我用wx小号在vps上docker运行，没有任何警告

**Comment by ftq617** [comment]
两个号，全被封了

**Comment by hawx1993** [comment]
有人知道怎么在手机电报接入chatgpt吗，有咩有手机电报app可以使用chatgpt的方式？

**Comment by lswencn** [comment]
> > 微信是怎么个检测机制
> 
> 最好笑的是张小龙给的理由是”经用户举报并查实“。只有少数几个朋友知道我在用这个bot，而且都不是那种会整别人的人。

别扯蛋。。。 都会被封。。

**Comment by Aoiujz** [comment]
两个号全被封了 大号解封了 小号解封不了

**Comment by alunzi** [comment]
+1+1

**Comment by youaremywind** [comment]
被警告了，大家还是别用了

**Comment by 0x0021** [comment]
> 

我一直分流，照样被T下线

**Comment by dudukee** [comment]
被封+1

**Comment by LFMJUN** [comment]
被封+1

**Comment by zjh2765400096** [comment]
八点多还能登，十点多突然被强制下线封号警告了

**Comment by dfaqw** [comment]
> > 微信是怎么个检测机制
> 
> 最好笑的是张小龙给的理由是”经用户举报并查实“。只有少数几个朋友知道我在用这个bot，而且都不是那种会整别人的人。

我是小号，就两个好友。一个是我，另一个也是我。我被被我举报了-

**Comment by Brawns** [comment]
有没有可以直接调用API的

**Comment by wanna1114** [comment]
我手机上两个微信号，全部被封，幸亏能解封
