### ISSUE TITLE
可以做一个微信群@我然后可以回复的嘛谢谢大佬

### ISSUE THREAD

**Issue by phpoh** [fuergaosi233/wechat-chatgpt#36]
可以做一个微信群@我然后可以回复的嘛谢谢大佬

**Comment by fuergaosi233** [comment]
Isn't that what this is now?

**Comment by yuanwangz** [comment]
当bot在群里并且在本群中的昵称与微信昵称不一致时，@将无法触发chatgpt。可以将群昵称改成微信昵称一致再试试。同时希望能优化一下这块代码

**Comment by wangzhen-CHN** [comment]
现在不是可以支持吗
<img width="646" alt="image" src="https://user-images.githubusercontent.com/27632679/206354048-8b5cf057-a2d1-4ddf-81d1-ee443be141d9.png">

**Comment by phpoh** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月8日(星期四) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fuergaosi233/wechat-chatgpt] 可以做一个微信群@我然后可以回复的嘛谢谢大佬 (Issue #36)





 
当bot在群里并且在本群中的昵称与微信昵称不一致时，@将无法触发chatgpt。可以将群昵称改成微信昵称一致再试试。同时希望能优化一下这块代码

**Comment by phpoh** [comment]
现在可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月8日(星期四) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fuergaosi233/wechat-chatgpt] 可以做一个微信群@我然后可以回复的嘛谢谢大佬 (Issue #36)





 
现在不是可以支持吗

**Comment by fuergaosi233** [comment]
> 当bot在群里并且在本群中的昵称与微信昵称不一致时，@将无法触发chatgpt。可以将群昵称改成微信昵称一致再试试。同时希望能优化一下这块代码

Can you create a new issue?
