### ISSUE TITLE
Error: ⚠️ No chatgpt item in pool

### ISSUE THREAD

**Issue by skychecker** [fuergaosi233/wechat-chatgpt#360]
🤖️ Start GPT Bot Success, ready to handle message!
Message: Message#Unknown[🗣Contact<sky_checker>]
Message: Message#Unknown[🗣Contact<sky_checker>]
Message: Message#Text[🗣Contact<Sky Walkar>]	在吗
🎯 Triggered ChatGPT: 在吗
Refresh token failed, account {"session_token":"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..hPxJ7XuiCMn8MOSd.AsHzSKCGEPLhFZs4lP0Imvi6R0BNdbe3c9o0rSEm93TtevfQeFGQT-wD-ScceVyskI8JZl9Nq_kDTJclrevPlhXklNljrkA-t2ucFE8H859Y7sW1O58P_MlBMVVy5jXM-TXkjmtXj8iDQeocrZteZQvnnO*****Snmdl5E7Om0AZ1UqqOcCooO7vqKkyE-cswUTVmWbJ-kE1c-Saqj3-sw4ob1cXStGzY6HmYdQJ_OSfqW2MXFd-M9KCm0LWN_3AHeuj-jEQjWhTua9bhxb7aSBKSwfOxc1jWHq6ic-*******ye0dewUbK43RsD52X8WX659WZ3DVMocuR28v8sPcPLqWKCMLf9-Ig3t2Yu2UQUq67-vI_Fe2pMmPbrSP2yx7J12jfmCl7buZTd8EWz2WXouTOR8xF1Nla_MGX6nf-Fx7EnYOIgXBkicKpwMMTO9FvkosVpjzCEkDoB19vooqUJxx_RRswvCCfLxNPMvEVKyefzGR2SZWYQuSJyz9YgILWs9A_ravNhDZVXYrVUcw3k6HSkCKULwz4fV0CWrWawTTfLIQz1MXKf8nUNNIcSVh-GNWe5mRYym9DAaqTp8ms_NmKvD4raiHUqGPotpIUxZoF1l5yYQM5A05YRZhaZMmbUZEOMw8ZjhNIfitNoOlySPN2K8nASJNROrJ76zMnlkMgtXnqkrAKyaCnY8Dlvolc7qI5tY-GYXmFCkQCp9FQY5Nnn5uR-1SKZhv0caX5g0l3ntOimoBCeILHdyEUm2gEBddOQp3UKH-AwoQqmL3uX-Cv3mjdHZvu7vR2sSXesBQpYqBXQPzT0vT4Qjw_o8Xn90133JC24MOBBzkYOL7P02VgnoSH8Hens8DPox0fwTSSavf6m6IwUuFCVn0meCZzHQK848SDJ4hg0JNK9LnNdHxo6_ZnVDwR5rIqwbIcjWcI0KzX7tdd20SsKFFTDYgfhT0kCVwiUDpP4JIJRrDVZt3YfUns1WoYqicSa9Wd8KAWmkIfwMLLdq5eCkXUCuwxC3ybEJyxsxqYBhALpWqZOO5rJhKWAXtUK8nU1wMBBxJsB1W4JE53b-ElGCRCv3qROtJpx_Jc*****MJ0SK7Sf4qSRxRfgVg"}
Error: ⚠️ No chatgpt item in pool
at ChatGPTPoole.getConversation (file:///app/src/chatgpt.ts:200:13)
at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:219:35)
at ChatGPTPoole.sendMessage (file:///app/src/chatgpt.ts:230:21)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:286:12)
at async ChatGPTBot.onPrivateMessage (file:///app/src/chatgpt.ts:341:24)
at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:367:16)
at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/210
