### ISSUE TITLE
我用railway部署不成功是为什么 新手

### ISSUE THREAD

**Issue by IceFruits** [fuergaosi233/wechat-chatgpt#361]
![QQ截图20221213192000](https://user-images.githubusercontent.com/13396875/207304649-a11a16f2-a715-441b-afac-8a1d4cb3348a.jpg)

**Comment by myholiday** [comment]
昨天（2022.12.12），OpenAI 加入了CloudFlare认证措施。

**Comment by gfwang-dev** [comment]
> 昨天（2022.12.12），OpenAI 加入了CloudFlare认证措施。

有解决方案不？

**Comment by xlxiaodai** [comment]
> > 昨天（2022.12.12），OpenAI 加入了CloudFlare认证泄露。
> 
> 有解决办法不？

目前还没有
