### ISSUE TITLE
基于这个项目改了一个用OpenAI API访问的bot，目前能稳定部署云端

### ISSUE THREAD

**Issue by kx-Huang** [fuergaosi233/wechat-chatgpt#371]
https://github.com/kx-Huang/ChatGPT-on-WeChat

**Comment by vegaviazhang** [comment]
hey，bro，你这个是openai GPT3 的API，不是CHATGPT呀。

**Comment by Huskey-dai** [comment]
CHATGPT的api是不是有问题，用不了

**Comment by RealTong** [comment]
> CHATGPT的api是不是有问题，用不了

是的, ChatGPT加上了验证码

**Comment by kx-Huang** [comment]
> hey，bro，你这个是openai GPT3 的API，不是CHATGPT呀。

你说的对，我之后会修改文档。

不过，如果是作为娱乐项目的话，GPT-3可以当作ChatGPT一个的替代，目前可以方便在云端部署😂

**Comment by yumu7777777** [comment]
这个接口地址是楼主自己的吗

**Comment by kx-Huang** [comment]
> 这个接口地址是楼主自己的吗

不是，是OpenAI官方的接口，具体可以参考[这里](https://openai.com/api/)

**Comment by yumu7777777** [comment]
我问他你叫什么，他说杨永安，我还以为是你呢

**Comment by kx-Huang** [comment]
> 我问他你叫什么，他说杨永安，我还以为是你呢

bot的行为具体可以参考[这个issue: "对话是随机的吗"](https://github.com/fuergaosi233/wechat-chatgpt/issues/371#issuecomment-1352806806)

**Comment by gujiwork** [comment]
https://github.com/dnsjia/luban.git

**Comment by Kashima-Akira** [comment]
这个项目有一个分支也用的达芬奇003，这个训练集有点旧了
