### ISSUE TITLE
目前唯一能用的好像只剩这个了https://chatgpt.sbaliyun.com/

### ISSUE THREAD

**Issue by sbaliyun** [fuergaosi233/wechat-chatgpt#373]
openai 智能聊天对话  https://chatgpt.sbaliyun.com/
chatgpt也是基于openai 做的

**Comment by cartoonistOL** [comment]
你自己成功运行了吗

**Comment by cartoonistOL** [comment]
> https://chatgpt.sbaliyun.com/
你自己成功运行了吗

**Comment by lonely1215225** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/44398275/207824205-b8d6482d-20a8-4660-9d97-fb0cda7dc085.png">

**Comment by lonely1215225** [comment]
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/44398275/207824205-b8d6482d-20a8-4660-9d97-fb0cda7dc085.png">

这也是个骗子，明明就不是chatgpt

**Comment by xpssssss** [comment]
chatgpt是不是崩掉了

**Comment by aswifi** [comment]
这个第三方网站调用了OpenAI的API，使用的语音模型是davinci-003，因为调用API访问服务能绕过Cloudflare的安全检测问题，所以到现在还能正常用。

**Comment by aswifi** [comment]
这个第三方网站调用了OpenAI的API，使用的语言模型是davinci-003，因为调用API访问服务能绕过Cloudflare的安全检测，所以到现在还能正常用。

**Comment by gujiwork** [comment]
https://github.com/dnsjia/luban.git

**Comment by cartoonistOL** [comment]
> 这个第三方网站调用了OpenAI的API，使用的语言模型是davinci-003，因为调用API访问服务能绕过Cloudflare的安全检测，所以到现在还能正常用。

官方api是不是收费来着？

**Comment by aswifi** [comment]
> > 这个第三方网站调用了OpenAI的API，使用的语言模型是davinci-003，因为调用API访问服务能绕过Cloudflare的安全检测，所以到现在还能正常用。
> 
> 官方api是不是收费来着？
我用的时候确实是收费了，不过新注册的账号由18美元的额度。

**Comment by aswifi** [comment]
> > 这个第三方网站调用了OpenAI的API，使用的语言模型是davinci-003，因为调用API访问服务能绕过Cloudflare的安全检测，所以到现在还能正常用。
> 
> 官方api是不是收费来着？

我用的时候确实是收费了，不过新注册的账号由18美元的额度。

**Comment by Linkada** [comment]
API和chatgpt是两个东西，儿子和爸爸的区别

**Comment by aswifi** [comment]
> API和chatgpt是两个东西，儿子和爸爸的区别
确实，只能做到一问一答，作为学习工具还是可以的。

**Comment by aswifi** [comment]
> API和chatgpt是两个东西，儿子和爸爸的区别


确实，只能做到一问一答，作为学习工具还是可以的。

**Comment by thechen130** [comment]
这个是基于API调用的，效果很差，应该是基于GPT-2，chatgpt基于GPT-3.5，两者的差距一个天一个地。这个看看就行
