### ISSUE TITLE
The stream is not readable. Maybe has already been consumed, and now it was drained.

### ISSUE THREAD

**Issue by tian-jie** [fuergaosi233/wechat-chatgpt#375]
cloned this project and try to save files to local disk, but when using filebox.toFile, it throws out the exception.

code:
      var filebox = await message.toFileBox();
      await filebox.toFile();

I saw the discussion: https://github.com/huan/file-box/issues/50
but I didn't find solution, it just said we need to save it in first use.
but this is the top thing I can do, just in on('message') function.

anyway to work around?

**Comment by ysrock** [comment]
遇到同样的问题

**Comment by Lyq0055** [comment]
请问解决了吗

**Comment by jerry-f** [comment]
遇到同样的问题~~， 没解决

**Comment by YuanDaoDao001** [comment]
+ 1

**Comment by bestK** [comment]
``` js
async function saveFile(filebox, path = 'resource') {
  const audioReadStream = Readable.from(filebox.stream);
  const filePath = PATH.join(path, filebox.name);
  const writeStream = FS.createWriteStream(filePath);

  audioReadStream.pipe(writeStream);

  await new Promise((resolve, reject) => {
    writeStream.on('finish', resolve);
    writeStream.on('error', reject);
  });
}
```
