### ISSUE TITLE
扫二维码无效[Service Unavailable]

### ISSUE THREAD

**Issue by GeneralCorn** [fuergaosi233/wechat-chatgpt#376]
If I use railway to deploy and try to scan the code in logs after clicking the link wechat says "Service unavailable for this account"
![10731671161874_ pic](https://user-images.githubusercontent.com/31541737/208016468-03279d1e-d432-4e36-9ae7-c2041449eddd.jpg)

Then after the third try this error shows up
![Screen Shot 2022-12-15 at 21 38 48](https://user-images.githubusercontent.com/31541737/208016560-ef022ca4-3b33-43bf-a23a-a9bc33591ea7.png)

Any idea?

Thanks!

**Comment by xlxiaodai** [comment]
现在已经无法部署了 等待解决方案

**Comment by owenthereal** [comment]
I ran into the same problem. Can anyone help?

**Comment by songty11** [comment]
Hi, just ran into the same issue, any solution here?
