### ISSUE TITLE
运行npm run dev失败

### ISSUE THREAD

**Issue by aipave** [fuergaosi233/wechat-chatgpt#377]
$ sudo npm run dev

> wechat-chatgpt@1.0.0 dev /wechat-chatgpt_docker
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

sh: 1: nodemon: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! wechat-chatgpt@1.0.0 dev: `nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the wechat-chatgpt@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-17T08_22_09_567Z-debug.log

是否是因为版本不对
$ node -v
v10.19.0

**Comment by alyu01** [comment]
i fix it with  
$ npm install nodemon --save-dev
To [https://stackoverflow.com/questions/28517494/nodemon-not-found-in-npm](url) for more info

**Comment by alyu01** [comment]
$ npm install nodemon --save-dev
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> leveldown@6.1.1 install/wechat-chatgpt_docker/node_modules/leveldown
> node-gyp-build


> puppeteer@13.7.0 install /wechat-chatgpt_docker/node_modules/puppeteer
> node install.js

Downloading Chromium r982053 - 150.3 Mb [====================] 100% 0.0s 
Chromium (982053) downloaded to /wechat-chatgpt_docker/node_modules/puppeteer/.local-chromium/linux-982053

> protobufjs@7.1.2 postinstall /wechat-chatgpt_docker/node_modules/protobufjs
> node scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN wechat-chatgpt@1.0.0 No repository field.

+ nodemon@2.0.20
added 508 packages from 405 contributors and audited 510 packages in 147.901s

78 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
  
  
然后发现新问题 执行 npm run dev
[nodemon] starting `node --loader ts-node/esm src/main.ts`
node: --loader requires --experimental-modules be enabled
[nodemon] app crashed - waiting for file changes before starting...

**Comment by qq286674943** [comment]
nodejs 版本他太低了 必须要大于18的版本

**Comment by hecarli555** [comment]
> nodejs 版本他太低了 必须要大于等于18的版本

安装指令要怎么写？debain11的
