### ISSUE TITLE
 No chatgpt item in pool 

### ISSUE THREAD

**Issue by Jqtao** [fuergaosi233/wechat-chatgpt#380]
No chatgpt item in pool  这个问题是不是还是没有被解决

**Comment by Sein-Ding** [comment]
作者阳了😅 等等吧

**Comment by RealTong** [comment]
> No chatgpt item in pool 这个问题是不是还是没有被解决

我们现在正在测试模拟浏览器的方案
如果你有一定的动手能力, 可以试用这个分支 : https://github.com/fuergaosi233/wechat-chatgpt/tree/feat/upgrade-chatgpt-api
