### ISSUE TITLE
微信登入后，与其对话无法接收，并输出以下内容

### ISSUE THREAD

**Issue by Ep2phany** [fuergaosi233/wechat-chatgpt#387]
TimeoutError: Waiting for selector `#password` failed: Waiting failed: 120000ms exceeded
    at Timeout.<anonymous> (E:\OPENAI\wechat-chatgpt-main(1.0.0 alpha)\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RealTong** [comment]
是手动打码还是自动打码?
如果是自动打码可能是因为验证码没过

**Comment by Ep2phany** [comment]
> 是手动打码还是自动打码? 如果是自动打码可能是因为验证码没过
是指验证码嘛，我并没有配置，请问如何配置

**Comment by Ep2phany** [comment]
> > > 是手动打码还是自动打码？如果是自动打码可能是因为验证码不过
> > > 是验证码嘛，我并没有配置，请问如何配置
> 
> 参考这里：[https](https://github.com/fuergaosi233/wechat-chatgpt#captchas) : //github.com/fuergaosi233/wechat-c​​hatgpt#captchas将打码平台的token设置到环境变化中 `export NOPECHA_KEY="XXXXXXXXXXXXXXXXX"

好的，感谢

**Comment by thechen130** [comment]
> > > 是手动打码还是自动打码? 如果是自动打码可能是因为验证码没过
> > > 是指验证码嘛，我并没有配置，请问如何配置
> 
> 参考这里: https://github.com/fuergaosi233/wechat-chatgpt#captchas 将打码平台的token 设置到环境变量中 `export NOPECHA_KEY="XXXXXXXXXXXXXXXXX"

请问NOPECHA_KEY是nopecha.com/manage界面的Subscription Key吗

**Comment by RealTong** [comment]
> > > > 是手动打码还是自动打码? 如果是自动打码可能是因为验证码没过
> > > > 是指验证码嘛，我并没有配置，请问如何配置
> > 
> > 
> > 参考这里: https://github.com/fuergaosi233/wechat-chatgpt#captchas 将打码平台的token 设置到环境变量中 `export NOPECHA_KEY="XXXXXXXXXXXXXXXXX"
> 
> 请问NOPECHA_KEY是nopecha.com/manage界面的Subscription Key吗

yes.

**Comment by dayeguilaiye** [comment]
你们成功了吗，我配置到了环境变量里，依然失败

**Comment by dayeguilaiye** [comment]
![image](https://user-images.githubusercontent.com/9746948/209261902-23650244-0cbf-4247-b333-e4ce4170a388.png)
uncaughtException Error: Command failed with exit code 1: sh -c poetry run python3 src/generate_session.py

**Comment by emmmnaadada** [comment]
> 你们成功了吗，我配置到了环境变量里，依然失败

没有

**Comment by thechen130** [comment]
> > > > > 是手动打码还是自动打码? 如果是自动打码可能是因为验证码没过
> > > > > 是指验证码嘛，我并没有配置，请问如何配置
> > > 
> > > 
> > > 参考这里: https://github.com/fuergaosi233/wechat-chatgpt#captchas 将打码平台的token 设置到环境变量中 `export NOPECHA_KEY="XXXXXXXXXXXXXXXXX"
> > 
> > 
> > 请问NOPECHA_KEY是nopecha.com/manage界面的Subscription Key吗
> 
> yes.

依旧没有成功

**Comment by tiger233** [comment]
> 是手动打码还是自动打码? 如果是自动打码可能是因为验证码没过

手动打码在哪里设置呢？ 设置环境变量是在容器里面还是在宿主机上面？ 我理解启动容器时使用-v xx=xx就可以吧
