### ISSUE TITLE
railway部署失败 WARN WechatyPuppetMixin start() starting puppet ... timeout

### ISSUE THREAD

**Issue by esojourn** [fuergaosi233/wechat-chatgpt#389]
![image](https://user-images.githubusercontent.com/12231232/208824588-658f07e3-f511-4202-a052-011f2635acd0.png)
部署后，显示
WARN WechatyPuppetMixin start() starting puppet ... timeout
xvfb-run: error: Xvfb failed to start

restart或redeploy之后 ，还是出现同样的问题。

我用的是starter plan，是因为硬件不够，需要升级到付费方案才能运行吗？

**Comment by RealTong** [comment]
你尝试删除`src/main.ts` L8-L12, 之后重新build

**Comment by lcm1475** [comment]
一样的错误 在哪里删除src/main.ts

**Comment by esojourn** [comment]
> 你尝试删除`src/main.ts` L8-L12, 之后重新build

感谢回复，您的意思是删8-10行吗？12行不能删吧？
11行也删掉？
![image](https://user-images.githubusercontent.com/12231232/208842209-5dc8bec9-17ae-40fc-8ced-3400369616b5.png)

**Comment by esojourn** [comment]
> 一样的错误 在哪里删除src/main.ts

我想应该是在github里，自己fork的代码里改。

**Comment by esojourn** [comment]
![image](https://user-images.githubusercontent.com/12231232/208843413-2642e04d-c685-4c7a-a5ea-86bcb6146497.png)


> 你尝试删除`src/main.ts` L8-L12, 之后重新build

试了删8-10行，和删8-11行，两种情况。
还是没成功。

![image](https://user-images.githubusercontent.com/12231232/208843667-f6ec3cff-d01d-43c9-96ab-fcbe9c3c0800.png)

**Comment by lcm1475** [comment]
好吧 那我不用试了

**Comment by eyaeya** [comment]
#385
