### ISSUE TITLE
railway部署，没有找到哪里填NOPECHA_KEY

### ISSUE THREAD

**Issue by esojourn** [fuergaosi233/wechat-chatgpt#392]
如题。直接加这里管用吗？
![image](https://user-images.githubusercontent.com/12231232/208843925-6bfbd9f0-e06f-41bd-b531-088a6a511e2e.png)

**Comment by lcm1475** [comment]
应该是填在这里的 我也是填在这里

**Comment by RealTong** [comment]
是在这里

**Comment by lcm1475** [comment]
你跑起来了吗

**Comment by esojourn** [comment]
> 你跑起来了吗

没有，现在railway部署好象有问题。在等作者处理。
https://github.com/fuergaosi233/wechat-chatgpt/issues/385
