### ISSUE TITLE
uncaughtException TimeoutError: Navigation timeout of 30000 ms exceeded at /app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:211:18

### ISSUE THREAD

**Issue by LittleXingzzZ** [fuergaosi233/wechat-chatgpt#393]
uncaughtException TimeoutError: Navigation timeout of 30000 ms exceeded
at /app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:211:18

这是什么问题 发生在 Start GPT Bot 后

**Comment by flashclub** [comment]
> uncaughtException TimeoutError: Navigation timeout of 30000 ms exceeded at /app/node_modules/puppeteer/src/common/LifecycleWatcher.ts:211:18
> 
> 这是什么问题 发生在 Start GPT Bot 后

+1 我都改了源码  设置了邮箱和密码又将谷歌登陆设置为true，终于不报邮箱的错之后走到这一步，实在不知道怎么解决了

**Comment by songdianxue** [comment]
我也遇到了同样的问题。

**Comment by songdianxue** [comment]
![image](https://user-images.githubusercontent.com/18309354/210976780-02233d69-0103-434e-8e42-3f7eb92827c8.png)
请各位大神专家看看是什么问题。
