### ISSUE TITLE
run erro

### ISSUE THREAD

**Issue by lofter414** [fuergaosi233/wechat-chatgpt#398]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:58) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
17:21:25 WARN WechatyPuppetMixin start() starting puppet ... timeout
17:21:25 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
17:22:10 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
17:22:10 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
17:22:10 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by MrQYX** [comment]
I ran the container after building the image. I encountered the same error as you. How can I solve it?

**Comment by gaoxianghua** [comment]
same error
