### ISSUE TITLE
如何解决微信登陆域名无法解析问题？

### ISSUE THREAD

**Issue by zjrwtx** [fuergaosi233/wechat-chatgpt#401]
![image](https://user-images.githubusercontent.com/86822589/209076405-72ea9da6-6f31-4163-857c-5ba92445cb6c.png)
![image](https://user-images.githubusercontent.com/86822589/209076477-58f41c8a-ae32-468d-b608-7ab7da6e8d27.png)

**Comment by RealTong** [comment]
你可以设置一下容器的网络

**Comment by zjrwtx** [comment]
> 你可以设置一下容器的网络

啊这 不应该啊 我docker都能下载这个镜像了 应该是可以访问外部网络的
