### ISSUE TITLE
配置了NOPECHA_KEY环境变量，依然无法登录chat

### ISSUE THREAD

**Issue by dayeguilaiye** [fuergaosi233/wechat-chatgpt#405]
![image](https://user-images.githubusercontent.com/9746948/209264873-f8598280-064b-47a0-89a3-99ffc3218deb.png)
微信登录也有报错，不过根据issues看，似乎不影响。

环境变量中我已经配置了NOPECHA_KEY

**Comment by emmmnaadada** [comment]
同样的错误

**Comment by tiger233** [comment]
一样的报错

**Comment by BigerPatax** [comment]
等作者更新docker的镜像吧  我看了一下docker镜像的chatgpt版本是2.几的  最新的支持打码的要3.3.4版本  设置了也没用上
