### ISSUE TITLE
chatgpt部分为什么不采用官方提供的个人密钥的接口调用方式？一定要用网页token方式？

### ISSUE THREAD

**Issue by orchief** [fuergaosi233/wechat-chatgpt#406]
具体申请地址如下：
https://beta.openai.com/account/api-keys

**Comment by fgs2008** [comment]
这个版本是3.0 不够智能

**Comment by eyaeya** [comment]
> 

ChatGPT的接口调用的是老版本，只有网页交互的才是大家津津乐道的新版本。

**Comment by h3clikejava** [comment]
因为web免费，走api要钱

**Comment by orchief** [comment]
是费用问题还是版本问题有谁知道

**Comment by znhooo** [comment]
> 是费用问题还是版本问题有谁知道

版本问题，我用过那个官方api，不智能。
