### ISSUE TITLE
首页文档看起来不连贯了，之前的部署步骤都没了，新手没看明白

### ISSUE THREAD

**Issue by OMGkillerMao** [fuergaosi233/wechat-chatgpt#407]

**Comment by linj121** [comment]
把哪里卡住了，从哪步到哪步的跳跃没看明白，以及报错信息等等都描述一下，才能够继续讨论啊

**Comment by emmmnaadada** [comment]
> 把哪里卡住了，从哪步到哪步的跳跃没看明白，以及报错信息等等都描述一下，才能够继续讨论啊

配置了key，但是api erro

**Comment by OMGkillerMao** [comment]
> 把哪里卡住了，从哪步到哪步的跳跃没看明白，以及报错信息等等都描述一下，才能够继续讨论啊

现在配置了帐号密码，报api错误，之前配置token的模板代码也不见了

**Comment by BigerPatax** [comment]
估计是提交了代码合并出问题了，你们可以从main分支切换到1.0.0-alpha  这个分支的文档比较完整 @OMGkillerMao @linj121 @emmmnaadada
