### ISSUE TITLE
微信扫码登陆失败（国内注册的非实名制微信号）

### ISSUE THREAD

**Issue by YangQing1989** [fuergaosi233/wechat-chatgpt#410]
![image](https://user-images.githubusercontent.com/26144773/209423475-0550b005-3936-4f57-8b03-56e4e12a6c5a.png)

**Comment by jayking0912** [comment]
#84 点微信我的->钱包->身份信息会提示完善个人信息。实名过后就解决了，应该是微信的限制的

**Comment by RealTong** [comment]
需要使用+86手机号注册, 并且实名的微信号.
你可以尝试自己是否可登录 https://wx.qq.com/
