### ISSUE TITLE
使用Railway deploy报错，Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by leaveshadowsky** [fuergaosi233/wechat-chatgpt#411]
![image](https://user-images.githubusercontent.com/34124192/209423943-52514f77-70c8-4af1-bf54-e97508f5edbd.png)

**Comment by ltDino** [comment]
我也是，mark一下

**Comment by ltDino** [comment]
可以了老哥，看这个https://github.com/fuergaosi233/wechat-chatgpt/issues/385

**Comment by vivihu** [comment]
> 可以了老哥，看这个#385

怎么解决呀？
