### ISSUE TITLE
使用railway配置session，扫码登录后报错提示无效email，仍需要配置email，重新配置email与passwd后报其他错误

### ISSUE THREAD

**Issue by shzhhan** [fuergaosi233/wechat-chatgpt#418]

**Comment by shzhhan** [comment]
![微信图片_20221226131939](https://user-images.githubusercontent.com/53850111/209505032-662eef78-338a-4168-b848-1a0910d0e1bc.png)
![微信图片_20221226131943](https://user-images.githubusercontent.com/53850111/209505063-2f630503-bca7-4793-a03a-aa74b463aeb7.png)

**Comment by shzhhan** [comment]
重新配置email与passwd后报错
![微信图片_20221226132118](https://user-images.githubusercontent.com/53850111/209505395-d212ae1d-1de1-411e-a178-9000582bfa95.png)

**Comment by cherrythefatbunny** [comment]
me too

**Comment by O-rz** [comment]
+1

**Comment by coolmian** [comment]
> 重新配置email与passwd后报错 ![微信图片_20221226132118](https://user-images.githubusercontent.com/53850111/209505395-d212ae1d-1de1-411e-a178-9000582bfa95.png)

me too

**Comment by yxrind** [comment]
me too

**Comment by h3clikejava** [comment]
me too too
