### ISSUE TITLE
扫码登录后 GError: Page crashed!

### ISSUE THREAD

**Issue by etvon** [fuergaosi233/wechat-chatgpt#419]
按照 #385 删除了一行后终于能扫码登录了  但是扫码后还是不行
报错如下

User Contact<微信昵称> logged in
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"账户","password":"密码"}],"chatGptRetryTimes":8,"chatPrivateTiggerKeyword":""}
GError: Page crashed!
at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
at /app/node_modules/puppeteer/src/common/Page.ts:573:53
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
code: 2,
details: 'Error: Page crashed!\n' +
'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
'    at Array.map (<anonymous>)\n' +
'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dolo** [comment]
一样……

**Comment by fuergaosi233** [comment]
This looks like wechaty's problem 🤔

**Comment by fuergaosi233** [comment]
Does this problem have to arise?

**Comment by etvon** [comment]
> Does this problem have to arise?

yes, tried many times and all end up with this result

**Comment by LFMJUN** [comment]
same question

**Comment by LFMJUN** [comment]
Some times it appeared this error

`User Contact<Fragile_> logged in
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"lfmjun@qq.com","password":"Yanxu.123"}],"chatGptRetryTimes":10,"chatPrivateTiggerKeyword":""}
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.
at Timeout.onTimeout (/app/node_modules/puppeteer/src/node/BrowserRunner.ts:284:9)
at listOnTimeout (node:internal/timers:564:17)
at processTimers (node:internal/timers:507:7)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by LFMJUN** [comment]
some times appears this error 
`User Contact<Fragile_> logged in
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"","password":""}],"chatGptRetryTimes":10,"chatPrivateTiggerKeyword":""}
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.
at Timeout.onTimeout (/app/node_modules/puppeteer/src/node/BrowserRunner.ts:284:9)
at listOnTimeout (node:internal/timers:564:17)
at processTimers (node:internal/timers:507:7)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by Chadwuo** [comment]
俺也一样

**Comment by fuergaosi233** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/22197568/209618496-8e80616d-54fc-43e3-9abe-0d16fb88c441.png">
Try to comment out line 11

**Comment by LegendLeo** [comment]
> 

it doesn't work, shows another error: Navigation failed because browser has disconnected!
<img width="978" alt="image" src="https://user-images.githubusercontent.com/25115173/209622326-b139b0d2-7924-48ec-93a1-74dad68cc708.png">

**Comment by etvon** [comment]
同上 注释掉11行后 
uncaughtException Error: Navigation failed because browser has disconnected!

**Comment by AmandaloveYang** [comment]
一样

**Comment by likfees** [comment]
注释掉11行后
uncaughtException Error: Navigation failed because browser has disconnected!

**Comment by hx3333** [comment]
> > 
> 
> it doesn't work, shows another error: Navigation failed because browser has disconnected! <img alt="image" width="978" src="https://user-images.githubusercontent.com/25115173/209622326-b139b0d2-7924-48ec-93a1-74dad68cc708.png">

I got the same problem, any solutions?
