### ISSUE TITLE
config.yml中openAIProxy如何填写

### ISSUE THREAD

**Issue by KillZero12138** [fuergaosi233/wechat-chatgpt#421]
![66dfdf521377084ff24bda4987d66fa](https://user-images.githubusercontent.com/112448787/209599329-b00a2598-5c61-4004-9113-36ae84f587c1.png)

**Comment by JK-zy** [comment]
AlsoAsk

**Comment by thorraythorray** [comment]
http_proxy ？

**Comment by KillZero12138** [comment]
> http_proxy ？

？

**Comment by dolo** [comment]
this only required for Chinese mainland user. 
optional for whom can direct access to open ai

**Comment by KillZero12138** [comment]
> 

If I use VPN，What need I do？

**Comment by KillZero12138** [comment]
> If I use VPN，What need I do？

**Comment by KillZero12138** [comment]
> 

If I use VPN，What need I do？

**Comment by fuergaosi233** [comment]
such as: http://localhost:7890
