### ISSUE TITLE
微信登录成功后提示app crashed

### ISSUE THREAD

**Issue by hanyin111** [fuergaosi233/wechat-chatgpt#424]
06:20:09 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
this.puppet.emit('error', new Error(
^
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
at Watchdog.emit (node:events:513:28)
at Watchdog.emit (node:domain:489:12)
at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
at listOnTimeout (node:internal/timers:564:17)
at processTimers (node:internal/timers:507:7) {
code: 2,
details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
'    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
'    at Watchdog.emit (node:events:513:28)\n' +
'    at Watchdog.emit (node:domain:489:12)\n' +
'    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
'    at listOnTimeout (node:internal/timers:564:17)\n' +
'    at processTimers (node:internal/timers:507:7)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by seolhw** [comment]
和我一样，不知道怎么解决

**Comment by coder-xiaotian** [comment]
大佬，解决了吗，我也遇到了

**Comment by mings-operation** [comment]
大佬解决了吗

**Comment by leoliew** [comment]
一样问题

**Comment by chenliu1993** [comment]
> 大佬解决了吗

没有，我换了别的repo在用

**Comment by chenliu1993** [comment]
我换了别的repo在用，这个光搭环境就已经很痛苦了
