### ISSUE TITLE
No chatgpt item in pool

### ISSUE THREAD

**Issue by govbk** [fuergaosi233/wechat-chatgpt#427]
![image](https://user-images.githubusercontent.com/21957825/209631679-a25c8be3-a1c7-4781-b797-27bdfaa37443.png)
docker搭建，能扫码能登陆微信，能接收到消息，但是消息不反馈，openai的账号密码是填对的，咋回事呢

**Comment by BigerPatax** [comment]
作者今天更新了readme，无法使用的问题正在努力解决

**Comment by dgqypl** [comment]
> 

Hi, 我按照您的方式在本地构建，报了这个错：

 ✘  ~/Downloads/opensourceForRead/wechat-chatgpt  ➦ 83353b0  docker build -t holegots/wechat-chatgpt-lb .
[+] Building 6.4s (6/10)
 => [internal] load build definition from Dockerfile                                            0.0s
 => => transferring dockerfile: 37B                                                             0.0s
 => [internal] load .dockerignore                                                               0.0s
 => => transferring context: 35B                                                                0.0s
 => [internal] load metadata for docker.io/library/node:19                                      2.3s
 => [internal] load build context                                                               0.0s
 => => transferring context: 3.04kB                                                             0.0s
 => CACHED [1/6] FROM docker.io/library/node:19@sha256:d5222e1ebd7dd7e9683f47a8861a4711cb4407a  0.0s
 => ERROR [2/6] RUN apt-get install -y wget     && wget -q -O - https://dl-ssl.google.com/linu  4.0s
------
 > [2/6] RUN apt-get install -y wget     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list     && apt-get update && apt-get -y install google-chrome-stable chromium  xvfb    && rm -rf /var/lib/apt/lists/*     && echo "Chrome: " && google-chrome --version:
#5 0.155 Reading package lists...
#5 0.162 Building dependency tree...
#5 0.163 Reading state information...
#5 0.168 wget is already the newest version (1.21-1+deb11u1).
#5 0.168 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#5 0.202 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#5 1.109 OK
#5 1.432 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#5 1.447 Get:2 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
#5 1.710 Get:3 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#5 1.843 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#5 1.949 Get:5 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
#5 2.768 Get:6 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [206 kB]
#5 2.876 Get:7 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#5 3.364 Fetched 8500 kB in 2s (3800 kB/s)
#5 3.364 Reading package lists...
#5 3.622 Reading package lists...
#5 3.877 Building dependency tree...
#5 3.945 Reading state information...
#5 3.992 E: Unable to locate package google-chrome-stable
------
executor failed running [/bin/sh -c apt-get install -y wget     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list     && apt-get update && apt-get -y install google-chrome-stable chromium  xvfb    && rm -rf /var/lib/apt/lists/*     && echo "Chrome: " && google-chrome --version]: exit code: 100

麻烦帮忙看一下
