### ISSUE TITLE
中文文档需要更新

### ISSUE THREAD

**Issue by WindowsRegedit** [fuergaosi233/wechat-chatgpt#428]
1. 配置文件方面
<img width="227" alt="image" src="https://user-images.githubusercontent.com/90195560/209645830-f0bfcbc8-aac6-4d1c-b7f0-a454f1ceec71.png">
<img width="209" alt="image" src="https://user-images.githubusercontent.com/90195560/209645872-94f9f5b7-2f1d-4f67-a102-825bdc8b2207.png">
（应该用openAIProxy而不是环境变量）
2. 旧功能删除
<img width="391" alt="image" src="https://user-images.githubusercontent.com/90195560/209646023-27715b7c-3c00-4931-8dac-9e5ba85110aa.png">
（在英文文档中，使用sessionToken的方法已被删除）

**Comment by RealTong** [comment]
感谢您的提醒, 现在中文文档已经更新了.
