### ISSUE TITLE
error while npm run dev

### ISSUE THREAD

**Issue by LFMJUN** [fuergaosi233/wechat-chatgpt#432]
`root@aiyun167005040150:~/wechat-chatgpt# npm run dev

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:756833) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
10:39:32 ERR PuppetWeChatBridge start() exception: Error: Failed to launch the browser process!
/root/wechat-chatgpt/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

10:39:32 ERR PuppetWeChat initBridge() exception: Failed to launch the browser process!
/root/wechat-chatgpt/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

10:39:32 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
⚠️ Bot start failed, can you log in through wechat on the web?: Error: Failed to launch the browser process!
/root/wechat-chatgpt/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

[nodemon] clean exit - waiting for changes before restart`

**Comment by LFMJUN** [comment]
Fixed with installing xvfb and chrome. 
But error continued #415 415

**Comment by LFMJUN** [comment]
using 2captcha is ok

**Comment by lishuiqiao** [comment]
> 

how did you install chrome? I got the same issue

**Comment by lishuiqiao** [comment]
> Fixed with installing xvfb and chrome. But error continued #415 415

how did you install chrome? I got the same issue

**Comment by LFMJUN** [comment]
> > Fixed with installing xvfb and chrome. But error continued #415 415
> 
> how did you install chrome? I got the same issue

search on google

**Comment by BigerPatax** [comment]
> > > Fixed with installing xvfb and chrome. But error continued #415 415
> > 
> > 
> > how did you install chrome? I got the same issue
> 
> search on google

how to use 2captcha? i set the CAPTCHA_TOKEN but not work, no captchas found
