### ISSUE TITLE
二维码生成失败

### ISSUE THREAD

**Issue by Zhangyf628** [fuergaosi233/wechat-chatgpt#433]
![捕获](https://user-images.githubusercontent.com/81681929/209814852-06f1c89e-e033-46b5-8f40-3faa97fbb6ec.PNG)
如图，启动项目的时候显示错误，二维码失效扫不出来，麻烦帮忙看一下这是怎么回事谢谢

**Comment by RealTong** [comment]
可能是你的Terminal字体有问题吧, 你可以试试点击二维码上面的链接扫描
