### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Kylsky** [fuergaosi233/wechat-chatgpt#435]
build 报错了:
Unable to locate package google-chrome-stable
m1 mac build的

**Comment by BigerPatax** [comment]
要安装google-chrome-stable  chromium  xvfb这三个包  看Dockerfile里的命令

**Comment by sherlockBJ** [comment]
我也一直遇到这个问题，没有安装上这三个包

Errors were encountered while processing:
 /tmp/apt-dpkg-install-bU4GFS/057-google-chrome-stable_111.0.5563.64-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y wget     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list     && apt-get update && apt-get -y install google-chrome-stable chromium  xvfb    && rm -rf /var/lib/apt/lists/*     && echo "Chrome: " && google-chrome --version' returned a non-zero code: 100

**Comment by sherlockBJ** [comment]
是不是和linux系统的版本有关系？

**Comment by umcai** [comment]
同报错，我用的亚马逊arm架构主机，Ubuntu 22.04.2 LTS

**Comment by QiYorkkk** [comment]
所以怎么解决？
