### ISSUE TITLE
运行npm run dev报错：app crashed

### ISSUE THREAD

**Issue by CSerht** [fuergaosi233/wechat-chatgpt#437]
我的系统是Ubuntu20.04.3LST。

运行`npm run dev`之后显示如下内容：

```
> wechat-chatgpt@1.0.0 dev /home/jht/college/chatgpt/chatGPT-wechat-real/wechat-chatgpt
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
node: --loader requires --experimental-modules be enabled
[nodemon] app crashed - waiting for file changes before starting...
```

最后显示了`[nodemon] app crashed - waiting for file changes before starting...`不知道如何解决。

我是按照12月29日main分支的版本，一键安装失效，因此进行手动安装配置，得到了以上结果。

其中在`npm install`的时候，得到了` inefficient regular expression complexity in nth-check`的高危漏洞警告，并且我没有处理，直接单独运行了`poetry install`，该命令没有问题。

不知道是什么原因导致的，Google之后也没有找到解决办法，请大家指教！

**Comment by HaitianJiang** [comment]
解决了，node版本有问题，node>=18

**Comment by ltDino** [comment]
> 解决了，node版本有问题，node>=18

我的在v18.12.0版本也会出现app crashed 的问题，想请问你的版本是多少？

**Comment by CSerht** [comment]
> > 解决了，node版本有问题，node>=18
> 
> 我的在v18.12.0版本也会出现app crashed 的问题，想请问你的版本是多少？

我的版本是18.2.1

**Comment by thechen130** [comment]
> > > 解决了，node版本有问题，node>=18
> > 
> > 
> > 我的在v18.12.0版本也会出现app crashed 的问题，想请问你的版本是多少？
> 
> 我的版本是18.2.1

有没有ubuntu安装18.2.1的教程

**Comment by CSerht** [comment]
> > > > 解决了，node版本有问题，node>=18
> > > 
> > > 
> > > 我的在v18.12.0版本也会出现app crashed 的问题，想请问你的版本是多少？
> > 
> > 我的版本是18.2.1
> 
> 有没有ubuntu安装18.2.1的教程

我没有特意安装18.2.1，我用的x代替，它默认安装的。你的问题可能不是node版本问题。或者具体的环境依赖，你看一下chatgpt-api这个项目的文档。
