### ISSUE TITLE
1.0.0版本docker安装报错waiting for selector `#username`超时

### ISSUE THREAD

**Issue by eyaeya** [fuergaosi233/wechat-chatgpt#444]
在安装了1.0.0最新版本，并使用docker安装后，在配置了环境变量邮箱、密码、nopecha的token后，运行出现超时错误。（同docker安装使用config.yaml文件配置遇相同问题。

= = = = = = 以下为报错信息 = = = = = =

Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"隐藏邮箱","password":"隐藏密码"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""} 

initializing nopecha extension with key 隐藏token ... 

TimeoutError: waiting for selector `#username` failed: timeout 30000ms exceeded
    at new WaitTask (/app/node_modules/puppeteer/src/common/DOMWorld.ts:813:28)
    at DOMWorld.waitForSelectorInPage (/app/node_modules/puppeteer/src/common/DOMWorld.ts:656:22) 
    at Object.internalHandler.waitFor (/app/node_modules/puppeteer/src/common/QueryHandler.ts:78:19) 
    at DOMWorld.waitForSelector (/app/node_modules/puppeteer/src/common/DOMWorld.ts:511:25) 
    at Frame.waitForSelector (/app/node_modules/puppeteer/src/common/FrameManager.ts:1290:47) 
    at Page.waitForSelector (/app/node_modules/puppeteer/src/common/Page.ts:3222:29)
    at getOpenAIAuth (file:///app/node_modules/chatgpt/src/openai-auth.ts:174:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at async ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:162:24) 
    at async file:///app/src/chatgpt.ts:72:11

**Comment by BigerPatax** [comment]
经过我的测试  nopecha好像不怎么行  我用的2captcha  而且还得挂梯子确保能访问到openai

**Comment by eyaeya** [comment]
> 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai

有两个问题请教：
1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？
2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。

**Comment by RealTong** [comment]
> > 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai
> 
> @BigerPatax 有两个问题请教： 1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？ 2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。
1. 对的.
2. 你的IP触发了CloudFlare的human验证，目前我们无法绕过CloudFlare验证， 导致无法找到输入框。这个问题可能出现在多人共用IP，机房IP等问题。你可以尝试更换IP

**Comment by eyaeya** [comment]
> > > 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai
> > 
> > 
> > @BigerPatax 有两个问题请教： 1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？ 2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。
> 
> 1. 对的.
> 2. 你的IP触发了CloudFlare的human验证，目前我们无法绕过CloudFlare验证， 导致无法找到输入框。这个问题可能出现在多人共用IP，机房IP等问题。你可以尝试更换IP

@RealTong 关于问题2，我购买并配置了NOPECHA打码服务，是否应可解决CloudFlare的验证问题？

**Comment by BigerPatax** [comment]
> > > > 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai
> > > 
> > > 
> > > @BigerPatax 有两个问题请教： 1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？ 2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。
> > 
> > 
> > 
> > 1. 对的.
> > 2. 你的IP触发了CloudFlare的human验证，目前我们无法绕过CloudFlare验证， 导致无法找到输入框。这个问题可能出现在多人共用IP，机房IP等问题。你可以尝试更换IP
> 
> @RealTong 关于问题2，我购买并配置了NOPECHA打码服务，是否应可解决CloudFlare的验证问题？

有人说NOPECHA不好使  你试试  不行就用2captcha  三刀也就十几块钱

**Comment by lianghaohahh** [comment]
> > > > > 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai
> > > > 
> > > > 
> > > > @BigerPatax 有两个问题请教： 1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？ 2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。
> > > 
> > > 
> > > 
> > > 1. 对的.
> > > 2. 你的IP触发了CloudFlare的human验证，目前我们无法绕过CloudFlare验证， 导致无法找到输入框。这个问题可能出现在多人共用IP，机房IP等问题。你可以尝试更换IP
> > 
> > 
> > @RealTong 关于问题2，我购买并配置了NOPECHA打码服务，是否应可解决CloudFlare的验证问题？
> 
> 有人说NOPECHA不好使 你试试 不行就用2captcha 三刀也就十几块钱

我和楼上情况一样我配置的2captcha的token  还是#username错误

**Comment by BigerPatax** [comment]
> > > > > > 经过我的测试 nopecha好像不怎么行 我用的2captcha 而且还得挂梯子确保能访问到openai
> > > > > 
> > > > > 
> > > > > @BigerPatax 有两个问题请教： 1、我是在群晖NAS上部署的Docker，且全屋软路由梯子（但对群晖NAS Bypass了）。Docker设置了桥接网络，这样出来是新IP应该仍然被软路由带上了梯子对吗？ 2、看报错是#username 的问题，还没有到nopecha那一步呢。似乎问题在前面账号那儿。
> > > > 
> > > > 
> > > > 
> > > > 1. 对的.
> > > > 2. 你的IP触发了CloudFlare的human验证，目前我们无法绕过CloudFlare验证， 导致无法找到输入框。这个问题可能出现在多人共用IP，机房IP等问题。你可以尝试更换IP
> > > 
> > > 
> > > @RealTong 关于问题2，我购买并配置了NOPECHA打码服务，是否应可解决CloudFlare的验证问题？
> > 
> > 
> > 有人说NOPECHA不好使 你试试 不行就用2captcha 三刀也就十几块钱
> 
> 我和楼上情况一样我配置的2captcha的token 还是#username错误

挂梯子多试几次  我是多跑了几遍就跑成功了
