### ISSUE TITLE
运行npm run dev出现错误提示，是不是食用方法有问题？

### ISSUE THREAD

**Issue by gmqjquan** [fuergaosi233/wechat-chatgpt#448]
一、配置文件如何使用KEY方式，我的是GOOGLE账号登陆，不能使用email加密码方式登陆，如何你知道如何使用KEY方式登陆，麻烦告知。
二、运行npm run dev，后出现这个提示，是不是使用方式不对？
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

**Comment by RealTong** [comment]
Hi, 你好. 如果你使用Google登陆，将 `config.yaml`文件中添加`isGoogleLogin: true`就可以了.

在运行`npm run dev`之前需要先运行`npm install`

**Comment by gmqjquan** [comment]
1、将package.json、pyproject.toml两个文件放在root下，安装提示如下，想问一下是不是包没有了或不支持了。
2、也试过将package.json、package-lock.json、pyproject.toml三个文件放进root也不行。
3、不放package.json、pyproject.toml这两个文件放在root下，直接安装出错。
以下是放两个文件的出错（非淘宝镜像，直接官方镜像，甲骨文新加坡ubuntu20.04,armv8）
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported

出错后，运行npm run dev 不没有二维码，提示是：
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
  Usage: nodemon [nodemon options] [script.js] [args]
  See "nodemon --help" for more.

**Comment by gmqjquan** [comment]
config.yaml已经放进去root目录，并配置了google账号登陆
也尝试在运行npm run dev之前运行npm install，结果也是一样，提示跟上面的一样：
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
  Usage: nodemon [nodemon options] [script.js] [args]
  See "nodemon --help" for more.

如果可以，麻烦帮忙解答一下

**Comment by gmqjquan** [comment]
进入目录再安装，成功安装了，但又有新提示
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT

**Comment by gmqjquan** [comment]
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gmqjquan** [comment]
rror: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/wechat-chatgpt-main/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at ChildProcess.<anonymous> (/root/wechat-chatgpt-main/node_modules/puppeteer/src/node/BrowserRunner.ts:257:9)

**Comment by gmqjquan** [comment]
Chromium 目前不为 Linux 提供 arm64 二进制文件。[在Puppeteer 的实验性支持下，](https://pptr.dev/contributing#macos-arm-and-custom-executables)只有 Mac ARM 的二进制文件

**Comment by RealTong** [comment]
> Chromium 目前不为 Linux 提供 arm64 二进制文件。[在Puppeteer 的实验性支持下，](https://pptr.dev/contributing#macos-arm-and-custom-executables)只有 Mac ARM 的二进制文件

啊偶, 这个就没办法了.

**Comment by gmqjquan** [comment]
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
换了AWS的日本x86_64的CPU也是这个错误，是不是NVM的问题，我用的NVM 0.39.1， npm 9.2.0 ，node v19.3.0
其他就是按照教程安装了，cpu已不是arm，一样也是提示上面的错误。

**Comment by gmqjquan** [comment]
(node:571405) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/wechat-chatgpt-main/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at ChildProcess.<anonymous> (/root/wechat-chatgpt-main/node_modules/puppeteer/src/node/BrowserRunner.ts:257:9)

**Comment by BigerPatax** [comment]
> 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT

这个要手动安装chrome  具体可以参考Dockerfile里面的命令
我是ubuntu x86架构的  手动安装了chrome就可以跑起来了

**Comment by thechen130** [comment]
> > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> 
> 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了

整个流程如何操作啊，尝试过好多次都不行

**Comment by BigerPatax** [comment]
> > > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> > 
> > 
> > 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了
> 
> 整个流程如何操作啊，尝试过好多次都不行

![image](https://user-images.githubusercontent.com/56615748/210693878-af4a1c3f-6201-4898-9824-5c9e571852e6.png)
这里分步执行  先安装google-chrome-stable  再安装xvfb  安装谷歌的可能要挂梯子
`wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -`
这一句比较关键

**Comment by BigerPatax** [comment]
> > > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> > 
> > 
> > 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了
> 
> 整个流程如何操作啊，尝试过好多次都不行

`echo "Chrome: " && google-chrome --version`这一句能出chrome的版本号就可以跑了

**Comment by xihzhang** [comment]
> > > > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> > > 
> > > 
> > > 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了
> > 
> > 
> > 整个流程如何操作啊，尝试过好多次都不行
> 
> `echo "Chrome: " && google-chrome --version`这一句能出chrome的版本号就可以跑了

能把上面图片里的完整命令copy一下吗？ 谢谢

**Comment by BigerPatax** [comment]
> > > > > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> > > > 
> > > > 
> > > > 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了
> > > 
> > > 
> > > 整个流程如何操作啊，尝试过好多次都不行
> > 
> > 
> > `echo "Chrome: " && google-chrome --version`这一句能出chrome的版本号就可以跑了
> 
> Chrome: Google Chrome 108.0.5359.124
> 
> echo 出来了， 还是一样。。。

用这句代码跑
`xvfb-run --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm run dev`

**Comment by liwuhou** [comment]
> > > > 进入目录再安装，成功安装了，但又有新提示 Error: Failed to launch the browser process! spawn /usr/bin/google-chrome-stable ENOENT
> > > 
> > > 
> > > 这个要手动安装chrome 具体可以参考Dockerfile里面的命令 我是ubuntu x86架构的 手动安装了chrome就可以跑起来了
> > 
> > 
> > 整个流程如何操作啊，尝试过好多次都不行
> 
> ![image](https://user-images.githubusercontent.com/56615748/210693878-af4a1c3f-6201-4898-9824-5c9e571852e6.png) 这里分步执行 先安装google-chrome-stable 再安装xvfb 安装谷歌的可能要挂梯子 `wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -` 这一句比较关键

试了下，可以了，很棒。有些 unbutu 要装 `chromium-bsu` 这个包，`chromium`装不了。换一下就行了。
