### ISSUE TITLE
镜像名有没有错呢，总是找不到镜像下载

### ISSUE THREAD

**Issue by gmqjquan** [fuergaosi233/wechat-chatgpt#451]
运行docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
后总提示以下信息，找不到镜像
Unable to find image 'holegots/wechat-chatgpt:latest' locally
总是找不到镜像，但一会儿有下载页面。
下载完成后提示
Download complete 
docker: write /var/lib/docker/tmp/GetImageBlob307260351: no space left on device
但运行后续的命令没有反应，说没有镜像，运行docker ps -a也没有wechat-chatgpt镜像

**Comment by gmqjquan** [comment]
解决了，AWS的EC2空间不足，系统不支持甲骨文的ARM。
但有新的问题了，出现以下错误，查了是微信不支持网页版，有其他渠道？
直接用本地的浏览器微信版也不行。
WARN WechatyPuppetMixin start() starting puppet ... timeout
15:49:08 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
15:49:55 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
15:50:01 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
15:50:01 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by fuergaosi233** [comment]
Consider using [corporate wechat](https://work.weixin.qq.com/), but you'll need to change the code 🤔
