### ISSUE TITLE
puppet ... timeout,puppet超时，没有二难码弹出

### ISSUE THREAD

**Issue by gmqjquan** [fuergaosi233/wechat-chatgpt#452]
🤖️ Start GPT Bot Success, ready to handle message!
WechatyPuppetMixin start() starting puppet ... timeout
出现这个是启动GPT成功，但没有二维码弹出，显示puppet超时，有大神知道如何解决吗？
docker运行、环境是ubuntu、docker已有其他正常镜像在运行
用另外的程序，证实我的微信可以登陆网页版

**Comment by fuergaosi233** [comment]
Try  comment 11 line.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/22197568/210199406-4f844d8e-ac40-480a-90b6-173a4edeedc5.png">

**Comment by qjquan** [comment]
谢谢了，注释了第11行还是不可以。GPT BOT已准备好，但 puppet ... timeout

🤖️ Start GPT Bot Success, ready to handle message!
08:41:49 WARN WechatyPuppetMixin start() starting puppet ... timeout
08:41:49 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
08:42:38 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
08:42:38 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
08:42:38 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed

**Comment by fuergaosi233** [comment]
> 谢谢了，注释了第11行还是不可以。GPT BOT已准备好，但 puppet ... timeout
> 
> 🤖️ Start GPT Bot Success, ready to handle message! 08:41:49 WARN WechatyPuppetMixin start() starting puppet ... timeout 08:41:49 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant) 08:42:38 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded 08:42:38 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded 08:42:38 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed

Try latest docker image?

**Comment by Jacklchen** [comment]
> > 谢谢了，注解了第11行还是不行。GPT BOT已经准备好了，但是puppet ...超时
> > 🤖️启动 GPT Bot Success，准备处理消息！08:41:49 WARN WechatyPuppetMixin start() starting puppet ... 超时 08:41:49 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant) 08:42:38 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation超过 60000 毫秒超时 08:42:38 ERR PuppetWeChat initBridge() 异常：导航超时超过 60000 毫秒 08:42:38 警告 PuppetWeChatBridge stop() page.close() 异常：错误：协议错误：连接已关闭。很可能该页面已关闭
> 
> 试试最新的 docker 镜像？

TimeoutError: waiting for selector `#password` failed: timeout 180000ms exceeded
怎么解决，使用的最新的镜像
已经配置验证码
lunix    dcoker

**Comment by lianghaohahh** [comment]
> 

我也遇到了TimeoutError: waiting for selector #password failed: timeout 180000ms exceeded

**Comment by LFMJUN** [comment]
> > > 
> > 
> > 
> > 我也遇到了TimeoutError: waiting for selector #password failed: timeout 180000ms exceeded
> 
> Is OpenAI Proxy configured?

how to configure CAPTCHA_TOKEN while using docker

**Comment by nemoming** [comment]
> 

docker run -e NOPECHA_KEY=<YourKeyFromNopecha> -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

**Comment by emmmnaadada** [comment]
> > 
> 
> docker run -e NOPECHA_KEY=_YourKeyFromNopecha_ -d --name wechat-chatgpt -v $（pwd）/config.yaml：/app/config.yaml holegots/wechat-chatgpt：latest

🤖️ Start GPT Bot Success, ready to handle message!
04:52:59 WARN WechatyPuppetMixin start() starting puppet ... timeout
04:52:59 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant)
