### ISSUE TITLE
NOPECHA_KEY和CAPTCHA_TOKEN 的具体配置方法

### ISSUE THREAD

**Issue by SHIONJIEITA** [fuergaosi233/wechat-chatgpt#458]
我用的是JP的VPS，CentOS7.6的系统，通过docker部署的，请问NOPECHA_KEY和CAPTCHA_TOKEN的具体配置方法是什么
我应该把把这两个变量写入哪里
是在当前用户的.bash_profile下面吗
另外对于2captcha来说，CAPTCHA_TOKEN是不是指的就是API Key呢
恳请补充一下NOPECHA_KEY和CAPTCHA_TOKEN 的具体配置方法

**Comment by RealTong** [comment]
Hi, 您如果使用Docker部署, 则需要使用-e参数设置环境变量
例如
`docker run -e CAPTCHA_TOKEN="XXXXXXXXXXX" holegots/wechat-chatgpt:latest`

**Comment by SHIONJIEITA** [comment]
太感谢了，感谢您回答我这么小白的问题！帮大忙了！
