### ISSUE TITLE
最新版镜像starting puppet ... timeout 

### ISSUE THREAD

**Issue by emmmnaadada** [fuergaosi233/wechat-chatgpt#459]
🤖️ Start GPT Bot Success, ready to handle message!
04:52:59 WARN WechatyPuppetMixin start() starting puppet ... timeout
04:52:59 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)

最新版的镜像，

**Comment by thechen130** [comment]
你是如何做到这一步的，用的什么系统，用npm还是docker方式

**Comment by emmmnaadada** [comment]
> 你是如何做到这一步的，用的什么系统，用npm还是docker方式

docker

**Comment by RealTong** [comment]
> 🤖️ Start GPT Bot Success, ready to handle message! 04:52:59 WARN WechatyPuppetMixin start() starting puppet ... timeout 04:52:59 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant)
> 
> 最新版的镜像，

微信发送消息, 可以在控制台看到吗

**Comment by Jacklchen** [comment]
> > 🤖️启动 GPT Bot Success，准备处理消息！04:52:59 WARN WechatyPuppetMixin start() starting puppet ...超时 04:52:59 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant)
> > 最新版的镜像，
> 
> 微信发送消息，可以在控制台看到吗

没有，还没到扫码的那一步

**Comment by eyaeya** [comment]
metoo！

**Comment by godsoul** [comment]
用npm启动，也是一样的报错

**Comment by oldthreefeng** [comment]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:50) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"***@gmail.com","password":"****","isGoogleLogin":true}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
03:48:18 WARN WechatyPuppetMixin start() starting puppet ... timeout
03:48:18 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
03:49:04 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
03:49:04 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
03:49:04 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

docker 日志报错

**Comment by 18908456216** [comment]
我也是这样的报错信息，用docker启动，用docker logs -f wechat-chatgpt，显示这些报错信息，请问这要怎么解决？
