### ISSUE TITLE
请问如何重置对话？

### ISSUE THREAD

**Issue by wrhsd1** [fuergaosi233/wechat-chatgpt#46]
就是重新开始新的对话的？

**Comment by RealTong** [comment]
目前还不支持.

你可以尝试将[chatgpt-api](https://github.com/transitive-bullshit/chatgpt-api) 降级到v1.0

具体请看: https://github.com/transitive-bullshit/chatgpt-api/pull/10

请注意: 降级到v1.0可能有破坏性更改

**Comment by fuergaosi233** [comment]
Reset conversation by command is not currently supported. The easiest way is to restart the service.
