### ISSUE TITLE
最新Docker镜像，报starting puppet ... timeout

### ISSUE THREAD

**Issue by SHIONJIEITA** [fuergaosi233/wechat-chatgpt#461]
最新的Docker镜像，配置了2captcha打码

solving captchas using 2captcha...
……
……
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
09:12:46 WARN WechatyPuppetMixin start() starting puppet ... timeout
09:12:46 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
09:13:32 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
09:13:32 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
09:13:32 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

反复尝试都是这个错误，请问有没有大佬知道怎么解决
环境：VPS with CentOS 7.9 and Docker 20.10.8
Local：JP，No proxy

**Comment by Jacklchen** [comment]
我也是，不知道什么情况

**Comment by budongsir** [comment]
我也是，同样的问题，docker方式

**Comment by budongsir** [comment]
同样的问题。

环境Ubuntu22，docker，nopehca也设置好了，us vps。

**Comment by SHIONJIEITA** [comment]
这个问题我已解决，参考#494
