### ISSUE TITLE
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}

### ISSUE THREAD

**Issue by PelyDeng** [fuergaosi233/wechat-chatgpt#462]
环境:
1. 云服务器美国节点 
2. docker 部署

问题1: 服务部署好之后, 延时太长, 回复消息得半分钟-一分钟不等, 这种情况如何解决 ?
问题2: 

![image](https://user-images.githubusercontent.com/41360929/210745206-ae3629eb-4a91-4cfd-9dc0-6347012b16f3.png)

**Comment by Jacklchen** [comment]
这个是GPT的原因，

**Comment by lianghaohahh** [comment]
同样遇到了 有谁知道啥问题吗
