### ISSUE TITLE
windows docker command has error

### ISSUE THREAD

**Issue by xihzhang** [fuergaosi233/wechat-chatgpt#463]
docker run -e NOPECHA_KEY=YourKeyFromNopecha -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest    will lead error  "docker: invalid reference format"

correct cli is to change $(pwd) to ${pwd}  eg

docker run -e NOPECHA_KEY=sdec0laqmc9tc3qj -d --name wechat-chatgpt -v ${pwd}/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

**Comment by RealTong** [comment]
Using `echo $(pwd)` in windows powershell doesn't give an error
![image](https://user-images.githubusercontent.com/67304509/210983572-548a316b-fb61-4c30-be7d-a71a466020e5.png)

**Comment by RealTong** [comment]
You need to make sure you are using powershell or cmd?

**Comment by xianrui69** [comment]
> 

powershell也不能用$() 得用${}，亲测换了之后才正常运行映射文件

**Comment by QixuanAI** [comment]
我是在路径两端加上双引号就行了，因为Windows路径本身可能有空格或冒号之类的问题
` docker run -it --name wechat-chatgpt -v "$(pwd)/config.yaml:/app/config.yaml" holegots/wechat-chatgpt:latest`
