### ISSUE TITLE
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}

### ISSUE THREAD

**Issue by lianghaohahh** [fuergaosi233/wechat-chatgpt#465]
docker部署 
昨天晚上还能用
今天早上就不能用了 然后报这个错误
有大哥解决吗

**Comment by emmmnaadada** [comment]
> docker部署 昨天晚上还能用 今天早上就不能用了 然后报这个错误 有大哥解决吗

你为什么没有遇到这个错误，timeout

**Comment by lianghaohahh** [comment]
> 

1.你需要确定你容器是否能连接chatgpt
2.确定是不是在auth/login 被人机检查了导致没有跳转到登录页面所以获取不到#username等超时问题（config.yaml 配置 clearanceToken 试试）
