### ISSUE TITLE
Railway deploy error：const error = new types.ChatGPTError('ChatGPT invalid email')

### ISSUE THREAD

**Issue by ha7da8** [fuergaosi233/wechat-chatgpt#466]
Railway deploy log:
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{}],"chatGptRetryTimes":10,"chatPrivateTiggerKeyword":""}
file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:102
const error = new types.ChatGPTError('ChatGPT invalid email')
^
ChatGPTError: ChatGPT invalid email
at new ChatGPTAPIBrowser (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:102:21)
at file:///app/src/chatgpt.ts:68:27
at Array.map (<anonymous>)
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:67:35)
at ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:28)
at main (file:///app/src/main.ts:15:20)
at file:///app/src/main.ts:51:1
at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
statusCode: 401
}
[nodemon] app crashed - waiting for file changes before starting...

Is this a token problem or needs input chatgpt email account?

**Comment by RealTong** [comment]
Please login with your email and password

**Comment by 94248** [comment]
solve no

**Comment by ha7da8** [comment]
I really don't think it must login with email and password,because I login with Google auth, if I login in with email and password, my Google account information will leak. The railway.app provides a token way to connect to ChatGPT to avoid email&password leaking which I used in railway deployment. I still have a question about why the error report shows " invalid email" because I leave it as optional blank.

**Comment by ha7da8** [comment]
I really don't think it must login with email and password,because I login with Google auth, if I login in with email and password, my Google account information will leak. The railway.app provides a token way to connect to ChatGPT to avoid email&password leaking which I used in railway deployment. I still have a question about why the error report shows " invalid email" because I leave it as optional blank.

**Comment by qianchao555** [comment]
Hi, have you solved this problem？

**Comment by hugegedegege** [comment]
我也遇到这个问题，部署在腾讯服务器，服务器地址在硅谷

**Comment by hellojiaru** [comment]
这问题竟然没人回复？同样遇到了，用session token登录不了，明明写的是用token，用户名密码可以不填

**Comment by wilsonzhu-2020** [comment]
> 我也遇到这个问题，部署在腾讯服务器，服务器地址在硅谷

如何解決的？

**Comment by ailoli1314** [comment]
if someone fix this problem,please call me,thanks
