### ISSUE TITLE
PuppetWeChat Error

### ISSUE THREAD

**Issue by budongsir** [fuergaosi233/wechat-chatgpt#470]
ubuntu22，docker下运行，nopecha打码也设置了。

但是，二维码不弹出，出现如下错误：

ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
03:07:54 WARN WechatyPuppetMixin start() starting puppet ... timeout
03:07:54 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
03:08:39 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
03:08:39 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
03:08:39 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by Jacklchen** [comment]
你是如何解决的这个问题

**Comment by budongsir** [comment]
> 你是如何解决的这个问题

我没解决，我是来找大佬解决的。

**Comment by RealTong** [comment]
你删除src/main.ts  L8 - L11之后重新`npm run dev`

**Comment by RealTong** [comment]
如果是docker的话, 删除之后重新build一下吧

**Comment by budongsir** [comment]
> 如果是docker的话, 删除之后重新build一下吧

删除 src/main.ts 如下8-11行后，重新bulid，问题依旧！错误提示没变化，二维码不弹出。
  8   puppetOptions: {
  9     uos: true, // 开启uos协议
 10   },
 11   puppet: "wechaty-puppet-wechat",

**Comment by SHIONJIEITA** [comment]
请问不使用镜像，直接部署的话，OPECHA_KEY或CAPTCHA_TOKEN应该配置在哪里

**Comment by RealTong** [comment]
> > 如果是docker的话, 删除之后重新build一下吧
> 
> 删除 src/main.ts 如下8-11行后，重新bulid，问题依旧！错误提示没变化，二维码不弹出。 8 puppetOptions: { 9 uos: true, // 开启uos协议 10 }, 11 puppet: "wechaty-puppet-wechat",

可以给出详细启动步骤吗?

**Comment by RealTong** [comment]
> 请问不使用镜像，直接部署的话，OPECHA_KEY或CAPTCHA_TOKEN应该配置在哪里

直接使用export命令就可以, 参考README

**Comment by theLastWinner** [comment]
> > > 如果是docker的话, 删除之后重新build一下吧
> > 
> > 
> > 删除 src/main.ts 如下8-11行后，重新bulid，问题依旧！错误提示没变化，二维码不弹出。 8 puppetOptions: { 9 uos: true, // 开启uos协议 10 }, 11 puppet: "wechaty-puppet-wechat",
> 
> 可以给出详细启动步骤吗?

我目前用的就是最新的1.0.2镜像，多次重启之后，终于登录openai了，但是提示超时。
```
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
16:12:12 WARN WechatyPuppetMixin start() starting puppet ... timeout
16:12:12 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
16:12:57 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
16:12:57 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
16:12:57 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
```

**Comment by dapaoxixixi** [comment]
> 

我也是

**Comment by theLastWinner** [comment]
> > > > 如果是docker的话, 删除之后重新build一下吧
> > > 
> > > 
> > > 删除 src/main.ts 如下8-11行后，重新bulid，问题依旧！错误提示没变化，二维码不弹出。 8 puppetOptions: { 9 uos: true, // 开启uos协议 10 }, 11 puppet: "wechaty-puppet-wechat",
> > 
> > 
> > 可以给出详细启动步骤吗?
> 
> 我目前用的就是最新的1.0.2镜像，多次重启之后，终于登录openai了，但是提示超时。
> 
> ```
> ChatGPTPools: 1
> 🤖️ Start GPT Bot Success, ready to handle message!
> 16:12:12 WARN WechatyPuppetMixin start() starting puppet ... timeout
> 16:12:12 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
> 16:12:57 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
> 16:12:57 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
> 16:12:57 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
> ```

@RealTong 通过clash监控到，验证码登录之后，其实是有访问wx的接口的，估计是在这里超时了，所以登录失败。截图如下：
![image](https://user-images.githubusercontent.com/11495358/211980750-8763910b-bb6a-4b42-9d35-96a355ff5bc4.png)
 
暂时不知道怎么解决，如果解决了，麻烦@一下我，谢谢。

**Comment by bianjiangjiangjiang** [comment]
> 

重建docker镜像需要修改一下Dockerfile 第一行，修改为FROM node:19
然后执行 docker build  -f ./Dockerfile -t vxbot .

**Comment by theLastWinner** [comment]
> > 
> 
> 重建docker镜像需要修改一下Dockerfile 第一行，修改为FROM node:19 然后执行 docker build -f ./Dockerfile -t vxbot .

现在里面的配置是FROM node:19 AS app，去掉as app感觉没有什么差别。
