### ISSUE TITLE
大佬何在

### ISSUE THREAD

**Issue by fanqiev** [fuergaosi233/wechat-chatgpt#471]
![1673103873(1)](https://user-images.githubusercontent.com/120728599/211157276-52cba81e-905f-4300-8be3-740997d9e55c.jpg)
大佬何在，这是什么原因造成的呢，怎么解决，

**Comment by 2465622629** [comment]
不是写了吗 无效的邮箱 你连配置文件都没改？

**Comment by ha7da8** [comment]
我觉得他应该是没用邮箱密码方式，使用了Token方式，这个方式是不需要邮箱密码的，我就是这么做的，提示是说如果用了Token方式，邮箱密码是Optiional的，可以不填，但实际情况是不填就报错，我的报错和这个一样。我用的是谷歌认证，如果填了邮箱密码会导致我的谷歌账号泄密，所以我用了Token方式。但看上去有问题

**Comment by 2465622629** [comment]
> 我觉得他应该是没用邮箱密码方式，使用了Token方式，这个方式是不需要邮箱密码的，我就是这么做的，提示是说如果用了Token方式，邮箱密码是Optiional的，可以不填，但实际情况是不填就报错，我的报错和这个一样。我用的是谷歌认证，如果填了邮箱密码会导致我的谷歌账号泄密，所以我用了Token方式。但看上去有问题

如何启用这个选项啊 只用token登录 我用的railway方式部署 给我提示账号不存在No chatgpt account in pool 换了登录方式也不行

**Comment by ha7da8** [comment]
![image](https://user-images.githubusercontent.com/7369211/211182720-be56f06d-7585-4fcd-8cfc-4fb52e4145a1.png)

**Comment by 2465622629** [comment]
只填这一个参数就能直接运行了吗 在 railway中

**Comment by 2465622629** [comment]
> ![image](https://user-images.githubusercontent.com/7369211/211182720-be56f06d-7585-4fcd-8cfc-4fb52e4145a1.png)

![800](https://user-images.githubusercontent.com/63027241/211183018-b4e7d553-b0d4-499b-9eda-c1bd8568117b.png)

为啥我没有这个参数啊

**Comment by fanqiev** [comment]
找到原因了，  非常感谢。刚开始没弄验证码验证，现在改成本地部署了，直接手动登录的账号  就没事了1

**Comment by fanqiev** [comment]
本地部署，回复速度的真的感人，要1分多钟 2分钟的样子

**Comment by 94248** [comment]
> 找到原因了，非常感谢。刚开始没有尝试验证码验证，现在改成本地区了，直接手动登录的账号就没有事了1

大佬能说的具体点吗？我买的阿里云的服务器搭建的也是这个问题

**Comment by fanqiev** [comment]
> > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> 
> 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題

账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，

**Comment by 94248** [comment]
> > > 找到原因了，非常感谢。刚开始没有尝试验证码验证，现在改成本地了，直接手动登录的账号就没有事了1
> > 
> > 
> > 大佬能说的具体点吗？我买的阿里云的服务器搭的也是这个问题
> 
> 账号登录不上去的原因吧，我本地没有用那个验证码，账号是手动登录的。登录账号的时候有验证码就是选，几个图片的戳
意思就是说要过那个人机验证

**Comment by 94248** [comment]
> > > 找到原因了，非常感谢。刚开始没有尝试验证码验证，现在改成本地了，直接手动登录的账号就没有事了1
> > 
> > 
> > 大佬能说的具体点吗？我买的阿里云的服务器搭的也是这个问题
> 
> 账号登录不上去的原因吧，我本地没有用那个验证码，账号是手动登录的。登录账号的时候有验证码就是选，几个图片的戳

本地部署在哪设置

**Comment by 2465622629** [comment]
> > > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> > 
> > 
> > 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題
> 
> 账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，

部署那个是不是得交费啊

**Comment by moelyman** [comment]
> > > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> > 
> > 
> > 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題
> 
> 账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，
请问如何本地部署？

**Comment by fanqiev** [comment]
> > > > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> > > 
> > > 
> > > 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題
> > 
> > 
> > 账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，
> > 请问如何本地部署？

我就是按win教程安装的

**Comment by fanqiev** [comment]
> > > > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> > > 
> > > 
> > > 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題
> > 
> > 
> > 账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，
> 
> 部署那个是不是得交费啊

是的，所以我就改成本地部署了

**Comment by moelyman** [comment]
> 

windows docker吗？

**Comment by moelyman** [comment]
> > > > > 找到原因了，非常感謝。剛開始沒有嘗試驗證碼驗證，現在改成本地了，直接手動登錄的賬號就沒有事了1
> > > > 
> > > > 
> > > > 大佬能說的具體點嗎？我買的阿里雲的服務器搭的也是這個問題
> > > 
> > > 
> > > 账号登录不上去的原因吧，我本地部署没用那个验证码，账号是手动登录的。登录账号的时候 有验证码 就是选几个图片的那个，
> > > 请问如何本地部署？
> 
> 我就是按win教程安装的


windows docker吗？

**Comment by fanqiev** [comment]
嗯
