### ISSUE TITLE
烦请大佬指导，xvbf

### ISSUE THREAD

**Issue by Rwolf996** [fuergaosi233/wechat-chatgpt#475]
lighthouse@VM-0-11-ubuntu:~$ sudo docker logs -f wechat-chatgpt

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"pa9867@covbase.com","password":"a12349868"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start

**Comment by XSD66** [comment]
+1，折磨好久了😭

**Comment by yuanhong078** [comment]
> lighthouse@VM-0-11-ubuntu:~$ sudo docker logs -f wechat-chatgpt
> 
> > wechat-chatgpt@1.0.0 dev
> > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
> 
> [nodemon] 2.0.20 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): config.yaml [nodemon] watching extensions: ts [nodemon] starting `node --loader ts-node/esm src/main.ts` (node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time (Use `node --trace-warnings ...` to show where the warning was created) Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"[pa9867@covbase.com](mailto:pa9867@covbase.com)","password":"a12349868"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""} xvfb-run: error: Xvfb failed to start xvfb-run: error: Xvfb failed to start

大兄弟，注意隐私信息打码啊

**Comment by liaozhangsheng** [comment]
大哥记得改密码
