### ISSUE TITLE
使用刚刚作者更新的镜像依旧报错

### ISSUE THREAD

**Issue by Jacklchen** [fuergaosi233/wechat-chatgpt#476]
🤖️ Start GPT Bot Success, ready to handle message!
05:50:21 WARN WechatyPuppetMixin start() starting puppet ... timeout
05:50:21 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
05:51:06 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
05:51:06 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
05:51:06 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by budongsir** [comment]
同样的问题，完全一样的错误提示，使用了最新的镜像。

ubuntu22，docker，us vps。

**Comment by LFMJUN** [comment]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:50) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:737:3)
    at tryReadSync (node:fs:432:20)
    at Object.readFileSync (node:fs:478:19)
    at file:///app/src/config.ts:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
[nodemon] app crashed - waiting for file changes before starting...


The latest docker image.

**Comment by RealTong** [comment]
> [nodemon] 2.0.20 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): config.yaml/**/* [nodemon] watching extensions: ts [nodemon] starting `node --loader ts-node/esm src/main.ts` (node:50) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time (Use `node --trace-warnings ...` to show where the warning was created) Error: EISDIR: illegal operation on a directory, read at Object.readSync (node:fs:737:3) at tryReadSync (node:fs:432:20) at Object.readFileSync (node:fs:478:19) at file:///app/src/config.ts:9:19 at ModuleJob.run (node:internal/modules/esm/module_job:194:25) { errno: -21, syscall: 'read', code: 'EISDIR' } [nodemon] app crashed - waiting for file changes before starting...
> 
> The latest docker image.

config.yaml权限不够吧

**Comment by wantMeat** [comment]
你解决了吗

**Comment by HappyImp** [comment]
> 

手动改下代码吧
```
puppetOptions: {
    uos: true, // 开启uos协议
    launchOptions:{
      headless:true,
      executablePath:"chrome路径",
      ignoreDefaultArgs:true,
      args:[
        "--proxy-server=代理"
      ]
    },
```

**Comment by zxy1124** [comment]
>大佬 那该怎么办呢
