### ISSUE TITLE
init account faild

### ISSUE THREAD

**Issue by Yadoon** [fuergaosi233/wechat-chatgpt#478]
我挂的全局代理，用chrome可以登录，yaml只填了用户名密码，初始化不了，试了最新的docker和本地运行是一样的现象。请问这是什么原因？
![Snipaste_2023-01-09_00-24-00](https://user-images.githubusercontent.com/51159734/211207906-fef27dd8-b8fe-465d-8687-36e925ede2d3.png)

**Comment by hx3333** [comment]
同样，我用railway部署的，也出现了这个问题，有什么解决办法吗？

**Comment by Yadoon** [comment]
应该是那个谷歌人机验证吧，没救了。
