### ISSUE TITLE
请问配置好后，扫描qrcode后，服务出现微信信息，下一步如何配置？

### ISSUE THREAD

**Issue by hcn1973** [fuergaosi233/wechat-chatgpt#48]

**Comment by RealTong** [comment]
扫描QRCode后没有报错, 即可食用

在私聊 可以直接问答
在群聊 需要使用@    (尽量保证群聊里昵称和微信昵称一样)

**Comment by cypggs** [comment]
> 扫描QRCode后没有报错, 即可食用
> 
> 在私聊 可以直接问答 在群聊 需要使用@ (尽量保证群聊里昵称和微信昵称一样)

和谁私聊呢，没加机器人？

**Comment by lutixiaya** [comment]
扫码后，你的微信就变成机器人了，可以用另外一个号和你的微信号对话

**Comment by cypggs** [comment]
> 扫描QRCode后没有报错, 即可食用
> 
> 在私聊 可以直接问答 在群聊 需要使用@ (尽量保证群聊里昵称和微信昵称一样)

uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

报错了

**Comment by huangzuomin** [comment]
扫码后，用另外的微信发信息给扫码微信，没有激活gpt
