### ISSUE TITLE
SOS，xvfb-run: error

### ISSUE THREAD

**Issue by XSD66** [fuergaosi233/wechat-chatgpt#482]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"*****@qq.com","password":"*******"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
xvfb-run: error: Xvfb failed to start

一个警告一个错误，不知道怎么改
（账号密码没有输错）
大佬大牛们求求了😘
![Suggestion](https://user-images.githubusercontent.com/122262957/211274699-eefcad66-0abb-4884-8a1d-5f4194db532d.gif)

**Comment by fuergaosi233** [comment]
Does it run in Docker?

**Comment by theLastWinner** [comment]
> Does it run in Docker?

when i restart the docker ,it will show the message:
```
xvfb-run: error: Xvfb failed to start
```

How can i solve it? @fuergaosi233

**Comment by XSD66** [comment]
> > Does it run in Docker?
> 
> when i restart the docker container ,it will show the message:
> 
> ```
> xvfb-run: error: Xvfb failed to start
> ```
> 
> How can i solve it? @fuergaosi233

me too😭

**Comment by bianjiangjiangjiang** [comment]
重新新建一个容器

**Comment by yaodaiyue** [comment]
> 重新新建一个容器

repeat many times with no help
