### ISSUE TITLE
err is SyntaxError

### ISSUE THREAD

**Issue by soGary** [fuergaosi233/wechat-chatgpt#484]
err is SyntaxError: Unexpected non-whitespace character after JSON at position 4, account {"email":"*********","password":"********","isGoogleLogin":"true"}
Message: Message#Text[🗣Contact<********>]    未知错误，请看日志 | Error unknown, please see the log

**Comment by helizhi1987** [comment]
same err,how to fixed it

**Comment by emmmnaadada** [comment]
same err,how to fixed it

**Comment by CSerht** [comment]
怀疑是官网做了什么调整……我昨天登录就发现进不去，说chatgpt负载了

**Comment by fuergaosi233** [comment]
https://github.com/transitive-bullshit/chatgpt-api/issues/247  this prob

**Comment by emmmnaadada** [comment]
> [transitive-bullshit/chatgpt-api#247](https://github.com/transitive-bullshit/chatgpt-api/issues/247) this prob

![image](https://user-images.githubusercontent.com/101549560/211501134-6e28b74e-78c0-4cb1-98e6-232ce7dd6f4c.png)
已有人提供了解决方案

**Comment by helizhi1987** [comment]
> [transitive-bullshit/chatgpt-api#247](https://github.com/transitive-bullshit/chatgpt-api/issues/247) this prob

thx u!!
