### ISSUE TITLE
docker及railway部署成功，登录失败

### ISSUE THREAD

**Issue by theLastWinner** [fuergaosi233/wechat-chatgpt#488]
使用最新的镜像1.0.2进行编译，账密设置无误，并设置了环境变量clearanceToken，多次测试都是提示：
```
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"****@qq.com","password":"***","isGoogleLogin":false}],"chatGptRetryTimes":1,"chatPrivateTiggerKeyword":"","openAIProxy":"http://**:88","clearanceToken":"***"}
Try init account: ***@qq.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...
```

请问如何解决？

**Comment by dreamfly32** [comment]
根据我多次尝试得出的经验，railway不适合部署，它只有512m内存，而运行项目需要chrome来模拟人工操作，它需要更大的内存和强壮的cpu，
之所以出现这个错误，是没过cloudflare验证，
没过验证的原因，1是代理ip问题，2是程序操作对应不上chrome的页面(内存，cpu，网络问题)，例如等待密码框的出现，实际上前面一步页面上还没完成（因为验证码加载失败或其他原因），最终会因为超时而报错。

**Comment by theLastWinner** [comment]
我测试了一下，是有走代理的。本地运行之后，代理设置为全局，有观察clash的流向，基本都是走新加坡的代理。所以IP方面，应该没问题的。镜像是直接拉官方的，应该没问题。不知道是哪里出现问题，导致故障。 @dreamfly32 你有顺利跑起来吗？

**Comment by dreamfly32** [comment]
> 我测试了一下，是有走代理的。本地运行之后，代理设置为全局，有观察clash的流向，基本都是走新加坡的代理。所以IP方面，应该没问题的。镜像是直接拉官方的，应该没问题。不知道是哪里出现问题，导致故障。 @dreamfly32 你有顺利跑起来吗？
大部分是第2个的原因，内存和cpu太小导致chrome运行很慢，程序操作对不上页面
我tx轻量云，配合国外代理ip跑起来了，需要多跑几次，有时会碰到openai服务繁忙
还有就是，我用的源码，没用docker，docker虽然能登录openai却登不了wx，会报超时错误

**Comment by theLastWinner** [comment]
> > 我测试了一下，是有走代理的。本地运行之后，代理设置为全局，有观察clash的流向，基本都是走新加坡的代理。所以IP方面，应该没问题的。镜像是直接拉官方的，应该没问题。不知道是哪里出现问题，导致故障。 @dreamfly32 你有顺利跑起来吗？
> > 大部分是第2个的原因，内存和cpu太小导致chrome运行很慢，程序操作对不上页面
> > 我tx轻量云，配合国外代理ip跑起来了，需要多跑几次，有时会碰到openai服务繁忙
> > 还有就是，我用的源码，没用docker，docker虽然能登录openai却登不了wx，会报超时错误

我本地电脑配置16核12G，刚刚启动容器分配了8核4G，也是跑不出来。我现在连openai都还没有登录上去。我看看是不是换成huaweiyun试试看。

**Comment by dreamfly32** [comment]
> > > 我测试了一下，是有走代理的。本地运行之后，代理设置为全局，有观察clash的流向，基本都是走新加坡的代理。所以IP方面，应该没问题的。镜像是直接拉官方的，应该没问题。不知道是哪里出现问题，导致故障。 @dreamfly32 你有顺利跑起来吗？
> > > 大部分是第2个的原因，内存和cpu太小导致chrome运行很慢，程序操作对不上页面
> > > 我tx轻量云，配合国外代理ip跑起来了，需要多跑几次，有时会碰到openai服务繁忙
> > > 还有就是，我用的源码，没用docker，docker虽然能登录openai却登不了wx，会报超时错误
> 
> 我本地电脑配置16核12G，刚刚启动容器分配了8核4G，也是跑不出来。我现在连openai都还没有登录上去。我看看是不是换成huaweiyun试试看。

最好的办法是源码运行，会弹出chrome，看看卡在哪一步

**Comment by theLastWinner** [comment]
> > > > 我测试了一下，是有走代理的。本地运行之后，代理设置为全局，有观察clash的流向，基本都是走新加坡的代理。所以IP方面，应该没问题的。镜像是直接拉官方的，应该没问题。不知道是哪里出现问题，导致故障。 @dreamfly32 你有顺利跑起来吗？
> > > > 大部分是第2个的原因，内存和cpu太小导致chrome运行很慢，程序操作对不上页面
> > > > 我tx轻量云，配合国外代理ip跑起来了，需要多跑几次，有时会碰到openai服务繁忙
> > > > 还有就是，我用的源码，没用docker，docker虽然能登录openai却登不了wx，会报超时错误
> > 
> > 
> > 我本地电脑配置16核12G，刚刚启动容器分配了8核4G，也是跑不出来。我现在连openai都还没有登录上去。我看看是不是换成huaweiyun试试看。
> 
> 最好的办法是源码运行，会弹出chrome，看看卡在哪一步

我本地源码跑起来，在poetry install这一步，会出现：Unable to find installation candidates for openaiauth (0.0.4)。请问你是怎么解决的？

**Comment by dreamfly32** [comment]
> 2captcha

2captcha

**Comment by dreamfly32** [comment]
> @dreamfly32 请问一下，是有使用nopecha或者2captcha的解决方案吗？是用了这两个，才能正确解析成功，还是不用也可以成功？

2captcha

**Comment by theLastWinner** [comment]
> > @dreamfly32 请问一下，是有使用nopecha或者2captcha的解决方案吗？是用了这两个，才能正确解析成功，还是不用也可以成功？
> 
> 2captcha

好的，谢谢。
