### ISSUE TITLE
香港linux服务器,不显示二维码

### ISSUE THREAD

**Issue by RansongZ** [fuergaosi233/wechat-chatgpt#489]
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:49) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"121768xxx9@qq.com","password":"xxxaswsx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
为什么我会一直卡在这儿，不显示二维码，最新版本，账号确定能正常登录，香港linux服务器

**Comment by milaicai** [comment]
你是liunx的吗？

**Comment by RealTong** [comment]
ChatGPT不在香港服务啊 朋友

**Comment by hugegedegege** [comment]
你解决了吗？我也是这个问题

**Comment by hugegedegege** [comment]
我是美国服务器
