### ISSUE TITLE
输入指令出现erro:ChatGPT failed to refresh auth token,Erroor:Unauthorized

### ISSUE THREAD

**Issue by hcn1973** [fuergaosi233/wechat-chatgpt#49]
我是用邮箱和密码登录的，没有使用sessiontoken!

**Comment by OliverGrace** [comment]
即使使用了sessiontken也有同样的问题

**Comment by fuergaosi233** [comment]
Please check whether it can be used on the web. I'll add more error information

**Comment by fuergaosi233** [comment]
> > Please check whether it can be used on the web. I'll add more error information
> 
> 
> 
> @fuergaosi233 yep, working flawlessly with web browser

🤔 Try to remove cache.json file to relogin pls.

**Comment by guch445** [comment]
> 

whereis cache.json

**Comment by gray-pigeons** [comment]
The token mechanism for OpenAI seems to have changed,
I logged in using a Google account, so in the profile everything was configured except the password, which was used as (access_token).
After Chatgpt pool size :1 is displayed on the server,
After the wechat client sent a message to him, the server prompted the following information:
🎯 Hit GPT Enabled User:  XXXXXX
Error: ChatGPT failed to refresh auth token. Error: Unauthorized
    at ChatGPTAPI.refreshAccessToken (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTAPI.sendMessage (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:114:25)
    at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:105:14)
    at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:137:24)
    at async WechatyImpl.<anonymous> (file:///app/src/main.ts:30:7)

**Comment by fuergaosi233** [comment]
Add auto update.

**Comment by fuergaosi233** [comment]
> The token mechanism for OpenAI seems to have changed, I logged in using a Google account, so in the profile everything was configured except the password, which was used as (access_token). After Chatgpt pool size :1 is displayed on the server, After the wechat client sent a message to him, the server prompted the following information: 🎯 Hit GPT Enabled User: XXXXXX Error: ChatGPT failed to refresh auth token. Error: Unauthorized at ChatGPTAPI.refreshAccessToken (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:273:13) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ChatGPTAPI.sendMessage (file:///app/node_modules/chatgpt/src/chatgpt-api.ts:114:25) at async ChatGPTBot.getGPTMessage (file:///app/src/chatgpt.ts:105:14) at async ChatGPTBot.onMessage (file:///app/src/chatgpt.ts:137:24) at async WechatyImpl. (file:///app/src/main.ts:30:7)

Try use latest image/code.
