### ISSUE TITLE
配置了CAPTCHA_TOKEN，启动容器未调用2captcha接口

### ISSUE THREAD

**Issue by theLastWinner** [fuergaosi233/wechat-chatgpt#491]
如题，使用最新镜像1.0.2，然后启动命令为：`docker run  -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml -e CAPTCHA_TOKEN="***" holegots/wechat-chatgpt:latest`，进入容器，使用`env` 命令可以查看CAPTCHA_TOKEN变量的值。但是启动之后，报错。因为代理是使用了clash，查看日志，未有2captcha接口调用，到2captcha控制台，也没有看到调用数。请问有没有人遇到相同的问题，然后解决了？

**Comment by 1024er** [comment]
+1 同问

**Comment by theLastWinner** [comment]
> +1 同问

需要多次重启尝试。刚刚有一次可以了。
