### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by dreamfly32** [fuergaosi233/wechat-chatgpt#492]
1，请在登录用的配置文件或环境变量加入下图的参数，方便调试，亦或在railway开启谷歌或微软登录
![image](https://user-images.githubusercontent.com/32086491/211968124-9b9e76b7-9749-4404-b76b-83210921fd9f.png)

2，请增加微信登录重试，或因网络问题，见下图
![image](https://user-images.githubusercontent.com/32086491/211968627-158b928e-c6e3-4a83-a6bc-00fa31f85296.png)

**Comment by theLastWinner** [comment]
> 1，请在登录用的配置文件或环境变量加入下图的参数，方便调试，亦或在railway开启谷歌或微软登录 ![image](https://user-images.githubusercontent.com/32086491/211968124-9b9e76b7-9749-4404-b76b-83210921fd9f.png)
> 
> 2，请增加微信登录重试，或因网络问题，见下图 ![image](https://user-images.githubusercontent.com/32086491/211968627-158b928e-c6e3-4a83-a6bc-00fa31f85296.png)

请问可以发文本吗？截图里面的日志输出是怎么输出的？

**Comment by dreamfly32** [comment]
> > 1，请在登录用的配置文件或环境变量加入下图的参数，方便调试，亦或在railway开启谷歌或微软登录 ![image](https://user-images.githubusercontent.com/32086491/211968124-9b9e76b7-9749-4404-b76b-83210921fd9f.png)
> > 2，请增加微信登录重试，或因网络问题，见下图 ![image](https://user-images.githubusercontent.com/32086491/211968627-158b928e-c6e3-4a83-a6bc-00fa31f85296.png)
> 
> 请问可以发文本吗？截图里面的日志输出是怎么输出的？

修改源码，传入debug
![image](https://user-images.githubusercontent.com/32086491/211990769-cf3d7dd6-9de1-4876-948f-ba95a4617704.png)

**Comment by theLastWinner** [comment]
> > > 1，请在登录用的配置文件或环境变量加入下图的参数，方便调试，亦或在railway开启谷歌或微软登录 ![image](https://user-images.githubusercontent.com/32086491/211968124-9b9e76b7-9749-4404-b76b-83210921fd9f.png)
> > > 2，请增加微信登录重试，或因网络问题，见下图 ![image](https://user-images.githubusercontent.com/32086491/211968627-158b928e-c6e3-4a83-a6bc-00fa31f85296.png)
> > 
> > 
> > 请问可以发文本吗？截图里面的日志输出是怎么输出的？
> 
> 修改源码，传入debug ![image](https://user-images.githubusercontent.com/32086491/211990769-cf3d7dd6-9de1-4876-948f-ba95a4617704.png)

好的，谢谢。请问除了这里，微信登录那块，有做了什么配置和修改可以登录吗？我这里通过clash做了分流，wx那块都是走本地，不走代理。但是还是超时。 @dreamfly32
