### ISSUE TITLE
有用docker成功的吗

### ISSUE THREAD

**Issue by thechen130** [fuergaosi233/wechat-chatgpt#496]
尝试了好多次都不行，一直报如下错误：
`Try init account: *********@qq.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...`

本人搭建的环境如下：
百度云服务器Ubuntu20.01系统（没装GUI，不确定要不要装）。
挂了梯子，用的是v2rayA，IP选的美国、印度、澳大利亚、巴西、墨西哥（会根据延时自动更换），能够curl www,google.com。
代理规则配置如图：
![image](https://user-images.githubusercontent.com/74664452/212528687-8e79b0f2-5dec-4f02-9df4-ade9547181bf.png)
![image](https://user-images.githubusercontent.com/74664452/212528701-072875be-f1fc-424f-9935-8c6d8cbac2ad.png)
然后安装了docker，按照的是这个[参考教程](https://blog.csdn.net/qq_44732146/article/details/121207737)。
然后就是git clone https://github.com/fuergaosi233/wechat-chatgpt.git。
接着进wechat-chatgpt目录，执行cp config.yaml.example config.yaml，并配置如下：
`chatGPTAccountPool:
  - email: **********@qq.com
    password: ********
    isGoogleLogin: false`

接着参考别人的提供的线索，新建了如下文件：
![image](https://user-images.githubusercontent.com/74664452/212528930-05e8e444-8b90-4aa5-89c6-abe561efa3e2.png)
然后删除/root/wechat-chatgpt/src/main.ts文件的8-11行内容。
为了防止docker run的时候出现WARNING: IPv4 forwarding is disabled. Networking will not work的报错，又在/etc/sysctl.conf中取消注释了net.ipv4.ip_forward=1这一行。
接着在https://2captcha.com 中注册，充值了3美元，复制了API Key。然后：
docker run -d --name wechat-chatgpt  -e CAPTCHA_TOKEN="复制的API Key" -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
接着：docker logs -f wechat-chatgpt，就出现了开头的那种错误。

我不清楚是哪里没有配置对或者方式不对，请问是否和以下因素有关：
是否需要安装GUI桌面、
是否需要安装chrome、
config.yaml中的openAIProxy该如何配置、
wechat-chatgpt目录中的哪些文件需要移除放到别的路径、
Ubuntu自带的python是3.8.10，是否需要别的版本、
是否需要别的操作步骤。

请大佬指教

**Comment by budongsir** [comment]
感觉你这个还是网络问题。

**Comment by RealTong** [comment]
不需要GUI. 不是你这样配代理.

代理在config.yaml配置, 参考README
![image](https://user-images.githubusercontent.com/67304509/213113037-0e4536e8-6c00-45f8-aaae-ecbf8bdc3f9f.png)

**Comment by thechen130** [comment]
> 

请问代理写哪个IP：端口啊，不太懂

**Comment by thechen130** [comment]
> 代理在config.yaml配置, 参考README ![image](https://user-images.githubusercontent.com/67304509/213113037-0e4536e8-6c00-45f8-aaae-ecbf8bdc3f9f.png)

请问代理写哪个IP：端口啊，不太懂

**Comment by zaiMoe** [comment]
遇到同样问题，请问有解决方案吗？

**Comment by stazeng** [comment]
> > 代理在config.yaml配置, 参考README ![image](https://user-images.githubusercontent.com/67304509/213113037-0e4536e8-6c00-45f8-aaae-ecbf8bdc3f9f.png)
> 
> 请问代理写哪个IP：端口啊，不太懂

such as: http://localhost:7890

**Comment by zxy1124** [comment]
大佬，dockers部署成功了吗？求教
