### ISSUE TITLE
solving captchas using 2captcha

### ISSUE THREAD

**Issue by GreenyDo** [fuergaosi233/wechat-chatgpt#499]
### **部署遇到一个问题：**
**在mac上通过Docker使用:**
```
cp config.yaml.example config.yaml
docker run -d --name wechat-chatgpt2 -e CAPTCHA_TOKEN="xxxxxxx" -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
docker logs -f wechat-chatgpt2
```

**然后终端有以下提示：**
```
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxx@foxmail.com","password":"xxxxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"你好","openAIProxy":""}
solving captchas using 2captcha...
captchas result {
  captchas: [
    {
      sitekey: '6LxxxxxxxxxXP',
      callback: 'callback',
      _vendor: 'recaptcha',
      id: '99xxxxxxxxpa',
      s: null,
      widgetId: 0,
      display: [Object],
      url: 'https://auth0.openai.com/u/login/identifier?state=xxxxxxxxxxxxxx',
      hasResponseElement: true,
      isEnterprise: true,
      isInViewport: true,
      isInvisible: false,
      _type: 'checkbox'
    }
  ],
  filtered: [],
  solutions: [
    {
      _vendor: 'recaptcha',
      provider: '2captcha',
      id: '99xxxxxxxxpa',
      requestAt: 2023-01-16T08:38:48.042Z,
      providerCaptchaId: '7xxxxxxxxx03',
      text: '0xxxxxxxxxxxxxxxxxx8',
      responseAt: 2023-01-16T08:39:13.096Z,
      hasSolution: true,
      duration: 25.054
    }
  ],
  solved: [
    {
      _vendor: 'recaptcha',
      id: '99xxxxxxxxpa',
      responseElement: true,
      responseCallback: true,
      isSolved: true,
      solvedAt: {}
    }
  ],
  error: undefined
}
```

**显示3次“solving captchas using 2captcha.................”后
最终提示：**
```
Try init account:xxxxxxxxx@foxmail.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...
```
**我登陆2captcha.com看了一下,每次执行命令，2captcha账户余额有扣减,次数也有使用**
![image](https://user-images.githubusercontent.com/11807239/212639206-cb1ada97-0adc-48e2-8636-9b90889f7af2.png)

请各位老哥帮忙看一下是啥原因呢？

**Comment by zyzlimit** [comment]
建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。

**Comment by GreenyDo** [comment]
> 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。

我其实一开始是在railway上部署的，总是不行，这又用的docker部署。我这系统是macos10.13，nodejs最高支持到16，所以直接npm运用也不行😂

**Comment by zyzlimit** [comment]
> > 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。
> 
> 我其实一开始是在railway上部署的，总是不行，这又用的docker部署。我这系统是macos10.13，nodejs最高支持到16，所以直接npm运用也不行😂

如果是x86的cpu就安装个ubuntu的虚拟机然后用高版本的nodejs部署呗，反正docker或者railway都不太行 很多问题

**Comment by RealTong** [comment]
> > 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。
> 
> 我其实一开始是在railway上部署的，总是不行，这又用的docker部署。我这系统是macos10.13，nodejs最高支持到16，所以直接npm运用也不行😂

需要Node >= 18

**Comment by dreamingms** [comment]
> 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。

老哥好，请问是怎么部署的，有没有详细的操作步骤？我这边折腾了2天，还是不行，docker、railway、npm 3种方式都是失败。

**Comment by zyzlimit** [comment]
> > 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。
> 
> 老哥好，请问是怎么部署的，有没有详细的操作步骤？我这边折腾了2天，还是不行，docker、railway、npm 3种方式都是失败。

别在服务器上运行，用npm在有界面的电脑上操作，而且满足None>=18。npm run dev 之后就会跳出chrome的登陆界面，然后手动登陆之后，命令行就会出来微信的登陆二维码，扫码之后就可以接入了。

**Comment by dreamingms** [comment]
> 

卧槽，是这样吗？服务器不能部署？我搞了半天，还花了3美元去买2captcha。

**Comment by dreamingms** [comment]
> > > 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。
> > 
> > 
> > 老哥好，请问是怎么部署的，有没有详细的操作步骤？我这边折腾了2天，还是不行，docker、railway、npm 3种方式都是失败。
> 
> 别在服务器上运行，用npm在有界面的电脑上操作，而且满足None>=18。npm run dev 之后就会跳出chrome的登陆界面，然后手动登陆之后，命令行就会出来微信的登陆二维码，扫码之后就可以接入了。

感谢，我这边部署成功了。弹出chrome登陆界面后，登陆完就行了，白瞎了我20块钱。

**Comment by Diaoest-Mian** [comment]
> > > > 建议还是别用docker部署了，直接npm运行吧。我也是搞了好久用docker部署，也添加了2captcha，但是不是Error: ⚠️ No chatgpt account in pool，就是微信登陆失败。
> > > 
> > > 
> > > 老哥好，请问是怎么部署的，有没有详细的操作步骤？我这边折腾了2天，还是不行，docker、railway、npm 3种方式都是失败。
> > 
> > 
> > 别在服务器上运行，用npm在有界面的电脑上操作，而且满足None>=18。npm run dev 之后就会跳出chrome的登陆界面，然后手动登陆之后，命令行就会出来微信的登陆二维码，扫码之后就可以接入了。
> 
> 感谢，我这边部署成功了。弹出chrome登陆界面后，登陆完就行了，白瞎了我20块钱。

老哥好， 我是用npm直接部署的，启动后为啥不弹chrome呀， 接着就提示app crashed, no chatgpt account in pool 了

**Comment by runto2006** [comment]
感谢感谢，windows方便多了，关键在于弹窗手动登录
