### ISSUE TITLE
日志卡在start GPT Bot ，是什么原因呀，大佬

### ISSUE THREAD

**Issue by yangy666** [fuergaosi233/wechat-chatgpt#500]
[root@qinglong wechat-chatgpt]# docker-compose    logs -f 
Attaching to wechat-chatgpt
wechat-chatgpt    | 
wechat-chatgpt    | > wechat-chatgpt@1.0.0 dev
wechat-chatgpt    | > nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
wechat-chatgpt    | 
wechat-chatgpt    | [nodemon] 2.0.20
wechat-chatgpt    | [nodemon] to restart at any time, enter `rs`
wechat-chatgpt    | [nodemon] watching path(s): config.yaml
wechat-chatgpt    | [nodemon] watching extensions: ts
wechat-chatgpt    | [nodemon] starting `node --loader ts-node/esm src/main.ts`
wechat-chatgpt    | (node:58) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
wechat-chatgpt    | (Use `node --trace-warnings ...` to show where the warning was created)
wechat-chatgpt    | Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxxxxx","password":"xxxxxxx.","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"/c","openAIProxy":""}

docker 启动的 日志卡在这里不动了 我试着进入容器执行curl -l -v https://chat.openai.com  是正常的

**Comment by LuckyDogg** [comment]
+1 . 我也卡住了

**Comment by LuckyDogg** [comment]
node:internal/modules/cjs/loader:1056
  throw err;
  ^

Error: Cannot find module '/app/...'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.4.0

**Comment by LuckyDogg** [comment]
执行了 node --trace-warnings ...， 结果如上

**Comment by yangy666** [comment]
本地启动报错这个

**Comment by LuckyDogg** [comment]
@yangy666 , 我知道了，我之前是docker运行的，然后现在本地运行试了一下，然后 网页报错 “ChatGPT is at capacity right now”， 应该是 ChatGPT现在暂时不给用了

**Comment by RealTong** [comment]
> @yangy666 , 我知道了，我之前是docker运行的，然后现在本地运行试了一下，然后 网页报错 “ChatGPT is at capacity right now”， 应该是 ChatGPT现在暂时不给用了

不要用香港节点, 不要用AWS, GCP, Azure等大厂服务器.  如果是调试, 尽量避开北京时间晚8时以后

**Comment by louisasea999** [comment]
> > @yangy666 , 我知道了，我之前是docker运行的，然后现在本地运行试了一下，然后 网页报错 “ChatGPT is at capacity right now”， 应该是 ChatGPT现在暂时不给用了
> 
> 不要用香港节点, 不要用AWS, GCP, Azure等大厂服务器. 如果是调试, 尽量避开北京时间晚8时以后

我貌似使用的Azure服务器，尴尬

**Comment by dryl90** [comment]
与楼主相同的问题，怎么解

**Comment by thechen130** [comment]
> > @yangy666 , 我知道了，我之前是docker运行的，然后现在本地运行试了一下，然后 网页报错 “ChatGPT is at capacity right now”， 应该是 ChatGPT现在暂时不给用了
> 
> 不要用香港节点, 不要用AWS, GCP, Azure等大厂服务器. 如果是调试, 尽量避开北京时间晚8时以后

请问为什么不能使用Azure

**Comment by d0glrq** [comment]
@yangy666 请问您这个报错怎么解决的呢？我是在本地起的docker，尝试更换docker的代理，也无法解决这个问题

**Comment by soyons** [comment]
> @yangy666 请问您这个报错怎么解决的呢？我是在本地起的docker，尝试更换docker的代理，也无法解决这个问题
老哥解决没啊，一样的问题
