### ISSUE TITLE
没有程序中提到的二维码，是什么情况，有大佬知晓吗？

### ISSUE THREAD

**Issue by liluosheng** [fuergaosi233/wechat-chatgpt#506]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:58) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxx","password":"xxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}

**Comment by xmlv** [comment]
卡住了没连上呢，不是网络就是验证码问题，先确保两件事
1 主机的ip不在限制范围内
2 验证码能过（从你返回的信息看，没配验证码接码平台）

**Comment by louisasea999** [comment]
我前两天还可以，今天一样就不行了，验证码接码的还没有调用，尴尬

**Comment by dryl90** [comment]
看下是不是chrome浏览器的地址与你实际chrome地址不匹配
