### ISSUE TITLE
Try init account: failed

### ISSUE THREAD

**Issue by szh-bash** [fuergaosi233/wechat-chatgpt#508]
本地 npm run dev 运行，未填写 captcha api。

[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:5104) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxx","password":"xxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
Try init account: xxxx failed, remove it from pool
file:///E:/wechat-chatgpt/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///E:/wechat-chatgpt/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///E:/wechat-chatgpt/src/bot.ts:41:5)
    at async main (file:///E:/wechat-chatgpt/src/main.ts:16:3)

这里应该是人机验证挂了吧？请问正常的表现自动打开 chrome 手动登陆还是必须填写 captcha api 自动过验证？本机未填写 api 的情况下未能自动打开 chrome

**Comment by zaiMoe** [comment]
遇到同样的问题，请问有解决方案吗

**Comment by szh-bash** [comment]
> 遇到同样的问题，请问有解决方案吗

没继续探索，等作者回复或者官方api了

**Comment by szh-bash** [comment]
@fuergaosi233 请问这里正常的表现应该如何？

**Comment by dryl90** [comment]
同样的问题 解决了吗？

**Comment by goushijie** [comment]
同样的问题，解决不了

**Comment by youbingchenyoubing** [comment]
有办法解决吗

**Comment by szh-bash** [comment]
已放弃
