### ISSUE TITLE
提示帐号有问题

### ISSUE THREAD

**Issue by a52948** [fuergaosi233/wechat-chatgpt#509]
由于帐号安全，此处密并非真实密码！使用真实密码时报如下错误
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"e.edd@live.com","password":"123456"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"666"}
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"e.edd@live.com","password":"123456"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"666"}
Try init account: e.edd@live.com failed, remove it from pool
Try init account: e.edd@live.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
throw new Error("⚠️ No chatgpt account in pool");

**Comment by zaiMoe** [comment]
我也是，有解决方案吗

**Comment by aooyoo** [comment]
我也是这个问题

**Comment by Seihui** [comment]
+1，插眼

**Comment by fuergaosi233** [comment]
有更多日志么?
或者可以在本地启动, 可以看一下登录过程 的报错

**Comment by a52948** [comment]
只需要配置账号密码就可以了，railway上面弄的人太多，报一堆错 另外容器运行注意配置文件权限，我是在根目录下创建文件夹，还成绝对路径运行的！

**Comment by alvin87** [comment]
> 

你好，请教下怎么配置权限？

**Comment by chmrhythm** [comment]
我也有同样问题，我的服务器在国内，个人猜测是否需要科学上网？

**Comment by Leetion07** [comment]
> 我也有同样问题，我的服务器在国内，个人猜测是否需要科学上网？

我也是try init账号时失败，服务器在国内 
请问你最后怎么解决的呀

**Comment by chmrhythm** [comment]
买了个国外的服务器，另外最好别搞了，我一上午没回复几条消息就被微信警告了
________________________________
发件人: XiyinLi ***@***.***>
发送时间: 2023年2月9日 20:01
收件人: fuergaosi233/wechat-chatgpt ***@***.***>
抄送: chmrhythm ***@***.***>; Comment ***@***.***>
主题: Re: [fuergaosi233/wechat-chatgpt] 提示帐号有问题 (Issue #509)


我也有同样问题，我的服务器在国内，个人猜测是否需要科学上网？

我也是try init账号时失败，服务器在国内
请问你最后怎么解决的呀

―
