### ISSUE TITLE
docker部署 Start GPT Bot Success，但后续报错

### ISSUE THREAD

**Issue by catlain** [fuergaosi233/wechat-chatgpt#510]
各位大佬求助，请问这个报错应该如何解决~

11:31:58 WARN WechatyPuppetMixin start() starting puppet ... timeout
11:31:58 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
11:32:44 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
11:32:44 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
11:32:44 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by wuwu19988** [comment]
同问

**Comment by Lyq0055** [comment]
请问解决了吗

**Comment by louisasea999** [comment]
同问，遇到一模一样的问题

**Comment by Doslin** [comment]
+1

**Comment by ux001840** [comment]
+1

**Comment by 1378056564** [comment]
这个有啥解决方式吗

**Comment by 1378056564** [comment]
> 这个有啥解决方式吗

感觉应该是node要升级到18，然而centos 7的不支持18版本

**Comment by Imccccc** [comment]
从日志感觉是网络超时

**Comment by Yang-HangWA** [comment]
+1 同问
