### ISSUE TITLE
m1 macbook 食用方法

### ISSUE THREAD

**Issue by Levin000** [fuergaosi233/wechat-chatgpt#516]
1. 下载仓库源代码；
2. 去nodejs官网下载nodejs的pkg安装包（本地有nodejs可忽略，注意version>=18.0);
3. 解压缩zip源代码，通过终端切换到源代码文件夹；
4. 修改config.yaml(添加自己的配置文件，openai账户注册自理)
5. 执行npm install
6. 执行npm run dev
7. 至此所有操作完成，静待所有动作完成

**Comment by emo8899** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/108335283/215681917-cf5dc0c0-ad3c-4e5c-8cc6-44e1a77ab3e6.png">
请问我遇到这种情况怎么解决

**Comment by pierwzw** [comment]
> <img alt="image" width="701" src="https://user-images.githubusercontent.com/108335283/215681917-cf5dc0c0-ad3c-4e5c-8cc6-44e1a77ab3e6.png">
> 
> 请问我遇到这种情况怎么解决

你这明显代理那写错了，你写的是api-key

**Comment by emo8899** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/108335283/215930909-f22464ca-bc65-42b5-a847-f0055396bee6.png">
自动输入账号后 提示这个

**Comment by anpplex** [comment]
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/108335283/215930909-f22464ca-bc65-42b5-a847-f0055396bee6.png">
> 
> 自动输入账号后 提示这个

遇到同样的问题，求1楼大佬解答

**Comment by Levin000** [comment]
> <img alt="image" width="701" src="https://user-images.githubusercontent.com/108335283/215681917-cf5dc0c0-ad3c-4e5c-8cc6-44e1a77ab3e6.png">
> 
> 请问我遇到这种情况怎么解决

网页GPT可以登录吗？

**Comment by Levin000** [comment]
> 

看起来好像你说的情况

**Comment by Levin000** [comment]
> > <img alt="image" width="818" src="https://user-images.githubusercontent.com/108335283/215930909-f22464ca-bc65-42b5-a847-f0055396bee6.png">
> > 自动输入账号后 提示这个
> 
> 遇到同样的问题，求1楼大佬解答

这个不懂

**Comment by lnisre** [comment]
这个查到应该是puppeteer这个组件会调起chromium，但是chromium对Mac M1芯片支持力度不好，需要做些什么改动。但是如何做还没研究明白
