### ISSUE TITLE
xvfb-run: error: Xvfb failed to start

### ISSUE THREAD

**Issue by Zuco-M** [fuergaosi233/wechat-chatgpt#519]
使用的是阿里云新加坡轻应用服务器
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:53) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxx","password":"xxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
xvfb-run: error: Xvfb failed to start

**Comment by Cluas** [comment]
```bash
docker run -d --name wechat-chatgpt -v $(pwd)/config.yaml:/app/config.yaml --entrypoint '/bin/sh' holegots/wechat-chatgpt:latest -c 'xvfb-run --auto-servernum --server-num=1 npm run dev'
```
temporary solutions, before https://github.com/fuergaosi233/wechat-chatgpt/pull/423 is merged.

**Comment by maskwang** [comment]
Good

**Comment by casens** [comment]
good
