### ISSUE TITLE
Error: No chatgpt session token

### ISSUE THREAD

**Issue by OliverGrace** [fuergaosi233/wechat-chatgpt#52]
When i use only the A method for config.yaml(meaning that my config.yaml only has email and passwd), both node running or docker deploying get this error. Plz fix this to make it get token or at least make the method A works.

**Comment by fuergaosi233** [comment]
Can you provide more Log, or you can use the Session Token to start.

**Comment by OliverGrace** [comment]
@fuergaosi233 https://github.com/fuergaosi233/wechat-chatgpt/issues/2#issuecomment-1342273877
