### ISSUE TITLE
想请教下作者为什么去掉了对session_token方式的支持，感谢

### ISSUE THREAD

**Issue by live106** [fuergaosi233/wechat-chatgpt#521]
还有CAPTCHA_TOKEN变量是如何生效的，没找到代码有使用的地方。非常感谢！

**Comment by fuergaosi233** [comment]
因为实现太麻烦了, 而且时效性很短 ,

**Comment by lkyuier** [comment]
> 

我一直没有办法实现账号密码登录，session token是用哪个版本docker镜像的？
