### ISSUE TITLE
大佬，不稳定呀

### ISSUE THREAD

**Issue by dlwang624** [fuergaosi233/wechat-chatgpt#522]

**Comment by RealTong** [comment]
Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码. 

这个分支现在使用官方API

**Comment by Gy-Hu** [comment]
@RealTong 你好，我用了你[new-wechatgpt](https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt)这个分支的代码，但是还是有错误，错误信息 `ChatGPT invalid apiKey` ，请问有解决办法吗？
<img width="761" alt="image" src="https://user-images.githubusercontent.com/43922980/216474809-4a2ae1e6-4fa0-4faa-b1c0-eae35cc9fa75.png">

**Comment by budongsir** [comment]
> Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码.
> 
> 这个分支现在使用官方API

@RealTong 可以运行，但有问题。大概是，会把之前的所有对话都会累加在一起重复发送。

**Comment by RealTong** [comment]
应该是没写key吧
你抄一下.env.example文件, 改名为`.env`填入`OPENAI_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Comment by Gy-Hu** [comment]
> @Gy-Hu 应该是没写key吧 将`.env.example`改名为`.env`填入`OPENAI_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

谢谢，不过写了KEY之后调用的还是ChatGPT吗？还是GPT3？

**Comment by budongsir** [comment]
> Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码.
> 
> 这个分支现在使用官方API

大佬，目前我用的是chatgpt 4.1.1，结果就是信息重复发送，每条信息都会把之前的所有信息累加在一起发出去。

**Comment by budongsir** [comment]
> Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码. 
> 
> 
> 
> 这个分支现在使用官方API

内容稍微多点就会出现如下

未知错误，请看日志 | Error unknown, please see the log

**Comment by dryl90** [comment]
> 

大佬这个分支代码有错误，编辑不通过

**Comment by dryl90** [comment]
> Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码.
> 
> 这个分支现在使用官方API

@RealTong 

err is ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by BanDianMan** [comment]
> > Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码.
> > 这个分支现在使用官方API
> 
> **@RealTong 大佬，用了你的分支报错如下**
> 
> err is ChatGPT error 404: { "error": { "message": "That model does not exist", "type": "invalid_request_error", "param": null, "code": null } }

我报的错也和你你一样

**Comment by bluef1ash** [comment]
> > > Hi, 你好, 请尝试https://github.com/fuergaosi233/wechat-chatgpt/tree/new-wechatgpt 这个分支的代码.
> > > 这个分支现在使用官方API
> > 
> > 
> > **@RealTong 大佬，用了你的分支报错如下**
> > err is ChatGPT error 404: { "error": { "message": "That model does not exist", "type": "invalid_request_error", "param": null, "code": null } }
> 
> 我报的错也和你你一样

我的也是
