### ISSUE TITLE
大佬，这个到底是GPT-3，还是chatGPT？

### ISSUE THREAD

**Issue by martin-songzy** [fuergaosi233/wechat-chatgpt#523]
如果是用的API，那就是GPT-3，因为chatgpt的api还没出，chatgpt只能通过chat.openai.com网页访问。所以我的问题是，这个程序到底是GPT-3，还是chatgpt？

**Comment by fuergaosi233** [comment]
Chatgpt 不然怎么会这么麻烦呢

**Comment by martin-songzy** [comment]
大佬已解答
