### ISSUE TITLE
Official ChatGPT API model found

### ISSUE THREAD

**Issue by acheong08** [fuergaosi233/wechat-chatgpt#524]
It's the model used for ChatGPT on the back end. It's missing some of the other layers such as automatic conversation tracking etc. You might want to update to it (No more browsers and still free).

It was found by mistake and not public yet

Model name is `text-chat-davinci-002-20230126`

@transitive-bullshit has updated his repo to support it

**Comment by 0xdevalias** [comment]
Seems this leaked ChatGPT API model got taken down already..

- https://github.com/acheong08/ChatGPT/issues/523
  - https://github.com/acheong08/ChatGPT/issues/523#issuecomment-14145246

**Comment by acheong08** [comment]
And now it's up again

**Comment by Cellenseres** [comment]
text-chat-davinci-002-20230126 is down for me the whole time. But text-chat-davinci-002-20221122 is up for me

**Comment by fengerzh** [comment]
> 

No, that model does not work either.

**Comment by Cellenseres** [comment]
Obviously, they taken all "free to use" ones diwn two weeks ago. My post on that they're still worming is over three weeks old

**Comment by acheong08** [comment]
We've got a new stable method that has been working for a week now. @fuergaosi233 is aware of the method I believe. Hopefully this updates if it proves stable for even longer
