### ISSUE TITLE
想问一下出现了err is ChatGPTAPI error 404该如何解决？

### ISSUE THREAD

**Issue by Zoumachuan** [fuergaosi233/wechat-chatgpt#525]
如图
<img width="694" alt="微信截图_20230202130849" src="https://user-images.githubusercontent.com/123653723/216236939-3b6ac3e7-9f64-4693-b40a-a6094668d27e.png">

**Comment by barius** [comment]
> 如图 <img alt="微信截图_20230202130849" width="694" src="https://user-images.githubusercontent.com/123653723/216236939-3b6ac3e7-9f64-4693-b40a-a6094668d27e.png">

@Zoumachuan 
换模型，用text-davinci-002-render-next

**Comment by Zoumachuan** [comment]
> > 如图 <img alt="微信截图_20230202130849" width="694" src="https://user-images.githubusercontent.com/123653723/216236939-3b6ac3e7-9f64-4693-b40a-a6094668d27e.png">
> 
> @Zoumachuan 换模型，用text-davinci-002-render-next

请问具体该如何操作呢？我是小白，不太懂，抱歉抱歉

**Comment by Zoumachuan** [comment]
> > 如图 <img alt="微信截图_20230202130849" width="694" src="https://user-images.githubusercontent.com/123653723/216236939-3b6ac3e7-9f64-4693-b40a-a6094668d27e.png">
> 
> @Zoumachuan 换模型，用text-davinci-002-render-next

刚看到了这个https://github.com/sudoskys/Openaibot/issues/132，请问如何根据上述链接中的方法更改模型呢？以及出现这个错误的具体原因大概是什么呢？还请回复，万分感谢！

**Comment by fuergaosi233** [comment]
> render

这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.

**Comment by Zoumachuan** [comment]
> > render
> 
> 这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.

非常感谢您对该项目的贡献，还有一个问题，我在项目的目录下新建了config目录，并按照
`            "backend": {
                "model": "text-davinci-003",
                "token_limit": 4000
            },`
创建了service.json，在重启了wechatgpt后仍然报错404，是否是模型没能成功更改，还是我的操作中某一步出现了问题？希望您能指导一下

**Comment by richaolas** [comment]
> 

您好，api方式，会带着上下文来对话么？还是只是一问一答？谢谢

**Comment by maconn** [comment]
> > render
> 
> 这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.

什么时候更新版本呀？坐等

**Comment by budongsir** [comment]
> > 
> 
> 
> 
> 您好，api方式，会带着上下文来对话么？还是只是一问一答？谢谢

同问

**Comment by fuergaosi233** [comment]
需要升级 SDK 了， 我升级一个， APIKey 已经挂了貌似。。。

**Comment by fuergaosi233** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/528

**Comment by E9C50** [comment]
> > > render
> > 
> > 
> > 这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.
> 
> 非常感谢您对该项目的贡献，还有一个问题，我在项目的目录下新建了config目录，并按照 ` "backend": { "model": "text-davinci-003", "token_limit": 4000 },` 创建了service.json，在重启了wechatgpt后仍然报错404，是否是模型没能成功更改，还是我的操作中某一步出现了问题？希望您能指导一下

修改模型配置，可以在node_modules中，chatgpt文件夹，73行修改配置，然后重启服务即可

**Comment by Zoumachuan** [comment]
> > > > render
> > > 
> > > 
> > > 这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.
> > 
> > 
> > 非常感谢您对该项目的贡献，还有一个问题，我在项目的目录下新建了config目录，并按照 ` "backend": { "model": "text-davinci-003", "token_limit": 4000 },` 创建了service.json，在重启了wechatgpt后仍然报错404，是否是模型没能成功更改，还是我的操作中某一步出现了问题？希望您能指导一下
> 
> 修改模型配置，可以在node_modules中，chatgpt文件夹，73行修改配置，然后重启服务即可

我是用docker安装的，所以没找到node_modules文件夹，请问该怎么解决呢？

**Comment by E9C50** [comment]
> > > > > render
> > > > 
> > > > 
> > > > 这个我后面可以更新一版本 .现在 ChatGPT 可以用 API key 调用了.
> > > 
> > > 
> > > 非常感谢您对该项目的贡献，还有一个问题，我在项目的目录下新建了config目录，并按照 ` "backend": { "model": "text-davinci-003", "token_limit": 4000 },` 创建了service.json，在重启了wechatgpt后仍然报错404，是否是模型没能成功更改，还是我的操作中某一步出现了问题？希望您能指导一下
> > 
> > 
> > 修改模型配置，可以在node_modules中，chatgpt文件夹，73行修改配置，然后重启服务即可
> 
> 我是用docker安装的，所以没找到node_modules文件夹，请问该怎么解决呢？

理论上docker exec进去之后应该也是有这个文件夹的，你进容器里看看，具体方法可以百度下
