### ISSUE TITLE
chatGPT已经启动了，但是wechaty又出问题。

### ISSUE THREAD

**Issue by kelvenlaw** [fuergaosi233/wechat-chatgpt#527]
大佬好，我今天把chatGPTAPI更新到最新的版本，然后按照新的接口对接上去了，但是出现了微信机器人启动不了的情况，请问有方法可以解决吗？急等！
`> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTApiPool":[{"apiKey":"12345"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
10:27:24 WARN WechatyPuppetMixin start() starting puppet ... timeout
10:27:24 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
10:28:18 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
10:28:20 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
10:28:20 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.`

**Comment by thechen130** [comment]
+1

**Comment by fuergaosi233** [comment]
可以尝试更新一下 WeChaty 的 Puppet

**Comment by thechen130** [comment]
> 可以尝试更新一下 WeChaty 的 Puppet

请问如何更新

**Comment by fuergaosi233** [comment]
> > 可以尝试更新一下 WeChaty 的 Puppet
> 
> 请问如何更新

https://wechaty.js.org/docs/puppet-services/

**Comment by kelvenlaw** [comment]
@fuergaosi233 请问是wechaty-puppet-wechat，这个库吗？我查了下，版本都还是最新的。

**Comment by thechen130** [comment]
> > > 可以尝试更新一下 WeChaty 的 Puppet
> > 
> > 
> > 请问如何更新
> 
> https://wechaty.js.org/docs/puppet-services/

看不懂，不知如何下手

**Comment by kelvenlaw** [comment]
> > > > 可以尝试更新一下 WeChaty 的 Puppet
> > > 
> > > 
> > > 请问如何更新
> > 
> > 
> > https://wechaty.js.org/docs/puppet-services/
> 
> 看不懂，不知如何下手

我把整个项目启动起来了，把main.ts 里面的 WechatyBuilder.build注释，更换成WechatyBuilder.singleton()即可
![image](https://user-images.githubusercontent.com/1327174/216798698-344c48b5-123b-41ab-a0ee-ffe1a2763172.png)

**Comment by fh12** [comment]
> 

最大的可能是接口问题, 如果是本地起的服务, 翻墙不能用全局模式,最好是pac模式,你用全局模式,微信的接口相当于在国外访问微信的WeChaty 接口,可能会不通.

**Comment by XinyuSun** [comment]
> > > > > 可以尝试更新一下 WeChaty 的 Puppet
> > > > 
> > > > 
> > > > 请问如何更新
> > > 
> > > 
> > > https://wechaty.js.org/docs/puppet-services/
> > 
> > 
> > 看不懂，不知如何下手
> 
> 我把整个项目启动起来了，把main.ts 里面的 WechatyBuilder.build注释，更换成WechatyBuilder.singleton()即可 ![image](https://user-images.githubusercontent.com/1327174/216798698-344c48b5-123b-41ab-a0ee-ffe1a2763172.png)

这个亲测有效

**Comment by kelvenlaw** [comment]
>

**Comment by PigCharid** [comment]
uncaughtException Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
    at Function.AxiosError.from (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)
    at RedirectableRequest.emit (node:events:525:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/follow-redirects/index.js:371:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27) {
  code: 2,
  details: 'Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded\n' +
    '    at Function.AxiosError.from (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
    '    at RedirectableRequest.handleRequestError (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/axios/lib/adapters/http.js:518:25)\n' +
    '    at RedirectableRequest.emit (node:events:525:35)\n' +
    '    at RedirectableRequest.emit (node:domain:489:12)\n' +
    '    at RedirectableRequest._processResponse (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/follow-redirects/index.js:371:10)\n' +
    '    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/pigcharid/Desktop/ChatGPT/wechat-chatgpt/node_modules/follow-redirects/index.js:62:10)\n' +
    '    at Object.onceWrapper (node:events:628:26)\n' +
    '    at ClientRequest.emit (node:events:513:28)\n' +
    '    at ClientRequest.emit (node:domain:489:12)\n' +
    '    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)'
}

**Comment by WangChangQin** [comment]
mark
