### ISSUE TITLE
err is ChatGPTAPI error 400

### ISSUE THREAD

**Issue by maconn** [fuergaosi233/wechat-chatgpt#531]
`err is ChatGPTAPI error 400, account {"email":"xxx","password":"xxxx"}
ChatGPT "xxx" error 400; An error ocurred. Try refreshing your browser.`

**Comment by fuergaosi233** [comment]
这个和我最新的修复有关, 可以降级到上一个Commit 版本...

**Comment by maconn** [comment]
可是上一个commit不是为了解决404吗

**Comment by richard-fu-1007** [comment]
确实是最新修复的问题  我降级到上一个commit成功了

**Comment by maconn** [comment]
> 确实是最新修复的问题 我降级到上一个commit成功了

但是上一个commit不是会404吗？我昨天就是用上一个commit出现了404的问题

**Comment by richard-fu-1007** [comment]
> > 确实是最新修复的问题 我降级到上一个commit成功了
> 
> 但是上一个commit不是会404吗？我昨天就是用上一个commit出现了404的问题

降级一个commit 就行，不用降级大版本。具体怎么查看上一个commit不好描述，可以问下百度

**Comment by richard-fu-1007** [comment]
> > 这个和我最新的修复有关, 可以降级到上一个Commit 版本...
> 
> 请问具体是降级到哪个版本呢？我尝试降级了几个版本还是有400错误

降级一个commit 就行，不用降级大版本。具体怎么查看上一个commit不好描述，可以问下百度

**Comment by richard-fu-1007** [comment]
> > 确实是最新修复的问题 我降级到上一个commit成功了
> 
> 请问你是怎么降级的，用的哪个本版

降级一个commit 就行，不用降级大版本。具体怎么查看上一个commit不好描述，可以问下百度

**Comment by Gy-Hu** [comment]
> > > 这个和我最新的修复有关, 可以降级到上一个Commit 版本...
> > 
> > 
> > 请问具体是降级到哪个版本呢？我尝试降级了几个版本还是有400错误
> 
> 降级一个commit 就行，不用降级大版本。具体怎么查看上一个commit不好描述，可以问下百度

我当然知道如何查看上一个commit....问题就是上一个commit还是有问题呀。请问你放了OpenAI API吗

**Comment by kunyu** [comment]
我也不行 @richard-fu-1007  你直接给个commitid 吧

**Comment by kunyu** [comment]
@fuergaosi233 给个commit id吧

**Comment by dryl90** [comment]
error 400; An error ocurred. Try refreshing your browser.  
**降到大佬1月11日提交的版本b0fa31909e6572287c0b9f83a27be0548aba608c  ，依然有同样的问题**

**Comment by XinyuSun** [comment]
> @fuergaosi233 error 400; An error ocurred. Try refreshing your browser. **降到大佬1月11日提交的版本b0fa31909e6572287c0b9f83a27be0548aba608c ，依然有同样的问题**

降到1月12日提交

**Comment by Zoumachuan** [comment]
> > @fuergaosi233 error 400; An error ocurred. Try refreshing your browser. **降到大佬1月11日提交的版本b0fa31909e6572287c0b9f83a27be0548aba608c ，依然有同样的问题**
> 
> 降到1月12日提交版本 [f2c8704](https://github.com/fuergaosi233/wechat-chatgpt/commit/f2c87041441e4c782759da1f24ba8775736e34f5)

亲测，降到1月12日版本有效

**Comment by laoyin** [comment]
切换到f2c8704， 目前还是会出现  err is ChatGPTAPI error 400, account。 请问你们今天还是正常的么？ @Zoumachuan @XinyuSun

**Comment by 1765659645** [comment]
> 切换到f2c8704， 目前还是会出现 err is ChatGPTAPI error 400, account。 请问你们今天还是正常的么？ @Zoumachuan @XinyuSun

我刚刚切换到了这个commit，可以正常访问

**Comment by zhaoyifei1998** [comment]
> > 切换到f2c8704， 之前还是会出现err is ChatGPTAPI error 400, account。 请问你们今天还是正常的么？@Zoumachuan @XinyuSun
> 
> 我刚刚切换到了这个commit，可以正常访问

我切了这个还三400 不知道为啥

**Comment by zhaoyifei1998** [comment]
ChatGPT "--------@gmail.com" error 400; An error ocurred. Try refreshing your browser.

**Comment by 1765659645** [comment]
> 

现在不行了，官网限流了

**Comment by Nabyssache** [comment]
> > 
> 
> 现在不行了，官网限流了

有解决方案吗？我没有用docker，用的本地环境也出现这个情况，最初的问题是：OpenAI 服务器限流，请稍后再试| The OpenAI server was limited, please try again later。现在直接报400错误
