### ISSUE TITLE
人机验证相关问题

### ISSUE THREAD

**Issue by ZHSheep** [fuergaosi233/wechat-chatgpt#532]
![image](https://user-images.githubusercontent.com/55422342/216531105-a7aa3ab9-40ee-4305-ac4c-d0f1a1a6e0b5.png)
CAPTCHA_TOKEN已经加入到环境变量，但是碰到人机验证需要手动点击才能进入到登录页面，否则卡到Start GPT Bot Config is ****这里，在使用无图形界面模式下没办法点击，就无法成功运行，有解决办法吗

**Comment by Ynlwys** [comment]
> ![image](https://user-images.githubusercontent.com/55422342/216531105-a7aa3ab9-40ee-4305-ac4c-d0f1a1a6e0b5.png) CAPTCHA_TOKEN已经加入到环境变量，但是碰到人机验证需要手动点击才能进入到登录页面，否则卡到Start GPT Bot Config is ****这里，在使用无图形界面模式下没办法点击，就无法成功运行，有解决办法吗

今天遇到了同样的问题,配置CAPTCHA_TOKEN后仍然无法自动验证,是不是调用自动验证的部分接口失效了

**Comment by RealTong** [comment]
@ZHSheep  Cloudflare的验证码无法打码成功. 绕不过去

@Ynlwys 应该也是因为出现了Cloudflare验证.

只能避免其出现

**Comment by dryl90** [comment]
> ![image](https://user-images.githubusercontent.com/55422342/216531105-a7aa3ab9-40ee-4305-ac4c-d0f1a1a6e0b5.png) CAPTCHA_TOKEN已经加入到环境变量，但是碰到人机验证需要手动点击才能进入到登录页面，否则卡到Start GPT Bot Config is ****这里，在使用无图形界面模式下没办法点击，就无法成功运行，有解决办法吗

本地npm run dev弹出的验证页面吗？为什么我这边弹不出来，需要怎么设置

**Comment by ZHSheep** [comment]
@Ynlwys 挂梯子就会出现cloudflare，不挂梯子提示国家不在服务范围，看来是没办法避免了

**Comment by dreamfly32** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/488

**Comment by hx3333** [comment]
这个人机验证也太恶心了。

**Comment by goushijie** [comment]
大佬为什么要使用人机验证，为什么不调用api？

**Comment by xusheng1987** [comment]
> 大佬为什么要使用人机验证，为什么不调用api？

那个api不是chatgpt的，目前官方没有api

**Comment by BaoHeTaiHe** [comment]
使用美洲的服务器能规避这个问题么

**Comment by fateplayer** [comment]
> 使用美洲的服务器能规避这个问题么

用美国服务器试了还是不行，可能是加了人工验证

**Comment by zhangchengtnt** [comment]
有解决方法了吗？
