### ISSUE TITLE
docker跑起来之后查看日志没有二维码

### ISSUE THREAD

**Issue by yul-h** [fuergaosi233/wechat-chatgpt#536]
docker跑起来之后查看日志没有二维码，是图里这样的，有人知道什么原因吗？
<img width="741" alt="235b3909abc29ddb3ed5238a3eae28e" src="https://user-images.githubusercontent.com/123927089/216806985-5c55fde6-ceaa-4cdc-b2ce-59a7cd71b53d.png">

**Comment by williamlee1982** [comment]
我也是同样的问题

**Comment by thechen130** [comment]
我也是这样

**Comment by zeruse** [comment]
一样

**Comment by likakuli** [comment]
一样

**Comment by thechen130** [comment]
有办法解决了吗？刚才试了以下还是这样

**Comment by yul-h** [comment]
没有啊

**Comment by yul-h** [comment]
什么内存？docker容器的吗？是run的时候要设置什么参数还是怎么设置？

**Comment by thechen130** [comment]
> 什么内存？docker容器的吗？是run的时候要设置什么参数还是怎么设置？

我增加了服务器的内存和网络带宽就可以了

**Comment by yul-h** [comment]
我是直接在自己电脑上跑的docker，内存和网络带宽应该都是够的额

**Comment by thechen130** [comment]
> 我是直接在自己电脑上跑的docker，内存和网络带宽应该都是够的额

那应该是网络的问题，梯子不稳定，我用的是阿里云的美国硅谷地区的服务器，可以直接访问外网

**Comment by yul-h** [comment]
> > 我是直接在自己电脑上跑的docker，内存和网络带宽应该都是够的额
> 
> 那应该是网络的问题，梯子不稳定，我用的是阿里云的美国硅谷地区的服务器，可以直接访问外网

多少钱呀，也想整一个

**Comment by Leetion07** [comment]
答主您好，我也是相同的问题。服务器是阿里云的国内内地的服务器，请问应该如何解决呀，再给服务器搞梯子啊
