### ISSUE TITLE
railway部署出现以下错误，好像是崩溃，请大佬帮我看看什么原因

### ISSUE THREAD

**Issue by Johnny970** [fuergaosi233/wechat-chatgpt#538]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"9**********@qq.com","password":"********"}],"chatGptRetryTimes":10,"chatPrivateTiggerKeyword":"小小圈"}
Try init account: 9*********@qq.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lihaomyname** [comment]
你重新部署试试

**Comment by LinkShen** [comment]
我也是一样的错误，这是指账号被封了吗？

**Comment by goushijie** [comment]
相同的问题，重新部署很多次了

**Comment by goushijie** [comment]
> 我也是一样的错误，这是指账号被封了吗？

账号肯定没有问题，在web测试都是可以的

**Comment by twinice** [comment]
+1

**Comment by fuckwho** [comment]
+1

**Comment by georgiawang5332** [comment]
+1
