### ISSUE TITLE
railway部署报错Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by lihaomyname** [fuergaosi233/wechat-chatgpt#540]
nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
﻿[nodemon] 2.0.20
﻿[nodemon] to restart at any time, enter `rs`
﻿[nodemon] watching path(s): config.yaml
﻿[nodemon] watching extensions: ts
﻿[nodemon] starting `node --loader ts-node/esm src/main.ts`
﻿(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
﻿(Use `node --trace-warnings ...` to show where the warning was created)
﻿Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxx","password":"xxx"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"x"}
﻿Error: Protocol error (Page.addScriptToEvaluateOnNewDocument): Session closed. Most likely the page has been closed.
﻿at CDPSession.send (/app/node_modules/puppeteer/src/common/Connection.ts:286:9)
﻿at Page.evaluateOnNewDocument (/app/node_modules/puppeteer/src/common/Page.ts:2599:24)
﻿at ChatGPTAPIBrowser.initSession (file:///app/node_modules/chatgpt/src/chatgpt-api-browser.ts:153:18)
﻿at processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿at async AsyncRetry.retries (file:///app/src/chatgpt.ts:75:13)
﻿at async ChatGPTPool.startPools (file:///app/src/chatgpt.ts:73:9)
﻿at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
﻿at async main (file:///app/src/main.ts:16:3)
﻿[nodemon] app crashed - waiting for file changes before starting...

**Comment by goushijie** [comment]
相同的问题，怎么解决，大佬，配置都是正确的，检查很多遍了
