### ISSUE TITLE
railway 部署出现问题

### ISSUE THREAD

**Issue by goushijie** [fuergaosi233/wechat-chatgpt#544]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxx@hotmail.com","password":"xxx"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
Try init account: goushijie@hotmail.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

你们可以吗?卡住几天了，搞不定啊，配置没有问题，检查几次了

**Comment by LuckyZcs** [comment]
+1

**Comment by linxiaozhun** [comment]
同样

**Comment by goushijie** [comment]
OMG，这怎么办啊？都2天了，还没有部署好

**Comment by jiangkunoa** [comment]
同样，配置正确的

**Comment by zhangyan54545** [comment]
同样问题

**Comment by allyscn** [comment]
没搞懂，配置密码什么的都正确，反正就是不能显示二维码

**Comment by xiaofeihhu** [comment]
出现这种问题直接放弃吧，暂时无解的。

**Comment by allyscn** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by clairelovesgravy** [comment]
+1

**Comment by pengxiaobao** [comment]
+1

**Comment by twinice** [comment]
+1

**Comment by zzkkui** [comment]
+1

**Comment by zzkkui** [comment]
+1

**Comment by YuChengHup** [comment]
我也是这个问题卡在这

**Comment by pengxiaobao** [comment]
me too!

**Comment by PigCharid** [comment]
+1

**Comment by superyzh** [comment]
同样的问题啊

**Comment by bearofcode** [comment]
+1

**Comment by goushijie** [comment]
大家都放弃了？

**Comment by twinice** [comment]
> 大家都放弃了？
放弃了，关键不是部署，是微信限制，railway部署失败，本地调试用两次，微信警告两次。

**Comment by LogerW-sudo** [comment]
+1

**Comment by xiaojidan141** [comment]
我也是，哭了
