### ISSUE TITLE
railway部署无日志

### ISSUE THREAD

**Issue by lessoon** [fuergaosi233/wechat-chatgpt#545]
正常填写，显示部署成功后为啥没日志？

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/37376803/217144585-ee444eb6-5e0e-454d-b06d-94eaad30f980.png">

<img width="322" alt="image" src="https://user-images.githubusercontent.com/37376803/217144815-66974949-dfec-40d1-9d8b-069e26128370.png">

**Comment by goushijie** [comment]
要等会，在部署

**Comment by lessoon** [comment]
又重新部了一把 等了20分钟都没日志

**Comment by goushijie** [comment]
哎，我都2天了，也还没有搞定

**Comment by lessoon** [comment]
弃railway改本机电脑加代理可以正常使用，railway不熟悉。
