### ISSUE TITLE
各位大佬，扫描完二维码后报错。

### ISSUE THREAD

**Issue by s0ng1** [fuergaosi233/wechat-chatgpt#546]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by s0ng1** [comment]
这是什么问题？删除了8-11行后正常显示二维码，提示以上报错信息。

**Comment by wqyliyang** [comment]
我也是这样的问题，我是注册调11行，有二维码，但是扫描就报错

**Comment by s0ng1** [comment]
> 我也是这样的问题，我是注册调11行，有二维码，但是扫描就报错

重启docker以后报错，然后docker就起不来了。

**Comment by tombarbar** [comment]
解决了吗  我也是这个问题
