### ISSUE TITLE
启动后不显示二维码。一直提示超时

### ISSUE THREAD

**Issue by suyongcheng123** [fuergaosi233/wechat-chatgpt#549]
🤖️ Start GPT Bot Success, ready to handle message!
08:52:21 WARN WechatyPuppetMixin start() starting puppet ... timeout
08:52:21 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
08:53:06 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
08:53:06 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
08:53:06 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by lilinyuanvr** [comment]
同问

**Comment by suyongcheng123** [comment]
我分别用 腾讯云 日服 美服 都试了，都是报一样得错，然后我把服务器硬件和带宽升级了，还是不行，

**Comment by STIVW** [comment]
这里已经解答: https://github.com/fuergaosi233/wechat-chatgpt/issues/494#issue-1531627469
修改配置文件,然后重新build一个新镜像.
我用177号commits,建立的镜像运行成功了

**Comment by fateplayer** [comment]
ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at file:///app/src/config.ts:9:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
[nodemon] app crashed - waiting for file changes before starting...


我报这个错误
