### ISSUE TITLE
No chatgpt account in pool 这个是啥问题，我的账号正常的呀。

### ISSUE THREAD

**Issue by kusila** [fuergaosi233/wechat-chatgpt#550]
root@iZuf64takeuikpdwukd2wzZ:~/bot# docker logs -f wechat-chatgpt

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"****","password":"****","isGoogleLogin":true}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":"http://127.0.0.1:15777"}
Try init account: dawsondn@126.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by renshiyou** [comment]
亲测安装最新版Chrome浏览器可以解决

**Comment by dawven** [comment]
> 亲测安装最新版Chrome浏览器可以解决

这个和浏览器有啥关系

**Comment by RayWong-codingPoet** [comment]
#551

**Comment by renshiyou** [comment]
> > 亲测安装最新版Chrome浏览器可以解决
> 
> 这个和浏览器有啥关系

这个程序应该是利用自动化测试 模拟人工打开浏览器去登录页面完成登录

**Comment by goushijie** [comment]
为什么不调用api来完成?

**Comment by zzkkui** [comment]
> 亲测安装最新版Chrome浏览器可以解决

我更新了也不行。。

**Comment by bigsniper** [comment]
求作者给个回复呀，我也是卡在这里了，浏览器也是最新的

**Comment by skystone011** [comment]
> 降低commits版本，用1月12号的试试，我是这样成功的

我也是这个问题，换成1.0.2版本后，二维码还是没有出来

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:50) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxx","password":"xxx"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
ChatGPTPools: 1
🤖️ Start GPT Bot Success, ready to handle message!
11:55:42 WARN WechatyPuppetMixin start() starting puppet ... timeout
11:55:42 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
11:56:42 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
11:56:47 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
11:56:47 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by d0glrq** [comment]
> 

1.0.2不就是最新的吗
