### ISSUE TITLE
"chatgpt": "^3.5.2"持续跳转至ChatGPT is at capacity right now

### ISSUE THREAD

**Issue by RayWong-codingPoet** [fuergaosi233/wechat-chatgpt#551]
该版本定向到https://chat.openai.com/auth/login ,会持续显示ChatGPT is at capacity right now页面。
同时通过正常页面登录跳转到https://chat.openai.com/chat 可正常使用。

**Comment by dawven** [comment]
没看懂，我需要做什么处理

**Comment by RayWong-codingPoet** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/blob/main/package.json#L15
这里可能需要用4.+版本。。

**Comment by RayWong-codingPoet** [comment]
Chrome Version 109.0.5414.119 (Official Build) (arm64)

**Comment by renshiyou** [comment]
https://chat.openai.com/auth/login这个登录页面已经被官方修改，应该是修改了原先的登录入口

**Comment by RayWong-codingPoet** [comment]
#552 提到使用session token方式规避了该问题。
但session token方式已被repo主 @fuergaosi233 废弃，且openai认证策略的变更让session方式也变得不太现实。#552 如何解决的让人费解。
