### ISSUE TITLE
Code 429: Too Many Requests

### ISSUE THREAD

**Issue by kychunab** [fuergaosi233/wechat-chatgpt#552]
wanna ask whether this error is due to error in chatgpt or error in railway?
becuz it happens quite frequently...
what time interval is suggested to ask next question?

**Comment by RayWong-codingPoet** [comment]
> wanna ask whether this error is due to error in chatgpt or error in railway? becuz it happens quite frequently... what time interval is suggested to ask next question?

u haven't encounter the #551 ? which would redirect to https://chat.openai.com/auth/login with "ChatGPT is at capacity right now" warning, and finally cuz pool init failed

**Comment by kychunab** [comment]
ohh i solved this problem by adding variable CHAT_GPT_RETRY_TIMES and set it to 3. Such that it will automatically retry if encounter error.
I encounter error #429 becuz i use token instead of login email and password. I guess thats a bit difference in terms of the services using.

> > wanna ask whether this error is due to error in chatgpt or error in railway? becuz it happens quite frequently... what time interval is suggested to ask next question?
> 
> u haven't encountered the #551 ? which would redirect to https://chat.openai.com/auth/login with "ChatGPT is at capacity right now" warning, and finally cuz pool init failed

**Comment by kychunab** [comment]
If using API from Openai website, the currently available model will be Ada,Babbage,Curie,Davinci. (Not Chatgpt, less smart than chatgpt but are more easily available even during peak time.)

For joining chatgpt api waitlist,  visit https://share.hsforms.com/1u4goaXwDRKC9-x9IvKno0A4sk30
