### ISSUE TITLE
不显示二维码

### ISSUE THREAD

**Issue by Leetion07** [fuergaosi233/wechat-chatgpt#553]
当登录时，不显示二维码，并显示如下的信息，应该如何进行解决？

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`

**Comment by dockercore** [comment]
哪个版本的 node

**Comment by Leetion07** [comment]
是指docker版本吗，我不太懂您提到的节点版本的意思，如果是的话，docker的版本信息为:
[root@VM-16-6-centos electron-ssr]# docker version 
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:49:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:46:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
