### ISSUE TITLE
使用微软账号默认登陆yaml怎么改？

### ISSUE THREAD

**Issue by samqin123** [fuergaosi233/wechat-chatgpt#554]
RT

**Comment by oiOxOio** [comment]
+1 同求

**Comment by samqin123** [comment]
chatGPTAccountPool:
  - email: email
    password: password
    isGoogleLogin: false
   【 is微软Login：？？？？】
chatPrivateTiggerKeyword: ""
openAIProxy: ""

**Comment by oiOxOio** [comment]
> chatGPTAccountPool：
> 
> * 电子邮件： 电子邮件密码： 密码是谷歌登录： 假 【 是微软登录：????】 聊天私人跳跳虎关键字： “” openAIProxy： “”

应该不是吧，代码里都没搜到和microsoft相关字眼

**Comment by zdRan** [comment]
为什么不使用API token实现呢？

**Comment by dreamfly32** [comment]
> 为什么不使用API token实现呢？

有限额，超过收费

**Comment by zdRan** [comment]
更奇怪的是，好像openAI 官网没有补充密码的地方
