### ISSUE TITLE
使用Docker安装方式，二维码显示不出来。chat-gpt账号被冻结

### ISSUE THREAD

**Issue by strin-v** [fuergaosi233/wechat-chatgpt#555]
启动时，二维码不会显示出来
![image](https://user-images.githubusercontent.com/74670147/217455183-e00d1819-70e5-4abe-8158-ca29f854524d.png)
浏览器登录chat-gpt时显示：异常登录行为，账号被封
![image](https://user-images.githubusercontent.com/74670147/217455455-8446dcbe-c9a6-4644-baf6-23c225bcb543.png)

**Comment by dockercore** [comment]
建议换一个浏览器代理的IP地址，最好全局模式，再进行配置！
