### ISSUE TITLE
出现这种错误怎么办

### ISSUE THREAD

**Issue by laditas** [fuergaosi233/wechat-chatgpt#56]
17:10:01 WARN PuppetWechat4u monkeyPatch() wechat4u.checkPolling() notifyMobile() exception: AssertionError [ERR_ASSERTION]: 1 == 0
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/root/wechatapt/node_modules/wechat4u/src/util/global.js:53:14)
    at /root/wechatapt/node_modules/wechat4u/src/core.js:228:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/root/wechatapt/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /root/wechatapt/node_modules/wechat4u/src/core.js:228:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

**Comment by HandsomeWu6** [comment]
微信需要实名认证 @laditas
