### ISSUE TITLE
ERR PuppetWeChatBridge start() exception  这是被微信封禁了吗？

### ISSUE THREAD

**Issue by dryl90** [fuergaosi233/wechat-chatgpt#566]
🤖️ Start GPT Bot Success, ready to handle message!
23:34:53 ERR PuppetWeChatBridge start() exception: Error: net::ERR_CONNECTION_CLOSED at https://wx2.qq.com?lang=zh_CN&target=t
23:34:53 ERR PuppetWeChat initBridge() exception: net::ERR_CONNECTION_CLOSED at https://wx2.qq.com?lang=zh_CN&target=t
23:34:53 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
⚠️ Bot start failed, can you log in through wechat on the web?: Error: net::ERR_CONNECTION_CLOSED at https://wx2.qq.com?lang=zh_CN&target=t

**Comment by dreamfly32** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/492
