### ISSUE TITLE
不显示微信登录

### ISSUE THREAD

**Issue by PigCharid** [fuergaosi233/wechat-chatgpt#568]
🤖️ Start GPT Bot Success, ready to handle message!
00:37:17 WARN WechatyPuppetMixin start() starting puppet ... timeout
00:37:17 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
00:38:02 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
00:38:02 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
00:38:02 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by hxinyun** [comment]
我也遇到同样的问题。

**Comment by dreamfly32** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/issues/492

**Comment by betta-cyber** [comment]
![image](https://user-images.githubusercontent.com/5920513/217982291-0642e283-fa00-44b8-b6a6-ab31d393b3d7.png)
试试？
