### ISSUE TITLE
请问这个项目的实现原理是调用gpt-3的模型api还是使用了其他办法调用了chatgpt的模型

### ISSUE THREAD

**Issue by 30skl** [fuergaosi233/wechat-chatgpt#569]
请问这个项目的实现原理是调用gpt-3的模型api还是使用了其他办法调用了chatgpt的模型

**Comment by null0034** [comment]
> 

根据commit的记录来看，应该切换到了使用openAI的api，并不是真正的调用ChatGPT的API

**Comment by dreamfly32** [comment]
模拟浏览器登录，不是调用api

**Comment by fuergaosi233** [comment]
模拟浏览器， 不是 API 接口

**Comment by femj007** [comment]
看代码是模拟浏览器登陆，不是用ChatGPT API（而且也没有让你输入API key，而是用邮箱密码登录）
