### ISSUE TITLE
请问如何修改代码来部署到vercel，目前会卡在building直到45min的上限

### ISSUE THREAD

**Issue by HandsomeWu6** [fuergaosi233/wechat-chatgpt#57]

**Comment by HandsomeWu6** [comment]
如果能部署到vercel的话会方便很多，白嫖服务器而且能解决国内代理的问题，不会出现503等failed fatch的问题

**Comment by fuergaosi233** [comment]
It's not realistic because the service is stateful, but it can be deployed to `railway`,it is in my Roadmap
