### ISSUE TITLE
no captchas found

### ISSUE THREAD

**Issue by ywzheng19** [fuergaosi233/wechat-chatgpt#570]
已添加-e CAPTCHA_TOKEN参数，
报错如下：
solving captchs using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchs using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchs using 2captcha...
no captchas found
no captchas found
no captchas found
Try init account: xxxx failed, remove it from pool

**Comment by ywzheng19** [comment]
docker方式部署。help

**Comment by dreamfly32** [comment]
两个原因，1是真的没有验证码，ip不需要人机验证，2是还没到验证码那一个页面

**Comment by xiuzigege** [comment]
wo ye yi yang zen me ban ne

**Comment by xiuzigege** [comment]
求助
