### ISSUE TITLE
有能解决微信账号被警告的方法吗

### ISSUE THREAD

**Issue by liaozhangsheng** [fuergaosi233/wechat-chatgpt#571]

**Comment by hnuzhoulin** [comment]
同问，3天就被警告了

**Comment by dreamfly32** [comment]
有类似issue搜下，好像是实名制

**Comment by dockercore** [comment]
建议申请一个小号，单独使用

**Comment by dockercore** [comment]
或者使用微信公众号对接使用

**Comment by thechen130** [comment]
+1，有什么办法解决呢

**Comment by RealTong** [comment]
付费即可😒
https://github.com/wechaty/wechaty#3-switch-protocolpuppet

**Comment by thechen130** [comment]
> 付费即可😒 https://github.com/wechaty/wechaty#3-switch-protocolpuppet

如何付费，该怎么操作呢，我是小白

**Comment by RealTong** [comment]
> > 付费即可😒 https://github.com/wechaty/wechaty#3-switch-protocolpuppet
> 
> 如何付费，该怎么操作呢，我是小白

链接里都有啊, 使用iPad协议, 找wechaty他们买token就行了
