### ISSUE TITLE
怎么进入聊天啊

### ISSUE THREAD

**Issue by PigCharid** [fuergaosi233/wechat-chatgpt#572]
我微信登录以后，只在终端有聊天记录，没有网页版的聊天对话
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       你看看 美国管没管过 腾讯 阿里
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       说实话 这两个龙头都没技术 没不可替代的技术
Message: Message#Text[🗣Contact<振轩>@👥Room<ChatGPT应用一群>]   没管说明那不是核心技术
Message: Message#Text[🗣Contact<曾超>@👥Room<ChatGPT应用一群>]   两种体验是两种体验，搜索技术百度
Message: Message#Text[🗣Contact<曾超>@👥Room<ChatGPT应用一群>]   不差
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       就是核心技术啊
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       看看 字节当初的tiktok
Message: Message#Text[🗣Contact<Diablo>@👥Room<ChatGPT应用一群>] 百度的产品 还能再烂一点吗？
Message: Message#Text[🗣Contact<振轩>@👥Room<ChatGPT应用一群>]   鸿蒙系统是自主研发的吗
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       华为
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       被制裁
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       自由贸易不见了
Message: Message#Text[🗣Contact<Diablo>@👥Room<ChatGPT应用一群>] 「江城月圆：看看 字节当初的tiktok」
- - - - - - - - - - - - - - -
认同
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       所谓的自由而已
Message: Message#Text[🗣Contact<江城月圆>@👥Room<ChatGPT应用一群>]       不要太当真
Message: Message#Text[🗣Contact<灵境星空>@👥Room<ChatGPT应用一群>]       注意讨论刹下车
Message: Message#Text[🗣Contact<alex>@👥Room<ChatGPT应用一群>]   倍制裁正常，现在美国就不想中国好，特别是华为这样的共识，美国是巴不得他倒闭的
Message: Message#Text[🗣Contact<Diablo>@👥Room<ChatGPT应用一群>] 字节的产品确实是一个从用户角度出发的产品，百度的产品就是一个大型广告平台而已
Message: Message#Text[🗣Contact<振轩>@👥Room<ChatGPT应用一群>]   国外不是天堂，中国不是地狱。

**Comment by kunleaa** [comment]
遇到了一样现象，请问问题解决了吗
