### ISSUE TITLE
部署成功的日志没有微信链接，只有一个配置信息

### ISSUE THREAD

**Issue by JackMore0328** [fuergaosi233/wechat-chatgpt#575]
Start GPT Bot Config is:{xxxx}

**Comment by dockercore** [comment]
配置格式不对，请安装文档给的案例来配置

**Comment by Leetion07** [comment]
我遇到和你相似的问题，请问你有解决掉吗

**Comment by 0xfather** [comment]
>微信-chatgpt@1.0.0 开发
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[节点蒙] 2.0.20
[nodemon] 要随时重新启动，请输入“rs”
[nodemon] 监视路径： config.yaml
[节点蒙] 观看扩展：TS
[nodemon] start 'node --loader ts-node/esm src/main.ts'
（节点：82） 实验警告：自定义 ESM 加载程序是一项实验性功能，可能随时更改
（使用“node --trace-warnings ...”显示创建警告的位置）
Start GPT Bot Config is：{“chatGPTAccountPool”：[{“email”：“xxxxxx@hotmail.com”，“password”：“*******”}]，“chatGptRetryTimes”：200，“chatPrivateTiggerKeyword”：“”}
杀
[nodemon] 应用程序崩溃 - 在启动之前等待文件更改...

**Comment by Leetion07** [comment]
> 配置格式不对，请安装文档给的案例来配置
您好 请问提示这个 不显示二维码 应该怎么解决呢
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxx.com","password":"xxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}

**Comment by egoiss** [comment]
我也是

**Comment by bearofcode** [comment]
同样

**Comment by wly1456839489** [comment]
我也是一样

**Comment by hushlonelyhug** [comment]
> > 配置格式不对，请安装文档给的案例来配置
> > 您好 请问提示这个 不显示二维码 应该怎么解决呢
> > [nodemon] 2.0.20
> > [nodemon] to restart at any time, enter `rs`
> > [nodemon] watching path(s): config.yaml
> > [nodemon] watching extensions: ts
> > [nodemon] starting `node --loader ts-node/esm src/main.ts`
> > (node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
> > (Use `node --trace-warnings ...` to show where the warning was created)
> > Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxx.com","password":"xxxxxx","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}

你好，解决了吗？二维码出来没有？
