### ISSUE TITLE
 Error: An executablePath or channel must be specified for puppeteer-core

### ISSUE THREAD

**Issue by NoobHaoZi** [fuergaosi233/wechat-chatgpt#576]
没有弹出微信二维码
![image](https://user-images.githubusercontent.com/82959289/217703333-b8c74391-395d-43e9-b7e8-82f2dc338892.png)

**Comment by tender001** [comment]
同样的遭遇

**Comment by Harry-Cao** [comment]
我也遇到了这样的问题，我去对比了wechaty的实例代码，注释了该项目不必要的代码后，成功运行了。
- 找到根目录-src-main.ts, 并将bot的初始化参数按下面实例注释
- `const bot =  WechatyBuilder.build({
  name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
  // puppetOptions: {
  //   uos: true, // 开启uos协议
  // },
  // puppet: "wechaty-puppet-wechat",
});`
- 重新运行即可

- 你也可以把下方的简化实例代码添加到main.ts中并调用单独测试wechaty是否运行正常
- `async function botTest() {
  bot
  .on("scan", async (qrcode, status) => {
    const url = `https://wechaty.js.org/qrcode/${encodeURIComponent(qrcode)}`;
    console.log(`Scan QR Code to login: ${status}\n${url}`);
    console.log(
      await QRCode.toString(qrcode, { type: "terminal", small: true })
    );
  })
  try {
    await bot.start();
  } catch (e) {
    console.error(
      `⚠️ Bot start failed, can you log in through wechat on the web?: ${e}`
    );
  }
}`
