### ISSUE TITLE
api key 接入方式更有场景

### ISSUE THREAD

**Issue by PengZezhou** [fuergaosi233/wechat-chatgpt#577]
申请api-key，接入使用更简单，不用爬坡，这个在哪个文件完善
https://beta.openai.com/account/api-keys

**Comment by albertwdl** [comment]
api-key的方式是接入的OpenAI的API模型，而网页版的还没有公开API，只能通过网页登陆。OpenAI已经公开的API模型最新的是GPT-3，对话能力不如网页版的。

**Comment by s0ng1** [comment]
> 

尤其是GPT-3的达芬奇3模型，我试了一下不是差了一点半点。。。

**Comment by LppinGView** [comment]
请问各位，这个项目里面使用账号和密码登录方式，是实时拉取网页版的答案吗？

**Comment by albertwdl** [comment]
> 请问各位，这个项目里面使用账号和密码登录方式，是实时拉取网页版的答案吗？

是实时拉取网页版的答案，你登陆网页版还可以看到对话记录

**Comment by fuergaosi233** [comment]
确实是 API Key 更方便， 但是目前的 APikey 对话效果太差了
