### ISSUE TITLE
no captchas found

### ISSUE THREAD

**Issue by xiuzigege** [fuergaosi233/wechat-chatgpt#578]
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
solving captchas using 2captcha...
no captchas found
no captchas found
no captchas found
Try init account: xxxxxxxx@gmail.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...
现在一直卡在这里 该怎么办呢 求助  help

**Comment by small-ora** [comment]
我也是，账号密码，验证码的key都配置了
