### ISSUE TITLE
泪的教训：不要跟机器人聊敏感话题

### ISSUE THREAD

**Issue by qiuziqqqq** [fuergaosi233/wechat-chatgpt#579]
会被请去喝茶的。
起因：机器人微信绑定的本人手机号。朋友A好奇想测试机器人(chatGPT)都知道什么，问它七七八八的问题
经过：A问了机器人美国敏感话题，chatGPT拒绝回答，然后朋友A就继续问了两个国内的敏感话题。
结果：第二天晚上民j叔叔上门找到我，就我(的机器人)在群里讨论敏感话题一事，带我去pcs了解情况

**Comment by moeik** [comment]
兄弟 我希望你是骗我的

**Comment by yszpat** [comment]
我的微信调通三天之后被封了

**Comment by licat233** [comment]
我很好奇，民j叔叔都问了你哪些问题？怎么辨别你是良民的？

**Comment by qiuziqqqq** [comment]
> 兄弟 我希望你是骗我的

我发现的时候就觉得不妙，但是时间过了撤回不了，就直接退出了群聊。没想到第二天民j叔叔还是来了

**Comment by qiuziqqqq** [comment]
> 我的微信调通三天之后被封了

我的昨天也封了，解了。是不是一天发言的次数太多？

**Comment by qiuziqqqq** [comment]
> 我很好奇，民j叔叔都问了你哪些问题？怎么辨别你是良民的？

问我是不是在群里讨论了那两个话题，问我和朋友的工作，问我们讨论话题的目的，问我是不是翻q了。
老老实实交代呀，解释了很久，我说我没参与讨论，是AI在回复。做了笔录，写了保证书(也没保证啥，我就写了保证不再给朋友使用人工智能聊天接口- -)

**Comment by jiuqianyuan** [comment]
> 问我是不是在群里讨论了那两个话题，问我和朋友的工作，问我们讨论话题的目的，问我是不是翻q了。
> 老老实实交代呀，解释了很久，我说我没参与讨论，是AI在回复。做了笔录，写了保证书(也没保证啥，我就写了保证不再给朋友使用人工智能聊天接口- -)

没让你保证别翻q啊

**Comment by qiuziqqqq** [comment]
> > 问我是不是在群里讨论了那两个话题，问我和朋友的工作，问我们讨论话题的目的，问我是不是翻q了。
> > 老老实实交代呀，解释了很久，我说我没参与讨论，是AI在回复。做了笔录，写了保证书(也没保证啥，我就写了保证不再给朋友使用人工智能聊天接口- -)
> 
> 没让你保证别翻q啊

我没承认:)，我说接这个不需要翻q

**Comment by roco2015** [comment]
被微信拦截的吧，和是不是与机器人说没关系
