### ISSUE TITLE
有没有兄弟知道这个是啥意思啊。

### ISSUE THREAD

**Issue by lth2000** [fuergaosi233/wechat-chatgpt#580]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"oli*0@*","password":"*`"}],"chatGptRetryTimes":5,"chatPrivateTiggerKeyword":"@bot"}
Try init account: ol*0@m*lllx.c* failed, remove it from pool
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by liaozhangsheng** [comment]
换成谷歌浏览器试试

**Comment by wangzhi0927** [comment]
我刚才也碰到了、账号密码肯定没错

**Comment by shinesky** [comment]
同样的问题，账号密码肯定没错的，而且我浏览器还开了无痕模式

**Comment by Kashima-Akira** [comment]
您还解决了吗

**Comment by Zoumachuan** [comment]
> 您还解决了吗

几天过去了，我感觉这个东西是概率出现的，大概和chatgpt自己的网站有关，对我个人而言，上午和中午大部分时间是可以登录的，晚上就不太行，所以我换apikey了，虽然但是效果不是很好
