### ISSUE TITLE
微信号被限制使用了

### ISSUE THREAD

**Issue by ls20vip** [fuergaosi233/wechat-chatgpt#583]
![image](https://user-images.githubusercontent.com/107453273/217827373-5b21a71c-31a3-4b26-9a17-662c3114c4a4.png)
限制原因：使用了微信外挂、非官方客户端或模拟器
也没有发一些什么不安全的内容，大概平均五六分钟一条消息，三个微信号同时被限制的
你们有遇到过这种情况吗？

**Comment by ls20vip** [comment]
这几天，使用uos协议的封了不少

**Comment by King-Of-Knights** [comment]
昨天上午搞好的，今天下午2点半被封的，我的大号不小心扫了一下，登录了被警告，小号被限制了

**Comment by tasty007** [comment]
是刚申请的小号吗.

**Comment by ls20vip** [comment]
不是，至少有一年了，平时经常保持登陆，只不过没什么好友



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月10日(周五) 上午9:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuergaosi233/wechat-chatgpt] 微信号被限制使用了 (Issue #583)




 
是刚申请的小号吗.

**Comment by qiuziqqqq** [comment]
昨天白天调试接口，短时间发送了大量消息，晚上被封了

**Comment by betta-cyber** [comment]
https://github.com/wechaty/wechaty-puppet-padpro 可解

**Comment by rickywu** [comment]
> https://github.com/wechaty/wechaty-puppet-padpro 可解

怎么解，不删除src/main.js那几行，install 这个？能详细说下吗？

**Comment by Aiyin5** [comment]
> https://github.com/wechaty/wechaty-puppet-padpro 可解

这个我看了一下，已经停止售卖token了，还有其他方式绕过限制吗？

**Comment by Zoumachuan** [comment]
> > https://github.com/wechaty/wechaty-puppet-padpro 可解
> 
> 这个我看了一下，已经停止售卖token了，还有其他方式绕过限制吗？

+1，有消息踢我，我看有卖个人token的，但200一个月感觉有点没必要，不知道有没有别的解决方法

**Comment by Zoumachuan** [comment]
> > https://github.com/wechaty/wechaty-puppet-padpro 可解
> 
> 怎么解，不删除src/main.js那几行，install 这个？能详细说下吗？

uos协议感觉确实是寄了，看来只能用付费的token了

**Comment by Angel0726** [comment]
> 昨天上午搞好的，今天下午2点半被封的，我的大号不小心扫了一下，登录了被警告，小号被限制了

使用的多吗？是不是不使用就不会被限制

**Comment by King-Of-Knights** [comment]
@Angel0726 只要扫了登录就会有问题

**Comment by Angel0726** [comment]
> @Angel0726 只要扫了登录就会有问题

 明白
