### ISSUE TITLE
微信太容易被封了，现在有个想法

### ISSUE THREAD

**Issue by thechen130** [fuergaosi233/wechat-chatgpt#585]
想找一些人一起做个小程序，一起出力整一个，等之后在再整个chatgpt plus版本进入进去岂不美滋滋

**Comment by yimouleng** [comment]
小程序不容易封吗。。。更容易封

**Comment by thechen130** [comment]
> 小程序不容易封吗。。。更容易封

我看已经网上已经有人做出来了，到现在还在。不容易封吧

**Comment by L-Qun** [comment]
可以啊，带带我

**Comment by charlotte076** [comment]
别， 兄弟。 小程序被人举报封的更快。想做只能做web版的。

**Comment by 1765659645** [comment]
前天做了个简单的网页，是基于chatgpt-api的，就是服务太容易400或者429，放弃了
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/57136514/217979188-6af4e322-3345-474c-a8f9-b931ef22bb5a.png">

**Comment by thechen130** [comment]
> 前天做了个简单的网页，是基于chatgpt-api的，就是服务太容易400或者429，放弃了 <img alt="image" width="1114" src="https://user-images.githubusercontent.com/57136514/217979188-6af4e322-3345-474c-a8f9-b931ef22bb5a.png">

你使用的是什么服务器，如果使用美国的VPS会不会效果好些

**Comment by 1765659645** [comment]
那我倒没测试，你可以看下chatgpt-api那个库，只需要设置apikey就可以使用

**Comment by DwyaneLee** [comment]
> 
chatgpt的小程序全被下架了
