### ISSUE TITLE
如何用谷歌账户登录

### ISSUE THREAD

**Issue by Nil-1** [fuergaosi233/wechat-chatgpt#586]
我注册的时候是直接用谷歌账户登录，没有openAi的账户和密码，我把谷歌账户和密码配置上去，会发生报错

**Comment by oliver-xie666** [comment]
同问，railway部署失败

**Comment by mabeijianxi** [comment]
同问

**Comment by xianzao** [comment]
PR里有一个升级chatgpt-api后使用api key的版本，就不会有跟ip或者limit相关的问题了
![image](https://user-images.githubusercontent.com/112499828/218399373-056ffab7-d46b-4bde-89ce-877cdbbf4910.png)

**Comment by leohxj** [comment]
> 

v4 版本使用的就是 openAI 的 API 了, 模型能力和 ChatGPT 浏览器版本还是有差距的

**Comment by max-sun-hongyi** [comment]
等一个更新
