### ISSUE TITLE
大佬可以帮忙看看这个报错应该如何解决吗，node和npm版本分别为18.14.0 和 9.4.2

### ISSUE THREAD

**Issue by Leetion07** [fuergaosi233/wechat-chatgpt#587]
`[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:161790) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/root/wechat-chatgpt/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:1:10 - error TS2305: Module '"wechaty"' has no exported member 'WechatyBuilder'.

1 import { WechatyBuilder } from "wechaty";
           ~~~~~~~~~~~~~~
src/main.ts:18:24 - error TS7006: Parameter 'qrcode' implicitly has an 'any' type.

18     .on("scan", async (qrcode, status) => {
                          ~~~~~~
src/main.ts:18:32 - error TS7006: Parameter 'status' implicitly has an 'any' type.

18     .on("scan", async (qrcode, status) => {
                                  ~~~~~~
src/main.ts:25:25 - error TS7006: Parameter 'user' implicitly has an 'any' type.

25     .on("login", async (user) => {
                           ~~~~
src/main.ts:29:27 - error TS7006: Parameter 'message' implicitly has an 'any' type.

29     .on("message", async (message) => {
                             ~~~~~~~

    at createTSError (/root/wechat-chatgpt/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/wechat-chatgpt/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/wechat-chatgpt/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/wechat-chatgpt/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/root/wechat-chatgpt/node_modules/ts-node/src/esm.ts:400:37)
    at /root/wechat-chatgpt/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/root/wechat-chatgpt/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2305, 7006, 7006, 7006, 7006 ]
}
[nodemon] app crashed - waiting for file changes before starting...
`
`
[root@VM-16-6-centos wechat-chatgpt]# node -v
v18.14.0
[root@VM-16-6-centos wechat-chatgpt]# npm -v
9.4.2
`

**Comment by foryo77** [comment]
linux上面插件版本不兼容

**Comment by LppinGView** [comment]
看一下package.json，这个文件里面的，wechaty 微信这个依赖包，版本是不是1.20.2。不是改成这个就行了

    "wechaty": "^1.20.2",

**Comment by Leetion07** [comment]
> 看一下package.json，这个文件里面的，wechaty 这个依赖包，版本是不是1.20.2。不是改成这个就行了
> 
> ```
> "wechaty": "^1.20.2",
> ```

还是没能解决，可以加个联系方式帮忙看看吗，有偿

**Comment by Leetion07** [comment]
> 看一下package.json，这个文件里面的，wechaty 这个依赖包，版本是不是1.20.2。不是改成这个就行了
> 
> ```
> "wechaty": "^1.20.2",
> ```

如果可以的话 我的qq是 1712184117

**Comment by LppinGView** [comment]
> > 看一下package.json，这个文件里面的，wechaty 这个依赖包，版本是不是1.20.2。不是改成这个就行了
> > ```
> > "wechaty": "^1.20.2",
> > ```
> 
> 如果可以的话 我的qq是 1712184117

把钱留着买书看吧。你是啥环境，现在报啥错了

**Comment by LppinGView** [comment]
你按这个先自查一遍

https://github.com/wechaty/wechaty/issues/2486

**Comment by Leetion07** [comment]
> > > 看一下package.json，这个文件里面的，wechaty 这个依赖包，版本是不是1.20.2。不是改成这个就行了
> > > ```
> > > "wechaty": "^1.20.2",
> > > ```
> > 
> > 
> > 如果可以的话 我的qq是 1712184117
> 
> 把钱留着买书看吧。你是啥环境，现在报啥错了

Centor OS 8服务器上，服务器在国内，但是我设置过shadowsocks，我ping了一下是能够访问‘google.cn’等的。现在的问题是要么`npm run dev`时，提示账号初始化失败，此时的wechaty版本为1.20.2。如果在`npm install`后，按照`shell`提示进行`npm audit fix --force`后，不会提醒账号初始化不过，但是此时的`package.json`文件中的wechaty版本号被修改，就会提醒前文提到的报错。可能由于我对计算机相关知识的不了解，在哪个地方犯了一个很基础的错误导致的吧。

**Comment by LppinGView** [comment]
> > > > 看一下package.json，这个文件里面的，wechaty 这个依赖包，版本是不是1.20.2。不是改成这个就行了
> > > > ```
> > > > "wechaty": "^1.20.2",
> > > > ```
> > > 
> > > 
> > > 如果可以的话 我的qq是 1712184117
> > 
> > 
> > 把钱留着买书看吧。你是啥环境，现在报啥错了
> 
> Centor OS 8服务器上，服务器在国内，但是我设置过shadowsocks，我ping了一下是能够访问‘google.cn’等的。现在的问题是要么`npm run dev`时，提示账号初始化失败，此时的wechaty版本为1.20.2。如果在`npm install`后，按照`shell`提示进行`npm audit fix --force`后，不会提醒账号初始化不过，但是此时的`package.json`文件中的wechaty版本号被修改，就会提醒前文提到的报错。可能由于我对计算机相关知识的不了解，在哪个地方犯了一个很基础的错误导致的吧。

你把版本改对，路子是对的。之后出现这个问题，那又是其他问题了，至少编译通过了。版本不对，编译报错，就是你前面那些报错了。
![image](https://user-images.githubusercontent.com/34837598/218052309-96eff35a-4f9b-48eb-bc34-870eca0a667a.png)
