### ISSUE TITLE
error 400; An error ocurred. Try refreshing your browser.

### ISSUE THREAD

**Issue by 1638234804** [fuergaosi233/wechat-chatgpt#588]
现在是没办法用了吗，一直400，我切换new分支，和回退版本到 f2c8704 都没用；[参考的这个issues](https://github.com/fuergaosi233/wechat-chatgpt/issues/531)

**Comment by ChinaMars521** [comment]
post 参数里面缺少conversation_id

**Comment by Aiyin5** [comment]
> post 参数里面缺少conversation_id

这个该怎么解决

**Comment by q1594081942** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/tree/f2c87041441e4c782759da1f24ba8775736e34f5,用12号的就行

**Comment by yang-fireworkhq** [comment]
记得 reset 后重新  npm install
commit 涉及 package.json

**Comment by RidiculousRonZzz** [comment]
@q1594081942 您好，链接好像无效了
