### ISSUE TITLE
继续使用有风险！

### ISSUE THREAD

**Issue by dreamfly32** [fuergaosi233/wechat-chatgpt#589]
最近chatgpt热度上升，wx已经开始打压，
昨天被指使用外挂限制登录，然后就没再使用，今天限制通讯功能，需要邀请一个好友帮助解封。
![c79a3ee33b1fd7ae508216e1176207c](https://user-images.githubusercontent.com/32086491/218025960-7d76062c-97d5-4664-862a-b937d18884af.jpg)

**Comment by twinice** [comment]
我也遇到了，昨天提示一次，今天又提示了

**Comment by thechen130** [comment]
可以接入钉钉吗，钉钉比较开放吧，有想法的叫我

**Comment by hx3333** [comment]
我也被警告两天了，好消息是还能自行解封

**Comment by s0ng1** [comment]
> thechen130

钉钉已经有了，搜一下，但是他用的是api，GPT-3模型，需要收费。

**Comment by thechen130** [comment]
> > thechen130
> 
> 钉钉已经有了，搜一下，但是他用的是api，GPT-3模型，需要收费。

可以给个链接吗

**Comment by FLIER001** [comment]
应该是wechaty的问题

**Comment by s0ng1** [comment]
> > > thechen130
> > 
> > 
> > 钉钉已经有了，搜一下，但是他用的是api，GPT-3模型，需要收费。
> 
> 可以给个链接吗

https://github.com/eryajf/chatgpt-dingtalk

**Comment by LQYHYQ** [comment]
我也遇到了，tx不当人

**Comment by Zoumachuan** [comment]
> 我也遇到了，tx不当人

真的逆天，把热度炒起来然后开始封杀，封杀完了就“自研”

**Comment by thechen130** [comment]
> > > > thechen130
> > > 
> > > 
> > > 钉钉已经有了，搜一下，但是他用的是api，GPT-3模型，需要收费。
> > 
> > 
> > 可以给个链接吗
> 
> https://github.com/eryajf/chatgpt-dingtalk

确实是GPT-3模型，太烂了，还是用这种网页登录的方式比较好，只需要把拿到的数据转到微信改成钉钉机器人就可以了吧。有大佬看得懂代码吗，愿意尝试尝试吗

**Comment by realzsy** [comment]
> 

你是不是wechat？我怀疑是不是国内微信的原因，我也一直不成功。

**Comment by thechen130** [comment]
> > 
> 
> 你是不是wechat？我怀疑是不是国内微信的原因，我也一直不成功。

国外的微信政策是否和国内一样，是否也会被检测封号

**Comment by realzsy** [comment]
> > > 
> > 
> > 你是不是wechat？我怀疑是不是国内微信的原因，我也一直不成功。
> 
> 国外的微信政策是否和国内一样，是否也会被检测封号

国外微信扫码直接无法登陆，我刚才那个回复针对上一条无法解锁的问题，没有引用到。

**Comment by SnapdragonLee** [comment]
如果想要使用chatgpt（而不是API的gpt-3），且不希望封号的话，可以尝试试用一下我新写的一个项目（还有很多API接口没有完成，配置模式与这个项目差不多）。如果想试用一下的话，可以来看下 https://github.com/SnapdragonLee/ChatGPT-weBot 。这个项目我会尽可能的开发下去，欢迎大家来贡献代码和交流，谢谢大家。

**Comment by thechen130** [comment]
> 如果想要使用chatgpt（而不是API的gpt-3），且不希望封号的话，可以尝试试用一下我新写的一个项目（还有很多API接口没有完成，配置模式与这个项目差不多）。如果想试用一下的话，可以来看下 https://github.com/SnapdragonLee/ChatGPT-weBot 。这个项目我会尽可能的开发下去，欢迎大家来贡献代码和交流，谢谢大家。

请问你这个实现的原理是什么，为什么能保证不被封号

**Comment by SnapdragonLee** [comment]
> > 如果想要使用chatgpt（而不是API的gpt-3），且不希望封号的话，可以尝试试用一下我新写的一个项目（还有很多API接口没有完成，配置模式与这个项目差不多）。如果想试用一下的话，可以来看下 https://github.com/SnapdragonLee/ChatGPT-weBot 。这个项目我会尽可能的开发下去，欢迎大家来贡献代码和交流，谢谢大家。
> 
> 请问你这个实现的原理是什么，为什么能保证不被封号

只能说，稳定运行了好久好久好久，使用的是微信官方安装包hook之后，相当于真实手动收发信息，只不过运行了个server转发了。这个应该不会被封号吧，只要不要键政、敏感话题之类的应该就没问题
