### ISSUE TITLE
win版勉强运行，但遇到了不少bug

### ISSUE THREAD

**Issue by Akashic-A** [fuergaosi233/wechat-chatgpt#593]
首先他默认chrome是x64，路径固定在c盘的一个位置，需要将chatgpt的index.js的executablePath改一改才能打开，不然会报 No chatgpt account in pool，正常运行会弹出一个浏览器，弹不出的大概都是这个原因。
接着又遇到了400，根据之前的issue，降级到1.0.1勉强可以使用，但经常出现err is SyntaxError: Unexpected non-whitespace character after JSON at position 4, account {，特别是在面对比较长的回答时。
同时还出现过403，404的报错（较少），重新运行程序时会把之前的内容一箩筐弄出来，然后显示被限流，如果删掉wechat-assistant.memory-card.json文件可以解决问题，但登录的微信号也会下线。

**Comment by RidiculousRonZzz** [comment]
请问index.js在哪里？我用的main分支里好像没有（哭

**Comment by Akashic-A** [comment]
> 

运行npm install后进入npmmodule文件夹，再进入chatgpt文件夹

**Comment by Akashic-A** [comment]
换了台电脑，这次1.0.2版本完美运行，nodejs版本是18.14.0 LTS，安装完nodejs后，进入wechat-chatgpt目录下，创建并修改好config.yaml文件，在cmd中wechat-chatgpt目录下运行npm install，将chrome浏览器安装位置移动到C:\Program Files，确保C:\Program Files\Google\Chrome\Application\chrome.exe路径能成功启动chrome，在cmd中wechat-chatgpt目录下运行npm run dev，over。
