### ISSUE TITLE
在多人发送的情况下，会出现failed to refresh auth token. TypeError: fetch failed

### ISSUE THREAD

**Issue by zfw3842415** [fuergaosi233/wechat-chatgpt#60]
![图片](https://user-images.githubusercontent.com/8286690/206414575-0c3dee5a-9a40-4c52-a7bd-37cc23519e6d.png)

**Comment by HandsomeWu6** [comment]
一般是代理的问题，挂国外的服务器基本不会遇到这个问题

**Comment by transitive-bullshit** [comment]
Please upvote https://github.com/transitive-bullshit/chatgpt-api/issues/47 if you want to add support for proxying API requests. Thanks!
