### ISSUE TITLE
no access token 是什么原因？

### ISSUE THREAD

**Issue by Eacolt** [fuergaosi233/wechat-chatgpt#601]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/15901920/218289747-0d9334a1-2246-47c7-a70d-61f3ca57cb46.png">

如上图，我已经按照要求，在yaml里填写我的账号密码和账户名称，但是依然无法npm run dev，一直报错无法启动，提示no access token， 请问是什么原因？

**Comment by spursy** [comment]
Have you solve this problem, I encounter the some issue?

**Comment by zieen** [comment]
I have the same problem, anyone know the solution?
