### ISSUE TITLE
AssertionError [ERR_ASSERTION]: 1102 == 0

### ISSUE THREAD

**Issue by diaolanshan** [fuergaosi233/wechat-chatgpt#603]
(node:32) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
uncaughtException AssertionError [ERR_ASSERTION]: 1102 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1102 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

这是什么原因啊兄弟们啊

**Comment by sseventeen** [comment]
也碰到同样问题了，想问问怎么解决的？
