### ISSUE TITLE
error 400; An error ocurred. Try refreshing your browser.新发现

### ISSUE THREAD

**Issue by dapaoxixixi** [fuergaosi233/wechat-chatgpt#607]
我发现我本来是可以用的，但是我开通chatgpt plus之后，就一直400了，为此我用另一个账号又开了一个plus，也变得不能用了报错400.有没有大佬知道怎么修改解决这个问题

I found that I was able to use it originally, but after I opened ChatGPT Plus, it kept showing an error 400. So I used another account to open another Plus, but it also became unusable and reported an error 400. Does anyone know how to solve this problem?

**Comment by dapaoxixixi** [comment]
来人啊兄弟萌

**Comment by hyne-shan** [comment]
有办法解决嘛 一样的问题

**Comment by dapaoxixixi** [comment]
救命救命help me
