### ISSUE TITLE
Error: ⚠️ No chatgpt account in pool

### ISSUE THREAD

**Issue by zoukun120** [fuergaosi233/wechat-chatgpt#608]
chatgpt账户初始化失败，该如何解决？

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --watch config.yaml --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): config.yaml
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"xxxxxxxxx@gmail.com","password":"xxxxxxxxx"}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":""}
**Try init account: xxxxxxxxx@gmail.com failed, remove it from pool**
file:///app/src/chatgpt.ts:104
throw new Error("⚠️ No chatgpt account in pool");
^
Error: ⚠️ No chatgpt account in pool
at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jianqiao0313** [comment]
+1

**Comment by SouperGeng** [comment]
+1

**Comment by wp-17** [comment]
+1

**Comment by kiga2008** [comment]
+1

**Comment by lpf19981004** [comment]
一直这样

**Comment by Zoumachuan** [comment]
可能是账号池里的账号有点多？去掉几个试试，我六个不行，四个就好了发自我的手机-------- 原始邮件 --------发件人： lpf19981004 ***@***.***>日期： 2023年2月13日周一 傍晚6:11收件人： fuergaosi233/wechat-chatgpt ***@***.***>抄送： Zoumachuan ***@***.***>, Comment ***@***.***>主    题： Re: [fuergaosi233/wechat-chatgpt] Error: ⚠️ No chatgpt account in pool (Issue #608)

一直这样

**Comment by Nafoaix** [comment]
一样，账号池里只放了一个账户，开了代理也是一样，有什么解决办法吗？

**Comment by Zoumachuan** [comment]
> 一样，账号池里只放了一个账户，开了代理也是一样，有什么解决办法吗？

那就不知道了，试试直接用API登录吧，但你做好微信概率被封号的准备

**Comment by TianHongZXY** [comment]
我也一直这样，但是我明明是可以访问外网了，而且我也加了CAPTCHA_TOKEN

**Comment by hbl8212** [comment]
> 这个东西我感觉是概率出现，我有的时候能用，有的时候用不了，但用API就没事，估计是网页端自己的问题

小白路过，API咋用呀辛苦大佬指导，小白用的教程里的railway的部署方式，不知道哪里填API key

**Comment by NidhoogJX** [comment]
我有一个猜测,我用docker部署本地以后运行处发这个报错,我以为是代理未生效,然后我本地跑了一下代码,我看到他是用模拟登陆浏览器的方式,在我的mac电脑上打开了谷歌浏览器,chatgpt加入了一个校验 verify human 需要点击一次才能进入登陆页面,是我手动点击的,所以我猜在这一步出了问题,导致登陆失败,所以解决方案很简单加入验证点击就可以,或者在带有GUI的操作系统上跑代码,出现校验按钮时手动点击,我对模拟浏览器这一块不太懂,所以没法解决这个问题,但是可以在本地运行手动点击

**Comment by NidhoogJX** [comment]
至于偶尔成功是因为没有触发校验

**Comment by TianHongZXY** [comment]
> 我有一个猜测,我用docker部署本地以后运行处发这个报错,我以为是代理未生效,然后我本地跑了一下代码,我看到他是用模拟登陆浏览器的方式,在我的mac电脑上打开了谷歌浏览器,chatgpt加入了一个校验 verify human 需要点击一次才能进入登陆页面,是我手动点击的,所以我猜在这一步出了问题,导致登陆失败,所以解决方案很简单加入验证点击就可以,或者在带有GUI的操作系统上跑代码,出现校验按钮时手动点击,我对模拟浏览器这一块不太懂,所以没法解决这个问题,但是可以在本地运行手动点击

是的，我也发现了这个问题

**Comment by liqiuh** [comment]
我在windows上是正常运行的,他会触发我的浏览器打开并且自动完成登录,我感觉他应该跟我以前使用python爬网页数据一样,是采用浏览器的模拟点击用的,但是在在centos上不行,我怀疑是打不开“浏览器”或者无法点击导致的

**Comment by casens** [comment]
> 这个东西我感觉是概率出现，我有的时候能用，有的时候用不了，但用API就没事，估计是网页端自己的问题

API 怎么用？ 请教
