### ISSUE TITLE
启动puppet超时，有没有大佬帮忙看一下

### ISSUE THREAD

**Issue by tanghongjie2** [fuergaosi233/wechat-chatgpt#609]
🤖️ Start GPT Bot Success, ready to handle message!
00:37:17 WARN WechatyPuppetMixin start() starting puppet ... timeout
00:37:17 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant)
00:38:02 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
00:38:02 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
00:38:02 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by tnwss** [comment]
我也一样

**Comment by xiaolajiyhy** [comment]
插眼
