### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by huangjiaxing** [fuergaosi233/wechat-chatgpt#610]
我现在知道有三种方式可以调用会话能力。
1. 通过chatgpt的session
2. 通过个人账户的api-key
3. openai收费的api
这三种的区别是什么，能帮忙解答下吗

**Comment by huangjiaxing** [comment]
我大概搞明白了一些，第二个和第三个是一种，只是个人账号有免费的18美元额度。  我想了解下，API调用形式，目前的模型跟ChatGPT官网差别还是很大是吗

**Comment by Zoumachuan** [comment]
> 我大概搞明白了一些，第二个和第三个是一种，只是个人账号有免费的18美元额度。 我想了解下，API调用形式，目前的模型跟ChatGPT官网差别还是很大是吗

很大，但也不是不能用
