### ISSUE TITLE
微信怎么多开 怎么用多个微信号登录

### ISSUE THREAD

**Issue by 8473136** [fuergaosi233/wechat-chatgpt#611]

**Comment by shaoao110** [comment]
安卓的话有些系统是支持的 系统设置里面可以开启应用多开，选择微信之后，相当于复制了一个微信，会在桌面生成一个新的微信图标

**Comment by pierwzw** [comment]
gta + trollstore，具体的自己谷歌

**Comment by RealTong** [comment]
如果你使用类原生安卓手机
则可以在`设置` --> `系统` --> `多用户` --> `添加用户`. 这样多个用户之间相互隔离
