### ISSUE TITLE
我看puppet-wechat的issues里说，ous协议封号了

### ISSUE THREAD

**Issue by Zoumachuan** [fuergaosi233/wechat-chatgpt#614]
https://github.com/wechaty/puppet-wechat/issues/222
这是否意味着已经获取的token也无法使用了，现在岂不是机器人被封号的概率大幅增加，而且没有有效的解决方案？
如果有，请踢我一下，谢谢！
当前的情况是：
`const bot =  WechatyBuilder.build({
  name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
  puppetOptions: {
    token: aXXXX6eef3ab42fc9e22XXX6fa0fXXXX //已打码处理
  },
  puppet: "wechaty-puppet-wechat",
});
// get a Wechaty instance
`
将以上代码添加至main.ts后，机器人运行报错
`src/main.ts(9,12): error TS2304: Cannot find name 'aXXXX6eef3ab42fc9e22XXX6fa0fXXXX'.`
不知道是不是和uos协议封号有关，还是我填写token的方式不对？印象中今年十二月份前后ous协议好像就基本用不了了
在#494里，删除
`8 puppetOptions: {
9 uos: true, // 开启uos协议
10 },
11 puppet: "wechaty-puppet-wechat",`
以上操作虽然能让puppet跑起来，但目前很多人的微信账号都因为第三方外挂被警告了。
希望有人能帮忙解答！

**Comment by Aassidusa** [comment]
同样，也有这个问题 ，第二天就提示

**Comment by RealTong** [comment]
或许使用付费的puppet可以解决.  请查看 Wechaty的文档 https://wechaty.js.org/docs/puppet-services

**Comment by joisonwk** [comment]
![image](https://user-images.githubusercontent.com/7928742/219599461-a2ef34d4-1bb4-46df-a6ad-0d99b122fa0c.png)
我用了puppet-services 里的workpro 也封号，还是一个比较老的微信号注册的企业微信，就测试了一天也没怎么发就被永久封了，当时提供这个workpro的token说了企业未认证有频率限制，我就自己发了几条信息应该不是因为频繁导致被封。是不是现在workpro也不安全了

**Comment by Zoumachuan** [comment]
已经无所谓了，我部署这玩意纯粹是为了用来降低门槛，让身边的哥们也能用上，现在我直接曲线救国，搭网页上去了

**Comment by coolshinejonson** [comment]
> 已经无所谓了，我部署这玩意纯粹是为了用来降低门槛，让身边的哥们也能用上，现在我直接曲线救国，搭网页上去了

请教网页怎么搭呀？搭的是gpt3还是chatgpt？
