### ISSUE TITLE
我这边docker运行完也没有弹二维码让我扫啊

### ISSUE THREAD

**Issue by jmiaob** [fuergaosi233/wechat-chatgpt#615]
我这边docker运行完也没有弹二维码让我扫啊

_Originally posted by @wly1456839489 in https://github.com/fuergaosi233/wechat-chatgpt/issues/604#issuecomment-1427241905_
            打印docker日志 二维码在里面

**Comment by chansanya** [comment]
扫了之后也没反应啊，完整的体验是怎么样的呢

**Comment by jmiaob** [comment]
日志会打印扫码成功

**Comment by lusains** [comment]
![image](https://user-images.githubusercontent.com/7510547/220516650-6b114e9f-f908-4134-80cc-a91a4d4e053a.png)
没有出现二维码链接。

**Comment by shaojs321** [comment]
> ![image](https://user-images.githubusercontent.com/7510547/220516650-6b114e9f-f908-4134-80cc-a91a4d4e053a.png) 没有出现二维码链接。

同样问题  有人解决了吗
