### ISSUE TITLE
服务器布置到底行不行呀！

### ISSUE THREAD

**Issue by qiye7766** [fuergaosi233/wechat-chatgpt#620]
邮箱账号，密码也给了，api也给了，就是池子没有账户，还一直报错

**Comment by waholulu** [comment]
+1

**Comment by sxiao3** [comment]
+1

**Comment by JerryGaoYJ** [comment]
+1

**Comment by 1iang** [comment]
+1

**Comment by pierwzw** [comment]
节点问题，首先确保官网能登上

**Comment by linkkzhzh** [comment]
同疑问：
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"linlinjkl@qq.com","password":"*********","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}

国内服务器  卡在这里  后面也是提示 池子里没有账号   只能国外服务搭建才行吗？

**Comment by dyaxjwv-leedon** [comment]
> 同疑问： Start GPT Bot Config is：{“chatGPTAccountPool”：[{“email”：“[linlinjkl@qq.com](mailto:linlinjkl@qq.com)”，“password”：“*********”，“isGoogleLogin”：false}]，“chatGptRetryTimes”：3，“chatPrivateTiggerKeyword”：“”，“openAIProxy”：“”}
> 
> 国内服务器 卡在这里 后面也是提示 池子里没有账号 只能国外服务搭建才行吗？

我用新加坡的站点也一样提示。。。

**Comment by lusains** [comment]
我用国外vps也是一样的。
![image](https://user-images.githubusercontent.com/7510547/220517017-2dfecfb0-6111-4f40-9034-10ae5e1cf218.png)

**Comment by liqiuh** [comment]
并不是节点问题，我怀疑是chatgpt.ts中， 浏览器唤醒得问题，在无gui页面得时候，没办法正常使用。

```
import { ChatGPTAPI, ChatGPTAPIBrowser } from "chatgpt";
```

我尝试安装过相关得浏览器组件，好像还是失败得。
// ubuntu
sudo apt-get install chromium-browser
sudo apt-get install  ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

**Comment by xinrzhan** [comment]
应该是cf报错不让登录，咋绕过cf啊
