### ISSUE TITLE
出二维码了但是扫码之后报错Timeout

### ISSUE THREAD

**Issue by ezopir96** [fuergaosi233/wechat-chatgpt#621]
有和我一样问题的吗，用代理也一样

**Comment by Jasmine-drs** [comment]
我看别人的视频说的好像是，二维码过期时间是五秒钟，但是微信扫码之后也要等五秒钟时间才能确认，所以貌似需要拼手速，一直点确认运气好就进去了，不知道你是不是这个问题

**Comment by ezopir96** [comment]
> 我看别人的视频说的好像是，二维码过期时间是五秒钟，但是微信扫码之后也要等五秒钟时间才能确认，所以貌似需要拼手速，一直点确认运气好就进去了，不知道你是不是这个问题

最新发现好像不是，登录貌似是成功的，一收到消息就超时崩溃了不知道是不是代理有问题
