### ISSUE TITLE
重启后会把之前所有问题回答一遍，导致触发限流

### ISSUE THREAD

**Issue by gaoobin** [fuergaosi233/wechat-chatgpt#624]
重启服务后会把用户之前问过的所有问题都再回答一遍，这个怎么解决，缓存数据存在哪里？这个还导致短时间内问了大量的问题，触发了限流，服务没法正常使用

**Comment by gaoobin** [comment]
我加了几行代码解决了，启动后30s内收到消息不回复。
![image](https://user-images.githubusercontent.com/3434892/218702040-b7af1fca-f47a-4c45-8929-b6bd75303adb.png)

**Comment by JerryGaoYJ** [comment]
The problem is solved, thank you！
