### ISSUE TITLE
railway部署登录成功后发信息提示"That model does not exist"

### ISSUE THREAD

**Issue by xingxin666** [fuergaosi233/wechat-chatgpt#626]
![image](https://user-images.githubusercontent.com/29698324/218706276-18bcf011-98f1-4569-80c0-984f4ebadd8e.png)
railway部署登录成功后发信息提示"That model does not exist"

model: 'text-chat-davinci-002-20230126',

怎么修改railway中的node_modules/chatgpt/build/index.js模型为text-davinci-003

**Comment by TianHongZXY** [comment]
你好，请问你是怎么用railway部署成功的？ 我填了帐号密码以及2captcha api token，但总是失败
<img width="504" alt="图片" src="https://user-images.githubusercontent.com/39355004/218801976-93c65d72-8522-435a-9432-fcffe2a151ab.png">

**Comment by xingxin666** [comment]
> 你好，请问你是怎么用railway部署成功的？ 我填了帐号密码以及2captcha api token，但总是失败 <img alt="图片" width="504" src="https://user-images.githubusercontent.com/39355004/218801976-93c65d72-8522-435a-9432-fcffe2a151ab.png">
![image](https://user-images.githubusercontent.com/29698324/218912883-b4414c06-085a-4517-89af-37a54cda162a.png)
![image](https://user-images.githubusercontent.com/29698324/218913070-3b0aa9dd-85a2-42d8-83ee-cdeaa1f6c00f.png)
我用的分支new-wechatgpt，只需要一个参数OPENAI_API_KEY就可以部署成功的，不需要账号密码
main分支没部署成功

**Comment by xingxin666** [comment]
问题已解决，我把我fork的代码package.json升级chatgpt版本就好了，"chatgpt": "^4.4.0"
![image](https://user-images.githubusercontent.com/29698324/218914011-291835ac-8ea7-4d53-b7f6-b3ba1b65fd36.png)

**Comment by 1iang** [comment]
> 问题已解决，我把我fork的代码package.json升级chatgpt版本就好了，"chatgpt": "^4.4.0" ![image](https://user-images.githubusercontent.com/29698324/218914011-291835ac-8ea7-4d53-b7f6-b3ba1b65fd36.png)

感谢大佬，用你的方法跑通了

**Comment by 2465622629** [comment]
> 问题已解决，我把我fork的代码package.json升级chatgpt版本就好了，"chatgpt": "^4.4.0" ![image](https://user-images.githubusercontent.com/29698324/218914011-291835ac-8ea7-4d53-b7f6-b3ba1b65fd36.png)

谢谢大佬提供的代码，我用你的方法也跑通了，但是上下文出现问题了不知道是原本就有的bug还是什么 看能帮忙解决下不
![20230217125219](https://user-images.githubusercontent.com/63027241/219552530-5473cb14-885f-4115-bf31-4730bba46445.png)
![20230217125301](https://user-images.githubusercontent.com/63027241/219552542-7584ff8a-37b3-4ce8-8384-4feb62d36cac.png)

**Comment by 2465622629** [comment]
> 问题已解决，我把我fork的代码package.json升级chatgpt版本就好了，"chatgpt": "^4.4.0" ![image](https://user-images.githubusercontent.com/29698324/218914011-291835ac-8ea7-4d53-b7f6-b3ba1b65fd36.png)

谢谢大佬提供的代码，我用你的方法也跑通了，但是上下文出现问题了不知道是原本就有的bug还是什么看能帮忙解决下不
![20230217125301](https://user-images.githubusercontent.com/63027241/219552542-7584ff8a-37b3-4ce8-8384-4feb62d36cac.png)
![20230217125219](https://user-images.githubusercontent.com/63027241/219552530-5473cb14-885f-4115-bf31-4730bba46445.png)

**Comment by sx565355044** [comment]
> > 你好，请问你是怎么用railway部署成功的？ 我填了帐号密码以及2captcha api token，但总是失败 <img alt="图片" width="504" src="https://user-images.githubusercontent.com/39355004/218801976-93c65d72-8522-435a-9432-fcffe2a151ab.png">
> > ![image](https://user-images.githubusercontent.com/29698324/218912883-b4414c06-085a-4517-89af-37a54cda162a.png)
> > ![image](https://user-images.githubusercontent.com/29698324/218913070-3b0aa9dd-85a2-42d8-83ee-cdeaa1f6c00f.png)
> > 我用的分支new-wechatgpt，只需要一个参数OPENAI_API_KEY就可以部署成功的，不需要账号密码
> > main分支没部署成功

railway 怎么部署分支呀？不是很懂
