### ISSUE TITLE
railway 部署失败，给账号密码 都登录不了

### ISSUE THREAD

**Issue by Topi9999** [fuergaosi233/wechat-chatgpt#627]
![image](https://user-images.githubusercontent.com/38421083/218755009-40e568d4-257d-41f7-8add-9fda435aa522.png)

**Comment by NaerDD** [comment]
一样的啊

**Comment by Topi9999** [comment]
没人解决的库= =感觉傻了，暴露密码。。

**Comment by Topi9999** [comment]
还是没人，唉。。

**Comment by ATMDXGS** [comment]
railway还能用吗

**Comment by Topi9999** [comment]
作者都不回复的问题。。无语 直接管了。

**Comment by fuergaosi233** [comment]
最新版应该没有问题🤔 之前的问题我记得修复了
