### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by ohmytime** [fuergaosi233/wechat-chatgpt#63]
代码克隆到本地后,执行
`docker run -v -it $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest`
然后就提示这个错误

**Comment by vincent-vinf** [comment]
应该是文档写错了，改为如下命令
```
docker run -it -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
```
-v 指定挂载点

**Comment by ohmytime** [comment]
使用新的文档就可以了,但是还有下面的问题
机器: MacBook Air M1

<img width="1036" alt="图片" src="https://user-images.githubusercontent.com/490477/206449428-12c193e3-d728-4f6d-97d2-986c059ec790.png">

**Comment by ohmytime** [comment]
对这个环境完全不熟悉,之前没接触过, 
我跑起来之后,只是显示一个命令行,怎么没有UI界面?

<img width="1085" alt="图片" src="https://user-images.githubusercontent.com/490477/206451623-ce2fe070-a383-463f-a35f-551258896172.png">

**Comment by OliverGrace** [comment]
> 对这个环境完全不熟悉,之前没接触过, 我跑起来之后,只是显示一个命令行,怎么没有UI界面?
> 
> <img alt="图片" width="1085" src="https://user-images.githubusercontent.com/490477/206451623-ce2fe070-a383-463f-a35f-551258896172.png">

@ohmytime 用微信扫码登录就行了

**Comment by ohmytime** [comment]
> > 对这个环境完全不熟悉,之前没接触过, 我跑起来之后,只是显示一个命令行,怎么没有UI界面?
> > <img alt="图片" width="1085" src="https://user-images.githubusercontent.com/490477/206451623-ce2fe070-a383-463f-a35f-551258896172.png">
> 
> @ohmytime 用微信扫码登录就行了

扫码登录之后呢，别人@我就行了？

**Comment by ohmytime** [comment]
的确是这样，貌似没有 登录成功 。

**Comment by fuergaosi233** [comment]
> > > 对这个环境完全不熟悉,之前没接触过, 我跑起来之后,只是显示一个命令行,怎么没有UI界面?
> 
> > > <img alt="图片" width="1085" src="https://user-images.githubusercontent.com/490477/206451623-ce2fe070-a383-463f-a35f-551258896172.png">
> 
> > 
> 
> > @ohmytime 用微信扫码登录就行了
> 
> 
> 
> 扫码登录之后呢，别人@我就行了？
> 
> 

Yes

**Comment by ohmytime** [comment]
Error: ChatGPT failed to refresh auth token. Error: Unauthorized
我明明已经填写了用户名和密码了啊，别人@我怎么 出现 这个错误

**Comment by ohmytime** [comment]
使用 - session_token 搞定 了

**Comment by ohmytime** [comment]
有时候会显示：Error: ChatGPTAPI error 500

**Comment by fuergaosi233** [comment]
> 有时候会显示：Error: ChatGPTAPI error 500

I will add retry.
