### ISSUE TITLE
微信一直反馈429 error code，网页版访问账号没问题啊

### ISSUE THREAD

**Issue by totao** [fuergaosi233/wechat-chatgpt#630]
有其他的设置需要改？

**Comment by JerryGaoYJ** [comment]
err is ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
我也遇到同样的问题

**Comment by lonely1215225** [comment]
那是说你openai账号没钱了

**Comment by JerryGaoYJ** [comment]
我用的text-davinci-003模型也收费吗？如果收费的话，那怎么配置免费版的呢

**Comment by Zoumachuan** [comment]
> 我用的text-davinci-003模型也收费吗？如果收费的话，那怎么配置免费版的呢

收费的，免费的是网页版，直接配置账号密码而非API那种

**Comment by AlphaCharry** [comment]
免费的反爬虫了全球没人能破解openai的反爬虫，429 就是 没钱了，只能付钱用

**Comment by RealTong** [comment]
> 我用的text-davinci-003模型也收费吗？如果收费的话，那怎么配置免费版的呢

这个模型是泄露的模型, 已经在当天失效了, 强行使用会报错404.

README的教程就是免费版的教程

**Comment by JerryGaoYJ** [comment]
> 免费的反爬虫了全球没人能破解openai的反爬虫，429 就是 没钱了，只能付钱用

可以破解的，只是国内代理的问题不好处理，最好用国外的服务器

**Comment by AlphaCharry** [comment]
楼上真的一本正经的胡说八道，连openai的官方文档估计都没看 就张口就来说 text-davinci-003 是泄露模型，建议睁大眼睛看看官方文档提供的 可用api 模型

**Comment by AlphaCharry** [comment]
> 

要什么 代理 ？？？我就是没用任何代理和vpn 挂的官网 chatGPT  直接内地访问。。。

**Comment by AlphaCharry** [comment]
![无代理](https://user-images.githubusercontent.com/38164385/220009129-ba0b2d6e-f219-4604-8ab5-61813d168354.gif)
