### ISSUE TITLE
WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by Jay-Z-zhang** [fuergaosi233/wechat-chatgpt#631]
06:33:49 WARN WechatyPuppetMixin start() starting puppet ... timeout
06:33:49 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
06:34:34 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
06:34:34 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
06:34:34 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

pls, i can't find any way to fix it 
求助

**Comment by RealTong** [comment]
Please check your network settings, please use a network other than mainland China, Hong Kong, and check if your DNS is configured correctly
