### ISSUE TITLE
有没有大佬知道这个error21是啥啊，什么文件权限没给？我用过sudo su了

### ISSUE THREAD

**Issue by zxy1124** [fuergaosi233/wechat-chatgpt#632]
<img width="745" alt="bug" src="https://user-images.githubusercontent.com/80298189/219039453-4285e64c-0d1e-45a7-9f87-40c000f1ba66.png">

**Comment by NidhoogJX** [comment]
我刚刚遇到了,config.yaml 名字打错了多了一个点 你检查一下config.yaml文件

**Comment by fuergaosi233** [comment]
检查下文件读写
