### ISSUE TITLE
isGoogleLogin":false

### ISSUE THREAD

**Issue by AlexLi03** [fuergaosi233/wechat-chatgpt#634]
我已经检查很多次了,为什么一直这样

**Comment by AlexLi03** [comment]
err is ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
, account {"email":"lexli03","password":","isGoogleLogin":false}

账号和密码检查很多了,也重新弄注册过

**Comment by RealTong** [comment]
`That model does not exist` 模型不存在

请问你使用的是哪个版本?
