### ISSUE TITLE
通过API的形式调用，会遇到429的问题吗

### ISSUE THREAD

**Issue by huangjiaxing** [fuergaosi233/wechat-chatgpt#635]
RT，请教一下

**Comment by fuergaosi233** [comment]
麻烦仔细描述一下问题？

**Comment by huangjiaxing** [comment]
> 麻烦仔细描述一下问题？

嗯嗯，这个不是问题，就是想了解一下。因为目前不是浏览器模式嘛，然后我想着如果限流了，可以降级到API调用模式。 但我不确定API模式遇到OpenAI返回429限流的情况多不多

**Comment by AlphaCharry** [comment]
只要key钱充足就很少429
