### ISSUE TITLE
有没有qq或者微信交流群

### ISSUE THREAD

**Issue by drttcrh** [fuergaosi233/wechat-chatgpt#636]
# 有没有qq或者微信交流群

**Comment by RealTong** [comment]
目前没有QQ或微信的交流群.

不过你可以加入 [Discord](https://discord.com/invite/8fXNrxwUJH) 交流群

**Comment by drttcrh** [comment]
> 目前没有QQ或微信的交流群.
> 
> 不过你可以加入 [Discord](https://discord.com/invite/8fXNrxwUJH) 交流群

好的
