### ISSUE TITLE
部分微信账号登陆会出现以下error

### ISSUE THREAD

**Issue by wulabing** [fuergaosi233/wechat-chatgpt#64]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by fuergaosi233** [comment]
I think you need real name authentication 🤔, Could you try to log in on the WeChat web via this account?

**Comment by wulabing** [comment]
这个号确实没实名，我去试试看
