### ISSUE TITLE
No chatgpt account in pool 国内服务器的原因吗？

### ISSUE THREAD

**Issue by linkkzhzh** [fuergaosi233/wechat-chatgpt#640]
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Start GPT Bot Config is:{"chatGPTAccountPool":[{"email":"****@qq.com","password":"******","isGoogleLogin":false}],"chatGptRetryTimes":3,"chatPrivateTiggerKeyword":"","openAIProxy":""}
Try init account: ****@qq.com failed, remove it from pool
file:///app/src/chatgpt.ts:104
      throw new Error("⚠️ No chatgpt account in pool");
            ^
Error: ⚠️ No chatgpt account in pool
    at ChatGPTPool.startPools (file:///app/src/chatgpt.ts:104:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTBot.startGPTBot (file:///app/src/bot.ts:41:5)
    at async main (file:///app/src/main.ts:16:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by huangjiaxing** [comment]
Try init account: ****@qq.com failed
你先试试看这个账号能不能登录上

**Comment by lidp280504357** [comment]
是的 我也遇到了这个问题  网页上是没有问题 可以登陆  但是npm run dev运行后 就出现无法初始化
![image](https://user-images.githubusercontent.com/43174359/219854724-44ca295c-f7a5-4161-8261-36ac62139c78.png)

**Comment by linkkzhzh** [comment]
> 尝试初始化帐户： ****@qq.com 失败 你先试试看这个账号能不能登录上

可以登录  这个账号从头到尾 申请 注册  都是自己操作的

**Comment by linkkzhzh** [comment]
> > （节点：54）实验性警告：自定义 ESM 加载程序是一项实验性功能，可能随时更改（用于显示警告的创建位置） 启动 GPT 机器人配置是：{“chatGPTAccountPool”：[{“email”：“@qq.com”，“password”：“**”，“isGoogleLogin”：false}]，“chatGptRetryTimes”：3，“chatPrivateTiggerKeyword”：“”，“openAIProxy”：“”} 尝试初始化帐户：********@qq.com**** 失败，将其从池中删除 file:///app/src/chatgpt.ts:104 抛出新的错误（”`node --trace-warnings ...`⚠️池中没有聊天帐户“）;^错误：⚠️在 ChatGPTPool.startPools （file:///app/src/chatgpt.ts:104:13） at processTicksAndRejections （node：internal/process/task_queues：95：5） at async ChatGPTBot.startGPTBot （file:///app/src/bot.ts:41:5） at async main （file:///app/src/main.ts:16:3） 的池中没有chatgpt帐户 [nodemon] 应用程序崩溃 - 在开始之前等待文件更改...
> 
> 请问解决了吗 我也是这样 自己本机部署的 要不要在配置中写代理的端口？ 要不要写 127.0.0.1:7890？ 我试了写不写都是`“”openAIProxy: ""`⚠️pool 中没有 chatgpt 帐户 我网页端是能登上的，账号密码都是正确的，但是程序登不上

在容器里写了 clash 代理 还是不行  目前只能先放弃了
