### ISSUE TITLE
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by pm0725** [fuergaosi233/wechat-chatgpt#641]
手机扫码后错误代码：
  at Object.equal (/root/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /root/wechat-chatgpt/node_modules/wechat4u/src/core.js:194:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/root/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /root/wechat-chatgpt/node_modules/wechat4u/src/core.js:194:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'

**Comment by fuergaosi233** [comment]
检查下能否在  Wechat web 端登录

**Comment by lzynb** [comment]
可以登入,请问应该如何解决

**Comment by lzynb** [comment]
应该是微信没有实名认证所以不行
