### ISSUE TITLE
增加几点修改意见

### ISSUE THREAD

**Issue by AlexLi03** [fuergaosi233/wechat-chatgpt#642]
1、长出现几个问题合并在一起回复.
2、增加分段显示.
3、回复的内容,在某些提问环节,字数多点,全面一点.
4、增加企业微信扫码.
5、增加ai绘画功能.

**Comment by lkyuier** [comment]
ai 绘画功能是另外一个接口来着

**Comment by fuergaosi233** [comment]
1. 这个有 Case 么
2. 目前多字数就是分段了
3. 这个取决于 OpenAI
4. 企业微信的 Bot 是收费的
5. 这个需要 APIkey 的设置， 对这个项目来说不合适

**Comment by PowerChina** [comment]
非常赞同，有同样的建议。

1. 私聊过程中，提第二个问题时会把第一个问题又重复回答了。比如第一个问题是今天天气怎么样，第二个问题是推荐一个周末去的餐厅。多个问题时也会如此。
2. 多字数如何设置？默认字数比较少是出于什么考虑？@fuergaosi233 

thanks！

**Comment by fuergaosi233** [comment]
> 非常赞同，有同样的建议。
> 
> 1. 私聊过程中，提第二个问题时会把第一个问题又重复回答了。比如第一个问题是今天天气怎么样，第二个问题是推荐一个周末去的餐厅。多个问题时也会如此。
> 2. 多字数如何设置？默认字数比较少是出于什么考虑？@fuergaosi233
> 
> thanks！

1. 这个问题我仍然不理解
2. 默认字数少是因为我不知道微信的单条消息分段，所以当消息较多以后就会自动给分段，分成多条消息进行发送

**Comment by PowerChina** [comment]
> 1. 这个问题我仍然不理解
> 2. 默认字数少是因为我不知道微信的单条消息分段，所以当消息较多以后就会自动给分段，分成多条消息进行发送

1. 比如说我微信私信机器人，第一个问题是今天天气怎么样，机器人回答”晴朗“，第二个问题是推荐一家周末去的餐厅，机器人回答会”晴朗，香格里拉饭店“，回答把第一个问题的答案也带上，问第三个、第四个问题也可能把第一个问题的回答带上，依次类推。下图中prompt可以看到会将所有的历史问题都带上。

2. 如下图日志所示，用户发prompt时，自带了简化回答的要求，所以回答较为简短，如何去掉这个简化回答的要求？

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/7401220/219942837-a1f13495-7413-455f-a842-ce48ba754fc9.png">

@fuergaosi233 @RealTong
