### ISSUE TITLE
在返回微信登陆二维码时，报错uncaughtException GError

### ISSUE THREAD

**Issue by KillZero12138** [fuergaosi233/wechat-chatgpt#644]
![9131d5d27b36df58c681cc90bcff2ee](https://user-images.githubusercontent.com/112448787/219864519-e3bbb4f5-a77d-48bf-be90-ec38b8299353.png)

**Comment by fuergaosi233** [comment]
检查下 DNS 配置了， 这个和本项目无关， 我怀疑是你容器里面网络配置有点问题
