### ISSUE TITLE
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by tombarbar** [fuergaosi233/wechat-chatgpt#647]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/root/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /root/wechat-chatgpt/node_modules/wechat4u/src/core.js:194:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/root/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /root/wechat-chatgpt/node_modules/wechat4u/src/core.js:194:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}这个是什么意思啊 大佬们  换了几个服务器都是这个错误

**Comment by drttcrh** [comment]
我之前可以扫码登录成功，发现日子报错后重启，也出现了相同的错误，猜测是被微信封了，或者是微信没有实名绑卡不让登录。希望提示可以优化一下，不然都不知道啥错误
