### ISSUE TITLE
一个多轮对话的修改意见，一个简化答案的疑问

### ISSUE THREAD

**Issue by PowerChina** [fuergaosi233/wechat-chatgpt#650]
1. 多轮对话理解需要优化：比如说我微信私信机器人，第一个问题是今天天气怎么样，机器人回答”晴朗“，第二个问题是推荐一家周末去的餐厅，机器人回答会”晴朗，香格里拉饭店“，回答把第一个问题的答案也带上，问第三个、第四个问题也可能把第一个问题的回答带上，依次类推。下图中prompt可以看到会将所有的历史问题都带上。

2. 如下图日志所示，用户发prompt时，自带了简化回答的要求，所以回答较为简短，如何去掉这个简化回答的要求？

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/7401220/219942837-a1f13495-7413-455f-a842-ce48ba754fc9.png">

_Originally posted by @PowerChina in https://github.com/fuergaosi233/wechat-chatgpt/issues/642#issuecomment-1435968278_

**Comment by JerryGaoYJ** [comment]
我遇到了同样的问题+1

**Comment by AlphaCharry** [comment]
加个AI： human ： 不就行了

**Comment by fuergaosi233** [comment]
你是不是发错地方了🤔

**Comment by PowerChina** [comment]
找到文件修改位置了，已经解决了
