### ISSUE TITLE
接入微信后，多人同时发送消息，OpenAI服务器限流，请稍后再试

### ISSUE THREAD

**Issue by Jedeiah** [fuergaosi233/wechat-chatgpt#653]
多个人同时和chatgpt聊天，就会出现429，请问能否加一个排队等候发消息的功能或者通过其他方式解决该问题？

**Comment by maooson** [comment]
可以试下[ChatGPT for Wechat](https://aow.me)用Chrome浏览器插件的方案，支持多群、多人同时提问，消息进队列有序回答。
fuergaosi233大佬的方案也很棒，最早用过，特此感谢！！！
