### ISSUE TITLE
充值了2captcha,还是出现 No chatgpt account in pool

### ISSUE THREAD

**Issue by lkyuier** [fuergaosi233/wechat-chatgpt#662]
已经充值了2captcha了，但是还是出现了No chatgpt account in pool 的错误，2captcha 上也没有扣钱，请问是什么原因
![image](https://user-images.githubusercontent.com/48005813/221103726-19afdd74-0664-4eee-a77a-7df6bc71b732.png)

**Comment by moeik** [comment]
No chatgpt account in pool 关2captcha什么事。。账户池没有添加账户么

**Comment by moeik** [comment]
> 

这个是bug 复现了。。。
