### ISSUE TITLE
请问captcha_token 是不是2captcha中的api key ？

### ISSUE THREAD

**Issue by casens** [fuergaosi233/wechat-chatgpt#666]
请问captcha_token 是不是2captcha中的api key ？

**Comment by yqty** [comment]
同问，api key填哪里啊，克隆后提示401错误

**Comment by casens** [comment]
> 自问自答
[yj20230101](https://github.com/yj20230101) commented [2 weeks ago](https://github.com/fuergaosi233/wechat-chatgpt/issues/494#issuecomment-1422021515)
我找到 我的原因了~ 还是网络问题 服务器宿主机是代理了，但docker容器内的网络是不通的，你可以进入容器curl [www.google.com.hk](http://www.google.com.hk/) 是不行的。 所以这里要配置一下， [参考官方文档](https://docs.docker.com/network/proxy/#configure-the-docker-client) 简单来说就是在 ~根目录下 新建文件夹.docker，再里面加一个config.json，内容为，

注意里面的ip为docker的网络地址docker的网络地址，127.0.0.1.7890<宿主机配的>是不通的（我用的clash端口7890）

{ "proxies": { "default": { "httpProxy": "http://172.12.0.1:7890/", "httpsProxy": "http://172.12.0.1:7890/", "noProxy": "*.test.example.com,.example2.com,127.0.0.0/8" } } } 网络问题解决后，再进行其他...（还有python环境记得安装）

使用人工在线验证，注册充钱$3起 用一次$0.01。[https://2captcha.com/，](https://2captcha.com/%EF%BC%8C)
注册后个人中心拿到key，然后在docker启动的时候带上 -e CAPTCHA_TOKEN="你的key"
docker run -e CAPTCHA_TOKEN="你的key" -d --name 2333 -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest

命令执行的时候，要在你配置config.yaml的路径下哦。

启动后查看日记，会报错啥的，进入容器，直接删除src/main.ts文件中第8-11行
docker logs -f wechat-chatgpt

看楼主的第二点要重新build的，无从下手，感觉还是重新拉了一个并没什么变化??。我就试试重启docker 再启动容器，可能就行了。（我好像就是这么弄来着，突然就行了）
systemctl restart docker, 还有一个重启配置dameon? 也可以弄下...
