### ISSUE TITLE
chatPrivateTiggerKeyword seems not work

### ISSUE THREAD

**Issue by distance295** [fuergaosi233/wechat-chatgpt#672]
chatGPTAccountPool:
  - email: xx
    password: xx
    isGoogleLogin: true
chatPrivateTiggerKeyword: "$$"
openAIProxy: ""

this config and appear like this

User Contact<中国人不卷中国人> logged in
Message: Message#Text[🗣Contact<Coder>]	111
🎯 Triggered ChatGPT: 111
Message: Message#Text[🗣Contact<中国人不卷中国人>]	I'm sorry, but I'm not sure what you mean by "111." Could you please p
Message: Message#Text[🗣Contact<Coder>]	$$111
🎯 Triggered ChatGPT: $$111
Message: Message#Text[🗣Contact<中国人不卷中国人>]	I apologize, but I'm still not sure what you mean by "$$111." The symb

@fuergaosi233

**Comment by RealTong** [comment]
Solved.
