### ISSUE TITLE
Official API?

### ISSUE THREAD

**Issue by acheong08** [fuergaosi233/wechat-chatgpt#679]
https://platform.openai.com/docs/api-reference/chat/create

https://github.com/transitive-bullshit/chatgpt-api#usage

**Comment by RealTong** [comment]
在 `https://github.com/fuergaosi233/wechat-chatgpt/tree/chatapi-api` 分支已经支持

**Comment by RealTong** [comment]
不对, 好像有问题

**Comment by RealTong** [comment]
好了
