### ISSUE TITLE
3个账号均正常登录，用的是国外的服务器，dmeo都跑不起来

### ISSUE THREAD

**Issue by clearcodecn** [fuergaosi233/wechat-chatgpt#686]
![image](https://user-images.githubusercontent.com/34591322/222967839-86701072-9b64-4377-b788-33e3021468d0.png)

，Error: ⚠️ No chatgpt account in pool

**Comment by JinhuW** [comment]
我也遇到一样的问题

**Comment by RealTong** [comment]
试试 `https://github.com/fuergaosi233/wechat-chatgpt/tree/chatgpt-api` 这个分支吧, 使用chatgpt-turbo api

**Comment by LYC941031** [comment]
> 我也遇到一样的问题

升级一下node 到v18就行了
