### ISSUE TITLE
docker内部网络问题一直无法解决，各位大大们进来指点下把

### ISSUE THREAD

**Issue by hailouweb** [fuergaosi233/wechat-chatgpt#688]
尝试过的方法:
方法1：docker run -d --name wechat-chatgpt --network host -e http_proxy=http://127.0.0.1:7890 -e https_proxy=http://127.0.0.1:7890 -e CAPTCHA_TOKEN="XXXXX" -v $(pwd)/config.yaml:/app/config.yaml holegots/wechat-chatgpt:latest
方法2：在这里通过官方网站设置服务代理~/.docker/config.json
方法3：配置clash代理  配置后直接无法访问网络  ping百度可以
懵逼中。。。。。

**Comment by wojiaobadaye** [comment]
你好，我也是用的clash，错误显示是超时，但我可以用谷歌，不知道怎么办

**Comment by hailouweb** [comment]
> 你好，我也是用的clash，错误显示是超时，但我可以用谷歌，不知道怎么办
超时，是账号池超时嘛？可以用谷歌是哪里 docker内还是外面

**Comment by wojiaobadaye** [comment]
> > 你好，我也是用的clash，错误显示是超时，但我可以用谷歌，不知道怎么办
> > 超时，是账号池超时嘛？可以用谷歌是哪里 docker内还是外面

![image](https://user-images.githubusercontent.com/20962914/224490946-90b71148-658e-4c50-a81c-b3496d6905c9.png)
你好，这是我的报错截图，docker外面可以连到谷歌，启动镜像也能看到有流量被代理出去了，但是报错就是超时

**Comment by RealTong** [comment]
更新以下镜像版本吧, 1.0.3有重大更改, 更稳定了, 更容易部署

**Comment by wojiaobadaye** [comment]
> 更新以下镜像版本吧, 1.0.3有重大更改, 更稳定了, 更容易部署

好的，谢谢大佬，我再去试一试

**Comment by hailouweb** [comment]
> > 更新以下镜像版本吧, 1.0.3有重大更改, 更稳定了, 更容易部署
> 
> 好的，谢谢大佬，我再去试一试

你的clash怎么弄得  为什么我配的就连不了网呢，我是按clash官方配置文档配的，配完curl就不行了 但是ping就可以 很奇怪，docke内还是外斗连不了谷歌

**Comment by wojiaobadaye** [comment]
> > > 更新以下镜像版本吧, 1.0.3有重大更改, 更稳定了, 更容易部署
> > 
> > 
> > 好的，谢谢大佬，我再去试一试
> 
> 你的clash怎么弄得 为什么我配的就连不了网呢，我是按clash官方配置文档配的，配完curl就不行了 但是ping就可以 很奇怪，docke内还是外斗连不了谷歌

ping 可以是因为ping 走的不是http协议。我换了另外一个项目，python那个，这个我再没有试过了不好意思
