### ISSUE TITLE
报错,长时间不使用的原因吗？

### ISSUE THREAD

**Issue by Klearcc** [fuergaosi233/wechat-chatgpt#70]
13:46:57 WARN PuppetWatchdogAgent start() reset() reason: {"data":"syncCheck()","timeoutMilliseconds":60000}
uncaughtException GError: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"syncCheck()","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///app/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by fuergaosi233** [comment]
I have the same problem that I'm trying to fix. It was caused by Wechaty.

**Comment by ilydybee9015** [comment]
I have encountered the same problem. Is there any way to avoid it?

**Comment by owwkmidream** [comment]
我的部署不到几分钟很快就会报这个错误

**Comment by zimplexing** [comment]
I encounter this error as well.

**Comment by zimplexing** [comment]
https://github.com/wechaty/wechaty/issues/2320

**Comment by kolamanlee** [comment]
同样問題，怎样延长时間

**Comment by corgy-w** [comment]
> 我的部署不到几分钟很快就会报这个错误

解决了吗

**Comment by Yy2z** [comment]
同问

**Comment by keepondream** [comment]
同问
