### ISSUE TITLE
使用Railway部署成功后，机器人收到消息后报错 TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by linxp001** [fuergaosi233/wechat-chatgpt#700]
User Contact<ChatGPT> logged in
﻿🎯 Fri Mar 10 2023 17:05:35 GMT+0000 (Coordinated Universal Time) Message: Message#Unknown[🗣Contact<ChatGPT>]
﻿🎯 Fri Mar 10 2023 17:05:35 GMT+0000 (Coordinated Universal Time) Message: Message#Unknown[🗣Contact<ChatGPT>]
﻿🎯 Fri Mar 10 2023 17:05:49 GMT+0000 (Coordinated Universal Time) Message: Message#Text[🗣Contact<林小朋>]	who are you
﻿🎯 Triggered ChatGPT: who are you
﻿TypeError: Cannot read properties of undefined (reading '0')
﻿at file:///app/src/chatgpt.ts:25:35
﻿at processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿at async ChatGPTBot.getGPTMessage (file:///app/src/bot.ts:68:12)
﻿at async ChatGPTBot.onPrivateMessage (file:///app/src/bot.ts:129:24)
﻿at async ChatGPTBot.onMessage (file:///app/src/bot.ts:155:16)
﻿at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by RealTong** [comment]
Hi, 可以试试新的Railway部署方式

**Comment by laihuamin** [comment]
我是最新部署的，也报这个错

**Comment by linxp001** [comment]
我部署最新版好使了。。。

**Comment by laihuamin** [comment]
就重新部署一下就可以了？那我试试看呢

**Comment by laihuamin** [comment]
Triggered ChatGPT: 你是谁呀
TypeError: Cannot read properties of undefined (reading '0')
at file:///app/src/chatgpt.ts:25:35
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ChatGPTBot.getGPTMessage (file:///app/src/bot.ts:68:12)
at async ChatGPTBot.onPrivateMessage (file:///app/src/bot.ts:129:24)
at async ChatGPTBot.onMessage (file:///app/src/bot.ts:155:16)
at async WechatyImpl.<anonymous> (file:///app/src/main.ts:32:9)

**Comment by laihuamin** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/28126886/224494402-2a6bba0a-059f-4db8-879c-637b3b846812.png">
