### ISSUE TITLE
docker pull fuergaosi/wechat-chatgpt:latest 报错啊

### ISSUE THREAD

**Issue by cvwet** [fuergaosi233/wechat-chatgpt#701]
Error response from daemon: pull access denied for fuergaosi/wechat-chatgpt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by cvwet** [comment]
使用第二种docker compose，运行也是有错：
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
⚠️ Bot start failed, can you log in through wechat on the web?: Error: no payload, please call load() first.
[nodemon] clean exit - waiting for changes before restart
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start

**Comment by aoruLola** [comment]
docker login也不行，仓库似乎不见了，docker hub找不到

**Comment by wojiaobadaye** [comment]
是的，我去dockerhub上查，好像也没有对应的仓库，等大佬修吧

**Comment by RealTong** [comment]
@wojiaobadaye @aoruLola @cvwet 应该可以了, 需要等待Actions build成功

**Comment by lingfengchencn** [comment]
依然存在：
docker-compose.yml

```
version: '3'
services:
  wechat-chatgpt:
    image: holegots/wechat-chatgpt:latest
    build: .
    volumes:
      - ./data/wechat-assistant.memory-card.json:/app/wechat-assistant.memory-card.json
    env_file:
      - .env
 ```

命令
```
docker-compose up -d wechat-chatgpt
```
log:
```
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] 2.0.20
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] to restart at any time, enter `rs`
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] watching path(s): src/**/*
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] watching extensions: ts
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] starting `node --loader ts-node/esm src/main.ts`
wechat-chatgpt-main-wechat-chatgpt-1  | (node:58) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
wechat-chatgpt-main-wechat-chatgpt-1  | (Use `node --trace-warnings ...` to show where the warning was created)
wechat-chatgpt-main-wechat-chatgpt-1  | 08:28:02 ERR PuppetWeChatBridge start() exception: Error: no payload, please call load() first.
wechat-chatgpt-main-wechat-chatgpt-1  | 08:28:02 ERR PuppetWeChat initBridge() exception: no payload, please call load() first.
wechat-chatgpt-main-wechat-chatgpt-1  | 08:28:02 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
wechat-chatgpt-main-wechat-chatgpt-1  | ⚠️ Bot start failed, can you log in through wechat on the web?: Error: no payload, please call load() first.
wechat-chatgpt-main-wechat-chatgpt-1  | [nodemon] clean exit - waiting for changes before restart

```

**Comment by dvlee1024** [comment]
> 
RR PuppetWeChatBridge start() 
这个问题有人回复了，可能是因为你的账号还没实名，在钱包里操作

**Comment by lingfengchencn** [comment]
> 
您好，请问哪个地方需要实名？或者在哪操作？
我的操作是：
```
cp .env.example .env

vim .env
--add  OPEN_API_KEY 

docker-composer -up -d wehcat-chatgpt
```
