### ISSUE TITLE
按照 Railway 的提示部署的，中间一步不差，但是还是报这个问题？

### ISSUE THREAD

**Issue by laihuamin** [fuergaosi233/wechat-chatgpt#707]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/28126886/224494427-775080e5-8803-4f26-8989-26cb50bebb08.png">
是因为网络么，还是我哪里操作的不对

**Comment by RealTong** [comment]
是bug. 在 `chatgpt-api` 分支已经修复
