### ISSUE TITLE
请问应该如何支持连续对话？我部署之后完全没有上下文功能

### ISSUE THREAD

**Issue by super-ttt** [fuergaosi233/wechat-chatgpt#713]

**Comment by verineliu** [comment]
我用docker部署的也没有连续对话的功能

**Comment by Kong9x** [comment]
同问

**Comment by a490077** [comment]
可能就是不支持😄  毕竟都没有参数可调

**Comment by RealTong** [comment]
@super-ttt @Li-dacheng @verineliu @Kong9x @a490077 

在 https://github.com/fuergaosi233/wechat-chatgpt/tree/chatgpt-api 已经支持设置prompt和连续对话

**Comment by zhuchao941** [comment]
@RealTong 这个为什么不合并到main里？

**Comment by RealTong** [comment]
@zhuchao941 等待更多的用户测试没啥问题之后会合并

**Comment by zhuchao941** [comment]
> @zhuchao941 等待更多的用户测试没啥问题之后会合并

哪些用户会自主用chatgpt-api这个分支deploy啊。貌似应该都是基于main的吧

**Comment by zhuchao941** [comment]
@RealTong 另外麻烦咨询下 railway是不是只支持部署github repo的default分支？找了半天好像没有看到哪里可以指定分支的
