### ISSUE TITLE
railway部署能否更换对话模型

### ISSUE THREAD

**Issue by yelicheng1010** [fuergaosi233/wechat-chatgpt#717]
railway部署能否更换对话模型

**Comment by RealTong** [comment]
添加环境变量MODEL="<MODEL_ID>"就行

**Comment by yelicheng1010** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/38903593/224920873-f8f663e2-24b2-41b8-b3c2-9200ff76bc6f.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/38903593/224921213-c689f78d-ace3-4a73-b7a2-c81c80e05921.png">
更换语言模型后，报错，根据官网显示，不同语言模型对应不同ENDPOINTS，这个在哪里更改
