### ISSUE TITLE
超时咋回事

### ISSUE THREAD

**Issue by zm520zyx** [fuergaosi233/wechat-chatgpt#719]
![image](https://user-images.githubusercontent.com/45876877/224976871-99520587-eacd-4e70-ba2a-20fe05d5ffc7.png)

**Comment by RealTong** [comment]
Please check your network

**Comment by zm520zyx** [comment]
![3a2162b8d680f1fbfd22efbb7b8c2b3](https://user-images.githubusercontent.com/45876877/225498435-73f908bd-c015-4e0f-9af7-565e30146dd6.jpg)
![3a2162b8d680f1fbfd22efbb7b8c2b3](https://user-images.githubusercontent.com/45876877/225498455-e3cadd7f-2423-473b-a1bc-7d1e5713365c.jpg)
