### ISSUE TITLE
求助    TypeError: fetch failed

### ISSUE THREAD

**Issue by Hsheep9** [fuergaosi233/wechat-chatgpt#721]
error.response.headers['set-cookie'] [
  'wxuin=500361197; Domain=wx.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'wxsid=z/jnku2hMqJ+d6Js; Domain=wx.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'wxloadtime=1678802639; Domain=wx.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'mm_lang=zh-CN; Domain=wx.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'wxuin=500361197; Domain=.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'webwx_data_ticket=gSf6mycf+B03EDMfFbUAOlH3; Domain=.qq.com; Path=/; Expires=Wed, 15-Mar-2023 02:03:59 GMT; Secure',
  'webwxuvid=fb6905a1c211b8eac85f01337aed44120e5d9a51c928332d5cc93f77a69bb2977b4e6af359d40c9607c1903701bbb49a; Domain=wx.qq.com; Path=/; Expires=Fri, 11-Mar-2033 14:03:59 GMT; Secure',
  'webwx_auth_ticket=CIsBEJDPpOsEGoAB3xphfRr7Nh0mJdfftPTQHevRW6R7/Hdt/UzAS3sjZSy0EpVFNxp2NqjJdERB0My2Kw405pKyzuVv1iosRGG8IhzBr3CXw6u4SoSN6lO3QfhH2r/QPPzJ6NdSg2BYLyEz81IuYwJjuH4EneMwp3hcL1s4w/mfpIatI6H5JjgWsi0=; Domain=wx.qq.com; Path=/; Expires=Fri, 11-Mar-2033 14:03:59 GMT; Secure'
]
对话报错“Something went wrong”

![image](https://user-images.githubusercontent.com/100297006/225030030-135beb8f-1d03-4f89-8127-8c8949f9662b.png)

**Comment by RealTong** [comment]
Please check your network.
