### ISSUE TITLE
my own questions are not responded to

### ISSUE THREAD

**Issue by loyon** [fuergaosi233/wechat-chatgpt#725]
I have deployed chatgpt, and my colleague's questions are answered normally, but my own questions are not responded to. I have briefly reviewed the bot file and found that the format is correct. Is it possible that the user data does not include myself? How can I modify it?

**Comment by suukii** [comment]
`isNonsense` function has filtered out your own messages. You can modify the code to meet your needs.

**Comment by vmxmy** [comment]
> `isNonsense` function has filtered out your own messages. You can modify the code to meet your needs.

How to modify the function? thanks

**Comment by suukii** [comment]
@vmxmy Remove this check.
![image](https://user-images.githubusercontent.com/30331289/227822387-915566c8-ee18-4aed-bc15-ad83341bedf5.png)
