### ISSUE TITLE
err is fetch failed, account {"email":"email","password":"password","isGoogleLogin":false}

### ISSUE THREAD

**Issue by jasonmajx** [fuergaosi233/wechat-chatgpt#728]
After scan QR code to login wechat and send message to it, it gives the folllowing error code
 🎯 Triggered ChatGPT: 你好
sendMessage (111 tokens) {
  max_tokens: 1000,
  model: 'text-davinci-003',
  temperature: 0.7,
  presence_penalty: 0.6,
  stop: [ '<|im_end|>' ],
  prompt: 'You are ChatGPT, a large language model trained by OpenAI. You answer as concisely as possible for each response (e.g. don’t be verbose). It is very important that you answer as concisely as possible, so please remember this. If you are generating a list, do not have too many items. Keep the number of items short.\n' +
    'Current date: 2023-03-15\n' +
    '\n' +
    'User:\n' +
    '\n' +
    '你好<|im_end|>\n' +
    '\n' +
    'ChatGPT:\n',
  stream: false
}
err is fetch failed, account {"email":"email","password":"password","isGoogleLogin":false}

curl -vv chat.openai.com has been confirmed working fine.

**Comment by jasonmajx** [comment]
I am using the nodejs environment.

**Comment by RealTong** [comment]
The version of the code you are using is deprecated. 
Please update your version
