### ISSUE TITLE
如何修改propmt部分

### ISSUE THREAD

**Issue by PmChai** [fuergaosi233/wechat-chatgpt#729]
看到大佬命令里面强调只能是简单的回复，请教下各位如何修改这个题主设定的指令

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/blob/f1ba4ae82e8e70aa2c9582657d55a9a6d5063bc3/src/chatgpt.ts#L17
还没想要有什么好的交互方式可以修改. 你有什么idea吗?

**Comment by RealTong** [comment]
@PmChai 在 https://github.com/fuergaosi233/wechat-chatgpt/tree/chatgpt-api 已经支持设置prompt和连续对话
