### ISSUE TITLE
有办法支持回复图片吗

### ISSUE THREAD

**Issue by jokerlinnn** [fuergaosi233/wechat-chatgpt#731]
都挺好的   就是不支持回复图片  有办法弄吗

**Comment by caohangabc** [comment]
mark

**Comment by caohangabc** [comment]
研究了两个小时，终于搞定了

**Comment by jokerlinnn** [comment]
怎么弄的  兄弟

**Comment by jokerlinnn** [comment]
> 研究了两个小时，终于搞定了

怎么弄的 兄弟

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/753

简单添加了AI 2 Img功能. 使用/img <YOUR PROMPT>调用

**Comment by caohangabc** [comment]
> 

抱歉兄弟，才看到， 我的思路和作者 @RealTong 一样，你可以参考他的， 提问时前缀使用 /img 就好

**Comment by caohangabc** [comment]
> > 研究了两个小时，终于搞定了
> 
> 怎么弄的 兄弟
这是我的效果图
![image](https://user-images.githubusercontent.com/35301893/226240187-6900839a-d047-4496-9749-2b086cbb5002.png)

**Comment by yyy-charlie** [comment]
私聊可以，群聊里@bot /img 内容 这样不行

**Comment by TheBlindM** [comment]
怎么获取接收的图片的二进制啊 @RealTong  大佬知道吗？

**Comment by FreezeStars** [comment]
> > > 研究了两个小时，终于搞定了
> > 
> > 
> > 怎么弄的 兄弟
> > 这是我的效果图
> > ![image](https://user-images.githubusercontent.com/35301893/226240187-6900839a-d047-4496-9749-2b086cbb5002.png)

兄弟兄弟，为啥我的图不是很高清，这是咋回事？
