### ISSUE TITLE
uncaughtException GError: already logout

### ISSUE THREAD

**Issue by qmaolong** [fuergaosi233/wechat-chatgpt#732]
uncaughtException GError: already logout
at new AlreadyLogoutError (/app/node_modules/wechat4u/src/core.js:17:44)
at /app/node_modules/wechat4u/src/core.js:193:17
at processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 2,
details: 'Error: already logout\n' +
'    at new AlreadyLogoutError (/app/node_modules/wechat4u/src/core.js:17:44)\n' +
'    at /app/node_modules/wechat4u/src/core.js:193:17\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by RealTong** [comment]
Please log in to your WeChat again
