### ISSUE TITLE
railway

### ISSUE THREAD

**Issue by 2211649442** [fuergaosi233/wechat-chatgpt#733]
xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start
﻿node[53]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
﻿1: 0xbf94a0 node::Abort() [node]
﻿2: 0xbf951e  [node]
﻿3: 0xc685de  [node]
﻿4: 0xc686c1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
﻿5: 0xbb6fab  [node]
﻿6: 0xbb762b node::Start(int, char**) [node]
﻿7: 0x7f0fe2673d0a __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
﻿8: 0xb291de _start [node]
﻿Aborted (core dumped)
﻿xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start
﻿xvfb-run: error: Xvfb failed to start

**Comment by 2211649442** [comment]
一直卡在这

**Comment by 2211649442** [comment]
会封号吗

**Comment by RealTong** [comment]
请更新一下代码或者docker镜像
