### ISSUE TITLE
微信怎么登录网页版的？

### ISSUE THREAD

**Issue by Linya-IronMan** [fuergaosi233/wechat-chatgpt#734]
我两个微信都不能登录，有什么办法么？

**Comment by GreenHat-MAN** [comment]
现在微信账号大部分都受限制登录网页版的微信，你用qq浏览器试一下看行不行

**Comment by RealTong** [comment]
2017年注册的账号不可以, wechat不可以.
但还是要在 https://wx.qq.com/ 实测

**Comment by yyy-charlie** [comment]
我是装了这个谷歌插件，This extension bypasses this check!
