### ISSUE TITLE
railway部署报错

### ISSUE THREAD

**Issue by tieliuzhou** [fuergaosi233/wechat-chatgpt#738]
用railway部署报错，uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
at /app/node_modules/wechat4u/src/core.js:195:16
at processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 2,
details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
'    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
'    at /app/node_modules/wechat4u/src/core.js:195:16\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by Aaron-zheng** [comment]
+1

**Comment by RealTong** [comment]
我有时也会报这个错误, 但是不影响收发消息. 目前不知道啥问题造成的

你会影响收发消息吗?

**Comment by Aaron-zheng** [comment]
我最后修复了，这个问题是因为，wx账号没有实名，需要手动实名后，就没有这个问题了。

**Comment by zhaoqingtao-hik** [comment]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
10:04:24 WARN WechatyPuppetMixin start() starting puppet ... timeout
10:04:24 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(wechat-assistant)
10:05:17 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
ERROR !!!
10:05:19 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
10:05:19 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
ERROR !!!
ERROR !!!
10:05:19 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting...
10:05:19 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... (max 5 seconds)
ERROR !!!
10:05:24 WARN ServiceCtl<PuppetServiceMixin> stop() found that is starting, waiting stable ... timeout
10:05:24 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

这是什么原因

**Comment by tieliuzhou** [comment]
> 我有时也会报这个错误, 但是不影响收发消息. 目前不知道啥问题造成的
> 
> 你会影响收发消息吗?

应该就像Aaron说的一样，就是账号问题，我换了个账号可以了
