### ISSUE TITLE
部署了最新版本到railway上，仍然没有上下文

### ISSUE THREAD

**Issue by hzmslx** [fuergaosi233/wechat-chatgpt#747]
不知道应该怎么开启上下文功能？而且询问的模型好像是003，不是3.5turbo

**Comment by ac1982** [comment]
你可以在railway配置变量model，改变你使用的模型，其他部署方式也可以改变这个变量参数。

**Comment by RealTong** [comment]
模型需要自己在环境变量中更换. 默认是`gpt-3.5-turbo`
