### ISSUE TITLE
请先执行/cmd prompt是什么意思

### ISSUE THREAD

**Issue by fangyirui** [fuergaosi233/wechat-chatgpt#749]
在railway上部署的

**Comment by zyl132** [comment]
设置prompt参数，传给chatgpt接口，来指导其回复的生成。

**Comment by fangyirui** [comment]
> 设置prompt参数，传给chatgpt接口，来指导其回复的生成。

那请问下这个怎么设置呢？ 我用railway部署完，也微信扫码登录了，测试任何一个问题语句，它都给我回复 “请先执行/cmd prompt命令，EXMPLE：/cmd prompt 你的命令”

**Comment by zyl132** [comment]
> 
发送“/cmd prompt 你是一个情感专家”即可，prompt后面的内容可以自己编写

**Comment by zyl132** [comment]
> > 设置prompt参数，传给chatgpt接口，来指导其回复的生成。
> 
> 那请问下这个怎么设置呢？ 我用railway部署完，也微信扫码登录了，测试任何一个问题语句，它都给我回复 “请先执行/cmd prompt命令，EXMPLE：/cmd prompt 你的命令”

如果想结束多轮对话，请向机器人发送/cmd clear，否则随着对话累计，消耗的token会越来越多

**Comment by zyl132** [comment]
> 在railway上部署的

你在railway上部署的main分支吗，现在main分支支持多轮对话了吗？为什么我用docker部署不支持

**Comment by fangyirui** [comment]
> > 
> 
> 发送“/cmd prompt 你是一个情感专家”即可，prompt后面的内容可以自己编写

十分感谢，已经可以了

**Comment by fangyirui** [comment]
> > 在railway上部署的
> 
> 你在railway上部署的main分支吗，现在main分支支持多轮对话了吗？为什么我用docker部署不支持

我看了，就是用的main分支的
