### ISSUE TITLE
为啥部署一切正常，微信人工回复都可以看到消息，但是机器人就没有是有什么关键字吗？railway部署的

### ISSUE THREAD

**Issue by CanradDong** [fuergaosi233/wechat-chatgpt#752]

**Comment by RealTong** [comment]
请提供日志

**Comment by CanradDong** [comment]
> ***@***.*** dev
﻿> nodemon --exec node --loader ts-node/esm src/main.ts
﻿[nodemon] 2.0.20
﻿[nodemon] to restart at any time, enter `rs`
﻿[nodemon] watching path(s): src/**/*
﻿[nodemon] watching extensions: ts
﻿[nodemon] starting `node --loader ts-node/esm src/main.ts`
﻿(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental
feature and might change at any time
﻿(Use `node --trace-warnings ...` to show where the warning was created)
﻿Scan QR Code to login: 2
﻿
https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FId3DBSEN7w%3D%3D
﻿ ▄▄▄▄▄▄▄ ▄ ▄ ▄ ▄ ▄▄▄▄▄▄▄
﻿ █ ▄▄▄ █ ▀▀▀▄▀▀▀██▀ ▀█ █ ▄▄▄ █
﻿ █ ███ █ ▄█▀▀▄██▀▀▄▄█▀ █ ███ █
﻿ █▄▄▄▄▄█ ▄ █▀█ █▀▄ █▀▄ █▄▄▄▄▄█
﻿ ▄ ▄ ▄ ▄ ▄▄█ █▄ ▄█ ▄█ ▄ ▄
﻿ ▀██▄▄▄▄▄▄▀ █▀▀██▄ ▄█▀▄▄▀▄▄█
﻿ ▀██▄ ▄▄ ▀▄▀▄▄█▀▀██▀▄█▀█▀▀▄ █▄
﻿ ▀▄ ▄█▄▀ ▄▀▄ █▀▀▀▄ ▀█▀▄ █ ▄█
﻿ █ █ ▄▀ ▄ ▀██ █▀█▄██ █ █▄
﻿ ▄▀ █ ▄▄▀▄█ ▀ ▄ █▄█▄ ▀▀▄█
﻿ ▄▀▀▀ ▄ █▀▀ ▄██▀████▄▄█▄█▀ ▀
﻿ ▄▄▄▄▄▄▄ ▀█ █▄ ▀ ▀▄ ▄█ ▄ █▄▀██
﻿ █ ▄▄▄ █ ▄█ ▄▀██▄█▀ █▄▄▄█▀ ▀▀
﻿ █ ███ █ ▄█▀▄▄▄▄▀▀ ██▄▀▀█
﻿ █▄▄▄▄▄█ ▄██▄ █▄██▄██▄▄█ █▄
﻿▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
﻿
﻿Scan QR Code to login: 3
﻿
https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FId3DBSEN7w%3D%3D
﻿ ▄▄▄▄▄▄▄ ▄ ▄ ▄ ▄ ▄▄▄▄▄▄▄
﻿ █ ▄▄▄ █ ▀▀▀▄▀▀▀██▀ ▀█ █ ▄▄▄ █
﻿ █ ███ █ ▄█▀▀▄██▀▀▄▄█▀ █ ███ █
﻿ █▄▄▄▄▄█ ▄ █▀█ █▀▄ █▀▄ █▄▄▄▄▄█
﻿ ▄ ▄ ▄ ▄ ▄▄█ █▄ ▄█ ▄█ ▄ ▄
﻿ ▀██▄▄▄▄▄▄▀ █▀▀██▄ ▄█▀▄▄▀▄▄█
﻿ ▀██▄ ▄▄ ▀▄▀▄▄█▀▀██▀▄█▀█▀▀▄ █▄
﻿ ▀▄ ▄█▄▀ ▄▀▄ █▀▀▀▄ ▀█▀▄ █ ▄█
﻿ █ █ ▄▀ ▄ ▀██ █▀█▄██ █ █▄
﻿ ▄▀ █ ▄▄▀▄█ ▀ ▄ █▄█▄ ▀▀▄█
﻿ ▄▀▀▀ ▄ █▀▀ ▄██▀████▄▄█▄█▀ ▀
﻿ ▄▄▄▄▄▄▄ ▀█ █▄ ▀ ▀▄ ▄█ ▄ █▄▀██
﻿ █ ▄▄▄ █ ▄█ ▄▀██▄█▀ █▄▄▄█▀ ▀▀
﻿ █ ███ █ ▄█▀▄▄▄▄▀▀ ██▄▀▀█
﻿ █▄▄▄▄▄█ ▄██▄ █▄██▄██▄▄█ █▄
﻿▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
﻿
﻿error.response.headers['set-cookie'] [
﻿'wxuin=1684534153; Domain=wx2.qq.com; Path=/; Expires=Mon, 20-Mar-2023
03:13:05 GMT; Secure',
﻿'wxsid=XJsjsv57fnZM8g8m; Domain=wx2.qq.com; Path=/; Expires=Mon,
20-Mar-2023 03:13:05 GMT; Secure',
﻿'wxloadtime=1679238785; Domain=wx2.qq.com; Path=/; Expires=Mon,
20-Mar-2023 03:13:05 GMT; Secure',
﻿'mm_lang=zh-CN; Domain=wx2.qq.com; Path=/; Expires=Mon, 20-Mar-2023
03:13:05 GMT; Secure',
﻿'wxuin=1684534153; Domain=.qq.com; Path=/; Expires=Mon, 20-Mar-2023
03:13:05 GMT; Secure',
﻿'webwx_data_ticket=gSeTsiBzIbd3PM+0Twj6f2zp; Domain=.qq.com; Path=/;
Expires=Mon, 20-Mar-2023 03:13:05 GMT; Secure',
﻿'webwxuvid=76e789d9f14f140c732ece4cd949680f87a2fc5d73c6b45e2b8912cf601862b949fa77358ce4391d0acd12650a182ed5;
Domain=wx2.qq.com; Path=/; Expires=Wed, 16-Mar-2033 15:13:05 GMT; Secure',
﻿'webwx_auth_ticket=CIsBEP3r4P4OGoABVJoBPS/nP4TQv9/Zp5wA/2XJOQGfyT/cuA9Xz3car4L1mAPEMnMi8svSyb7iApJ9YG3Sai/KzJbcZ6x2uqUQxLzO/azBCEuDFjdR796bpxAOAG6063laiRk3ixK9Dph9lE26BtbQwV+AWCV/eZfzHDHHWljz4yvwcp7JjWJr5J4=;
Domain=wx2.qq.com; Path=/; Expires=Wed, 16-Mar-2033 15:13:05 GMT; Secure'
﻿]
﻿User Contact<快手-立星> logged in
﻿🎯 Sun Mar 19 2023 15:13:04 GMT+0000 (Coordinated Universal Time) Message:
Message#Unknown[🗣Contact<mm>] hello
﻿

**Comment by RealTong** [comment]
```
﻿User Contact<快手-立星> logged in
﻿🎯 Sun Mar 19 2023 15:13:04 GMT+0000 (Coordinated Universal Time) Message:
Message#Unknown[🗣Contact<mm>] hello
```
可以看到机器人已经收到信息了.

但是没有触发ChatGPT. 触发ChatGPT需要在群聊中@机器人, 在私聊中可以直接回复

**Comment by CanradDong** [comment]
以上信息有个人敏感信息，请帮忙删除，感谢

**Comment by CanradDong** [comment]
> ```
> ﻿User Contact<快手-立星> logged in
> ﻿🎯 Sun Mar 19 2023 15:13:04 GMT+0000 (Coordinated Universal Time) Message:
> Message#Unknown[🗣Contact<mm>] hello
> ```
> 
> 可以看到机器人已经收到信息了.
> 
> 但是没有触发ChatGPT. 触发ChatGPT需要在群聊中@机器人, 在私聊中可以直接回复

以上信息有个人敏感信息，请帮忙删除，感谢
