### ISSUE TITLE
扫码之后报错app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by 1099234990** [fuergaosi233/wechat-chatgpt#758]
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/*.ts
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:82) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
05:42:36 ERR Puppet resolvePuppetName
Failed to import Wechaty Puppet Provider (WPP) NPM module: "wechaty-puppet-wechat4u"
Please make sure:
1. it has been installed correctly. (run `npm install wechaty-puppet-wechat4u` if it doesn't)
2. "wechaty-puppet-wechat4u" is a valid Wechaty Puppet Provider (WPP).
learn more about Wechaty Puppet Providers (WPP) from the official website:
<[https://wechaty.js.org/docs/puppet-providers>](https://wechaty.js.org/docs/puppet-providers%3E);
⚠️ Bot start failed, can you log in through wechat on the web?: Error: Cannot find package 'wechaty-puppet-wechat4u' imported from /app/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-resolver.js
[nodemon] clean exit - waiting for changes before restart

**Comment by RealTong** [comment]
尝试添加一个环境变量: WECHATY_PUPPET=wechaty-puppet-wechat

**Comment by 1099234990** [comment]
> 尝试添加一个环境变量：WECHATY_PUPPET=wechaty-puppet-wechat

有二维码了，但是扫码登录又报错了
06:03:59 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
code: 2,
details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
'    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by 1099234990** [comment]
前天用railway成功部署使用了两天，今天想换成chatcpt-api分支来部署就不行了。

**Comment by RealTong** [comment]
你的账号可以登录 https://wx.qq.com 吗

**Comment by 1099234990** [comment]
现在登不了，前两天还正常用的
![image](https://user-images.githubusercontent.com/111104984/226322276-9580468e-b521-4132-b977-3b29a94550b4.png)

**Comment by RealTong** [comment]
Hi. 你可以尝试以下将 `src/main.ts` L7行添加

```typescript
const bot =  WechatyBuilder.build({
  name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
  puppet: "wechaty-puppet-wechat",
  puppetOptions: {
    uos: true
  }
});
```
最后查看 log 看看可以登录吗

**Comment by 1099234990** [comment]
改了之后的报错
![image](https://user-images.githubusercontent.com/111104984/226332883-4059074f-a9bf-497b-b1b2-35fa6978bb1b.png)
11:58:20 WARN PuppetWeChatBridge proxyWechaty() noWechaty exception: Error: Execution context was destroyed, most likely because of a navigation.
11:58:20 ERR PuppetWeChatBridge getUserName() exception: Execution context was destroyed, most likely because of a navigation.
11:58:20 ERR PuppetWeChatEvent onLogin() exception: Error: Execution context was destroyed, most likely because of a navigation.
GError: Execution context was destroyed, most likely because of a navigation.
at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)
at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)
at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)
at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20) {
code: 2,
details: 'Error: Execution context was destroyed, most likely because of a navigation.\n' +
'    at rewriteError (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)\n' +
'    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)\n' +
'    at async Bridge.proxyWechaty (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)\n' +
'    at async Bridge.getUserName (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)\n' +
'    at async PuppetWeChat.onLogin (file:///app/node_modules/wechaty-puppet-wechat/src/event.ts:147:20)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by 1099234990** [comment]
你把这一段 截图我看看，是不是我哪里改错了啊

**Comment by 1099234990** [comment]
> Hi. 你可以尝试以下将 `src/main.ts` L7行添加
> 
> ```ts
> const bot =  WechatyBuilder.build({
>   name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
>   puppet: "wechaty-puppet-wechat",
>   puppetOptions: {
>     uos: true
>   }
> });
> ```
> 
> 最后查看 log 看看可以登录吗

我的也好了，原来改了这个就不需要再加变量了。

**Comment by RealTong** [comment]
那我就先关闭这个issues了. 有需要我们再重新打开它

**Comment by Abraham-wy** [comment]
> > Hi. 你可以尝试以下将 `src/main.ts` L7行添加
> > ```ts
> > const bot =  WechatyBuilder.build({
> >   name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
> >   puppet: "wechaty-puppet-wechat",
> >   puppetOptions: {
> >     uos: true
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后查看 log 看看可以登录吗
> 
> 我的也好了，原来改了这个就不需要再加变量了。

你后面咋解决的，我跟你一样的问题

**Comment by thusjr** [comment]
> > Hi. 你可以尝试以下将 `src/main.ts` L7行添加
> > ```ts
> > const bot =  WechatyBuilder.build({
> >   name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
> >   puppet: "wechaty-puppet-wechat",
> >   puppetOptions: {
> >     uos: true
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后查看 log 看看可以登录吗
> 
> 我的也好了，原来改了这个就不需要再加变量了。

源码增加了这个，但是没有解决。

**Comment by Abraham-wy** [comment]
> 15:36:13 WARN WechatyPuppetMixin start() starting puppet ... timeout
> 15:36:13 WARN WechatyPuppetMixin start() puppet info: Puppet(wechat-assistant)
> 15:37:00 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
> 15:37:01 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
> 15:37:01 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

这个应该是超时了吧，我也是这样的问题

**Comment by lustm** [comment]
我也是超时，'Error: WatchdogAgent reset: lastFood: "{"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/QfgQxxX=="},"timeoutMilliseconds":60000}"\n' 微信必须能登录网页版么

**Comment by majq1990** [comment]
然后扫描以后，没下文了。。
01:26:33 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'

**Comment by snorazera** [comment]
> > Hi. 你可以尝试以下将 `src/main.ts` L7行添加
> > ```ts
> > const bot =  WechatyBuilder.build({
> >   name: "wechat-assistant", // generate xxxx.memory-card.json and save login data for the next login
> >   puppet: "wechaty-puppet-wechat",
> >   puppetOptions: {
> >     uos: true
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最后查看 log 看看可以登录吗
> 
> 我的也好了，原来改了这个就不需要再加变量了。

请问在如何增加这段代码？
