### ISSUE TITLE
Bot start failed, can you log in through wechat on the web?: Error: Cannot find package 'wechaty-puppet-wechat4u' imported from /app/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-resolver.js

### ISSUE THREAD

**Issue by drewBroSpace** [fuergaosi233/wechat-chatgpt#763]
![image](https://user-images.githubusercontent.com/49440700/226341172-86f4ff98-0e99-4c82-8347-a610ae8b3b23.png)

**Comment by vincentli2023** [comment]
SAME HERE

**Comment by jk256** [comment]
Same Here +1 ，#758 No effect

**Comment by thusjr** [comment]
使用chatgpt-api分支部署，并且按照修改代码 [#758](https://github.com/fuergaosi233/wechat-chatgpt/issues/758)

**Comment by tiger233** [comment]
> 使用chatgpt-api分支部署，并且按照修改代码 [#758](https://github.com/fuergaosi233/wechat-chatgpt/issues/758)

根据这个方法登录上了，但是对话后程序直接报错，无法进行机器人对话
![image](https://user-images.githubusercontent.com/27544964/226445161-b0c77a53-3576-49cb-9426-2a4465e59c66.png)
