### ISSUE TITLE
为什么我部署这个不太聪明的样子，他说自己不是ChatGPT

### ISSUE THREAD

**Issue by a173030685** [fuergaosi233/wechat-chatgpt#765]
是我环境变量配置的不对还是怎么回事，感觉回答的很弱，跟官方的差距很大：
![image](https://user-images.githubusercontent.com/9361755/226410952-f8dc9a47-60ca-49ac-b12b-ea858fe237a9.png)

![image](https://user-images.githubusercontent.com/9361755/226410246-8d45bd22-986f-467f-988e-fd50da61aed2.png)
![39c19327fc0b17d483ef8ec0e4ef6f0](https://user-images.githubusercontent.com/9361755/226410658-51e18a1b-b3b4-41ee-a5a1-09dd51047268.png)
正常的应该是这种回答：
![image](https://user-images.githubusercontent.com/9361755/226411284-844aec9a-c3d6-48dc-945c-e48ff2a6a01a.png)

**Comment by hanszaishengzhang** [comment]
我也有同样问题。你问一下他是不是GPT3.5，他如果回答是GPT3说明他是愚蠢版本的

**Comment by hanszaishengzhang** [comment]
@RealTong Any ideas how we can make sure we have GPT3.5 vesion deployed?

**Comment by a173030685** [comment]
> 他说他不是，这是哪里出了问题？

![image](https://user-images.githubusercontent.com/9361755/226495406-517e3961-5f77-4492-875b-a2abd3bc67d2.png)

**Comment by RealTong** [comment]
https://platform.openai.com/docs/guides/chat/introduction

请问检测是否是 `GPT-3.5` 的有效方法是 ?  @hanszaishengzhang @a173030685 

![image](https://user-images.githubusercontent.com/67304509/226510872-7a6a15b9-8c45-4b7d-a43a-d1065f63eaa1.png)

**Comment by hanszaishengzhang** [comment]
> https://platform.openai.com/docs/guides/chat/introduction
> 
> 请问检测是否是 `GPT-3.5` 的有效方法是 ? @hanszaishengzhang @a173030685
> 
> ![image](https://user-images.githubusercontent.com/67304509/226510872-7a6a15b9-8c45-4b7d-a43a-d1065f63eaa1.png)

谢谢分享，但还是无法解释在railway部署之后机器人没有本体表现得那么”聪明“和”人性化“这件事情， 问题没有得到解决。

而且上下文的功能有时候也无法适用，which让他显得更蠢了

**Comment by zrwkkd** [comment]
![1679500661753](https://user-images.githubusercontent.com/51474277/226965573-26218855-bbf0-4ccf-8fff-8131029c73c9.png)

**Comment by kk456852** [comment]
![image](https://user-images.githubusercontent.com/36686544/227404245-3aeaf80f-eb15-41f6-828c-11ea1e1b6a95.png)

**Comment by hanszaishengzhang** [comment]
> ![image](https://user-images.githubusercontent.com/36686544/227404189-f1820970-4362-401d-a7c4-6221af32c36b.png)

好家伙，你这个更离谱，居然是GPT-2，愚蠢中的愚蠢，怎么做到的。。。
