### ISSUE TITLE
萌新报错

### ISSUE THREAD

**Issue by RuthlessXdream** [fuergaosi233/wechat-chatgpt#767]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /wechat-chatgpt/node_modules/wechat4u/src/core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /wechat-chatgpt/node_modules/wechat4u/src/core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by RealTong** [comment]
请确认微信是否实名认证.
