### ISSUE TITLE
总是莫名其妙停止服务

### ISSUE THREAD

**Issue by a173030685** [fuergaosi233/wechat-chatgpt#770]
![image](https://user-images.githubusercontent.com/9361755/226498149-bda697c4-9c44-4385-a0dd-7ecde570b0fc.png)

**Comment by a173030685** [comment]
运行10来分钟就停了，chatgpt-api版本是有问题么，哪个版本最稳定？

**Comment by RealTong** [comment]
可能是内存不够了. Railway Free plan最高只有512MB

**Comment by thusjr** [comment]
我也是同样的问题

**Comment by thusjr** [comment]
> 可能是内存不够了. Railway Free plan最高只有512MB

确实！当我把dashboard其他项目清空就可以用了

**Comment by RealTong** [comment]
Memory overflow.
Please upgrade your server.

**Comment by wwcy1998** [comment]
我就只有一个这个wechat-gpt项目，也是只有十几分钟就停了

**Comment by a173030685** [comment]
> 可能是内存不够了. Railway Free plan最高只有512MB

请教一下如何提高内存呢，升级railway付费就可以了么？
