### ISSUE TITLE
railway 某个微信群出bug，其他好好的

### ISSUE THREAD

**Issue by thusjr** [fuergaosi233/wechat-chatgpt#771]
![image](https://user-images.githubusercontent.com/53186008/226531240-7f304ec6-00d8-4023-acb9-ecc891546d82.png)
如上

**Comment by thusjr** [comment]
注 chatgpt-api分支

**Comment by RealTong** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/400
