### ISSUE TITLE
执行 docker run 命令并扫码后提示下方的Error

### ISSUE THREAD

**Issue by Shimmers688** [fuergaosi233/wechat-chatgpt#774]
09:32:22 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Bridge.onLoad (file:///app/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by majq1990** [comment]
求问，咋解决的
