### ISSUE TITLE
最新版本貌似缺少上下文实现

### ISSUE THREAD

**Issue by liaojinmin** [fuergaosi233/wechat-chatgpt#775]

**Comment by majq1990** [comment]
wechat-chatgpt_1  | 
wechat-chatgpt_1  | > wechat-chatgpt@1.0.0 dev
wechat-chatgpt_1  | > nodemon --exec node --loader ts-node/esm src/main.ts
wechat-chatgpt_1  | 
wechat-chatgpt_1  | [nodemon] 2.0.20
wechat-chatgpt_1  | [nodemon] to restart at any time, enter `rs`
wechat-chatgpt_1  | [nodemon] watching path(s): src/**/*
wechat-chatgpt_1  | [nodemon] watching extensions: ts
wechat-chatgpt_1  | [nodemon] starting `node --loader ts-node/esm src/main.ts`
wechat-chatgpt_1  | (node:55) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
wechat-chatgpt_1  | (Use `node --trace-warnings ...` to show where the warning was created)
wechat-chatgpt_1  | ⚠️ Bot start failed, can you log in through wechat on the web?: Error: no payload, please call load() first.
wechat-chatgpt_1  | [nodemon] clean exit - waiting for changes before restart
