### ISSUE TITLE
docker 启动报错

### ISSUE THREAD

**Issue by majq1990** [fuergaosi233/wechat-chatgpt#777]
[root@VM-0-7-centos wechatgpt]# docker logs -f wechat-chatgpt

> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/*.ts
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:54) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
15:07:18 ERR Puppet resolvePuppetName 
Failed to import Wechaty Puppet Provider (WPP) NPM module: "wechaty-puppet-wechat4u"
Please make sure:
 1. it has been installed correctly. (run `npm install wechaty-puppet-wechat4u` if it doesn't)
 2. "wechaty-puppet-wechat4u" is a valid Wechaty Puppet Provider (WPP).

learn more about Wechaty Puppet Providers (WPP) from the official website:
<https://wechaty.js.org/docs/puppet-providers>

?? Bot start failed, can you log in through wechat on the web?: Error: Cannot find package 'wechaty-puppet-wechat4u' imported from /app/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-
resolver.js[nodemon] clean exit - waiting for changes before restart

**Comment by cbabypig** [comment]
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/*.ts
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:50) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
15:26:49 ERR Puppet resolvePuppetName
Failed to import Wechaty Puppet Provider (WPP) NPM module: "wechaty-puppet-wechat4u"
Please make sure:
 1. it has been installed correctly. (run `npm install wechaty-puppet-wechat4u` if it doesn't)
 2. "wechaty-puppet-wechat4u" is a valid Wechaty Puppet Provider (WPP).

learn more about Wechaty Puppet Providers (WPP) from the official website:
<https://wechaty.js.org/docs/puppet-providers>

⚠️ Bot start failed, can you log in through wechat on the web?: Error: Cannot find package 'wechaty-puppet-wechat4u' imported from /app/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-resolver.js

**Comment by cbabypig** [comment]
我也报错，错误编号不一样，但是反馈的问题一样。

**Comment by Shimmers688** [comment]
在 docker run 命令中增加一个环境变量 -e WECHATY_PUPPET=wechaty-puppet-wechat
详见https://github.com/fuergaosi233/wechat-chatgpt/issues/758
