### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by li0228** [fuergaosi233/wechat-chatgpt#790]
request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v1/chat/completions',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.openai.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v1/chat/completions'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 150,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 150,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v1/chat/completions HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.2.1\r\n' +
        'Authorization: Bearer EXAMPLE\r\n' +
        'Content-Length: 150\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/chat/completions',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://api.openai.com/v1/chat/completions',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
 Contact: 自己想想  Text: Something went wrong
你好，运行成功但是一直回复这个，请问是什么问题

**Comment by RealTong** [comment]
你的Key漏了, 请在OpenAI删除泄露的API

从这个日志里看不出来. 应该还有一个 http 状态码吧.

**Comment by zrwkkd** [comment]
代理没搞好

**Comment by jessiSYJ** [comment]
我也遇到了这个问题，求解

**Comment by ackerx** [comment]
> 代理没搞好 ps：一开始以为'RealTong'说key泄露了是指在日志里，不过这个大概率不关key事，可能用的是万人骑的机场，而导致针对ip的请求过多错误，换个好点的机场就行，当然，万一真的是key泄露了，要换都换了吧

我也遇到这个问题了。代理没搞好是指？麻烦具体说说怎么处理的。

**Comment by li0228** [comment]
> 代理没搞好 ps：一开始以为'RealTong'说key泄露了是指在日志里，不过这个大概率不关key事，可能用的是万人骑的机场，而导致针对ip的请求过多错误，换个好点的机场就行，当然，万一真的是key泄露了，要换都换了吧

能否详细说说？怎么换机场？

**Comment by RealTong** [comment]
@jessiSYJ 日志中会存在调用API的key, 只要拥有这个key任何人可以调用, 扣的是你的钱. 所以在贴日志的时候注意脱敏.
![image](https://user-images.githubusercontent.com/67304509/227106778-237dce37-4c44-4cb6-ab8d-0b63fde22d58.png)

**Comment by li0228** [comment]
> @jessiSYJ 日志中会存在调用API的key, 只要拥有这个key任何人可以调用, 扣的是你的钱. 所以在贴日志的时候注意脱敏. ![image](https://user-images.githubusercontent.com/67304509/227106778-237dce37-4c44-4cb6-ab8d-0b63fde22d58.png)

感谢你的提醒，我已经把key删掉了。但是这个标题这个问题请问应该怎么解决呢

**Comment by luqicoder** [comment]
我也遇到这个问题（第一次启动就出现），有尝试直接curl请求是正常的。
