### ISSUE TITLE
[Bug]: Something went wrong问题麻烦尽快修复哦

### ISSUE THREAD

**Issue by zhangjiajun0523** [fuergaosi233/wechat-chatgpt#791]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

Something went wrong问题麻烦尽快修复哦

### wechat-chatgpt operation log

<details>
```console
# Paste output here
```
</details>

**Comment by daigaofei** [comment]
同遇到一样的问题，回复我Something went wrong

**Comment by lqhLoveSmy** [comment]
也不知道什么时候能修复

**Comment by lqhLoveSmy** [comment]
啥时候能修复啊

**Comment by RealTong** [comment]
这是一个开源项目, 有能力自己Clone -> fix -> pr. 

提Issues连日志都不贴怎么给你解决?
