### ISSUE TITLE
[Bug]: 消息过于频繁

### ISSUE THREAD

**Issue by explorer2x** [fuergaosi233/wechat-chatgpt#795]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

请问消息过于频繁是什么原因以及怎么设置取消限制呢

🤵 Contact: bot 💬 Text: 抱歉，由于您发送的消息过于频繁，系统已经限制了您的消息发送。请您稍等片刻，过一段时间再尝试发送消息。如果您需要发送大量消息，请尝试分批发送，以避免被系统视为垃圾信息。如果您有任何其他问题，请告诉我。

### wechat-chatgpt operation log

🎯 Triggered ChatGPT: 发送消息过于频繁，可稍后再试。
🤵 Contact: bot 💬 Text: 抱歉，您的消息发送过于频繁，因此系统限制了您的消息发送。请您稍等片刻，过一段时间再尝试发送消息。如果您需要发送大量消息，请尝试分批发送，以避免被系统视为垃圾信息。如果您有任何其他问题，请告诉我。

**Comment by zccguagua** [comment]
这应该是chatgpt的回复,免费版本的chatgpt有使用限制,不能发送消息频繁.过一个小时再问应该就可以了
