### ISSUE TITLE
[Bug]: GError: Page crashed!

### ISSUE THREAD

**Issue by lx348321409** [fuergaosi233/wechat-chatgpt#796]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

正常聊天 聊着聊着就报这个错，没输入特殊符号之类的

### wechat-chatgpt operation log

<details>```GError: Page crashed!
at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)
at /app/node_modules/puppeteer/src/common/Page.ts:573:53
at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
at Array.map (<anonymous>)
at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)
at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)
at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
code: 2,
details: 'Error: Page crashed!\n' +
'    at Page._onTargetCrashed (/app/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
'    at /app/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
'    at /app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
'    at Array.map (<anonymous>)\n' +
'    at Object.emit (/app/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
'    at CDPSession.emit (/app/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
'    at CDPSession._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
'    at Connection._onMessage (/app/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
'    at WebSocket.<anonymous> (/app/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
'    at WebSocket.onMessage (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}
```</details>

**Comment by jk256** [comment]
相同报错，报错前正常运行两天

**Comment by zccguagua** [comment]
#770

**Comment by RealTong** [comment]
> 

本项目仅需要一个集合即可实现上下文功能.
数据库(即使是SQLite)对于本项目太过庞大

**Comment by dustookk** [comment]
> > 
> 
> 本项目仅需要一个集合即可实现上下文功能. 数据库(即使是SQLite)对于本项目太过庞大

@RealTong 感谢回答，看了下代码，除非调用clear的命令，否则内存数据库都是一个无限增大的逻辑，再大的内存也不够啊 😂

**Comment by RealTong** [comment]
> > > 
> > 
> > 本项目仅需要一个集合即可实现上下文功能. 数据库(即使是SQLite)对于本项目太过庞大
> 
> @RealTong 感谢回答，看了下代码，除非调用clear的命令，否则内存数据库都是一个无限增大的逻辑，再大的内存也不够啊 😂

token最大只有4096呀（在chatgpt-api分支修了和没合并）。不存在无限增大

**Comment by dustookk** [comment]
@RealTong 好的 看到代码了 `isTokenOverLimit` 👌🏻

**Comment by phoenixg** [comment]
> @jk256 @lx348321409 `Railway` free plan 最高512MB内存. 当前版本会将用户和Bot的对话记录存入内存, 以供实现上下文功能, 时间长 内容多会导致内存溢出(Page crashed), 需要定时重启或者`/cmd clear`手动清理会话记录.
`cmd clear` 在 railway.app 里要怎么设置？
