### ISSUE TITLE
请求chatgpt超时

### ISSUE THREAD

**Issue by zane0904** [fuergaosi233/wechat-chatgpt#800]
你好 本地启动完成项目，微信收到消息请求gpt时超时，本地开了全局代理，单独访问网页和使用postman请求都没问题 ，这个应该怎么解决呢

**Comment by xwjla** [comment]
终端也需要配置代理，可以百度一下

**Comment by zane0904** [comment]
> 终端也需要配置代理，可以百度一下

谢谢你的回复 目前找到了解决方案 

 const response = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: messages,
    temperature: 0.6
  },{ proxy: {
      protocol: 'http',
      host: '127.0.0.1',
      // hostname: '127.0.0.1' // Takes precedence over 'host' if both are defined
      port: 7890, // clash的默认端口
  }
这样转发到当前本机的代理上，参数和axios报纸一致

**Comment by zane0904** [comment]
ok
