### ISSUE TITLE
美国节点，微信登录不上报超时 WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"

### ISSUE THREAD

**Issue by liuhaichaogithub** [fuergaosi233/wechat-chatgpt#803]
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"

![image](https://user-images.githubusercontent.com/40063899/227700128-d412f0cc-0a2c-4d17-bc43-14a4682886c5.png)

**Comment by RealTong** [comment]
删除 `src/main.ts` L9-L12 试试
