### ISSUE TITLE
[Bug]: WARN PuppetWeChat friendshipRawPayload

### ISSUE THREAD

**Issue by zane0904** [fuergaosi233/wechat-chatgpt#804]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [X] Node.js

### Description of the problem

    "wechaty": "^1.20.2",
    "wechaty-puppet-wechat": "^1.18.4"

### wechat-chatgpt operation log

<details>
```console
# Paste output here
18:22:39 WARN PuppetWeChat friendshipRawPayload(8106990055130456657)

18:22:39 WARN PuppetWeChat friendshipRawPayload(5105864346954028696)

18:22:39 WARN PuppetWeChat friendshipRawPayload(1632615326328390624)

18:22:40 WARN PuppetWeChat friendshipRawPayloadParser([object Object])

18:22:40 WARN PuppetWeChat friendshipRawPayloadParser([object Object])

18:22:40 WARN PuppetWeChat friendshipRawPayloadParser([object Object])

.on('friendship', async friendship => {
        console.log('received friend event.', friendship.type());
    });
```
</details>

**Comment by RealTong** [comment]
Please make sure your WeChat account can log in [WeChat on web](https://wx.qq.com/)

**Comment by zane0904** [comment]
> Please make sure your WeChat account can log in [WeChat on web](https://wx.qq.com/)

Can't I use friendship if I can't log in to WeChat on the web? However, I can currently scan the code and log in to Wechat, and I can also receive WeChat messages, which indicate that there may be problems with this friend application
