### ISSUE TITLE
部署不成功，如下是关键错误信息～ 求助

### ISSUE THREAD

**Issue by CustomerThink** [fuergaosi233/wechat-chatgpt#805]
uncaughtException AssertionError [ERR_ASSERTION]: 400 != 400
at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)
at /app/node_modules/wechat4u/src/core.js:108:16
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
code: 2,
details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
'    at Object.notEqual (/app/node_modules/wechat4u/src/util/global.js:63:14)\n' +
'    at /app/node_modules/wechat4u/src/core.js:108:16\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by RealTong** [comment]
请不要打开重复的issue
