### ISSUE TITLE
A few quick chatgpt questions

### ISSUE THREAD

**Issue by transitive-bullshit** [fuergaosi233/wechat-chatgpt#81]
Hey @fuergaosi233, really love the project ❤️ 

1. I was wondering if you wouldn't mind adding [chatgpt](https://github.com/transitive-bullshit/chatgpt-api ) to the readme (can be somewhere minor at the bottom) to help other people find the package? No worries if not; just a thought.

2. I really like the way you're creating a pool of ChatGPTAPI instances. I'm curious how you're getting different session tokens; did you just sign up with different emails and get one per account? If so, I hadn't tried that... 🤯 

3. Is there anything you'd like to see added / changed with the `chatgpt` package that would make this project easier?

Thanks!

**Comment by OliverGrace** [comment]
@transitive-bullshit Hi, speaking of point 3, text-splitting has been a problem for a while. The situation now is that the respond of openai often gets cut (e.g. a long story won't be fully told, the story just disappears with unfinished words, or some long codes are not finished), and this situation is especially serious when chatGPT responses in Chinese.

**Comment by transitive-bullshit** [comment]
@OliverGrace can you send me some example interactions where this occurs so I can try to reproduce what's going on? Maybe create an issue on the `chatgpt` repo with details and I'll investigate.
