### ISSUE TITLE
[Bug]: 无法下载docker最新版本manifest for docker.io/holegots/wechat-chatgpt:latest not found

### ISSUE THREAD

**Issue by brainfish42** [fuergaosi233/wechat-chatgpt#812]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

1.02及以前没问题

### wechat-chatgpt operation log

<details>
```console
# Paste output here
```
</details>

**Comment by RealTong** [comment]
docker源问题.  请换官方源

**Comment by KyrieY** [comment]
你好，请问一下，官方源是什么，docker默认的不就是官方源吗 @RealTong

**Comment by RealTong** [comment]
hub.docker.com

> 你好，请问一下，官方源是什么，docker默认的不就是官方源吗 @RealTong
