### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AD696** [fuergaosi233/wechat-chatgpt#814]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [X] Node.js

### Description of the problem

Node.js 部署的时候没有出现二维码，通过连接的二维码无法登录

### wechat-chatgpt operation log

部署的时候没有出现二维码，通过连接的二维码无法登录

**Comment by RealTong** [comment]
Please make sure your WeChat account can log in [WeChat on web](https://wx.qq.com/)
