### ISSUE TITLE
[Bug]: Speech to text failed

### ISSUE THREAD

**Issue by samanhappy** [fuergaosi233/wechat-chatgpt#816]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [ ] Railway
- [ ] Fly.io
- [X] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

got "Speech to text failed" for any audio message 

### wechat-chatgpt operation log

```
 [Error: ENOENT: no such file or directory, open '/app/public/6446491591471262325.mp3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/public/6446491591471262325.mp3'
}
```

**Comment by msyzzm** [comment]
Need to update docker image
