### ISSUE TITLE
[Bug]: 为什么我在railway上扫了二维码没有任何聊天框弹出

### ISSUE THREAD

**Issue by Master-PLC** [fuergaosi233/wechat-chatgpt#819]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

在railway上部署完成后，扫了二维码没有任何聊天框弹出，但是能记录我与其他人的对话聊天

### wechat-chatgpt operation log

[nodemon] app crashed - waiting for file changes before starting...
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
xvfb-run: error: Xvfb failed to start
> wechat-chatgpt@1.0.0 dev
> nodemon --exec node --loader ts-node/esm src/main.ts
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/*.ts
[nodemon] watching extensions: ts
[nodemon] starting `node --loader ts-node/esm src/main.ts`
(node:83) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Master-PLC** [comment]
不久后出现的状况，有人跟我聊天，结果chatgpt替我回复了对方，是哪里出错了，我变成了gpt

**Comment by Saviio** [comment]
@Master-PLC 比较推荐的实践可能是你应该用一个小号来代理 gpt 回答，而不是用主号。 或者你给你的机器人设置专门的 trigger word
