### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by Leo4zhou** [fuergaosi233/wechat-chatgpt#82]
TypeError: Cannot read properties of undefined (reading 'reduce')
    at file:///F:/ProjectsGithub/wechat-chatgpt/src/config.ts:18:59
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by xueshuai0922** [comment]
add trigger-word 
yaml中增加一个触发chatGpt的词

**Comment by Leo4zhou** [comment]
> add trigger-word yaml中增加一个触发chatGpt的词

好了，谢谢！
