### ISSUE TITLE
[Question]: Is there any doc about the diffierent branch?

### ISSUE THREAD

**Issue by shiyuhang0** [fuergaosi233/wechat-chatgpt#822]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

I have found there are some branches with different abilities from the master. For example, the `chatgpt-api` branch

Are there any docs describing the different from them?

### wechat-chatgpt operation log

<details>
```console
# Paste output here
```
</details>

no operation

**Comment by RealTong** [comment]
Sorry, there is no documentation describing the differences between the two branches at this time.

The main branch is one [commit ](https://github.com/fuergaosi233/wechat-chatgpt/commit/4d39ea4989dad46945a0aea93a9be43a739b38e4) behind chatgpt-api. 

This commit is used to fix [a bug](https://github.com/fuergaosi233/wechat-chatgpt/issues/788) that causes the chatgpt-api interface to report an error when the message is too long
