### ISSUE TITLE
当回复内容比较长，会产生截断

### ISSUE THREAD

**Issue by fushuang001** [fuergaosi233/wechat-chatgpt#825]
当 ChatGPT 回复的内容比较长的时候，发现微信里面只收到了部分回复，被截断了。

**Comment by woann** [comment]
我也发现了，还有就是有时候被阶段的分开发送，顺序是反的

**Comment by fushuang001** [comment]
最近测试，Railway 部署的没有问题。之前遇到的截断是本地 npm 部署。
Railway 部署以后，测试了大概 10 次问答，微信就被封号了...
