### ISSUE TITLE
微信助手无法使用

### ISSUE THREAD

**Issue by wuzhihuazhuanyong** [fuergaosi233/wechat-chatgpt#835]
无法完成定时发送消息的任务，在吩咐任务的时候AI会接受定时任务，但时间到达时不会有任何反应，即不会完成定时发布任务。

要求私信发消息也是只会口头承诺，没有把需要发私信的消息发出去。

顺带一提如果问时间的话会回复这个：
根据我的记录，现在北京时间是：{{datetime "Asia/Shanghai"}}

**Comment by zhujunkun** [comment]
gpt3.5是没有联网的。传给模型之后，它没法调用时间接口

**Comment by RealTong** [comment]
Are you kidding me?
