### ISSUE TITLE
被限制所有社交场景，有没有什么办法

### ISSUE THREAD

**Issue by qsyao** [fuergaosi233/wechat-chatgpt#836]
没有人举报，不是第三方软件

限制原因: 骚扰/虚假营销/欺诈等违规行为

![图片](https://user-images.githubusercontent.com/44317931/228896040-4b4760d6-e564-483b-82c7-3949637236b8.png)

**Comment by lucifer8023** [comment]
同问

**Comment by lyn1026** [comment]
@qsyao @lucifer8023  我小号也是，手动验证身份解除后，可以正常运行，运行到现在是一天，目前没有被封号
