### ISSUE TITLE
[Bug]: 没有回复，没有机器人

### ISSUE THREAD

**Issue by Coder2cdb** [fuergaosi233/wechat-chatgpt#857]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, **FULL** config, **FULL** log, etc).

### Deployment Platform

- [X] Railway
- [ ] Fly.io
- [ ] Docker & Docker Compose
- [ ] Node.js

### Description of the problem

railway上部署成功了 但是没看到有任何回复 看了issue说和机器人聊天   哪里来的机器人...??? :(
![image](https://user-images.githubusercontent.com/26293686/229847810-5ff22090-cb55-4e24-a154-027c3f926713.png)

### wechat-chatgpt operation log

<details>
```console
333
```
</details>

**Comment by RealTong** [comment]
The robot is yourself.
