### ISSUE TITLE
session_token现在是必填 的么

### ISSUE THREAD

**Issue by Yang1k** [fuergaosi233/wechat-chatgpt#86]
'Logging in...',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/app/src/generate_session.py", line 29, in <module>\n' +
    '    print(login(email, password))\n' +
    '          ^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/app/src/generate_session.py", line 15, in login\n' +
    '    chatbot.login(\n' +
    '  File "/root/.cache/pypoetry/virtualenvs/chatbot-twitter-9TtSrW0h-py3.11/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 171, in login\n' +
    "    self.config['session_token'] = auth.session_token\n" +
    '                                   ^^^^^^^^^^^^^^^^^^\n' +
    "AttributeError: 'OpenAIAuth' object has no attribute 'session_token'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by fuergaosi233** [comment]
This means that the login failed

**Comment by Liu-10004** [comment]
我也碰到这个问题，账号和密码都正确的

**Comment by HandsomeWu6** [comment]
same question

**Comment by OliverGrace** [comment]
Now the A method works without a problem, try again. Problem fixed.
