### ISSUE TITLE
请问如何在群聊中和机器人交互 ？

### ISSUE THREAD

**Issue by Cigarliu** [fuergaosi233/wechat-chatgpt#88]
我把机器人拉到群里后 @机器人 看后台日志是能收到消息，但是就是不回复  没有hit gpt enable user   我请问需要如何开启呢

**Comment by RealTong** [comment]
在群聊使用 @
在私聊直接发送就可以了

**Comment by Cigarliu** [comment]
> 

但是艾特后 没起作用，他不回复信息

**Comment by RealTong** [comment]
> 但是艾特后 没起作用，他不回复信息

群聊需要保证 群内的昵称和微信昵称一样.
私聊保证消息中包含在config配置的 `chatPrivateTiggerKeyword`

**Comment by Cigarliu** [comment]
> Message: Message#Unknown[🗣Contact<Cc>@👥Room<快乐源泉之开黑车者拉出去枪毙>]
Message: Message#Unknown[🗣Contact<Cc>@👥Room<快乐源泉之开黑车者拉出去枪毙>]
Message: Message#Text[🗣Contact<Cc>@👥Room<快乐源泉之开黑车者拉出去枪毙>]        @bot 1111

Message: Message#Text[🗣Contact<Cc>@👥Room<快乐源泉之开黑车者拉出去枪毙>]        @bot 说话
Message: Message#Unknown[🗣Contact<Cc>]
Message: Message#Unknown[🗣Contact<Cc>]
Message: Message#Unknown[🗣Contact<Cc>]




这是他的日志， 就是不回复 已经艾特了，群内昵称和微信昵称都是bot

**Comment by RealTong** [comment]
> > Message: Message#Unknown[🗣Contact@👥Room<快乐源泉之开黑车者拉出去枪毙>]
> > Message: Message#Unknown[🗣Contact@👥Room<快乐源泉之开黑车者拉出去枪毙>]
> > Message: Message#Text[🗣Contact@👥Room<快乐源泉之开黑车者拉出去枪毙>]        @bot 1111
> 
> Message: Message#Text[🗣Contact@👥Room<快乐源泉之开黑车者拉出去枪毙>] @bot 说话 Message: Message#Unknown[🗣Contact] Message: Message#Unknown[🗣Contact] Message: Message#Unknown[🗣Contact]
> 
> 这是他的日志， 就是不回复 已经艾特了，群内昵称和微信昵称都是bot

你不会是在自己@自己吧.
你可以尝试用小号在群聊里@BotName

**Comment by JingchengLi** [comment]
![image](https://user-images.githubusercontent.com/5918144/206708475-b38038c3-5a7a-45ae-be98-2ab6a6e4d20f.png)
群聊确实没反应，没有回复。昵称没有改，是一样的。

**Comment by JingchengLi** [comment]
用最新代码重新打了docker镜像，是可以的
