### ISSUE TITLE
feat：群聊中同时被多个人@，能否只响应第一个人的问题

### ISSUE THREAD

**Issue by caixiaoguang** [fuergaosi233/wechat-chatgpt#91]
目前在群聊中同时被多个人@，会回答所有人问题，频率过快会导致503，能否在每轮问答中，给出答案之前，只响应第一次问题，忽略掉剩下的

**Comment by fuergaosi233** [comment]
> 目前在群聊中同时被多个人@，会回答所有人问题，频率过快会导致503，能否在每轮问答中，给出答案之前，只响应第一次问题，忽略掉剩下的

It's weird because you don't know that it's responding or hanging up

**Comment by xueshuai0922** [comment]
wirte a queue ,delay
