### ISSUE TITLE
feat: 屏蔽除纯文本以为所有的富文本 i.e., 例如表情图片等等. 

### ISSUE THREAD

**Issue by m4p1e** [fuergaosi233/wechat-chatgpt#93]
如题.

**Comment by z-koki** [comment]
我也有同样的问题，我把触发关键字设成了cc，然后很多表情包的内容里包含了，例如：
`Triggered ChatGPT: <msg><emoji fromusername = "xxx" tousername = "xxx" type="2" idbuffer="media:0_0" md5="8c2b38ab82e8344e2a75e14fb9eccbab" len = "132399" productid="" androidmd5="8c2b38ab82e8344e2a75e14fb9eccbab" androidlen="132399" s60v3md5 = "8c2b38ab82e8344e2a75e14fb9eccbab" s60v3len="132399" s60v5md5 = "8c2b38ab82e8344e2a75e14fb9eccbab" s60v5len="132399" cdnurl = "http://vweixinf.tc.qq.com/110/20401/stodownload?m=8c2b38ab82e8344e2a75e14fb9eccbab&amp;amp;filekey=30440201010430302e02016e0402535a04203863326233386162383265383334346532613735653134666239656363626162020302052f040d00000004627466730000000131&amp;amp;hy=SZ&amp;amp;storeid=323032313037313531363131343430303039363833613866633338646566353534633566303930303030303036653031303034666231&amp;amp;ef=1&amp;amp;bizid=1022" designerid = "" thumburl = "" encrypturl = "http://vweixinf.tc.qq.com/110/20402/stodownload?m=c5fffc90980dbe539681c6cb854f3bcd&amp;amp;filekey=30440201010430302e02016e0402535a042063356666666339303938306462653533393638316336636238353466336263640203020530040d00000004627466730000000131&amp;amp;hy=SZ&amp;amp;storeid=323032313037313531363131343430303061343161333866633338646566353534633566303930303030303036653032303034666232&amp;amp;ef=2&amp;amp;bizid=1022" aeskey= "d31e7a3e65ba4530bb72599a2b4898be" externurl = "http://vweixinf.tc.qq.com/110/20403/stodownload?m=c9600860794fea1de70370924aa0b73a&amp;amp;filekey=3043020101042f302d02016e0402535a0420633936303038363037393466656131646537303337303932346161306237336102021780040d00000004627466730000000131&amp;amp;hy=SZ&amp;amp;storeid=323032313037313531363131343430303061633933633866633338646566353534633566303930303030303036653033303034666233&amp;amp;ef=3&amp;amp;bizid=1022" externmd5 = "8d5eefa6d39f431dc1a8c276c3121249" width= "374" height= "365" tpurl= "" tpauthkey= "" attachedtext= "" attachedtextcolor= "" lensid= "" emojiattr= "" linkid= "" desc= "" ></emoji> </msg>`

**Comment by RealTong** [comment]
https://github.com/fuergaosi233/wechat-chatgpt/pull/41 Completed
